### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ag2522** [jasp-stats/jasp-issues#1895] opened 2022-11-08 20:39 UTC
### JASP Version

0.16.4

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

Linear Modeling

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Was dragging my independent variable over and this message popped up: This analysis terminated unexpectedly.

Error in UseMethod('.applyEnDeCoder', x): no applicable method for '.applyEnDeCoder' applied to an object of class 'character'

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

was trying to drag my independent variable over and this came up

### Steps to Reproduce

1.
2.
3.
...
I click visual modeling, I click linear modeling, and I try to drag my independent variable over. It allows me to drag the dependent, but not the independent. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-11-09 09:05
I suppose this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1849, and can be tracked there.

**Closed by juliuspf** 2022-11-09 09:05 UTC
Labels: Module: jaspVisualModeling, OS: macOS Intel

**Comment by ag2522** [comment] 2022-11-09 16:08
Hi, attached is a screenshot of the message I receive when trying to drag
my dependent variable into the dependent variable box on linear modeling.

**Comment by ag2522** [comment] 2022-11-09 16:34
Yes It does, it but the error says:
This analysis terminated unexpectedly.

Error in `$<-.data.frame`(`*tmp*`, 'model', value =
structure(list(coefficients = c(`(Intercept)` = 130.000495867769), :
replacement has 11 rows, data has 1

Stack trace

To receive assistance with this problem, please report the message above
at: https://jasp-stats.org/bug-reports

**Comment by juliuspf** [comment] 2022-11-09 16:38
Which seems like the same error reported here: https://github.com/jasp-stats/jasp-issues/issues/1849. If you dont mind, you could just follow the updates there, to see how the fix for this progresses.

**Comment by ag2522** [comment] 2022-11-09 16:45
Thank you. I just looked at it and did not see a fix, and if there was one
I did not understand. Can you clarify if there is a fix for this issue yet?
