### ISSUE TITLE
[Feature Request]: RM ANOVA - allow interactions between within/between factors in marginal means 

### ISSUE THREAD

**Issue by mlapcn** [jasp-stats/jasp-issues#2351] opened 2023-10-19 15:47 UTC
### JASP Version

0.18.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA (Classical)

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

In the Repeated Measures ANOVA I can find some issues, related to different aspects:

1) Estimated Marginal Means: Bug when computing the Marginal Means in a RM Anova, the SE that are reported appear with the same value for each level of the  factor (either in the within or between factors). (Image 1) 

2) Estimated Marginal Means: Moreover, we are not able to see the marginal means of the interaction effect in a mixed anova (crossing the within and the between subjects factor) in order to report the correct estimated marginal means. (but we can calculate the EMM crossing two within subjects factors) (Image 1)

3) Define Repeated Measures Cells:  I am not sure this last thing is a bug or if it is me needing clarification. But, when using two or more RM factors,  I am not understanding how to define/indicate/allocate my levels of each factor to the repeated measures cells. What appears in this menu is the combination of the levels of the two RM factors (see image 2), but what I should have is a clear definition of Repeated Measure and the specific level to allocate my variables (EX: in a 2 x 2 design it should appear in the Repeated Measures Cells Menu: RM Factor 1, level 1; RM Factor 1, Level 2; RM Factor 2, level 1; RM Factor 2, Level 2). Am I right?

Thank you for 

[Arquivo.zip](https://github.com/jasp-stats/jasp-issues/files/13044727/Arquivo.zip)

### Expected Behaviour

1) It should appear the specific SE for each RM Factor level, or group of the BS variable.
2) We should have the possibility to calculate the EMM for the RM factor * Between Subj Variable.
3) We should have is a clear definition of Repeated Measure and the specific level to allocate my variables (EX: in a 2 x 2 design it should appear in the Repeated Measures Cells Menu: RM Factor 1, level 1; RM Factor 1, Level 2; RM Factor 2, level 1; RM Factor 2, Level 2).

### Steps to Reproduce

1. Ask for Repeated Measures with one or two RM Factor and Between Subj variable
2. Define two or three levels to each RM Factor
3. Ask for the EMM
4. Look for the SE of each level of the factors
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by altunenes** [comment] 2023-12-22 10:56
"Estimated Marginal Means: Bug when computing the Marginal Means in a RM Anova, the SE that are reported appear with the same value for each level of the factor (either in the within or between factors). (Image 1)"

same issue here.  :-)

os: Win 11 (up-date)
jasp: latest ver.
CPU: Ryzen 6800h
ram: 16 gb


But interestingly, if I click "Use multivariate model for follow-up tests" it becomes fixed. 
before:
![image](https://github.com/jasp-stats/jasp-issues/assets/54986652/fb072f31-6403-4c6d-8059-11d52d642682)

after:
![image](https://github.com/jasp-stats/jasp-issues/assets/54986652/dc72a263-408e-4eae-804b-159c400011d3)

Note: if I remove the checkbox, it reverts back to the wrong version.

**Comment by tomtomme** [comment] 2024-02-09 15:08
confirmed for 0.19 beta.

@JohnnyDoorn 
can you have a look?

**Comment by JohnnyDoorn** [comment] 2024-02-09 16:38
Hi @altunenes and @mlapcn,

1. This is not a bug, but a feature of the ANOVA model, where the standard errors are based on the full model and not on the sd's of the individual factor levels (i.e., the ANOVA assumes equal variances and this is reflected in the SE's used in the follow-up tests). Using the multivariate test allows the variances to differ, which is why the numbers differ. Using the multivariate model is more suitable in cases where sphericity is (starting to get) violated, and so we are making this the default option. The bigger the difference in results between univariate and multivariate follow-up tests, the more of an indication of sphericity violation.

2. Yes, this is still a feature to be added - I will update the title of your post to reflect this part as a feature request.

3. The way the GUI works, is that you first specify the RM structure (give the name of the within factor, and then provide names). These names then show up in the box below (without the name of the within factor), where you can map your variables (in the wide data format) onto the RM cells. Here it is a good idea to have unique RM factor level names across different RM factors, so that you can more easily distinguish. The way the interface works, is that the first name refers to the first specified RM factor, then the name after the comma refers to the second specified RM Factor, then the third, etc. 

Kind regards,
Johnny

**Comment by altunenes** [comment] 2024-02-09 16:57
Thank you for the feedbacks/insights. Also for your contributions, really lovely software.

**Comment by tomtomme** [comment] 2024-02-09 18:08
This leaves the feature request of 2)
- Add marginal means of the interaction effect in a mixed anova (crossing the within and the between subjects factor) in order to report the correct estimated marginal means

I think we have a duplicate of this somewhere - I will look into it tomorrow.

**Comment by TarandeepKang** [comment] 2024-03-16 12:34
Hi all,
Just a quick bump for this from me and a forum user:  
https://forum.cogsci.nl/discussion/9199/rm-anova-estimated-marginal-means-for-interaction#latest

**Closed** 2024-04-08 13:11 UTC
Labels: Module: jaspAnova, Feature Request
