### ISSUE TITLE
[Bug]: when using Edit Title, paste always overwrites entirety of existing title

### ISSUE THREAD

**Issue by DIV-on-github** [jasp-stats/jasp-issues#1612] opened 2022-02-11 07:52 UTC
### JASP Version

0.15

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When using **Edit Title**, the paste command (issued with Ctrl+V) always overwrites the entirety of the existing title with the text on the clipboard.

### Expected Behaviour

When using **Edit Title**, the paste command (issued with Ctrl+V) should:

* if no existing text is selected, then insert text on the clipboard at the current cursor position, preserving all of the existing text around it;  or 
* if some/all existing text is selected, then insert text on the clipboard at the current cursor position, preserving any unselected portions of the existing text around it.

—DIV

### Steps to Reproduce

1. Copy text to clipboard.
2. In JASP run an analysis.
3. Click to Edit Title.
4. Click somewhere in title field.
5. Press Ctrl+V

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment] 2022-02-12 05:37
@DIV-on-github  Could you please try it on the latest JASP16 or JASP 16.1 [pre-release](http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-development-3882b2dc5c519f0093bea7d427f3bd50ee060de2.zip) and record  a video or gif, I just tried but can't reproduce it on my windows with JASP pre-release.

**Comment by DIV-on-github** [comment] 2022-02-14 01:36
Has the issue at https://github.com/jasp-stats/jasp-issues/issues/1604 been fixed?
That is why I did not proceed to JASP 0.16.
—DIV

**Comment by juliuspf** [comment] 2022-10-14 07:51
It seems that has been fixed yes!

**Comment by shun2wang** [comment] 2022-10-17 08:22
Closed due to inactivity for a long time. @DIV-on-github Please try the latest version and if there is a problem reopen it.

**Comment by juliuspf** [comment] 2022-10-17 08:58
Sorry, but I think the issue is still there.

**Comment by juliuspfadt** [comment] 2023-02-09 07:44
Also a duplicate of https://github.com/jasp-stats/jasp-issues/issues/638

**Closed** 2023-03-21 15:46 UTC
Labels: duplicate, Bug: Low
