### ISSUE TITLE
[Bug]: LINEAR REGRESSION OUTPUTS STANDARDIZED COEFFICIENT EQUAL TO 1

### ISSUE THREAD

**Issue by annamalerba** [jasp-stats/jasp-issues#1805] opened 2022-08-22 08:20 UTC
### JASP Version

0.16.3

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

linear regression

### What OS are you seeing the problem on?

window 11

### Bug Description

![Screenshot (78)](https://user-images.githubusercontent.com/111734620/185873095-f1cc244c-498d-4bb2-b23e-c03975413c26.png)

### Expected Behaviour

the standardized coefficient for "TOT_IUS_R_T3" is equal to 1.106, which should not be possible given that it is standardized. 

### Steps to Reproduce

1. perform linear regression on my data
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-08-22 09:41
Hi @annamalerba, thanks for reporting this. Is it possible for you to attach a .jasp file, or the data set that lead to this issue?

**Comment by juliuspf** [comment] 2022-08-22 09:46
In the meantime, I think it is not impossible to have standardized coefficients be outside the -1,1 range. See, for example, https://doi.org/10.1177/001316447803800404

**Comment by tomtomme** [comment] 2022-08-22 10:53
Yeah. Only simple linear regression standardized coefficients are forced to the range of -1 to 1. For multiple regression this is normal and not a bug, afaik.

**Comment by annamalerba** [comment] 2022-08-22 13:30
Thanks a lot. I will look into what might cause this (admissible) anomaly. how might I export the dataset in a .jasp extension? I can only create a .csv or .xlsx

**Comment by juliuspf** [comment] 2022-08-22 20:54
from the menu tab you can choose "save as" and choose a directory and name, and then your analyses combined with your dataset will get saved as a .jasp file. For now, I dont think you need to upload the file though, since this is most likely not a bug. I will close this issue for now, but you can always reopen if the issue is not solved.

**Closed by juliuspf** 2022-08-22 20:54 UTC
Labels: Module: jaspRegression
