### ISSUE TITLE
[Feature Request]: Sensitivity analysis for Bayesian RM ANOVA

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#2319] opened 2023-10-02 12:58 UTC
### Description

Sensitivity analysis for Bayesian RM ANOVA

### Purpose

To be able to run sensitivity analyses on RM ANOVA factors

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

Currently, Bayesian sensitivity analyses are only available for Bayesian t-tests. It would be great if they were also available for Bayesian RM ANOVA models, for Bayesian model averaged posteriors

### Additional context

Currently, Bayesian sensitivity analyses are only available for Bayesian t-tests. It would be great if they were also available for Bayesian RM ANOVA models, for Bayesian model-averaged posteriors. For example, if one has a 2 (factor 1) x 4 (factor 2) design, to be able to run a sensitivity analysis, with different prior distributions, for each factor. Currently, this option is only available for t-tests, where one only compares between 2 conditions.

**Comment by JohnnyDoorn** [comment] 2023-10-02 13:29
Hi @RenzoLanfranco ,

I would also really like such a feature, but the problem here is that the BANOVA's typically take (at least) a little while to run, and if we want to create such plots as for the t-tests, that would result in very long run-times. For now it seems that the only possibility is to do this manually, and set the prior parameters to different values yourself. It could be an option for JASP to at some point offer a checkbox that reruns the analysis for 2 or 3 other value of the prior distribution. 

Kind regards
Johny

**Comment by EJWagenmakers** [comment] 2023-10-02 13:45
Also, there are multiple priors in the ANOVA, so we'd have to think about which ones to vary.
EJ

**Comment by RenzoLanfranco** [comment] 2023-10-14 02:29
> Hi @RenzoLanfranco ,
> 
> I would also really like such a feature, but the problem here is that the BANOVA's typically take (at least) a little while to run, and if we want to create such plots as for the t-tests, that would result in very long run-times. For now it seems that the only possibility is to do this manually, and set the prior parameters to different values yourself. It could be an option for JASP to at some point offer a checkbox that reruns the analysis for 2 or 3 other value of the prior distribution.
> 
> Kind regards Johnny

I understand. Thank you. Even if it took a long time, as long as the analysis has a progress bar, I think it would be fine. How would you manually set different prior parameters? Are there rules to do that? With Bayesian t-tests, the "robustness check" does it automatically.

**Comment by tomtomme** [comment] 2024-02-20 12:03
@RenzoLanfranco 
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/201
201 wants this for all bayesian anovas. I will transfer important remarks from this issue and close this one for now. Please reopen, if you disagree!

**Closed as completed by tomtomme** 2024-02-20 12:03 UTC
Labels: Module: jaspAnova, Feature Request
