### ISSUE TITLE
Box plots of column data

### ISSUE THREAD

**Issue by DrMarkGS** [jasp-stats/jasp-issues#832] opened 2020-06-30 13:14 UTC
Hi folks
In Descriptives, we can currently plot boxplots for multiple variables if they are in one column and there is a grouping variable.  However, if I want to plot 3 different variables, for example (in seperate columns),  JASP plots them individually.  It would be nice to have the option to plot them on the same graph.

Cheers
Mark

**Comment by Jan-K-Hart** [comment] 2023-09-12 16:05
The extension from one split factor to multiple split factors is an important step to increase the power of this graph. This is a property which a lot of professional statistic tools have and I miss it in JASP. This type of graph is the most used one out of my experience in Six Sigma to eye-ball data and to state hypothesis (before hypothesis testing is applied: ANOVA, T-Test, ...).  In most cases 2 to 3 split factors are sufficient. Rare it is needed for 4 factors (then it makes sense only if each factor has a low number of levels). 
I fond a workaround by creating a new column with text functions in an .ods file. This column contained finally all factor combination. But I could not apply color coding on my prefered parameter.
I attached a Minitab graph which I want to plot in JASP too to show one example. There are 3 factors used but the file offers more factors.
![Individual Value Plot of B29](https://github.com/jasp-stats/jasp-issues/assets/143706205/030f2ab4-47b1-42b1-86f2-1dc1a748018c)
[Multiple Factor Split Workaround.docx](https://github.com/jasp-stats/jasp-issues/files/12588518/Multiple.Factor.Split.Workaround.docx)
I would appreciate if this Feature Request would lead to an implementation soon. If there is anything I can do. Then let me know

**Comment by tomtomme** [comment] 2024-01-11 11:57
@Jan-K-Hart 
Have you tried Flexplot from the Visual Modeling Module? It can split be many factors!

@DrMarkGS 
A merge option for boxplots and also barplots (for stacked or grouped bar plots) in Descriptives would still be cool, yeah. This is needed, when you have no grouping variable, especially for wide format date (e.g. repeated measures)

**Comment by Jan-K-Hart** [comment] 2024-01-11 12:38
Hello Thomas
Thanks for the hint. I will test it soon.
Hope this was of responding works.

Jan

Von: Thomas Langkamp ***@***.***>
Gesendet: Donnerstag, 11. Januar 2024 12:58
An: jasp-stats/jasp-issues ***@***.***>
Cc: Hartmann, Jan ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Box plots of column data (#832)


[CAUTION] This email originates from outside of TE. Be cautious when clicking links, opening attachments and providing sensitive information.

@Jan-K-Hart<https://github.com/Jan-K-Hart>
Have you tried Flexplot from the Visual Modeling Module? It can split be many factors!

@DrMarkGS<https://github.com/DrMarkGS>
A merge option for boxplots and also barplots (for stacked or grouped bar plots) in Descriptives would still be cool, yeah. This is needed, when you have no grouping variable, especially for wide format date (e.g. repeated measures)

**Comment by tomtomme** [comment] 2024-01-30 19:40
@Jan-K-Hart 
yeah, it works. Could you test already?

**Comment by Jan-K-Hart** [comment] 2024-01-31 16:18
Hello Thomas
Yes, I did some checks and it worked well.
At least I can use 2 factors and add two additional factors which are indicated in a table structure.
In our cases we usually do not need more than 4 factors.

I never heard before about flex-plot.
Thanks for this great hint. I explored it at the beginning of January.

Best regards
Jan

Von: Thomas Langkamp ***@***.***>
Gesendet: Dienstag, 30. Januar 2024 20:40
An: jasp-stats/jasp-issues ***@***.***>
Cc: Hartmann, Jan ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Box plots of column data (#832)


[CAUTION] This email originates from outside of TE. Be cautious when clicking links, opening attachments and providing sensitive information.

@Jan-K-Hart<https://github.com/Jan-K-Hart>
yeah, it works. Could you test already?

**Comment by tomtomme** [comment] 2024-01-31 16:28
Nice. This leaves the original request then of boxplots for RMs

**Comment by tomtomme** [comment] 2024-05-27 11:24
I just realized, that this is basically a duplicate of 
https://github.com/jasp-stats/jasp-issues/issues/33

If we have a button that enables seemless switching between wide and long format data we do not need to add special-wide-data-format plotting options for all the different plots out there. So lets just implement that button and thus tackle all sorts of plots at the same time. This is much more efficient. Hence closing this one. 

@DrMarkGS 
Please reopen if you disagree!

**Closed by tomtomme** 2024-05-27 11:24 UTC
Labels: Component: Result Plots, Module: jaspDescriptives, Feature Request
