### ISSUE TITLE
[Bug]: jasp module prophet not loading and refreshing 

### ISSUE THREAD

**Issue by ruee08** [jasp-stats/jasp-issues#2448] opened 2023-11-29 13:21 UTC
### JASP Version

0.18.1

### JASP Module

Prophet

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Prophet module isn’t loading/ refreshing when I am adding/ clicking on the plots and evaluations sections. It has been trying to load for hours.

### Expected Behaviour

It should load in a timely manner. 

### Steps to Reproduce

1. Open prophet 
2. And just try to run it and make adjustments under plot and evaluation. 
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by ruee08** [comment] 2023-11-29 13:22
![Uploading IMG_1044.jpeg…]()

**Comment by tomtomme** [comment] 2024-02-09 13:23
@ruee08 
I cannot reproduce with jasp 0.18.3. Please reopen if the problem is not fixed on your side. Thx!

**Closed by tomtomme** 2024-02-09 13:23 UTC
Labels: Module: jaspProphet, OS: Windows 10, Bug
