### ISSUE TITLE
[Bug]: File doesn't save using Command-S when changes are made only to column/variable names

### ISSUE THREAD

**Issue by dermotlynott** [jasp-stats/jasp-issues#2355] opened 2023-10-20 15:23 UTC
### JASP Version

0.18.0

### JASP Module

Other

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

If I open a JASP file, click on Edit Data, and then edit a variable/column name, the file will not save the updated name change using Command-S. If If I I close the file, it does not ask if I wish to save the changes. And when you reopening the file, you can see the changes have not been recorded. 

However, if you use the Main Menu --> Save command, the changes to the column name are saved. 

### Expected Behaviour

When variable names are edited, it should be noted as a change to the file, and 1) pressing Command-S should save the change as usual, OR 2) the user should be prompted to save when closing the file. 

### Steps to Reproduce

1. Open File that contains some data
2. Click Edit data
3. Click any column name
4. Click in the Name box, and make a name change
5. Press X to exit the column name editor
6. Press the Analyses button to return to the Analyses window
7. Press Command-S...there should be no response
8. Close the window (there will be no prompt to save changes)
9. Reopen the file and navigate to the edited variable name, and the change will not have been saved. 
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by dermotlynott** [comment] 2023-10-20 15:30
[TestFile-notSavingVariableNameChanges.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13055866/TestFile-notSavingVariableNameChanges.jasp.zip)

**Comment by boutinb** [comment] 2023-10-23 08:45
Hi @dermotlynott, you closed this issue, is it because it works now, or is it by mistake?

**Comment by dermotlynott** [comment] 2023-10-23 08:48
Ah sorry - no, I didn’t intend to close it. The issue still persists. Apologies, it was my first bug report!

Best wishes,
Dermot.


Dermot Lynott
Associate Professor
Maynooth University
Department of Psychology

Email: ***@***.******@***.***>
Web: https://www.maynoothuniversity.ie/psychology/our-people/dermot-lynott  <https://www.maynoothuniversity.ie/psychology/our-people/dermot-lynott>
ImpactStory: https://impactstory.org/u/0000-0001-7338-0567
Scholar: http://scholar.google.co.uk/citations?user=IkMV2OwAAAAJ&hl=en
How to pronounce my name<http://namedrop.io/dermotlynott>

On 23 Oct 2023, at 09:45, bruno boutin ***@***.***> wrote:

*Warning*
This email originated from outside of Maynooth University's Mail System. Do not reply, click links or open attachments unless you recognise the sender and know the content is safe.


Hi @dermotlynott<https://github.com/dermotlynott>, you closed this issue, is it because it works now, or is it by mistake?

**Comment by boutinb** [comment] 2023-10-23 08:49
Yes, I can reproduce it. It will be solved with the next release.

**Comment by dermotlynott** [comment] 2023-10-23 08:51
Super! Thanks for looking at this Bruno.

Best wishes,
Dermot.

Dermot Lynott
Associate Professor
Maynooth University
Department of Psychology

Email: ***@***.******@***.***>
Web: https://www.maynoothuniversity.ie/psychology/our-people/dermot-lynott  <https://www.maynoothuniversity.ie/psychology/our-people/dermot-lynott>
ImpactStory: https://impactstory.org/u/0000-0001-7338-0567
Scholar: http://scholar.google.co.uk/citations?user=IkMV2OwAAAAJ&hl=en
How to pronounce my name<http://namedrop.io/dermotlynott>

On 23 Oct 2023, at 09:50, bruno boutin ***@***.***> wrote:

*Warning*
This email originated from outside of Maynooth University's Mail System. Do not reply, click links or open attachments unless you recognise the sender and know the content is safe.


Yes, I can reproduce it. It will be solved with the next release.

**Closed** 2023-10-27 11:37 UTC
Labels: OS: macOS Intel, Bug
