### ISSUE TITLE
[Bug]: JASP files won't open

### ISSUE THREAD

**Issue by jennthepaprof** [jasp-stats/jasp-issues#1593] opened 2022-01-29 21:53 UTC
### JASP Version

0.16

### What OS are you seeing the problem on?

macOS Monterey 12.01

### Bug Description

JASP is working properly but when I go to open a JASP file on my desk top it says the file type isn't supported. How do I hope a .jasp

### Expected Behaviour

The file should open

### Steps to Reproduce

1. open a jasp file
2. it won't open
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2022-01-30 16:55
Can you open the file from within jasp?

Click the 3 blue stripes top right corner in jasp, then open, then computer, then browse to select your hasp file.

**Comment by ilkerduymaz** [comment] 2022-02-01 13:53
I have the same problem. I can open the file from within jasp (rather than clicking on the file itself). However, I can only have one open data at a time. When I try to open another jasp file (again, from within jasp) when I already have an open file, a new jasp window opens and I see the loading animation but it immediately closes after loading.

**Comment by JorisGoosen** [comment] 2022-09-01 11:57
@ilkerduymaz are you using 0.16.3 ?

In any case, I cannot reproduce this so I would like to see some logs. Could either you or @jennthepaprof send my some logs?

Howto: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md#mac

What you could try is: 
```
cd /Applications/JASP.app/Contents/MacOS/
./JASP --logToFile <path-to-jaspfile>
```

where you replace `<path-to-jaspfile>` by the path.

**Comment by tomtomme** [comment] 2024-02-01 20:10
@ilkerduymaz  @jennthepaprof 
I saw this bug in the past on older MacOS machines of my students. But not anymore during the last months. Can you re-test with JASP 0.18.3?

**Comment by ilkerduymaz** [comment] 2024-02-01 20:42
@tomtomme Hi!

I can confirm that I stopped having this problem somewhere along the line, although I cannot pinpoint which update solved it. 

Thank you for the continued development of this awesome tool!

**Comment by tomtomme** [comment] 2024-02-01 21:00
Great!
Then I will close this for now. Reopen if the bug re-emerges!

**Closed by tomtomme** 2024-02-01 21:00 UTC
Labels: waiting for requester, OS: macOS Intel, Bug: Low
