### ISSUE TITLE
PLS SEM algorithm

### ISSUE THREAD

**Issue by srk7774** [jasp-stats/jasp-issues#846] opened 2020-07-06 09:00 UTC
* Enhancement: Structural Equation Modelling can be done using covarience based sem (which is already available in JASP using lavaan package) and Partial least squares algorithm (PLS SEM) which is currently not avaialble.  
* Purpose:  PLS SEM can be used when latent variables have formative constructs. 

**Describe the solution you'd like**
 
There is an R package already available "PLSPM".  

**Describe alternatives you've considered**
 
https://www.smartpls.com/

**Additional context**

Refer to https://www.amazon.in/Partial-Squares-Structural-Equation-Modeling/dp/148337744X

**Comment by vankesteren** [comment] 2020-07-28 14:09
Duplicate of #354

**Closed by vankesteren** 2020-07-28 14:09 UTC
