### ISSUE TITLE
[Bug]: Path diagram in SEM and ordinal variables

### ISSUE THREAD

**Issue by rraph-r** [jasp-stats/jasp-issues#1629] opened 2022-02-22 18:36 UTC
### JASP Version

0.16

### JASP Module

jaspSem

### What analysis are you seeing the problem on?

SEM - Path Diagram

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Hello!

I have encountered an error when producing a path diagram for my SEM analysis. My model has 3 exogenous and 5 endogenous latent variables. All of them are continuous data except for EK_A which is an indicator variable. My model is specified as follows (JASP file and dataset sent to you directly):

#latent structures
SE =~ VAL8 + VAL9 + VAL18 + VAL19
ST =~ VAL3 + VAL4 + VAL13 + VAL14
NEP =~ NEP1 + NEP2 + NEP3 + NEP4 + NEP5
AC =~ AC1 + AC2 + AC3 + AC4
AR =~ AR1 + AR2
PN =~ PN1 + PN2 + PN3 + PN4
EK_A =~ EK_A1 + EK_A2 + EK_A4 + EK_C_L1 + EK_C_L2 + EK_C_L3 + EK_C_L4
LIT =~ WDB1 + WDB2 + WDB3 + WDB4 + WDB5 + WDB6

#regressions

NEP ~ SE + ST
AC ~ NEP
AR ~ AC
PN ~ AR
LIT ~ PN

Please see the JASP settings below:

![settings 1](https://user-images.githubusercontent.com/100230704/155195716-32aeaa6e-10ad-4055-957a-70ff1445f592.jpg)
![settings 2](https://user-images.githubusercontent.com/100230704/155195725-05d1b788-ada9-4a85-b0c2-f8c4905ccfe4.jpg)

All is well with the analysis if the Path diagram option is not toggled, but when it is selected, it shows the error below:

![sem path diagram error](https://user-images.githubusercontent.com/100230704/155195029-a3fecede-2bc4-4603-a5ea-d54aff990ad2.jpg)

### Expected Behaviour

Instead of a bug, the JASP must produce a regular path diagram. I have tested other models and it was able to give one without issues:
![path](https://user-images.githubusercontent.com/100230704/155196518-0b04ad78-cc6b-4650-ae7e-d92c657dce52.jpg)

### Steps to Reproduce

1. Select "Path diagram" and "Show parameter estimates" in the SEM module
2. 
3. 
...

### Log (if any)

```bash
This analysis terminated unexpectedly.

Error in bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

SEM(...)

.semPathPlot(modelContainer, dataset, options, ready)

.semCreatePathPlot(modelContainer[['results']][['object']][[1]], NULL, pcont, options, ready)

.suppressGrDevice(semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE))

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE)
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by icekylin** [comment] 2022-02-23 00:05
hi @rraph-r thanks for your report. could you please upload a data file with that issue? you can zip the file and drag to this comment to upload it. this could be helpful,thanks!

**Comment by Kucharssim** [comment] 2022-02-23 08:17
Thank you for reporting this error. It seems that this bug could be related to bug previously fixed in mediation (https://github.com/jasp-stats/jaspSem/pull/16); it seems that the path diagram does not know how to deal with ordinal variables. I will fix this.

**Comment by rraph-r** [comment] 2022-02-23 11:13
Hello Simon!                                Thank you for the update and your efforts on fixing this bug. Your software has helped me a lot in my research! :)                                Does this mean that the path diagram will be able to work on ordinal variables in the next version release?                                 Many thanks!                -Raph                                                               --       Sent from Canary                                                            On Wednesday, Feb 23, 2022 at 4:17 PM, Simon Kucharsky ***@***.******@***.***> wrote:                                 Thank you for reporting this error. It seems that this bug could be related to bug previously fixed in mediation (jasp-stats/jaspSem#16); it seems that the path diagram does not know how to deal with ordinal variables. I will fix this.       —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.You are receiving this because you were mentioned.Message ID: ***@***.***>       ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/jasp-stats/jasp-issues/issues/1629#issuecomment-1048537272","url": "https://github.com/jasp-stats/jasp-issues/issues/1629#issuecomment-1048537272","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by Kucharssim** [comment] 2022-03-10 10:47
Dear @rraph-r,

it will be fixed in version 0.17.

Simon

**Comment by juliuspf** [comment] 2022-06-27 07:52
this also seems to be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1617, right?

**Comment by Kucharssim** [comment] 2022-06-27 10:40
You are right - I will close https://github.com/jasp-stats/jasp-issues/issues/1617 since here is more details about the issue. (and I better solve this problem soon!)

**Closed** 2022-11-30 08:54 UTC
Labels: Module: jaspSem, Bug: Medium
