### ISSUE TITLE
[Bug]: listwise deletion in PCA

### ISSUE THREAD

**Issue by FloSchuberth** [jasp-stats/jasp-issues#2419] opened 2023-11-17 13:08 UTC
### JASP Version

0.18.1

### JASP Module

Factor

### What analysis are you seeing the problem on?

PCA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I have a dataset that contains missing values. For both EFA and PCA pairwise deletion works fine. However, if I want to use listwise deletion, the PCA module of JASP returns an error "Estimation failed: Internal error message 'x' must be numeric", see the following screenshot
![MissingPCA](https://github.com/jasp-stats/jasp-issues/assets/16427204/34448534-273b-46ce-bf4d-030879a245b7)

 For EFA, listwise deletion works fine, see the following screenshot 

I thought it might be worthwhile for you to check what is going when listwise deletion is used. Please find attached also my JASP file. 
[Customer_Loyalty_BR.zip](https://github.com/jasp-stats/jasp-issues/files/13392046/Customer_Loyalty_BR.zip)

### Expected Behaviour

I would have expected that listwise deletion works either for both EFA and PCA or for none.

### Steps to Reproduce

See the JASP file attached. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2024-02-07 09:34
yes, there is a bug in PCA when the data is ordinal and contains missings.

**Comment by FloSchuberth** [comment] 2024-02-10 20:22
Please double-check. Even though I use ordinal indicators they are treated as metric as the correlation matrix is used as input.

**Comment by juliuspfadt** [comment] 2024-02-12 06:37
Thats not what I mean :) Anyways, the issue is fixed with the PR that I linked.

**Closed as completed** 2024-04-15 09:29 UTC
Labels: Module: jaspFactor, Bug: Medium
