### ISSUE TITLE
JASP Goes Blank When Computing Large Tables of Correlations

### ISSUE THREAD

**Issue by 16665k00** [jasp-stats/jasp-issues#712] opened 2020-04-26 09:34 UTC
* JASP version: 12.2
* OS name and version: Windows 10
* Analysis: Pearson's correlation (for a large set of variables; in this case, 94 variables, 93 of which are the language features generated by the Linguistic Inquiry and Word Count software). 
* Bug description: The whole output window simply goes blank after a while (see attached). It first looks as if it's computing (i.e., the variable names are shown, with blank entries where the _r_-values and _p_-values will appear), but then it all goes blank.  
* Expected behaviour: The whole table of correlations should appear. 
![Screenshot (43)](https://user-images.githubusercontent.com/54776575/80303628-029c5000-87cf-11ea-95d5-ce667603969b.png)

--->

**Comment by boutinb** [comment] 2020-04-28 07:20
Hi @16665k00 Could you give us (in a zip format) the JASP log files: go to Preferences/Advanced/Logging options, click Log to file, then redo the reproduction path of this issue. When you click the Show Logs button, you should see the last 4 log files: 1 desktop & 4 engines log files.
Hopefully can we get some hints over this issue with these log files.

**Comment by 16665k00** [comment] 2020-04-29 09:43
Hello, thanks for this suggestion. I have tried, but now, JASP displays "not responding" when I try to obtain the full 94x94 table of correlations (see attached). Will it help if I sent the logs for a smaller number of correlations, say 20-25? 
![Screenshot (44)](https://user-images.githubusercontent.com/54776575/80581773-48555480-8a2b-11ea-95d7-21acb447eadf.png)

**Comment by EJWagenmakers** [comment] 2020-04-29 11:09
This happens because, by mistake, JASP computes Kendall's tau for all correlations, even though it is not requested. This really, really slows down the computation time. 
@Kucharssim , would be very good to have this fixed before the new release.

**Comment by 16665k00** [comment] 2020-04-29 11:14
Thank you very much, both. I was just trying to get the log files you
requested, but indeed, JASP has crashed again while computing the
correlations (or more accurately, it states "not responding").

But at least we know why. But does this mean that all the correlations that
are reported are Kendall's taus, rather than Pearson's *r*s? Or is that
Pearson's *r*s are shown, but Kendall's taus are calculated but "hidden"?

Many thanks!

Amar

**Comment by EJWagenmakers** [comment] 2020-04-29 11:16
@Kucharssim The output it correct (99.9% sure here, otherwise we would have to do a hotfix) so the tau's a hidden.

**Comment by Kucharssim** [comment] 2020-05-01 08:05
> @Kucharssim , would be very good to have this fixed before the new release.

Yes indeed, we already have a fix (https://github.com/jasp-stats/Regression/pull/1), but we need to test and merge it. It will be in the next release.

@16665k00 It would be great if you could please share with us your data, so that I can confirm that the fix really solves your problem. That would help us a lot.

**Comment by 16665k00** [comment] 2020-05-01 08:41
Yes, of course. What email address can I send the data to you at?

**Comment by Kucharssim** [comment] 2020-05-01 13:27
s.kucharsky@uva.nl, please, thank you!

**Closed** 2020-06-02 09:25 UTC
