### ISSUE TITLE
[Bug]: Error in diag(scales) %*% truevar: non-conformable arguments

### ISSUE THREAD

**Issue by AntonioJSCouto** [jasp-stats/jasp-issues#2587] opened 2024-02-13 01:27 UTC
### JASP Version

0.18.3

### JASP Module

Factor, SEM

### What analysis are you seeing the problem on?

cfaTableReliability compRelSEM

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This issue seems the same as Issue #2294 and issue #2189. However, in my case there is no special characters (e.g. / ) nor long variable names.

When opening my .JASP project and I check Reliability (under Additional Output) the attached error messages are displayed.
------------------------------------------------------------------------------------------------------------------------------------------
This analysis terminated unexpectedly.

Error in diag(scales) %*% truevar: non-conformable arguments

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableReliability(jaspResults, options, cfaResult)

semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)

omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])

### Expected Behaviour

Successful run of the **Confirmatory Factor Analysis 6 Fatores EGA** from my JASP project using CFA with Reliability

### Steps to Reproduce

1. Unzip the attached **Base coleta EFPP trab e estudantes_ paraJASP.zip** file and open the **Base coleta EFPP trab e estudantes_ paraJASP.jasp** JASP project.
2. Verify the Relialibity checkbox under Additional Output is checked.
3. Verify the error under **Confirmatory Factor Analysis 6 Fatores EGA** analysis.
4. ... attached file: **Base coleta EFPP trab e estudantes_ paraJASP.zip**
[Base coleta EFPP trab e estudantes_ paraJASP.zip](https://github.com/jasp-stats/jasp-issues/files/14254483/Base.coleta.EFPP.trab.e.estudantes_.paraJASP.zip)
 

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2024-02-13 07:35
@AntonioJSCouto, this is indeed a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2294, and we can't fix it until semTools makes it to CRAN. So may follow the workaround described in the other issue.

**Closed by juliuspfadt** 2024-02-13 07:35 UTC
Labels: duplicate, Module: jaspSem, Module: jaspFactor, OS: Windows 11, Bug
