### ISSUE TITLE
Split parameter for all (relevant) analyses...

### ISSUE THREAD

**Issue by PsyTechMMU** [jasp-stats/jasp-issues#635] opened 2020-03-11 15:38 UTC
* Enhancement: Add the 'Split' optional parameter to all relevant analyses
* Purpose: Analysis-specific tests on subsets of data without additional files and filtering
* Use-case: Perform any analyses on subsets of data within each analysis e.g., paired-samples t-tests within each group

**Comment by nahorp** [comment] 2020-04-15 06:16
I would like to see this as well. It'd be great to be able to conduct analyses on subsetted data, all in one .jasp file rather than having multiple files.

**Comment by juliuspfadt** [comment] 2023-02-09 13:08
I think this is also a kind of duplicate of https://github.com/jasp-stats/jasp-issues/issues/385

**Comment by juliuspfadt** [comment] 2023-03-03 10:27
Let's all track this here: https://github.com/jasp-stats/jasp-issues/issues/1330

**Comment by tomtomme** [comment] 2023-12-25 17:18
can be closed, since duplicate of 
https://github.com/jasp-stats/jasp-issues/issues/333
https://github.com/jasp-stats/jasp-issues/issues/385
https://github.com/jasp-stats/jasp-issues/issues/1330

**Closed** 2023-12-25 20:23 UTC
Labels: duplicate, Feature Request
