### ISSUE TITLE
[Bug]: Independent Samples t-test unable to calculate when 3 groups present but one group filtered out.

### ISSUE THREAD

**Issue by DudleyUOC** [jasp-stats/jasp-issues#2893] opened 2024-09-03 16:58 UTC
### JASP Version

0.19.0

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Independent Samples t-test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

<img width="1196" alt="JASP independent t-test bug" src="https://github.com/user-attachments/assets/d053f4f6-2268-4

[Feedback Frequency Netball Shooting Part A.zip](https://github.com/user-attachments/files/16852186/Feedback.Frequency.Netball.Shooting.Part.A.zip)

Screenshot and data attached.
I have a grouping variable with three groups. I want to do a comparision (classical independent t-test) between two of the groups.  I have filtered the variable out using both the shown method and the filter function. When I move the grouping variable the message "Maximum number of levels is 2. Variable Group has 3 levels."

I have replicated the error with multiple data sets. I have saved and close the file and reopened the file and the error persists. Error applies to Bayesian independent t-test

### Expected Behaviour

In previous versions of JASP.
Having filtered out 1 of the three groups the test would run a comparision between the remaining two groups.

### Steps to Reproduce

1. Open filter window for grouping variable
2.Deselect one of the three groups.
3.Open t-test menu and select Classical independent samples t-test
4. Move dependent variables to selection box
5. Move Group to Grouping variable selection box
6. Error message "Maximum number of levels is 2. Variable Group has 3 levels." appears
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-09-04 06:53
Thx for the report.
This is solved in https://github.com/jasp-stats/jasp-desktop/pull/5645
There will be a new version of JASP hopefully in some weeks, which includes the fix. 

Also this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2853

**Closed by tomtomme** 2024-09-04 06:53 UTC
Labels: Module: jaspTTests, OS: Windows 10, Bug
