### ISSUE TITLE
[Feature Request]: Make filter a part of the analysis

### ISSUE THREAD

**Issue by grezniczek** [jasp-stats/jasp-issues#1820] opened 2022-09-06 17:40 UTC
### Description

Instead of a global filter that affects all analyses, add filtering capabilities to each analysis panel

### Purpose

Make life a lot easier

### Use-case

Subgroup-analysis

### Describe the solution you would like

To each analysis panel, add a data filter option - let users filter data for this particular analysis and add a toggle to set whether the global filter should be taken into consideration or not.

### Additional context

This has been brought up a number of times already, but hey, why not once more, since this, in my opinion, would be HUGE!

So, it was yesterday that I learned about JASP, and today, I downloaded and installed it. And my first impression was: Wow! This is great. Why have I not seen this before?!

After playing a bit with it, I came to the question: How can I analyse just a subset of the data. It took me a while to find the small filter icon, but I was so glad I finally found it, because I was afraid that there would not be one and that one would have to make a round-trip to some other software just to limit the data, re-import it (to a new file), and re-create the analyses I'd like to run.

Then, however, came a moment of (rather big) disappointment, when I realized that there is no way to limit or apply the filtering to a particular analysis panel. What's worse, there is no way, it seems, to keep a set of filters. Well, one might us the R syntax and arrange the filter expressions in lines that are commented out as needed, but this doesn't really work because of the invalid syntax when there are hanging "&" (and you can't put them on their own line).

I believe that the ability to filter per-analysis would be a huge benefit.

I've read that one of the concerns is that it might not be clear to (new) users that there might be filters in place. I do not consider this a valid argument against having per-analysis filters, as the fact of an active filter can (and should!) be made quite clear, ideally on the final output, too! (Which currently is not indicated there at all, outside of the actual results).

Ideally, global filters could be named and stored. Compsite filters of such named/stored filters should be possible.
Similarly, it should be possible to apply these named, global filters (again, maybe compositable) to individual analysis panels, plus there should be a facility in each panel to define a filter right there.

Thanks!

And of cource, thank you for providing such a beautiful software in the first place!

**Comment by shun2wang** [comment] 2022-09-07 01:35
It is definitely on our radar,  a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1392 and https://github.com/jasp-stats/jasp-issues/issues/1330

**Closed** 2022-09-07 09:53 UTC
Labels: Feature Request
