### ISSUE TITLE
[Feature Request]: Backward Regression when using categorical variables

### ISSUE THREAD

**Issue by WrldTraveler1632** [jasp-stats/jasp-issues#2321] opened 2023-10-02 17:26 UTC
### Description

Unable to do backward regression at times

### Purpose

Dissertation 

### Is your feature request related to a problem?

Yes, I am unable to run my data the way I want to because one variable is a categorical variable. 

### Is your feature request related to a JASP module?

Regression

### Describe the solution you would like

I would like to be able to run my data like I could in SPSS, even when using categorical data 

### Describe alternatives that you have considered

going back to SPSS, writing that JASP software is a limitation to my dissertation, possibly starting over an using an ANCOVA

**Comment by tomtomme** [comment] 2024-02-09 10:43
@WrldTraveler1632 
I cannot reproduce this with jasp 0.18.3. Can you share your jasp file, by renaming to .zip and drag&drop it here?

**Comment by tomtomme** [comment] 2024-02-21 09:07
@WrldTraveler1632 
I just found out that your request must be a duplicate of the problem described here: https://github.com/jasp-stats/jasp-issues/issues/2597

Lets discuss there!
Closing this one for now. Please reopen, if you disagree!

**Closed by tomtomme** 2024-02-21 09:07 UTC
Labels: Waiting for requester, Module: jaspRegression, Feature Request
