### ISSUE TITLE
[Feature Request]: Add the option to perform normality tests in ANOVA

### ISSUE THREAD

**Issue by wpsilvestre** [jasp-stats/jasp-issues#2695] opened 2024-05-02 11:46 UTC
### Description

Add the option to perform normality tests in ANOVA, such as Shapiro-Wilk, along with the Q-Q plot

### Purpose

Add the option to carry out a normality test procedure, such as Shapiro-Wilk's (or other options)

### Use-case

This feature would benefit any user that works with Jasp

### Is your feature request related to a problem?

No

### Describe the solution you would like

The ANOVA module already has the option of calculating homoscedasticity (Levene's test). The same could be done for a normality of residuals test

### Describe alternatives that you have considered

Although there is the Q-Q plot, for novice users interpreting only the Q-Q graph may be confusing/difficult, and, in some situations, only assessing the graph cannot give a clear view whether the data has a normal distribution of residuals or not

### Additional context

@JohnnyDoorn , as explained above, adding the possibility of carrying out a normality test (such as Levene's and showing the Q-Q plot) may help ease the interpretation of the ANOVA results during analysis.

**Comment by tomtomme** [comment] 2024-05-02 12:37
@wpsilvestre 
Thx for the request.
It is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/490 
Thus we will track the progress there. Feel free to reopen, if I am mistaken!

**Closed by tomtomme** 2024-05-02 12:37 UTC
Labels: Module: jaspAnova, Feature Request
