### ISSUE TITLE
95% CIs around median

### ISSUE THREAD

**Issue by Ivanbuljan** [jasp-stats/jasp-issues#602] opened 2020-01-28 19:56 UTC
Hello, 
My name is Ivan and I work at the medical school. Due to the small samples and asymmetrical distributions, we often use medians instead of means in data presentation. I usually use JASP for any analysis possible, but for calculation of confidence intervals around medians I need to use R, because the current versions of JASP do not have that feature. For that reason, it would be  nice to implement that feature in future versions (if possible, of course). 
Thank you, and all the best, 
Ivan
 
* Enhancement: 95% CIs around median
* Purpose: Presentation of data, and differences between groups.
* Use-case:

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by FransMeerhoff** [comment] 2020-01-29 08:29
Hi @Ivanbuljan 

Thanks for this suggestion. I think this would definitely be possible.

@vankesteren 
Can you have a look at this one?

Cheers Frans

**Comment by vankesteren** [comment] 2020-01-30 09:34
The sampling distribution of the median (and therefore its confidence interval) is not trivial to compute.

We can do either an approximation as follows ([Hojo & Pearson, 1931](https://www.jstor.org/stable/2332422)):

![](https://latex.codecogs.com/gif.latex?%5Csigma_%7Bmedian%7D%20%5Capprox%20%5Csqrt%7B%5Cpi%20/%202%7D%20%5Ccdot%20%5Cfrac%7B%5Csigma%7D%7B%5Csqrt%7BN%7D%7D)

(interestingly, this approximation works better for even sample size than an odd sample size)

Or run a simulation-based approximation (bootstrap).

What does the R procedure you use do?

**Comment by Ivanbuljan** [comment] 2020-01-30 09:49
Hi Erik,

Well, in R I usually use MedianCI function in DescTools package (if I need
median and CI for one group), or in another case (if I need medians and CIs
for groups) I use groupwiseMedian function from rcompanion package.
I am fine with whichewever approach you decide to use, because i know it is
tricky sometimes to compute this, especially with small samples. If it
helps, I found an article from BMJ (it is rather old) about calculation
different non-parametric parameters and it is in the attachment.
Best,
Ivan


čet, 30. sij 2020. u 10:34 Erik-Jan van Kesteren <notifications@github.com>
napisao je:

**Comment by tomtomme** [comment] 2024-02-19 11:28
@Ivanbuljan 
closing as duplicate of 
https://github.com/jasp-stats/jasp-issues/issues/1529
https://github.com/jasp-stats/jasp-issues/issues/1698

Only the latter will stay open and gathers alle infos.

please reopen, if you do not aggree

**Closed by tomtomme** 2024-02-19 11:28 UTC
Labels: First project, Module: jaspDescriptives, Feature Request
