### ISSUE TITLE
[Bug]: Value-column too thin in label-editor

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1576] opened 2022-01-15 16:15 UTC
### JASP Version

0.16

### What analysis are you seeing the problem on?

Data editing mode

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I am editing data with Swedish variable namnes i get some funny  looking letters (see below). This was also an issue but in different analysis modes during the development of version 0.15. I am using a CSV UTF-8  data file () this is normally the only CSV format that works with Swedish langue an the additional letter å, ä and ö. Would be grateful if the could be fixed for the new version because it it a bit annoying😁. 
![Namnlös](https://user-images.githubusercontent.com/79397662/149628997-7684f047-6829-445c-9dd2-89025c91edff.png)
[1 Dataimport.csv](https://github.com/jasp-stats/jasp-issues/files/7875341/1.Dataimport.csv)

All the best
Per

### Expected Behaviour

Normal letters

### Steps to Reproduce

1. There is a screen shot
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by PerPalmgren** [comment] 2022-01-15 18:52
Strangely if I close it and re-open it a second time seems fine :-o

**Comment by PerPalmgren** [comment] 2022-01-19 14:55
Was this report noticed?

**Comment by boutinb** [comment] 2022-01-21 08:23
Apparently, this occurs only on Windows. On my Mac there is no problem either.

**Comment by PerPalmgren** [comment] 2022-01-21 08:46
Will this be rectified?

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet - a medical university

**Comment by boutinb** [comment] 2022-01-21 09:11
@JorisGoosen Can you have a look at this issue?

**Comment by JorisGoosen** [comment] 2022-01-21 12:19
Hey all,

I can have a look of course, but from the issue I don't really understand what are exactly the "funny looking letters" ?

First of all, if I load the attached csv I get:
![image](https://user-images.githubusercontent.com/29062713/150525770-ab78f8c6-dedb-4845-8f8c-adac0dd11a6b.png)

Looks fine right?

So then when I look at the OP screenshot I see:
![image](https://user-images.githubusercontent.com/29062713/150525833-7a3c2638-a55f-47d1-86ca-47aaccb7adfb.png)

Which is not actually strangely rendered letters, but actually the "Value" column seems to be too thin, which makes it overlap with "Label" and definitely looks funny. But there is not actually a problem with the swedish characters as far as I can see?

But maybe I misunderstand.

Of course even if the only problem is that that column is too thin that would still have to be rectified, no doubt.

**Comment by PerPalmgren** [comment] 2022-01-21 12:30
You are completely correct Joris. It has nothing to do with the Swedish but the column with.👍
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by PerPalmgren** [comment] 2022-05-21 12:19
Has these thin columns been rectified for 0.16.3?

**Comment by PerPalmgren** [comment] 2022-11-15 07:50
This still seems to be a problem in 0.16.4
![Namnlös](https://user-images.githubusercontent.com/79397662/201860349-74412d35-607b-4f8d-a24a-7a1026905cc6.png)

**Comment by shun2wang** [comment] 2022-11-15 08:20
@PerPalmgren Could you try check/uncheck "use Qt's textrendering" option on/off?

I can reproduce it when use native textrendering but Qt is OK.

**Comment by PerPalmgren** [comment] 2022-11-15 08:25
Yes, then it works👍! What does this do?

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by shun2wang** [comment] 2022-11-15 08:32
I'm not sure, @JorisGoosen is expert in this field 👍

**Comment by PerPalmgren** [comment] 2022-11-15 08:33
Good if this could be rectified.

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by JorisGoosen** [comment] 2022-11-15 09:22
Hey all,

The text rendering is about exactly how the letters in the interface are converted to pixelvalues.
The native rendering is from Windows itself and the qt one, well, I guess that is obvious.

We used to have the native one as default on windows because it seemed to render a bit sharper.
However, there were some other issues and since then we have switched to setting Qt as default rendering and left the native one as a fallback just in case.

However, if youve used JASP with a version that used native as default this will have been saved to your local settings.
And Im fairly sure people would not take kindly to having their settings get lost with every new JASP version.

**Comment by PerPalmgren** [comment] 2023-02-01 14:36
@JorisGoosen @boutinb @shun2wang @vandenman 
This still be a probleam in version 0.17 (se image below)
Kind regards
Per
![Namnlös](https://user-images.githubusercontent.com/79397662/216072440-632c3574-3e75-40d0-a049-28ecfcd975a9.png)

**Comment by shun2wang** [comment] 2023-02-02 02:26
Oh yes, This may be because we have bound `valueColWidth` to the maximum width of the value somewhere, so when the "value" is a singular number such as "1", overlapping and crowding may occur, perhaps Giving an adequate initial minimum width can solve this I guess.

![image](https://user-images.githubusercontent.com/10348402/216215388-fb4e1597-1386-444b-88a1-09b3d039557d.png)
![image](https://user-images.githubusercontent.com/10348402/216215447-60f44ca5-8fbf-49d6-8a69-6dc52892f978.png)

**Comment by JorisGoosen** [comment] 2023-02-02 07:48
Well I think the variableswindow tableview width-determiner should just also take the title into account nd then it should be fine.

**Comment by JorisGoosen** [comment] 2023-02-02 07:49
(Because the width could change drastically with other languages which wouldnt work so well with a minimum width)

**Comment by PerPalmgren** [comment] 2023-06-10 06:51
This is still an issue in 0.17.2.1

**Comment by JorisGoosen** [comment] 2023-06-10 08:06
> This is still an issue in 0.17.2.1

Indeed, but the fix will be included with the data-editing version that is upcoming, 0..18

**Closed** 2023-06-15 12:13 UTC
Labels: Fonts
