### ISSUE TITLE
[Bug]: Error when running Reliability Test 

### ISSUE THREAD

**Issue by tarajbur** [jasp-stats/jasp-issues#1742] opened 2022-06-14 08:42 UTC
### JASP Version

0.16.2

### JASP Module

jaspReliability

### What analysis are you seeing the problem on?

unidimensional reliability 

### What OS are you seeing the problem on?

mac Monterey 

### Bug Description

This analysis terminated unexpectedly.

Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Applications/JASP.app/Contents/Modules/renv-cache/v5/Bayesrel/0.7.3/85bae416106eba0f3347ad27232b5a60/Bayesrel/libs/Bayesrel.so':
  dlopen(/Applications/JASP.app/Contents/Modules/renv-cache/v5/Bayesrel/0.7.3/85bae416106eba0f3347ad27232b5a60/Bayesrel/libs/Bayesrel.so, 0x0006): Library not loaded: @executable_path/../Frameworks/R.framework/Versions/4.1-arm64/Resources/opt/R/arm64/gfortran/lib/libgfortran.dylib
  Referenced from: /Applications/JASP.app/Contents/Modules/renv-cache/v5/Bayesrel/0.7.3/85bae416106eba0f3347ad27232b5a60/Bayesrel/libs/Bayesrel.so
  Reason: tried: '/Applications/JASP.app/Contents/MacOS/../Frameworks/R.framework/Versions/4.1-arm64/Resources/opt/R/arm64/gfortran/lib/libgfortran.dylib' (no such file), '/usr/lib/libgfortran.dylib' (no such file)

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

reliabilityUniDimFrequentist(...)

.frequentistComputeScaleResults(jaspResults, dataset, options, model)

loadNamespace(x)

library.dynam(lib, package, package.lib)

dyn.load(file, DLLpath = DLLpath, ...
[JASPreport.csv](https://github.com/jasp-stats/jasp-issues/files/8898014/JASPreport.csv)
)

### Expected Behaviour

Reliability output

### Steps to Reproduce

1. Upload data
2. Reliability > Unidimensional Reliability > add relationship score and mainstream score
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-06-20 09:43
this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1694 and is fixed with 0.16.3

**Closed by juliuspf** 2022-06-20 09:43 UTC
