### ISSUE TITLE
macOS wrongly thinks Jasp is unable to open .csv files 

### ISSUE THREAD

**Issue by JasperRobinson** [jasp-stats/jasp-issues#857] opened 2020-07-07 09:40 UTC
* JASP version: 0.11.1

* OS name and version: macOS 10.15.5
* Analysis: ⌘ Clicking on a .csv file gives the option "Open With" and a selection of likely applications. 
* Bug description: Jasp does not appear as an application capable of opening .csv files. 

This means that it is necessary either to: 
1. Put Jasp on the mac's dock and drag the .csv onto it while holding ⌥ ⇧, or; 
2. Get the Open With widow to show "All Applications" rather than just "Recommended Applications", then go back and select Jasp
3. As 2 but change the default application to always open with Jasp—where you'd probably used TextEdit. 

[2 - AE Phase 2 NOFEED-wide.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4883977/2.-.AE.Phase.2.NOFEED-wide.jasp.zip)

I've been told that Jasp would need to be updated to include something that tells macOS that it can open .csv files—perhaps other formats that I have not tried too...?

* Expected behaviour:

**Comment by JorisGoosen** [comment] 2020-07-07 12:27
Aah, well it seems that we are not registering it correctly as being capable of that. I assure you that JASP *can* open csv files.
This is a good one to add to the installer though!

**Comment by JasperRobinson** [comment] 2020-07-07 12:41
Thank you!

Yes, Jasp *can* open .csv files

It’s also odd that macOS doesn’t ‘learn’ this once it has successfully opened once—but that’s a matter for a different forum!

**Comment by djdekker** [comment] 2022-02-25 20:16
Hello @amirmasoudabdol,
Would you please consider if this issue could be solved? It would require JASP to be registered in macOS as an app that can open .csv files. Thank you very much for the great work you've been doing recently on the Mac version of JASP!
Greetings!

**Comment by amirmasoudabdol** [comment] 2022-02-28 08:36
@djdekker, thanks for bringing this to my attention. Yes, I will look into it as part of our macOS installer, but it might not make it to the immediate release, but the one after it!

**Comment by djdekker** [comment] 2022-03-12 07:56
Great, thank you for your attention!

**Comment by tomtomme** [comment] 2024-01-10 15:45
@djdekker & @JasperRobinson 
Can you check if this is fixed? It seems to be according to the merged patch from march 2022

**Comment by djdekker** [comment] 2024-01-10 18:56
@tomtomme I can confirm that this issue has been fixed. In macOS, JASP is now registered as an app that can open .csv files. Thank you for your attention.

**Closed** 2024-01-10 19:45 UTC
Labels: waiting for requester
