### ISSUE TITLE
[Feature Request]: Ability to open large CSV files

### ISSUE THREAD

**Issue by JHJP** [jasp-stats/jasp-issues#2715] opened 2024-05-10 13:47 UTC
### Description

I attempted to open a CSV file of approximately 8GB in size. However, the following error message appears. "Unable to open file because: Could not access file"

**Comment by tomtomme** [comment] 2024-05-11 19:28
Thx for the request.
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2327
Lets track progress on this there :)

**Closed by tomtomme** 2024-05-11 19:28 UTC
Labels: Feature Request
