### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by bmatyasb** [jasp-stats/jasp-issues#2800] opened 2024-06-27 17:06 UTC
### Description

Plot size settings

### Purpose

The idea is that you don't have to break the mouse to get the same size graphics.

### Use-case

Making plots

### Is your feature request related to a problem?

I would like to make the same type of diagrams, but often the diagrams are too big. I would like to scale them a bit, but I can only do that with a mouse. Which doesn't always work well. In addition, it's impossible to make figures of exactly the same size.

### Describe the solution you would like

Just have an option in the edit image where you can set the width and length of a figure.

### Additional context

Obviously you can save them in ppt, then scale them there, then export the plot from ppt. But this is an extra tedious step. Many people want to do full analyses in JASP, because it's a great piece of software anyway. But because of the inconveniences with plots (lack of scaling and editing), many times you simply have to abandon JASP.

**Comment by tomtomme** [comment] 2024-06-28 09:00
closing this one, since it is a duplicate of: https://github.com/jasp-stats/jasp-issues/issues/1444

please reopen if you disagree!

**Closed by tomtomme** 2024-06-28 09:00 UTC
Labels: Feature Request
