### ISSUE TITLE
[Feature Request]: Coherence in ANOVA output

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1741] opened 2022-06-10 15:12 UTC
### Description

Order of variables in ANOVA descriptives output

### Purpose

Consistency between outputs

### Is your feature request related to a problem?

When reordering levels in variabels and not employing alphabetical default (see figure) there seems to be a glitch. This works fine when in the Descriptive module (see picture). However, in the ANOVA module there seems to be an inconsistency. It follows the reordering for the descriptive plot but not for the table (see picture).  

### Describe the solution you would like

I would like a coherence in JASP outputs. Thus, when reordering levels in a variable this is reflected throughout all outputs.  

### Additional context

Picture 1
![Namnlös](https://user-images.githubusercontent.com/79397662/173095365-c48d253e-43a4-4430-81ea-dc19689beccc.png)
Picture 2
![Namnlös 1](https://user-images.githubusercontent.com/79397662/173095413-89ee719a-205a-4676-8354-5976a4c0be2a.png)
Picture 3
![Namnlös 2](https://user-images.githubusercontent.com/79397662/173095496-ad1be5f0-20a4-4efe-af77-46cd4bbeac50.png)

I also see there seem still to be a problem with the thin value column (encircled in green in picture 1.) see earlier post https://github.com/jasp-stats/jasp-issues/issues/1576

**Comment by Kucharssim** [comment] 2022-06-10 17:05
Dear @PerPalmgren,

thank you for the report, this is indeed not optimal and should be fixed!

@JohnnyDoorn, could you have a look please?

**Comment by PerPalmgren** [comment] 2023-02-21 18:46
This still to be s problem in JASP 017.1

**Comment by JohnnyDoorn** [comment] 2023-02-27 16:22
Thanks for the reminder @PerPalmgren ! Although I think the thin column issue has been fixed in the meantime?
It seems the issue is in the descriptives table for all ANOVA's (but only the descriptives tables - e.g., contrasts and posthocs are fine). @vandenman  was there a reason for the internal reordering to the terms for the descriptives table?

**Comment by PerPalmgren** [comment] 2023-04-01 09:38
@vandenman @JohnnyDoorn Great if this could be rectified for the next version as it make little more cumbersome to read te results. 
By the way! Any news on release date for next version?

**Comment by PerPalmgren** [comment] 2023-05-01 15:20
@vandenman @JohnnyDoorn 
Will this be incorporated in the updated version?
All the best
Per

**Comment by PerPalmgren** [comment] 2023-05-23 20:39
So this was not rectified in version 0.17.2?

**Comment by vandenman** [comment] 2023-05-24 07:19
I don't think so. @JohnnyDoorn do you have time for this or shall I give it a try?

**Comment by JohnnyDoorn** [comment] 2023-05-24 10:05
If you can that would be great! i guess it affects all ANOVA's?

**Comment by PerPalmgren** [comment] 2023-06-07 08:25
@vandenman Will this be done in the near future?

**Comment by tomtomme** [comment] 2024-02-08 11:14
@JohnnyDoorn 
Can you review vandenmans PR so that the fix can be included in 0.19?

**Closed** 2024-02-09 15:37 UTC
Labels: Module: jaspAnova, Feature Request
