### ISSUE TITLE
[Bug]: QtWebEngineQuick not initialized with some graphics render backend

### ISSUE THREAD

**Issue by Yojai** [jasp-stats/jasp-issues#2643] opened 2024-03-22 02:25 UTC
### JASP Version

0.18.3

### JASP Module

NA

### What analysis are you seeing the problem on?

Linear Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I was running a multiple regression model but no results were showed. There also wasn't any error reminders, just an empty space.
![screenshot](https://github.com/jasp-stats/jasp-issues/assets/74539983/8a55b694-0079-4d40-916a-dac2d9561b31)

### Expected Behaviour

An analysis table

### Steps to Reproduce

1. Open the csv file and insert the data
2. Choose Regression-Linear regression
3. Add dependent variable and factors
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment] 2024-03-22 02:51
Hi @Yojai thanks for the report, could you try this:

- Start a command prompt by typing command prompt in the Start menu.
- Type "c:\Program Files (x86)\JASP\JASP.exe --safeGraphics" > logJASP.txt
- Check whether you have still the same problem.
- If yes, type 'notepad logJASP.txt'
- Send me these log files in a comment of this GitHub issue.

if still has problems, you can try start a command prompt again and try:

```
c:\Program Files (x86)\JASP\JASP.exe  --webEngineArgs --remote-debugging-port=1234
```
then open the Microsoft edge browser and open the link of: `http://localhost:1234`
click first link of 'JASP' -> click 'console' and then give us a screenshot here.

with thanks.

**Comment by tomtomme** [comment] 2024-03-22 07:52
Last bug that did show such a completely empty result pane the computer just needed some restarts and windows updates. But sure, if that does not help, shunwang showed the way to go.

**Comment by Yojai** [comment] 2024-03-25 01:37
Thank you @shun2wang, I have tried your suggestions but I still have the same problem. The log files were just empty but the link  you shared is blocked from my computer. Is there any other action I can take to fix this?

**Comment by shun2wang** [comment] 2024-03-25 01:50
>you shared is blocked from my computer

Hi, What do you mean of this? could I get a screenshot? you should first run in cmd.exe `c:\Program Files (x86)\JASP\JASP.exe  --webEngineArgs --remote-debugging-port=1234` to open JASP.exe with that analysis and then open `http://localhost:1234` in Edge/Chrome browser.

**Comment by RensDofferhoff** [comment] 2024-03-25 09:02
Hmmm a webengine crash. Are you running Windows 11 with any sort of virtualization? VM or container solutions, etc?

**Comment by Yojai** [comment] 2024-03-25 09:58
Yes sure @shun2wang, I already put the screenshots in the comment below
![screenshot1](https://github.com/jasp-stats/jasp-issues/assets/74539983/f4329ec0-811c-40e2-861e-7c63999b2c22)
![screenshot2](https://github.com/jasp-stats/jasp-issues/assets/74539983/49ecfc99-e568-4475-b7f0-9b95ec39a43e)
![screenshot3](https://github.com/jasp-stats/jasp-issues/assets/74539983/4bb5f503-70f7-4377-a3ee-420855ff8aaf)

And I am also using Windows 11

**Comment by shun2wang** [comment] 2024-03-25 11:52
Did you try check/uncheck the option in `Preferences  -> Interface -> safe graphics mode` then restart JASP?

**Comment by Yojai** [comment] 2024-03-26 01:41
Yes Shun @shun2wang , I checked the safe graphics mode and restarted JASP at the beginning.

Bruno @boutinb
1. The browser page I saw was an empty page with a heading line saying “Inspectable pages”on the top.
![截图](https://github.com/jasp-stats/jasp-issues/assets/74539983/f02d2285-c46a-47b2-ba4b-6179a865da38)
2. Yes, my Windows system is kept up to date.
3. I checked the 'Safe graphic mode' and restart JASP.
4. I did all the stuff above and unfortunately they did not help. The logs are attached below.
[JASP 2024-03-26 09_15_30 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/14751187/JASP.2024-03-26.09_15_30.Desktop.log)
[JASP 2024-03-26 09_15_30 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/14751189/JASP.2024-03-26.09_15_30.Engine.0.log)
[JASP 2024-03-26 09_30_20 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/14751190/JASP.2024-03-26.09_30_20.Desktop.log)
[JASP 2024-03-26 09_30_20 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/14751191/JASP.2024-03-26.09_30_20.Engine.0.log)
[JASP 2024-03-26 09_30_20 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/14751192/JASP.2024-03-26.09_30_20.Engine.1.log)

Thank you Shun and Bruno for your patient instructions and kind help.

**Comment by shun2wang** [comment] 2024-03-26 02:48
Well, if you click the 'info' button (the blue `i` icon) in analysis panel and see if help doc window are showing ok?

**Comment by boutinb** [comment] 2024-03-26 08:28
@Yojai Hmm our most common tricks do not seem to work for you....
When you start JASP from the command line, do you see some output on the terminal? If yes could you give us this output. If no, could you start JASP from your home folder with: `"c:\Program Files (x86)\JASP\JASP.exe" > logJASP.txt` and give us this logJASP.txt. For this to work you need to be on a folder where you have the permission to add a file, and if you start the command prompt from the start menu, it should set the default folder to your home folder where should have this right.

**Comment by Yojai** [comment] 2024-03-26 10:38
to @shun2wang The 'infor' button didn't help neither and the help doc window was also empty.

to @boutinb Well, there is no output on the terminal after I start JASP from the command line. I tried to start JASP from my home folder but it opened a browser page saying the IP address is blocked.
![screenshot](https://github.com/jasp-stats/jasp-issues/assets/74539983/e378e375-ed0f-41ad-bb60-9bcdee7738bc)

**Comment by JorisGoosen** [comment] 2024-03-26 11:59
@Yojai what kind of videocard do you have?

Is it perhaps an intel and is it possible to get a new(er) driver?

**Comment by JorisGoosen** [comment] 2024-03-26 12:01
Also, could you try to save a jasp-file and upload it here?
(You have to change the extension to zip or put the file in a zip to be allowed to attach it here)

**Comment by Yojai** [comment] 2024-03-27 01:04
Yes Joris @JorisGoosen, I am using an intel Grphics UHD 630, and the JASP file is attached below. 
[data.zip](https://github.com/jasp-stats/jasp-issues/files/14766145/data.zip)

**Comment by JorisGoosen** [comment] 2024-03-27 08:56
> Yes Joris @JorisGoosen, I am using an intel Grphics UHD 630, and the JASP file is attached below. [data.zip](https://github.com/jasp-stats/jasp-issues/files/14766145/data.zip)

Thanks @Yojai !

This definitely confirms that the results are not working *at all* (I was hoping it was maybe just invisible)
In any case, good to know it is an intel card... They do sometimes give trouble.

Did you try going to intel.com and installing the latest driver?
I see this one for your system: https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html

**Comment by tomtomme** [comment] 2024-03-27 10:22
Works for me on intel iGPU manjaro flatpak with 0.18.3 and 0.19beta
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/c255ac7e-68d7-4dd8-ab27-e61daa6c4d40)

so yeah, maybe windows driver specific issue

**Comment by boutinb** [comment] 2024-04-03 10:02
Hi @Yojai Could you start the Task Manager (CTRL-ALT-DELETE) and check whether 2 QtWebEngineProcess processes has started (onder the JASP process)
![JASPProcess](https://github.com/jasp-stats/jasp-issues/assets/503332/389a68c5-d147-41f3-8003-a4ff9a0cd7c2)

**Comment by boutinb** [comment] 2024-04-03 10:04
Also it is strange that you don't have a log file when starting JASP from the command line:
`"c:\Program Files (x86)\JASP\JASP.exe --safeGraphics" > logJASP.txt`
I have tried it, and you have first to stop JASP before having the log messages written in the file.

**Comment by JorisGoosen** [comment] 2024-04-03 12:44
Windows on release doesnt really print anything

**Comment by JorisGoosen** [comment] 2024-04-03 12:45
Just run `"c:\Program Files (x86)\JASP\JASP.exe --safeGraphics --logToFile"`. and check the normal log location...

**Comment by shun2wang** [comment] 2024-05-15 14:46
hi @Yojai sorry for delay. could you try this version https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-delayCheckVersion-HEAD.msi

**Comment by tomtomme** [comment] 2024-05-24 10:53
@Yojai 
So again thx for the report. Since this bug is now confirmed to be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2643 - I will close this one. If you have feedback for us, please share it there. Thx!

**Closed by tomtomme** 2024-05-24 10:53 UTC
Labels: Waiting for requester, OS: Windows 11, Bug
