### ISSUE TITLE
[Bug]: When the "bootstrap number" of network analysis is too high, it cannot be analyzed.

### ISSUE THREAD

**Issue by feng-666-cell** [jasp-stats/jasp-issues#2917] opened 2024-09-19 03:04 UTC
### JASP Version

0.19.0

### JASP Module

Network

### What analysis are you seeing the problem on?

bootstrap

### What OS are you seeing the problem on?

Windows 10

### Bug Description

[4c7956142f7048adee72877f5d58eae.zip](https://github.com/user-attachments/files/17052998/4c7956142f7048adee72877f5d58eae.zip)
[6fc31be64f080acfcd4d8072ec32034.zip](https://github.com/user-attachments/files/17052999/6fc31be64f080acfcd4d8072ec32034.zip)

### Expected Behaviour

Should've handled my boot strap 500 times

### Steps to Reproduce

When I only process a few times or even a dozen times, the error does not occur, and when I increase the number of processes to more than 100 times, it will occur.

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 10 Version 22H2
Product Version: 10
Kernel Type: winnt
Kernel Version: 10.0.19045
Architecture: x86_64
Install Path: C:/Program Files/WindowsApps/45842JASP.JASP_0.19.1.0_x64__wz6q9dg667qsj
Platfotm Name: windows
System Local: zh_CN

-------- Extra Info --------
Current code page
�����ҳ: 936
Active code page: 65001

Host Name:                 LAPTOP-MAF57L8D
OS Name:                   Microsoft Windows 10 家庭中文版
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          8618383005335
Registered Organization:   HP
Product ID:                00342-35459-56375-AAOEM
Original Install Date:     2021/5/17, 16:30:55
System Boot Time:          2024/9/19, 9:08:16
System Manufacturer:       HP
System Model:              HP Pavilion Gaming Laptop 15-dk0xxx
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2400 Mhz
BIOS Version:              Insyde F.04, 2019/5/3
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume4
System Locale:             zh-cn;Chinese (China)
Input Locale:              zh-cn;Chinese (China)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
Total Physical Memory:     8,042 MB
Available Physical Memory: 1,582 MB
Virtual Memory: Max Size:  12,906 MB
Virtual Memory: Available: 2,374 MB
Virtual Memory: In Use:    10,532 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-MAF57L8D
Hotfix(s):                 38 Hotfix(s) Installed.
                           [01]: KB5042097
                           [02]: KB5030841
                           [03]: KB4562830
                           [04]: KB4580325
                           [05]: KB5003791
                           [06]: KB5011048
                           [07]: KB5011050
                           [08]: KB5012170
                           [09]: KB5015684
                           [10]: KB5008575
                           [11]: KB5043064
                           [12]: KB5006753
                           [13]: KB5007273
                           [14]: KB5011352
                           [15]: KB5011651
                           [16]: KB5014032
                           [17]: KB5014035
                           [18]: KB5014671
                           [19]: KB5016705
                           [20]: KB5018506
                           [21]: KB5020372
                           [22]: KB5022924
                           [23]: KB5023794
                           [24]: KB5028380
                           [25]: KB5029709
                           [26]: KB5031539
                           [27]: KB5032392
                           [28]: KB5032907
                           [29]: KB5034224
                           [30]: KB5036447
                           [31]: KB5037018
                           [32]: KB5037240
                           [33]: KB5037995
                           [34]: KB5039336
                           [35]: KB5041579
                           [36]: KB5043935
                           [37]: KB5005699
                           [38]: KB5034441
Network Card(s):           5 NIC(s) Installed.
                           [01]: Sangfor SSL VPN CS Support System VNIC
                                 Connection Name: 以太网 2
                                 Status:          Media disconnected
                           [02]: VPN Client Adapter - VPN
                                 Connection Name: VPN - VPN Client
                                 Status:          Media disconnected
                           [03]: Intel(R) Wireless-AC 9560 160MHz
                                 Connection Name: WLAN
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.16.255.254
                                 IP address(es)
                                 [01]: 10.16.247.13
                                 [02]: fe80::9af0:2a51:19a:878d
                           [04]: Realtek Gaming GbE Family Controller
                                 Connection Name: 以太网
                                 Status:          Media disconnected
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: 蓝牙网络连接
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-09-19 06:11
@feng-666-cell 
thx for the report. This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2863
Lets discuss there.

**Closed by tomtomme** 2024-09-19 06:11 UTC
Labels: Module: jaspNetwork, OS: Windows 10, Bug

**Comment by tomtomme** [comment] 2024-09-19 06:51
@feng-666-cell 
More Infos on this but from vandenman, who wrote this in https://github.com/jasp-stats/jasp-issues/issues/2088:

> Thanks for reporting the issue! What goes wrong internally is that the correlation matrix is not positive definite. If you change the correlation method to Cor or the method for Missing values to Exclude listwise then the error disappears and you do get output. I'll adjust the code so you receive a more informative error message in the future.

Also switching form non-parametric to parametric bootstrapping could help

Sorry for the huge delay. The better error message for the network module was added at some point but seems not to work in all cases. We will work on a fix.
