### ISSUE TITLE
[Bug]: VIF calculation seem different for linear and logistic regression

### ISSUE THREAD

**Issue by JuliusWelzel** [jasp-stats/jasp-issues#1800] opened 2022-08-10 06:52 UTC
### JASP Version

0.16.2

### What analysis are you seeing the problem on?

Regression

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When comparing VIF values for parameters I get different outcomes for the linear and logistic regression module. As I could not find how these are determined respectively, I was wondering if there might be a bu. 

### Expected Behaviour

Same VIF values in both modules

### Steps to Reproduce

1. Load data
2. Run linear regression (including Collinearity diagnostics)
3. Run logistic regression (including Multicollinearity diagnostics)
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JuliusWelzel** [comment] 2022-08-10 06:56
![Screenshot 2022-08-10 085557](https://user-images.githubusercontent.com/52565341/183835227-ff36c774-1d72-4f75-85ff-605c9524c8a9.png)

**Comment by juliuspf** [comment] 2022-08-10 07:28
Hi @JuliusWelzel, thanks for the report. Could you attach a .jasp or a data file that causes this issue? I am not an expert in regression, but could you explain to me why you expect to get the same results with different regressions?

**Comment by juliuspf** [comment] 2022-08-10 08:47
somehow, that did not work for me. I can't get any file when clicking on this link

**Comment by Kucharssim** [comment] 2022-08-10 08:57
It's ok, I know how to reproduce it, I am just writing an explanation for this result, so need to bother with the data set :)

**Comment by Kucharssim** [comment] 2022-08-10 09:52
Thank you @JuliusWelzel for the report. It is true that the collinearity diagnostics are different for the same set predictors used in a different model, because the VIF is dependent not only on the predictors, but also on the model used to predict the dependent variable. The VIF calculated in JASP is a generalisation of the VIF, and is calculated by the following formula ([Fox & Monette, 1992](https://www.tandfonline.com/doi/abs/10.1080/01621459.1992.10475190)):

![Screenshot 2022-08-10 at 11 02 28](https://user-images.githubusercontent.com/7093546/183861271-8c804a21-2398-4567-a8d9-99f017fa914c.png)

Where R is the correlation (or covariance) matrix of the predictors (R11 is then the covariance matrix of the predictor we calculate VIF for and R22 the covariance matrix of the rest of the predictors). However, this formula can be applied for the covariance matrix of the estimated regression coefficients ([Fox, 2016](https://socialsciences.mcmaster.ca/jfox/Books/Applied-Regression-3E/index.html)). In case of a linear regression, this gives the identical result as if we take the covariance matrix of the predictors, but for other models it makes a difference. This makes sense because VIF sort of tells you how much are the standard errors inflated compared to a hypothetical scenario that the predictors would be uncorrelated, and this will not only depend on the correlations between the predictors, but also on the model that was used.

Just for the sake of transparency, here is an example (using the [mtcars](https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/mtcars) data set), where I predict variable `vs` with variables `mpg`, `cyl`, and `hp`. 

In JASP, the VIF for linear regression is 
![Screenshot 2022-08-10 at 11 30 37](https://user-images.githubusercontent.com/7093546/183867582-4b31ecba-3801-4a39-8377-0c8c446bfb68.png)

And for logistic regression is
![Screenshot 2022-08-10 at 11 31 16](https://user-images.githubusercontent.com/7093546/183867680-68c1b4a5-98a8-490c-9642-88f7fa56fd9f.png)

We can reproduce these results in R using the [`car`](https://cran.r-project.org/web/packages/car/index.html) package that implements this VIF calculation:

```r
df <- mtcars

linearModel <- lm(vs ~ mpg + cyl + hp, data = df)
car::vif(linearModel)
#      mpg      cyl       hp 
# 3.856662 4.993840 3.439491 

logisticModel <- glm(vs ~ mpg + cyl + hp, data = df, family = binomial())
car::vif(logisticModel)
#      mpg      cyl       hp 
# 3.611485 4.011240 2.096281  
```

or we can do the same manually. Here I do the calculation only for the predictor `mpg`, the formula would be the same for the other predictors would be the same, just different terms entered into the equation.

In linear regression

```r
# define helper function that implements the formula above
vif <- function(R, which) {
  R11 <- R[ which, which,drop=FALSE]
  R22 <- R[-which,-which,drop=FALSE]
  det(R11) * det(R22) / det(R)
}

# using covariance between predictors
covPredictors <- cov(df[,c("mpg", "cyl", "hp")])
vif(covPredictors, 1) # 3.856662

# using covariance between regression coefficients
covLinear <- vcov(linearModel)[-1,-1]
vif(covLinear, 1) # also 3.856662
```

In logistic regression

```r
covLogistic <- vcov(logisticModel)[-1,-1]
vif(covLogistic, 1) # 3.611485
```

Attached is the jasp file I used: [vif.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/9298865/vif.jasp.zip)


I hope this clarifies the problem! I will close the issue now, please feel free to reopen if you still have a suspicion there is an error in the calculations. Thank you!

**Closed by Kucharssim** 2022-08-10 09:52 UTC
Labels: Module: jaspRegression

**Comment by JuliusWelzel** [comment] 2022-08-10 10:08
Thanks, that clarified it. Is the VIF calculation somewhere referenced in the JASP documentation?
