### ISSUE TITLE
Jasp crashes, and causes my system to crash.  I have uninstalled and reinstalled but is does not function

### ISSUE THREAD

**Issue by thesaw123** [jasp-stats/jasp-issues#402] opened 2019-06-26 19:21 UTC
* JASP version:
* OS name and version:
* Analysis:
* Bug description:
* Add JASP files as a zip:
* Screenshot: 
* Expected behaviour:
* Steps to reproduce:

**Comment by JorisGoosen** [comment] 2019-06-27 09:02
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/391

**Comment by JorisGoosen** [comment] 2019-06-27 09:03
And if it is not, then please flesh out this issue to give a fuller description of the problem.

**Closed by JorisGoosen** 2019-06-27 09:02 UTC
