### ISSUE TITLE
A post hoc analysis for Pearson’s chi-squared test for categorical data

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1442] opened 2021-10-02 16:18 UTC
* Enhancement: Posthoc for Chi-square
* Purpose: Not have to calculate by hand
* Use-case:

**Is your feature request related to a problem? Please describe.**
 When computing Pearson’s Chi-squared test the only result you get is that you know that there is a significant difference in the data. When using larger contingency tables like 3x3 or even 2x3 it is cumbersome to search which parts of the data are responsible for differences. In R there is apparently a package that can produce standardized residuals and which are also accompanied with p-values. This would be REALLY good thing in JASP. Presently me and my students have to calculate this by hand. I am not a R guy at all but as JASP is simple, clean and user friendly program but that runs with the power of R. I think this would a very valuable contributions for teachers, students and researchers. 

**Describe the solution you'd like**
 Please see the solution here: https://cran.r-project.org/web/packages/chisq.posthoc.test/vignettes/chisq_posthoc_test.html
**Describe alternatives you've considered**
 

**Additional context**

**Comment by JohnnyDoorn** [comment] 2021-10-05 15:57
I think this belongs in the "more love for contingency table" project, which I think @FBartos is undertaking?

**Comment by PerPalmgren** [comment] 2021-11-12 16:22
Just wanted to check if this request for presumptive feature is advancing?

**Comment by boutinb** [comment] 2021-11-15 17:15
@FBartos How far are you with this?

**Comment by FBartos** [comment] 2021-11-16 09:12
I did not have time to start it yet, It would be probably best to delegate this task to someone else.

**Comment by EJWagenmakers** [comment] 2021-11-16 09:37
I think we'll probably have to wait with this feature until Frantisek has the time to give more love to contingency tables generally. There are also some students who could help out I guess, so we'll keep our eyes open

**Comment by PerPalmgren** [comment] 2021-12-11 11:28
I saw that the same request as mine was already posted  in november 2020 on the post "Adjusted standardized residuals to chi square tests #727". It was responded  that standardized and adjusted standardized residuals was going to be added to the chi square tests. How is this work progressing?
All the best 
Per

**Comment by PerPalmgren** [comment] 2022-01-06 14:00
@EJWagenmakers @FBartos @JohnnyDoorn @boutinb I really hope that this will come in the near future🤩 so researchers and students using JASP dont need to use SPSS for it or calculate it by hand.

**Comment by boutinb** [comment] 2022-01-12 16:03
@FBartos Is this issue still on your radar?

**Comment by EJWagenmakers** [comment] 2022-01-12 22:46
I'm positive Frantisek is still eager to improve the contingency table funcationality :-)

**Comment by PerPalmgren** [comment] 2022-01-14 15:44
Analysis with residuals (Pearson) and standardized residuals would really be so beneficial. You can do them in R, see:
https://stackoverflow.com/questions/52656990/residual-analysis-based-on-the-results-of-chi-squared-test-of-independence-in-r
See also the link that @EJWagenmakers have earlier referred to: https://github.com/jasp-stats/jasp-issues/issues/727
I think it does not to be so fancy. So in "Frequencies" under "Contingency tables", just adding under "Cells" a heading "Residuals" with three tick buttons: unstandardized, standardized and adjusted standardized. These statistics are then added to the table :-). Like in SPSS.

**Comment by PerPalmgren** [comment] 2022-04-05 10:26
Possible inclusion of this for 0.17?

**Comment by JohnnyDoorn** [comment] 2022-04-05 11:18
Hi @PerPalmgren,

I think this issue has been orphaned a bit for now, since the usual statistics programmers are focusing on some more pressing features at the moment (we are also occupied by things like teaching etc.). I think the inclusion for 0.17 might be too ambitious, but the version after that one will probably work! It is also not a very extensive addition, so hopefully we can find someone with some time for this soon. 

Kind regards,
Johnny

**Comment by PerPalmgren** [comment] 2022-04-05 12:26
That would be wonderful. Because my students (and me) don’t like to have to do these calculations in SPSS or by hand.
Per😎

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by Kucharssim** [comment] 2022-04-05 13:40
Perhaps @LSLindeloo can take a look?

**Comment by PerPalmgren** [comment] 2022-05-21 12:16
So, this will be featured in 0.16.3? 🙏🏻😜

**Comment by PerPalmgren** [comment] 2022-05-23 06:38
It seems like there is a R module for this. See attached.
[chisq.posthoc.test.pdf](https://github.com/jasp-stats/jasp-issues/files/8752026/chisq.posthoc.test.pdf)

**Comment by juliuspf** [comment] 2022-05-23 13:49
Hi @PerPalmgren, it seems this will be part of 0.16.4

**Comment by PerPalmgren** [comment] 2022-05-24 10:29
That is sad as this request has been around for a couple of years (from others and than me). Well, the students will have to go in to awful SPSS again :-)
I will be waiting for 0.16.4
All the best
Per

**Comment by tomtomme** [comment] 2022-05-24 16:02
@PerPalmgreen 

The "solution" I use is the JASP extra-Module "Visual Modeling => Flexplot". Put 2 categorial variables there and you can visually spot " which parts of the data are responsible for differences" - the longer the bar, the higher the difference between your empirical  and the expected frequencies.

I hope this helps for the moment?!?

**Comment by PerPalmgren** [comment] 2022-05-25 16:52
Thank you Thomas. It is a great tip. However, I want the students to get familiar with wouwith standardised residuals  and adjusted standardised residuals. Until 0.16.4 it will manual calculations and SPSS😢.
Per


Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

24 maj 2022 kl. 18:02 skrev Thomas Langkamp ***@***.***>:

﻿

@PerPalmgreen

The "solution" I use is the JASP extra-Module "Visual Modeling => Flexplot". Put 2 categorial variables there and you can visually spot " which parts of the data are responsible for differences" - the longer the bar, the higher the difference between your empirical and the expected frequencies.

I hope this helps for the moment?!?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1442%23issuecomment-1136114164&data=05%7C01%7Cper.palmgren%40ki.se%7C664435056c674add966e08da3d9ed5e6%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637890049646839141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xVqinl4rVfaJ6OLD14Vfcg5%2Ffj8p%2FABRYOeV%2B7XHaIo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS5YGHXYPASAMJ2RJMUIH7DVLT4SDANCNFSM5FGRXIGA&data=05%7C01%7Cper.palmgren%40ki.se%7C664435056c674add966e08da3d9ed5e6%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637890049646995134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wkcwshQ2%2F17L2Hsb5KFHSxgYIlRjcYPs1BOEoNgyO7Q%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by PerPalmgren** [comment] 2022-07-22 06:56
@Kucharssim @juliuspf @amirmasoudabdol @LSLindeloo @JohnnyDoorn 
Hi guys,
I hope you are enjoying the "warm" summer🌞🏊‍♀️⛱🍹🥵.
Just want to check in if you think the feature with added standardized residuals  and adjusted standardized residuals for post hoc analysis with chi-square analysis will be incorporated for 0.16. 4? I really hope so🙏.
All the best
Per😎

**Comment by Kucharssim** [comment] 2022-07-22 07:08
Hi @PerPalmgren,

Yes, this feature will be in the next release!

**Closed** 2022-07-22 07:07 UTC
Labels: Feature Request

**Comment by tomtomme** [comment] 2024-01-05 12:24
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/727
