### ISSUE TITLE
Velicer MAP Test

### ISSUE THREAD

**Issue by lucieunice** [jasp-stats/jasp-issues#1235] opened 2021-04-01 16:02 UTC
* Enhancement: Add Velicer MAP Test feature
* Purpose: Exploratory Factor Analysis

Hi! Is there any way of doing a Velicer MAP Test for Exploratory Factor Analysis in JASP? It is recommended in addition to parallel analysis and the eigenvalues method, and could be useful as an added feature! 

Thanks :)

**Comment by tomtomme** [comment] 2024-01-23 20:08
Closing, since duplicate of the more active: https://github.com/jasp-stats/jasp-issues/issues/1951

**Closed by tomtomme** 2024-01-23 20:08 UTC
Labels: Module: jaspFactor, Feature Request
