### ISSUE TITLE
[Bug]: Can't install any developer modules under Ubuntu 20.04

### ISSUE THREAD

**Issue by petersen-f** [jasp-stats/jasp-issues#1659] opened 2022-03-15 18:02 UTC
### JASP Version

0.16.1

### What analysis are you seeing the problem on?

jaspDescriptives, jaspBSTS

### What OS are you seeing the problem on?

Ubuntu 20.04.3 LTS

### Bug Description

Right now I am having a problem with installing any developer modules in JASP 16.1 under Ubuntu 20.04. I have attached screenshots and the log files for both errors. I tried the same modules under Windows 10 with the same JASP version where it worked fine. I also tried installing previous version of JASP but no success as well.

I first discovered this problem when I wanted to install the current repository for jaspBSTS. But this apparently extends to any modules from jasp-stats as I downloaded modules like jaspDescriptives or jaspFrequencies and tried to install them as a developer modules but got the same error.

The error I get is the following:
<img src="https://user-images.githubusercontent.com/65158001/158433951-aac00afe-9fc0-4781-bdc5-d6d973fce5b6.png" width="60%" height="60%">

I also tried whether this has something to do with the default PAT for GITHUB so I used my own GITHUB_PAT under advanced preferences but this results in a different error:
<img src="https://user-images.githubusercontent.com/65158001/158435493-83339c09-d84f-43b0-a2c1-cca4530f7821.png" width="60%" height="60%">

### Expected Behaviour

The expexted behaviour would be that the developer modules install in JASP without any error.

### Steps to Reproduce

1. Under Ubuntu Ubuntu 20.04.3 LTS, download the jasp-Descriptives module as a zip file from jasp-stats and unpack it
2. Select the folder as a developer module under Setting > Advanced
3. Click on "Install Developer Module"

### Log (if any)

[JASP_Engine_error1.log](https://github.com/jasp-stats/jasp-issues/files/8256019/JASP_Engine_error1.log)
[JASP_engine_error2.log](https://github.com/jasp-stats/jasp-issues/files/8256017/JASP_engine_error2.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment] 2022-03-16 08:22
If you do `gcc --version`, do you get output? Also, what does `apt list --installed build-essential` return?

**Comment by petersen-f** [comment] 2022-03-16 09:08
Thanks you for your quick reply!
```
> gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
> apt list --installed build-essential
Listing... Done
build-essential/focal-updates,now 12.8ubuntu1.1 amd64 [installed,automatic]
N: There is 1 additional version. Please use the '-a' switch to see it
```
(and if I add the suggested '-a' switch:
```
> apt list --installed build-essential -a
Listing... Done
build-essential/focal-updates,now 12.8ubuntu1.1 amd64 [installed,automatic]
build-essential/focal 12.8ubuntu1 amd64
```

**Comment by vandenman** [comment] 2022-03-16 09:18
@JorisGoosen it looks to me that flatpak does not have access to gcc when trying to compile because the logs show this many times:
```r
* installing *source* package 'commonmark' ...
** package 'commonmark' successfully unpacked and MD5 sums checked
** using staged installation
** libs
rm -f cmark/cmark.o cmark/node.o cmark/iterator.o cmark/blocks.o cmark/inlines.o cmark/scanners.o cmark/utf8.o cmark/buffer.o cmark/references.o cmark/render.o cmark/man.o cmark/xml.o cmark/html.o cmark/commonmark.o cmark/latex.o cmark/houdini_href_e.o cmark/houdini_html_e.o cmark/houdini_html_u.o cmark/cmark_ctype.o cmark/arena.o cmark/html.o cmark/linked_list.o cmark/plugin.o cmark/registry.o cmark/syntax_extension.o cmark/plaintext.o cmark/footnotes.o cmark/map.o extensions/autolink.o extensions/core-extensions.o extensions/ext_scanners.o extensions/strikethrough.o extensions/table.o extensions/tagfilter.o extensions/tasklist.o extensions.o init.o wrapper.o commonmark.so cmark/libstatcmark.a
gcc -I"/app/lib64/R/include" -DNDEBUG -Icmark -I. -DCMARK_GFM_STATIC_DEFINE -DCMARK_GFM_EXTENSIONS_STATIC_DEFINE -DR_NO_REMAP -DSTRICT_R_HEADERS  -I/usr/local/include  -fvisibility=hidden -fpic  -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Wno-error  -c extensions.c -o extensions.o
/bin/sh: line 1: gcc: command not found
make: *** [/app/lib64/R/etc/Makeconf:168: extensions.o] Error 127
ERROR: compilation failed for package 'commonmark'
```
where
```
/bin/sh: line 1: gcc: command not found
```
seems a bit funny.

@petersen-f can you change the repository to `https://packagemanager.rstudio.com/cran/__linux__/focal/latest`?
You can do that here:

![image](https://user-images.githubusercontent.com/21319932/158556922-f5044cfa-908f-434d-96b8-2df4202d942e.png)

that way jasp should use download binaries which hopefully can be installed without any issues. However, if somewhere one of your dependencies downloads `igraph` then this will fail (that's a known bug).

**Comment by JorisGoosen** [comment] 2022-03-16 10:21
> /bin/sh: line 1: gcc: command not found
Ah yeah, so you have to make sure you have installed `org.kde.Sdk` and then start JASP as `flatpak run --devel org.jaspstats.JASP`

This way it uses `gcc` in the sdk, because it doesn't have access to the one on your system

**Comment by JorisGoosen** [comment] 2022-03-16 10:22
Also, probably the linux version is forced to install from sources, so probably your repository workaround won't work anyway...

**Comment by vandenman** [comment] 2022-03-16 10:27
nah, that repository should download Linux binaries rather than compiling anything from source. So as long as @petersen-f's system
- does not have arm,
- can install pure R code,

it should work (although I haven't tested this myself).

Your workaround is probably better though. However, I also saw this message in the logs:
```
--------------------------- [ANTICONF] --------------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 ...
```
@JorisGoosen is it possible to somehow do `apt install libssl-dev` *inside* a flatpak build?

**Comment by JorisGoosen** [comment] 2022-03-16 12:01
> is it possible to somehow do apt install libssl-dev inside a flatpak build?

Nope... I don't know how you could solve that to be honest.

> nah, that repository should download Linux binaries rather than compiling anything from source. So as long as @petersen-f's system isnt ARM and can install pure R code.

Ah well there is definitely no harm in trying it, if it works it would be a lot better. And other missing libraries in flatpak-sdk might make it a pain anyway. Knowing whether we can work with binaries in flatpak should be good!

**Comment by petersen-f** [comment] 2022-03-18 07:58
> @petersen-f can you change the repository to `https://packagemanager.rstudio.com/cran/__linux__/focal/latest`?

Yes this worked! But I had to enable my private PAT for Github otherwise I was getting the same error about being unable to resolve jasp-stats/jaspBase.


> Ah yeah, so you have to make sure you have installed `org.kde.Sdk` and then start JASP as `flatpak run --devel org.jaspstats.JASP`

This solution also worked but I also had to use my own PAT. 

Thank you both so much! I tried both solutions with multiple packages and it works.

**Comment by JorisGoosen** [comment] 2022-03-30 09:08
@vandenman would it be a good idea to set the repository of JASP on flatpak default to `https://packagemanager.rstudio.com/cran/__linux__/focal/latest` ?

Although I guess I should at least test whether it also works on, for instance, Arch Linux and others. But I think it will.

**Comment by vandenman** [comment] 2022-03-30 09:17
@JorisGoosen You can try but I don't think it'll work on all Linux OSes, which is a pity because it's much faster than compiling from source. 

I don't think it'll work on aarch Also, some packages (`igraph` is the only one I know of) are broken on that repository (they fail on the Ubuntu runners of GitHub actions).

Once, I tried to create a flatpak build where I used these binaries for jasp (rather than compiling source tarballs) and it didn't work either.

**Comment by JorisGoosen** [comment] 2022-03-30 10:25
> @JorisGoosen You can try but I don't think it'll work on all Linux OSes, which is a pity because it's much faster than compiling from source.

Well, can't hurt to have a look once we have a new beta build.

> I don't think it'll work on aarch Also, some packages (`igraph` is the only one I know of) are broken on that repository (they fail on the Ubuntu runners of GitHub actions).

Very good point, but there probably is an aarch build somewhere as well?

> Once, I tried to create a flatpak build where I used these binaries for jasp (rather than compiling source tarballs) and it didn't work either.

Aah yeah, but it is kind of weird that this *does* work...

**Comment by petersen-f** [comment] 2022-08-22 20:19
Hello! 
I updated to Ubuntu Version Ubuntu 22.04 LTS and can't install developer modules again. It's a different error but since it's also related to Ubuntu I thought I would just update this issue. Let me know if I should open a new one.

The problem occurs under both JASP version 0.16.1 and 0.16.3. For the logs I used the current fork of the jaspRegression module but it happens for all development modules I tried. The error I get is the following:
<img src="https://user-images.githubusercontent.com/65158001/186010819-61a6cc22-dedc-4af4-b0c3-cc6c57b45ab5.png" width="60%" height="60%">
Do you have any idea how to fix this @vandenman?

[JASP 2022-08-22 21_46_33 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9397290/JASP.2022-08-22.21_46_33.Desktop.log)
[JASP 2022-08-22 21_46_33 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9397291/JASP.2022-08-22.21_46_33.Engine.0.log)

**Comment by JorisGoosen** [comment] 2022-08-23 08:40
@petersen-f have you tried the `beta`? 

https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/jasp-module-workflow.md#linux

I'll trigger a new build as well.
And Ill try it myself on a linux.

**Comment by petersen-f** [comment] 2022-08-23 11:19
> @petersen-f have you tried the `beta`?

Thanks for the suggestion! I tried it and am getting a similar error:
<img src="https://user-images.githubusercontent.com/65158001/186144588-76619287-f336-4230-9899-1edeaee0cce2.png" alt="drawing" width="500"/>

**Comment by JorisGoosen** [comment] 2022-08-23 12:20
Aah, well maybe I can fix that

**Comment by tomtomme** [comment] 2024-01-20 21:21
@petersen-f  & @JorisGoosen 
Was this fixed?
I just tried with default settings (standard PAT etc.) and JASP  0.18.3 hard crashes, when I click the "install dev module" button.

Logs
[JASP 2024-01-20 22_15_44 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/13999240/JASP.2024-01-20.22_15_44.Desktop.log)
[JASP 2024-01-20 22_15_44 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/13999241/JASP.2024-01-20.22_15_44.Engine.0.log)

**Comment by tomtomme** [comment] 2024-02-15 09:38
closing now as duplicate of https://github.com/jasp-stats/jasp-issues/issues/2588

**Closed by tomtomme** 2024-02-15 09:38 UTC
Labels: OS: Linux / Flatpak, Bug: High
