### ISSUE TITLE
[Bug]: When interaction term is entered in regression, JASP 'terminated unexpectdly'

### ISSUE THREAD

**Issue by LauraSambaer** [jasp-stats/jasp-issues#1679] opened 2022-04-08 08:21 UTC
### JASP Version

0.16.1

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Model (Interaction term)

### What OS are you seeing the problem on?

macOS Monterey (12.1)

### Bug Description

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/103247013/162395095-6be82053-3406-4593-affd-a65432d5404b.png">
[MP_FINALEDATA_KORTER.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/8449993/MP_FINALEDATA_KORTER.jasp.zip)

### Expected Behaviour

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/103247013/162395245-1693093d-0705-49f3-8352-6d4cdf3242bd.png">
This is the outcome with a different, but similar covariate

### Steps to Reproduce

No idea.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2022-04-13 15:48
Hi @LauraSambaer I cannot reproduce your problem. Could you send a file where I can reproduce it?
Maybe could you try also the beta version (that should be released next week): http://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-stable-2509cc21037a54e6f20c5dc5d54b81403ae7690f.dmg
Maybe this is already solved here.

**Comment by boutinb** [comment] 2022-04-13 15:58
@Saguaroman Do you have a precise reproduction path that works for example with a JASP Data Library dataset?

**Comment by Saguaroman** [comment] 2022-04-13 16:58
I don't have a reproduction path.  In the attached data, when I run it (aggressi as DV, VSP_trai as covariate, Viol_Exp as Factor), it generates the error. When I just basically mess around adding and subtracting variables from the model, it seems like in a few tries it suddenly generates the output. I haven't managed to figure out the precise pattern of adding/removing variables from the model that does it. I don't know if it will show on your end, but in the attached file the first set of analysis has the error, while the second has the correct output, even though the analyses being requested are identical.   It looks like I can't attach a JASP file, so the link to it is below, along with a screenshot. 

https://emailarizona-my.sharepoint.com/:u:/g/personal/jharwood_email_arizona_edu/EZDGLgC-y5tFmrqyzU8ZvPEBzCXG4wi9KN0T-rxDn8At2w?e=XO2nMf 


![image](https://user-images.githubusercontent.com/40039345/163231859-05d84ec6-faff-4872-84be-125d17c043aa.png)

**Comment by boutinb** [comment] 2022-04-14 07:08
I still cannot reproduce this problem even with your data. But maybe @vandenman has an idea of what could go wrong: the error message refers to a line in regressionlinear.R

**Comment by LauraSambaer** [comment] 2022-04-14 07:20
> FYI, I've encountered this same problem, and it seems to go away if you run the model without the categorical variable (factor), then add the categorical variable to the model, and then add the interaction term. It seems a bit glitchy, but that workaround seems to work most of the time.
@Saguaroman Thanks for this tip! I do have another question. My statistics knowledge isn't that good, so I hope this isn't a stupid question. 
Not all the JASP versions have a separate 'factors-box' in linear regression, so I didn't found any videos that could help me, but what exactly is the difference between covariates and factors in JASP? Or do you know any documents or videos that give examples of this? 
Thanks in advance!

**Comment by Saguaroman** [comment] 2022-04-19 23:33
@boutinb @vandenman -- FYI, I think I have reproduced the sequence a bit more specifically.  In the "model" area, if I enter the "factor" (dichotomous variable) first, then the covariate (continuous variable), and then the interaction/moderator term, it crashes. Whenever I enter the covariate, then the factor, and then the moderator term, it runs fine.   So literally the order in which the variables are in the "Model terms" window makes the difference. 

I've replicated this in the "Big Five" data library data. If I enter Extraversion and Openness predicting neuroticism, it crashes if in the regression model I enter openness first, extraversion second, and then the interaction. But it runs fine if they're in the other order. Even if I just reorder them in the model list it causes a good model to crash.  Not sure why the program only likes the variables in the same order they are in the data set / covariates window.  If nothing else, there's an easy workaround (don't mess with the order in the model!).   Thanks.

**Comment by boutinb** [comment] 2022-04-20 09:46
Yes I can reproduce this problem now. Thanks for your investigation: it is indeed if you first add Openness in the Model Terms, then Extraversion, and finally the interaction that the error occurs. @vandenman can you have a look?

**Comment by tomtomme** [comment] 2024-01-30 20:11
This is still a problem with jasp 0.18.3. I think this 2 year old bug warrants a higher prio, thus changing to "Bug: High"

**Comment by tomtomme** [comment] 2024-02-12 16:18
@vandenman 
with jasp 0.19 beta from Feb 9 the interaction term is not computed at all at first: 
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/f192c16f-9906-4c47-b36c-d34871317f8f)

Only if I trigger it by reordering vars in the "model term" box or hit "add to null model"

**Comment by tomtomme** [comment] 2024-05-08 07:34
@JohnnyDoorn 
@LauraSambaer 
@Saguaroman 

This one is fixed in 0.19beta from yesterday, except the highlighted part :D

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/466729a0-99b6-4990-bd3d-80392a8a3e32)

**Comment by JohnnyDoorn** [comment] 2024-05-08 11:10
Hmm that could be some Linux thing - on Mac I get a proper little star.. @RensDofferhoff @JorisGoosen  is this part of the Linux fixes you are working on?
<img width="269" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/15704203/58f9c644-6a9a-43c7-a585-c9cfa1a2cd41">

**Comment by tomtomme** [comment] 2024-05-08 11:42
@JohnnyDoorn 
Ok thx. I will make a proper bug report if this is still in final then.

**Closed by tomtomme** 2024-05-08 11:42 UTC
Labels: Module: jaspRegression, Bug: High
