### ISSUE TITLE
[Feature Request]: Size effect with KW test

### ISSUE THREAD

**Issue by GUYON29** [jasp-stats/jasp-issues#1539] opened 2021-12-09 10:26 UTC
### Description

 teach statisitic for psychological students with JASP (Université de Bretagne Occidentale, France). With an ANOVA, Il would like to use size effect with Kruskal-Wallis test. 

### Describe the solution you would like

We can use kruskal_effsize in rstatix package (very simple formulate that I used with my students). But someone prefers epsilon square (King, B.M., P.J. Rosopa, and E.W. Minium. 2018. Statistical Reasoning in the Behavioral Sciences, 7th ed. Wiley (2010) ; Cohen, B.H. 2013. Explaining Psychological Statistics, 4th ed. Wiley. Or 3rd (2008). The formulate is too very simple (see http://www.wbc.poznan.pl/Content/325867/5_Trends_Vol21_2014_%20no1_20.pdf).

**Comment by tomtomme** [comment] 2023-12-30 13:12
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1905

Issue can be closed.

**Closed** 2024-01-03 12:47 UTC
Labels: Module: jaspAnova, Feature Request
