### ISSUE TITLE
Different values for Tau-B but not for CI-Interval in Bayesian Correlation

### ISSUE THREAD

**Issue by fplatz** [jasp-stats/jasp-issues#1082] opened 2020-11-26 12:15 UTC
* JASP version: 0.15.1

* OS name and version: maOS Catalina (10.15.7)
* Analysis: Bayesian Correlation Pairwise Plots (Kendalls Tau-B)
* Bug description: Different values for tau-b and BF were reported in the table output compared to the Prior & Posterior plot 
* Expected behaviour: Same values should be reported in the tables and figures for tau-b etc.

All the best
Friedrich

**Comment by Kucharssim** [comment] 2020-12-09 09:34
Hello @fplatz,

Thank you for the report. I am unable to reproduce this problem on the upcoming 0.14.1 version (I am not sure what is the 0.15.1 version you use, we are not there yet 😅 ).

Could you perhaps share a .jasp file that shows this problem? (note: GitHub does not accept attachments through e-mail so you need to upload it directly to the website)

Thank you!

Best,
Simon

**Comment by fplatz** [comment] 2020-12-09 10:07
Hello @Kucharssim,

thank you very much for your response. I've the same problem with Version 0.14.1. Actually, I would like to send you a JASP-File via mail. Would you please give me an address? Thanks in advanced! 
Best,
Friedrich

**Comment by Kucharssim** [comment] 2020-12-09 11:19
Hello @fplatz,

of course, you can send me an e-mail to s.kucharsky@uva.nl. Thanks!

Best,
Simon

**Comment by SootyBlue** [comment] 2021-05-05 05:28
I found a potential bug/error: 

JASP version: 0.14.10
OS name and version:  Windows 10 & 20H2
Analysis: Bayesian Correlation Pairwise Plots (Kendalls Tau-B)

Bug description: Values shown on tables/graphs are incorrect to data file limits. 

Expected behavior: Same values should be reported in the tables and figures for tau-b etc.

![image](https://user-images.githubusercontent.com/67675556/117100085-2e74ed00-adb6-11eb-87b8-b70e9403d6ac.png)

JASP version: 0.14
OS name and version:  Windows 10 & 20H2
Analysis: Bayesian Correlation Pairwise Plots (Kendalls Tau-B)

![Screenshot 2021-05-05 150050](https://user-images.githubusercontent.com/67675556/117100123-51070600-adb6-11eb-9350-c0bd04d275da.jpg)

Not sure if this is a known bug, but I am a first time poster. Please move or refer me to the right place. 

Kind regards, 
Jen

**Comment by Kucharssim** [comment] 2021-05-05 11:07
Dear @SootyBlue,

thank you for posting, welcome!

I am not sure what do you show with the attached figures - are the plots incorrect? Are you referring to the same issue as @fplatz did? Thank you for clarifying.

Just for completeness, here is what I wrote to @fplatz over email about the current issue (correlation coefficient is different in the table and the plot), maybe that will clarify it as well for you:

> The issue here is that the tables in the Bayesian correlations report the observed sample correlation coefficient, whereas the plots show the median of the posterior distribution. In other words, whereas the table shows the summary statistic of the data, the plot shows a summary of the population parameter (i.e., descriptive statistic of the posterior distribution). These two values do not need to be the same. 
>Notice, for example, that changing the prior affects the posterior distribution (and therefore the median value reported in the plot), but does not change the value in the table. This is because the table reports the coefficient calculated from the raw data and thus does not depend on the prior.
>To make it easier to distinguish between these two statistics within JASP, we try to be consistent by using Latin labels for sample descriptive statistics and Greek labels for the population parameters. For example, the table refers to "tau" sample coefficient, whereas the plot shows the population parameter "τ".

@fplatz recommended making the distinction between the sample and population statistics more explicit, which needs to be done indeed in the future.

Please let me know if this helps you. In case that you found a different problem with the analysis, please open a new issue at: https://github.com/jasp-stats/jasp-issues/issues so that we can have a separate discussion dedicated to the bug you found.

Thank you!

Best,
Simon

**Comment by tomtomme** [comment] 2024-01-12 10:51
@fplatz & @SootyBlue 
I checked in 0.18.3 with data library file from Adam Sandler. Did also a recompute and activated kendall etc. The distinctions made seem quite clear and the help file also states what value is from a population and what is from a sample.
If I have overlooked something feel free to reopen.

**Closed by tomtomme** 2024-01-12 10:51 UTC
Labels: Module: jaspRegression
