### ISSUE TITLE
Issue to run "network" on JASP 

### ISSUE THREAD

**Issue by AM886jpg** [jasp-stats/jasp-issues#426] opened 2019-07-19 16:23 UTC
Hello, 
i am actually having a lot of issues to use JASP, i have a chromebook. I cant run Jasp through linux, so i tried on rollapp. It works until i try the network analysis. Each time, i'm trying to use the nework analysis it is said : "there is no package called bootnet". I also tried with the premium version of rollapp. Still the same : network analysis crashed. 

Can somebody help me ti understand the issue ? 
Thank you 

![Screenshot 2019-07-19 at 18 07 56](https://user-images.githubusercontent.com/53092740/61550229-38e3bc80-aa52-11e9-902b-836eb839ba17.png)
![Screenshot 2019-07-19 at 18 07 45](https://user-images.githubusercontent.com/53092740/61550230-38e3bc80-aa52-11e9-9d7f-3b15297358dd.png)

**Comment by JorisGoosen** [comment] 2019-07-22 14:35
It seems the rollapp version misses a specific package.

@EJWagenmakers when did you want to notify the RollApp people of the new release of JASP? Maybe that would already solve this problem.

**Comment by tomtomme** [comment] 2023-12-26 16:12
@AM886jpg 
rollapp is on version 0.14.3 at the moment. Maybe the issue is fixed there?

Also the current version 0.18.1 may be running better on chromebooks? 
Please let us know and feel free to close this issue if resolved.

Also:
Related to https://github.com/jasp-stats/jasp-issues/issues/1760

**Comment by AM886jpg** [comment] 2023-12-26 18:36
> @AM886jpg rollapp is on version 0.14.3 at the moment. Maybe the issue is fixed there?
> 
> Also the current version 0.18.1 may be running better on chromebooks? Please let us know and feel free to close this issue if resolved.
> 
> Also: Related to #1760

Indeed. Thank you !

**Closed** 2023-12-26 18:37 UTC
Labels: Module: jaspNetwork
