### ISSUE TITLE
This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by fnkie** [jasp-stats/jasp-issues#2200] opened 2023-06-26 11:50 UTC
### JASP Version

0.17.1

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Super Vector Machine Classification, K-Nearest Neighbours, all ML reports actually

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This analysis terminated unexpectedly.

Error in str2lang(x): :1:11: unexpected symbol
1: BSA ~ 6011P0200
              ^

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mlClassificationTableSummary(dataset, options, jaspResults, ready, position = 1, type = 'knn')

.decodeJaspMLobject(model)

.decodeJaspMLobject.kknn(model)

formula(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

formula.character(paste(decodeColNames(as.character(model$terms)[2]), '~', paste0(decodeColNames(strsplit(as.character(model$terms)[3], split = ' + ', fixed = TRUE)[[1]]), collapse = ' + ')))

str2lang(x)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

I want to save the model to use in a future prediction but the BUG is preventing me from saving the model.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by fnkie** [comment] 2023-06-26 18:54
Hello ! Thanx for the response.
I was able to work the issue myself.
The Field TItles were too long.

e.g.   6011P0200, i have truncated this to P0200 and it works now.

But shouldnt field names be able to be longer than 9 digits?

In any case thank you for your time on this.

**Comment by EJWagenmakers** [comment] 2023-06-26 19:22
Maybe the problem was that the name started with a number?

**Comment by koenderks** [comment] 2023-06-27 07:21
Thanks for reporting! The problem is indeed in the variable names, this is a known issue (linking to https://github.com/jasp-stats/jaspMachineLearning/issues/158 for completeness). There should be a warning in the next version of JASP about invalid column names for saving models. Unfortunately, I did not have time to check what causes this bug yet and so there will be no fix.

**Comment by fnkie** [comment] 2023-06-27 07:23
> Thanks for reporting! The problem is indeed in the variable names, this is a known issue (linking to [jasp-stats/jaspMachineLearning#158](https://github.com/jasp-stats/jaspMachineLearning/issues/158) for completeness). There should be a warning in the next version of JASP about invalid column names for saving models. Unfortunately, I did not have time to check what causes this bug yet and so there will be no fix in that version yet.

Thanck You Koen !
:)

**Comment by koenderks** [comment] 2023-06-29 05:36
No worries, I will close this issue as there is a (temporary) solution for your problem and we are keeping tabs on this in https://github.com/jasp-stats/jaspMachineLearning/issues/158.

**Closed by koenderks** 2023-06-29 05:36 UTC
Labels: Module: jaspMachineLearning, OS: Windows 10, Bug
