### ISSUE TITLE
Jasp not displaying the exact value

### ISSUE THREAD

**Issue by MalavikaSunil** [jasp-stats/jasp-issues#1409] opened 2021-09-08 05:49 UTC
* JASP version: 0.14.1.0

* OS name and version: Windows 10
* Analysis: Structural Equation Modelling
* Bug description: 
* Expected behaviour:
![SEM 2021-09-08 074847](https://user-images.githubusercontent.com/89886678/132453533-1fb07e0e-7af0-41db-abcc-2ec7054a57ba.png)

#### Steps to reproduce:

If you didn't feel all fields from this template are necessary for your issue please take the time to remove them from the issue. 
--->

**Comment by vandenman** [comment] 2021-09-08 07:05
Could you explain more clearly what the problem is?

For example, is this about seeing something like `2.757e-10` (first value in the column p)? 

If the issue is about only seeing 3 digits after the decimal point, you can increase the number of digits in the menu:
![image](https://user-images.githubusercontent.com/21319932/132462193-b6fd043b-4461-4879-b4b0-234d09db6904.png)

**Comment by MalavikaSunil** [comment] 2021-09-08 07:08
Hi ,

Yes ,
* For example, is this about seeing something like 2.757e-10 (first value in the column p)?* .... this is indeed the issue ..Could you tell me what can be done?

**Comment by vandenman** [comment] 2021-09-08 07:18
So it is not possible to adjust this, at least not right now, because a value like `2.220e-16` would be printed as `0.000000000000000222`, which will quickly make the table become too wide to become readable.

**Comment by MalavikaSunil** [comment] 2021-09-08 07:39
Yes...thank you for that.
Also, I am unable to process the path diagram. Could you tell me what can be the issue mainly for that to happen?

**Comment by vandenman** [comment] 2021-09-08 07:42
> I am unable to process the path diagram.

Is there an error when you click on path diagram? Or would you like a quick run-through of how to interpret it?

**Comment by MalavikaSunil** [comment] 2021-09-08 07:46
![PD_2021-09-08 094510](https://user-images.githubusercontent.com/89886678/132468030-b2670f3b-1c2a-4c2d-b481-efb297b5e734.png)
This is how I have been getting.

**Comment by vandenman** [comment] 2021-09-08 07:47
Oh yeah, that's an error. Would it be possible to share a jasp file that led to this error?

**Comment by MalavikaSunil** [comment] 2021-09-08 07:51
[SEM testing 1.csv](https://github.com/jasp-stats/jasp-issues/files/7126988/SEM.testing.1.csv)

**Comment by vandenman** [comment] 2021-09-08 08:00
could you also share the model code for the SEM model?

**Comment by MalavikaSunil** [comment] 2021-09-08 08:01
#latent variables
ER =~ B_1 + B_2 + B_3 + B_4 + B_5 + B_6 + B_7 + B_8 + B_9 + B_10
TD =~ C_1 + C_2 + C_3 + C_4 + C_5 + C_6 + C_7 + C_8 + C_9 + C_10 + C_11 + C_12 + C_13  + C_14
FP =~ D_1 + D_2 + D_3 + D_4 + D_5 + D_6 + D_7 + D_8 + D_9 + D_10 + D_11 + D_12 + D_13 + D_14 + D_15+D_16+D_17+D_18+D_19+D_20+D_21+D_22+D_23+D_24+D_26+D_27+D_28+D_29+D_30+D_35+D_36+D_37+D_38+D_45+D_46+D_47+D_48+D_49+D_51+D_52+D_53+D_54+D_56+D_57+D_61+D_62

#regression
FP ~ ER
FP ~ TD

#residual relation
 B_1 ~~ D_1 + D_2 + D_3 + D_4 + D_5 + D_6 + D_7 + D_8 + D_9 + D_10 + D_11 + D_12 + D_13 + D_14 + D_15+D_16+D_17+D_18+D_19+D_20+D_21+D_22+D_23+D_24+D_26+D_27+D_28+D_29+D_30+D_35+D_36+D_37+D_38+D_45+D_46+D_47+D_48+D_49+D_51+D_52+D_53+D_54+D_56+D_57+D_61+D_62

**Comment by MalavikaSunil** [comment] 2021-09-08 08:02
This is the first code I am testing ...So I have taken only one variable at the "Residual Relation"

**Comment by vandenman** [comment] 2021-09-08 08:22
Well, I tried your code in the new release (which should be out in a couple of weeks) and got this figure:

![image](https://user-images.githubusercontent.com/21319932/132473329-94aeb486-d51b-43a3-b333-01308d5c78e0.png)

this is not very pretty, but with so many variables there is nog real hope for a pretty plot.

**Comment by MalavikaSunil** [comment] 2021-09-08 08:38
What should be done to the current version so that I can get a path diagram this way?

**Comment by MalavikaSunil** [comment] 2021-09-08 09:47
I have tried multiple times but I get an error for the path diagram :(

**Comment by juliuspf** [comment] 2022-10-14 09:05
@MalavikaSunil I will close this as completed, since the graph works with the latest release version. Please feel free to reopen this if your issue still persists.

**Closed by juliuspf** 2022-10-14 09:05 UTC
Labels: Module: jaspSem
