### ISSUE TITLE
[Bug]: Issue with Changing Variable Scale from Nominal to Ordinal in JASP

### ISSUE THREAD

**Issue by MareikeK22** [jasp-stats/jasp-issues#2384] opened 2023-11-05 16:07 UTC
### JASP Version

0.18.1

### JASP Module

Descriptives

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I am currently working on a project that involves three variables that should be ordinal in nature (Alter, Abschluss & Betriebszugehörigkeit). However, they are being categorized as nominal within the JASP system. When I try to manually change the measurement level of these variables to ordinal by clicking on the column title and selecting "Ordinal" from the dropdown menu, I encounter an error message.
The error persists even after ensuring that my data is formatted correctly and checking my CSV file for any inconsistencies or missing data. I have also tried updating JASP to the latest version but the issue remains unresolved.
Could you please provide assistance or guidance on how to rectify this issue? Any help would be greatly appreciated.
Thank you in advance for your time and support.

### Expected Behaviour

The three variables should be categorized as ordinal. 

### Steps to Reproduce

1.
2.
3.
...

### Log (if any)

<img width="666" alt="Screenshot 2023-11-05 170547" src="https://github.com/jasp-stats/jasp-issues/assets/149955651/c9ade06b-f88a-4417-9057-13202e23418d">
[FinaleErgebnistabelle-_Alterblöcke.csv](https://github.com/jasp-stats/jasp-issues/files/13260146/FinaleErgebnistabelle-_Alterblocke.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2023-11-05 17:09
You have the data in a nominal format, because it involves not only numbers, but also strings.
To make it ordinal you would need to recode your data.
Like

1 for Bachelor
2 for Master
3 for PhD
...

or

Betriebszugehörigkeit
0,5 for 0-1  Jahre
3 for 1-5 jahre
usw.

Only if you use numbers only, the computer can do operations like > and < which are required for ordinal data.
Also "alter" and "betriebszugehörigkeit" are metric if you recode them in the way above. Next time just ask directly "how old are you" with a free field to put the number in years in. That makes life easier.

I guess this can be closed, as this is not a bug.

**Comment by shun2wang** [comment] 2023-11-06 01:23
@MareikeK22 yes @tomtomme (thanks you) is right, you may recode the variables, now we have data editor inside JASP 0.18.1 so you can try it.

I'm closing it for now if you still have some problems with it feel free to reopen it.

**Closed by shun2wang** 2023-11-06 01:23 UTC
Labels: Module: jaspDescriptives, OS: Windows 11, Bug
