### ISSUE TITLE
[Bug]: argument 'value' is missing, with no default

### ISSUE THREAD

**Issue by LilianYou** [jasp-stats/jasp-issues#1512] opened 2021-11-24 00:12 UTC
### JASP Version

0.15

### JASP Module

jaspJags

### What analysis are you seeing the problem on?

bandit task

### What OS are you seeing the problem on?

macOS Catalina

### Bug Description

No output
<img width="679" alt="Screen Shot 2021-11-23 at 4 09 40 PM" src="https://user-images.githubusercontent.com/30990195/143148208-2f3dbb4c-beea-4631-abfb-b881fc25f23b.png">
t.

### Expected Behaviour

<img width="729" alt="Screen Shot 2021-11-23 at 4 07 36 PM" src="https://user-images.githubusercontent.com/30990195/143148036-eb0dcd74-7e86-4437-9e15-810efd7ffe18.png">

### Steps to Reproduce

I've attached my JASP file, along with a sample data .csv file in the "Archive.zip" 

[Archive.zip](https://github.com/jasp-stats/jasp-issues/files/7597839/Archive.zip)

### Log (if any)
```bash
This analysis terminated unexpectedly.

Error in .JAGSsetState(jaspResults, '__moduleLoading', value): argument 'value' is missing, with no default

Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

JAGS(...)

.JAGSrunMCMC(jaspResults, dataset, options)

.JAGSloadModules(jaspResults)

.JAGSsetModuleLoadingError(e)

.JAGSsetState(jaspResults, '__moduleLoading', value)

createJaspState(value, dependencies = dependencies)

jaspStateR$new(object = object, dependencies = dependencies)

initialize(...)
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2021-11-24 10:21
Hi @LilianYou To attach a jasp file, you have first to rename it with a zip extension, then GitHub allows you to drag & drop it into a new comment in this issue.

**Comment by LilianYou** [comment] 2021-11-24 17:54
Hi @boutinb , 

Thanks! I‘ve attached my jasp file along with my sample data. Please let me know if there is anything else I need to do.

Best,
Lily

**Comment by vandenman** [comment] 2021-11-25 08:13
@boutinb this should be fixed by https://github.com/jasp-stats/jaspJags/pull/59. The problem is that there is something wrong with the jags installation but we don't know what is wrong because the code that is supposed to show the error message contains an error...

@LilianYou we have recently released a new version of JASP (0.16). Could you check if the error persists with that version?

**Comment by LilianYou** [comment] 2021-11-25 22:23
@vandenman I just installed JASP 0.16, but there is a new error showing "The engine crashed while trying to run this analysis...". See the screenshot attached.

<img width="574" alt="Screen Shot 2021-11-25 at 2 20 56 PM" src="https://user-images.githubusercontent.com/30990195/143504492-690f87f8-b094-4056-857a-449657c99b34.png">

**Comment by vandenman** [comment] 2021-11-26 08:15
@LilianYou Thanks for trying the new version and sorry to hear that it still doesn't work. 

Would it be possible to post the log files? See https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md for how to enable logging. Note that you have to enable logging before reproducing the crash.

**Comment by LilianYou** [comment] 2021-11-27 06:32
Hi @vandenman Here are the log files
[JASP 2021-11-26 22_26_57 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7611321/JASP.2021-11-26.22_26_57.Desktop.log)
[JASP 2021-11-26 22_26_57 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7611322/JASP.2021-11-26.22_26_57.Engine.0.log)
.

**Comment by boutinb** [comment] 2021-11-29 12:20
@vandenman If I load the banditWSL_2 JASP file and refresh, I get the following error:
<img width="453" alt="Screenshot 2021-11-29 at 13 18 01" src="https://user-images.githubusercontent.com/503332/143867089-8c20f2a4-ca3b-45a3-b5b7-1a88616eda16.png">

**Comment by vandenman** [comment] 2021-11-29 13:31
@boutinb something indeed goes wrong there. But if I hardcode the values like so:
![image](https://user-images.githubusercontent.com/21319932/143876732-1162e701-c975-4cf7-b530-c6619ef968ef.png)

the analysis works.

However, that won't help @LilianYou (yet) as there is something wrong with the JAGS installation on their system which leads to the initial error.

**Comment by LilianYou** [comment] 2021-11-29 18:54
Hi @boutinb @vandenman Please let me know if there is anything else I could try out to give you more clues. If there is a system issue, would upgrading my IOS system solve the issue? I know R had a problem with the Catalina system before. I could also try downgrading JASP to an older version if it may work out alternatively.

**Comment by boutinb** [comment] 2021-12-01 11:13
Hi @LilianYou I have also Catalina, so I don't think that upgrading your IOS would help (even it is not a bad idea to do it anyway).
From the log files you sent, I could not see the crash. Could you start JASP by loading only the data file, and afterwards start the JAGS analysis. Does it crash already when you use a dummy model? Or can you add some models without crash? When it crashes, can you send again the log files?

**Comment by LilianYou** [comment] 2021-12-01 18:01
Hi @boutinb, thank you for the suggestion.

I added one bayesian binomial test to the JAGS module, and it worked (see screenshot) although my original model still crashes. Let me know if the log file records it this time. I did load data first and then add JAGS analysis.

![Screen Shot 2021-12-01 at 9 58 42 AM](https://user-images.githubusercontent.com/30990195/144288398-035960e0-384e-4140-a571-310e788d868e.png)

[JASP 2021-12-01 09_46_58 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/7636184/JASP.2021-12-01.09_46_58.Desktop.log)
[JASP 2021-12-01 09_46_58 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/7636185/JASP.2021-12-01.09_46_58.Engine.0.log)

**Comment by amirmasoudabdol** [comment] 2021-12-02 15:23
Oh wait, those are from the data! 🤔 But, then why does `unique` fails on the data?

**Comment by boutinb** [comment] 2021-12-02 15:42
Hi @LilianYou  What I wanted to ask, is whether you can add a new JAGS analysis, with no model. And if there is no crash, can you then add a simple model?
Could you also do the following:

- Download this attached file: [jags.sh.zip](https://github.com/jasp-stats/jasp-issues/files/7643179/jags.sh.zip)
- Unzip it by double-clicking it in the Finder
- Start a Terminal
- Type 'cd Downloads' to go to the Downloads folder
- Type 'chmod 777 jags.sh'
- Type './jags.sh'
This should run the JAGS module installed in JASP.
Can you send me what you see in your Terminal?

**Comment by LilianYou** [comment] 2021-12-02 17:04
@boutinb Here is the output from my terminal

`➜  Downloads ./jags.sh
Welcome to JAGS 4.3.0 on Thu Dec  2 09:02:38 2021
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
. 
`

**Comment by LilianYou** [comment] 2021-12-02 17:09
@boutinb Here is the output from my terminal:

> ➜  Downloads ./jags.sh
Welcome to JAGS 4.3.0 on Thu Dec  2 09:02:38 2021
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
. 
<img width="576" alt="Screen Shot 2021-12-02 at 9 09 15 AM" src="https://user-images.githubusercontent.com/30990195/144469652-97434621-6a75-4527-a309-f301fb9e49da.png">

**Comment by boutinb** [comment] 2021-12-03 10:42
OK, so JAGS can be started apparently...
Could you also in JASP, just start a new empty JAGS analysis. Check whether it crashes already, and if not just set a simple model like:
```
model{
d ~ dnorm(1, 10)
}
```

**Comment by LilianYou** [comment] 2021-12-03 18:21
@boutinb The new empty analysIs doesn't crash. See screenshot below:
![Screen Shot 2021-12-03 at 10 20 04 AM](https://user-images.githubusercontent.com/30990195/144653269-4504be2a-4c8a-404d-97e5-bebd1bf58dc1.png)

**Comment by vandenman** [comment] 2021-12-06 08:32
@LilianYou what happens when you drag `d` to the right? Until you select any parameters, no sampling is done.

**Comment by LilianYou** [comment] 2021-12-07 20:22
@vandenman Here you go. It looks normal.

<img width="1435" alt="Screen Shot 2021-12-07 at 12 21 50 PM" src="https://user-images.githubusercontent.com/30990195/145100582-6e39c538-f992-4e95-9088-2b958fc17b52.png">

**Comment by boutinb** [comment] 2021-12-08 10:15
Hi @LilianYou So it means that JAGS can work on your Mac. And that it's apparently the model you use or the options you checked that makes JAGS crashing.
So I was a bit playing with your model, and I get a crash already if I set in a new JAGS analysis this model:
# Bandit win-stay lose-shift, long format
```
model{
  # Data
  for (t in 2:nTotalTrials){  
    decision[t] ~ dbern(theta[t])
    theta[t] = ifelse(equals(trial[t], 1), 0.5, 
               alpha[person[t]]*equals(reward[t-1], 1)*equals(decision[t-1], 1)
               + (1 - alpha[person[t]])*equals(reward[t-1], 1)*equals(decision[t-1], 0)
               + (1 - beta[person[t]])*equals(reward[t-1], 0)*equals(decision[t-1], 1)
               + beta[person[t]]*equals(reward[t-1], 0)*equals(decision[t-1], 0))  
  }
  # Prior
  for (p in 1:nPeople){
    alpha[p] ~ dunif(0, 1)
    beta[p] ~ dunif(0, 1)
  }
}
```
And just select the alpha parameter. Maybe @vandenman can have a look at it?

**Comment by vandenman** [comment] 2021-12-08 12:18
@boutinb what error message do you get? For what it's worth:

- The original JASP file runs without issues on Linux (after removing `unique` under observed values).
- The model you provided also runs without issues on Linux.

**Comment by boutinb** [comment] 2021-12-08 13:38
Sorry it was a mistake: I have run the model without the observed values nPeople & nTotalTrials (the error is 'Engine has crashed, which is not really informative...). If I add the observed values it works.
@LilianYou Could you play a bit with JAGS, by adding a more complex model, and to check when JAGS crashes?
For example, does this model work?
```
model{
  # Data
  for (t in 2:3){  
    decision[t] ~ dbern(alpha[t])
  }
  # Prior
  for (p in 1:100){
    alpha[p] ~ dunif(0, 1)
  }
}
```
(by adding the alpha parameter in the results).
If that works, can you make a more complex model?

**Comment by LilianYou** [comment] 2021-12-08 17:51
Yes. The model works.
<img width="719" alt="Screen Shot 2021-12-08 at 9 48 25 AM" src="https://user-images.githubusercontent.com/30990195/145258390-528c478a-0beb-4a16-bb45-8fe7a0263307.png">

**Comment by LilianYou** [comment] 2021-12-08 19:01
@boutinb I have increased model complexity:

Before defining any observed variables, this model works:
![Screen Shot 2021-12-08 at 10 55 03 AM](https://user-images.githubusercontent.com/30990195/145267281-69673d7c-7e4b-44b4-9338-5a3ecef0c0a7.png)

The model still works after I defined nTotalTrials:
![Screen Shot 2021-12-08 at 10 57 34 AM](https://user-images.githubusercontent.com/30990195/145267586-08d0ecbb-8cae-4691-b38f-2def190a7c00.png)

The crash took place when I defined nPeople:
![Screen Shot 2021-12-08 at 10 59 26 AM](https://user-images.githubusercontent.com/30990195/145267790-2bc7adb4-9cbf-4deb-94bb-69e99cbaec04.png)
The error says "unique() only applies only to vectors"

Any suggestions?

**Comment by vandenman** [comment] 2021-12-09 08:15
@LilianYou that's no longer a crash because JAGS cannot be found, so that's progress!

In this case, something goes wrong with `length(unique(person))` under `Observed values`. Although I'm not sure yet what is going wrong, if I hardcode the value to 2 then the model works.

**Comment by LilianYou** [comment] 2021-12-13 04:42
Hi @vandenman , gotcha! I think the only issue is that unique() R function somehow doesn't work with the column. I think my question is answered. Thank you so much for your help!

**Comment by boutinb** [comment] 2021-12-14 09:36
OK, then we can close this issue.

**Closed by boutinb** 2021-12-14 09:36 UTC
Labels: Module: jaspJags
