### ISSUE TITLE
JASP show up as Jedi Academy on Discord

### ISSUE THREAD

**Issue by MykolasSimasPoskus** [jasp-stats/jasp-issues#1101] opened 2020-12-17 01:52 UTC
* JASP version: 0.13.1
* OS name and version: Win 10
* Analysis: -
* Bug description: JASP shows up as Star Wars Jedi Knight: Jedi Academy on Discord. Since I've been using Discord to stream my statistics lectures I've encountered this very fun bug (or a feature?).
* Expected behaviour: To show up as JASP or not to show up at all.

#### Steps to reproduce:
1. Start Discord
2. Start JASP
3. It shows that I'm playing Jedi Academy...

**Comment by vandenman** [comment] 2020-12-18 14:36
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/1030. 

> From [this discord blog](https://blog.discord.com/all-your-game-are-detection-fd06b1683137), it looks like it is Discord that detects JASP, rather than JASP communicating anything to Discord. As such it's probably possible to ignore JASP somewhere within the Discord settings.
>
> Also, I cannot replicate this with Ubuntu 18.04, but my Discord never recognizes which games I'm playing though.

Perhaps we should contact Discord to see how they detect what game is running and ask them to add an exception for JASP.

**Comment by JorisGoosen** [comment] 2021-01-18 16:33
I think they just look at the name of the exe or something like that.. Ive seen this in Nvidia's configuration screen as well.

**Comment by juliuspf** [comment] 2022-11-25 13:14
Lets track this over there then: https://github.com/jasp-stats/jasp-issues/issues/1030

**Closed by juliuspf** 2022-11-25 13:14 UTC
Labels: duplicate
