### ISSUE TITLE
[Feature Request]: Just a question: is there any documentation for performing PLS in the last version of JASP 0.17???

### ISSUE THREAD

**Issue by Ghassan-Okour** [jasp-stats/jasp-issues#1992] opened 2023-02-03 15:30 UTC

**Comment by tomtomme** [comment] 2024-02-04 18:24
@Ghassan-Okour 
Closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/2529

**Closed by tomtomme** 2024-02-04 18:24 UTC
Labels: Feature Request
