### ISSUE TITLE
Sequential analysis for Bayesian ANOVA

### ISSUE THREAD

**Issue by franklenin** [jasp-stats/jasp-issues#1118] opened 2021-01-06 13:12 UTC
Sequential analysis for the Bayesian ANOVA

* Purpose: To implement a sequential analysis for the Bayesian ANOVA

Sequential analysis is a powerful tool of Bayesian analysis. While you already offer a sequential analysis for the Bayesian t-test, there is not an option for the Bayesian ANOVA. It will be extremely useful to have this option in future versions of JASP.

**Comment by boutinb** [comment] 2021-01-08 12:37
@JohnnyDoorn Could you answer this request?

**Comment by Andre3582** [comment] 2022-11-15 14:03
Just want to add a comment to say I completely agree and that I would love to see this feature added to JASP!

**Comment by tomtomme** [comment] 2024-01-12 12:30
@franklenin 
@Andre3582 
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/201
Lets track this there

**Closed by tomtomme** 2024-01-12 12:30 UTC
Labels: Module: jaspAnova, Feature Request
