### ISSUE TITLE
[Bug]: native BioArch JASP Version broke about 2 days ago - initializing modules loop

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1776] opened 2022-07-19 11:26 UTC
### JASP Version

0.16.3

### What analysis are you seeing the problem on?

all

### What OS are you seeing the problem on?

Manjaro with BioArch Repo

### Bug Description

@sukanka 
around 2 days ago some r-packages came as update from the bio-arch repo. Since then all modules try to initialize and show the spinning circle for about 10 seconds. The circle vanishes then for some seconds, then spins again. Thus I infer I have a infinite loop initializing modules

### Expected Behaviour

modules should initialize. I tested this on two desktop computers (one all intel, one all amd)

### Steps to Reproduce

1. update jasp on manjaro with bioarch repo to latest
2. start jasp
3. open any analysis even the "distribution module" without data
...

### Log (if any)

<img width="315" alt="grafik" src="https://user-images.githubusercontent.com/4428185/179738844-199bb663-9f55-4adc-89ff-86c12ddbf1e3.png">
```

[thomasl@thomas-msh-desktop ~]$ jasp
Making new argument list for Application startup: ./JASP
Starting JASP 0.16.3 from commit  and branch 
QtWebEngineQuick initialized
Application initialized
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name JASP 
  *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

Application init entered
MainWindow constructor started
TempFiles::createSessionDir(): '/home/thomasl/.JASP/temp/30191' about to be (removed and re)created.
Going to construct the necessary models for JASP to function.
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-pt.qm
Desktop:        Language (Portuguese) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-de.qm
Desktop:        Language (German) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-es.qm
Desktop:        Language (Spanish) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-ja.qm
Desktop:        Language (Japanese) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-nl.qm
Desktop:        Language (Dutch) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-gl.qm
Desktop:        Language (Galician) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-id.qm
Desktop:        Language (Indonesian) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-tr.qm
Desktop:        Invalid translation file found with name: jaspDesktop-tr.qm
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-fr.qm
Desktop:        Language (French) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-eo.qm
Desktop:        Invalid translation file found with name: jaspDesktop-eo.qm
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-zh_Hans.qm
Desktop:        Language (Chinese) not registered in LanguageModel, adding it now
Entering eventloop
Mehr als eine Klasse "Rcpp_jaspBoollist" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspBoollist" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspColumn" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspColumn" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspContainer" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspContainer" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspDoublelist" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspDoublelist" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspHtml" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspHtml" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspIntlist" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspIntlist" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspObject" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspObject" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspPlot" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspPlot" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspQmlSource" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspQmlSource" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspResultsClass" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspResultsClass" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspState" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspState" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspStringlist" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspStringlist" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspTable" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Mehr als eine Klasse "Rcpp_jaspTable" im Cache gefunden; nutze die erste, kommt aus Namensraum 'jaspBase'
Auch definiert durch ‘.GlobalEnv’
Lade nötigen Namensraum: ragg
Found more than one class "Rcpp_jaspResultsClass" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
QSGPlainTexture: Mipmap settings changed without having image data available. Call setImage() again or enable m_retain_image. Falling back to previous mipmap filtering mode.
Found more than one class "Rcpp_jaspContainer" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
Found more than one class "Rcpp_jaspPlot" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
Found more than one class "Rcpp_jaspContainer" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
Found more than one class "Rcpp_jaspContainer" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
Found more than one class "Rcpp_jaspState" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
Found more than one class "Rcpp_jaspState" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
Found more than one class "Rcpp_jaspState" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
Found more than one class "Rcpp_jaspContainer" in cache; using the first, from namespace 'jaspBase'
Also defined by ‘.GlobalEnv’
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2022-07-19 11:30
Since the log mentions "Cache" frequently I tried deleting home/.cache to no avail

**Comment by sukanka** [comment] 2022-07-19 12:12
Thanks for letting me know, I guess it's caused by https://github.com/BioArchLinux/Packages/commit/65bb641c22e292093d8fba3b8dd597cca4333ad1 and https://github.com/jasp-stats/jaspBase/pull/66
I'm now looking into it.

**Comment by sukanka** [comment] 2022-07-19 12:24
I have pinned the commit used to build `jaspbase` for a while, https://github.com/BioArchLinux/Packages/commit/84cd0bfb01056c963cb9a39a699760f42dee3117,
it will be in the repository in 6 hours, or you can use that PKGBUILD to build it yourself.

When a new version of jasp-desktop is released, I will update them to follow the  jasp mainline

**Comment by tomtomme** [comment] 2022-07-20 06:47
Many Thanks @sukanka for the quick fix. Analyzing like a champ - again :dagger: 
cheers

**Closed** 2022-07-20 06:48 UTC

**Comment by boutinb** [comment] 2023-01-26 16:49
@sukanka 0.17.0 has been just released. Can you update BioArchLinux? Thank you!

**Comment by boutinb** [comment] 2023-02-13 10:53
@sukanka We have just released a 0.17.1 (hotfix) version.

**Comment by sukanka** [comment] 2023-02-13 11:20
> @sukanka We have just released a 0.17.1 (hotfix) version.

Oh, it was updated in BioArchLinux repo 2 days ago, you can use `yay -Ss jasp-desktop` to check.
Generally, it will get updated in 6 hours when a newer release comes out.
If it failed to be built automatically, I will receive a notification, and fix it manually.

```
➜  ~ yay -Ss jasp-desktop
bioarchlinux/jasp-desktop 0.17.1-1 [103.77MiB 131.87MiB]
    A complete statistical package for both Bayesian and Frequentist statistical methods
bioarchlinux/jasp-desktop-debug 0.17.1-1 [42.20MiB 159.02MiB]
    Detached debugging symbols for jasp-desktop
arch4edu/jasp-desktop 0.16.4-5 [0B 120.92MiB]
    A complete statistical package for both Bayesian and Frequentist statistical methods
aur/jasp-desktop 0.17.1-1 [+1 ~0.01]
    A complete statistical package for both Bayesian and Frequentist statistical methods
```

**Comment by boutinb** [comment] 2023-02-13 11:43
OK, thanks, so I don''t have to warn you anymore, it goes automatically updated when a new release is made.

**Comment by shun2wang** [comment] 2023-02-13 12:06
@boutinb cloud you also add tags for modules and jaspBase/jasptools because they using tag for build on archlinux.
