### ISSUE TITLE
can't change column type in JASP

### ISSUE THREAD

**Issue by amandazhang0727** [jasp-stats/jasp-issues#1064] opened 2020-11-19 15:33 UTC
Hi I cannot change the column type in JASP, even for age and gender.
I understand that this is because it contains non-nominal context but the thing is I don't know how to edit it.
Can someone please help me?
I have sent the data set to a.ly@jasp-stats.org just now.

**Comment by AlexanderLyNL** [comment] 2020-11-19 16:40
Hi Amanda, 

Every column in JASP is read as a variable and it assumes that the first row in each column contains the name of the column. The third column of your data set has in the first cell "Status", which is the name of your column. The second cell is "Response type", because the second cell is text, the variable "Status" is now interpreted as a text variable. The third cell is "{importId: ..." so that's also text. 

The data that you're interested in are in rows 4 until the end. My advice is to replace the first three rows in your data set by a variable name of your liking. This will then allow you to change the variable type. 

Cheers,
Alexander

**Comment by bknakker** [comment] 2021-03-25 19:43
Dear Alexander and JASP team,

I'm not sure whether it is the same problem, but I also cannot change variable type (from scale to ordinal or from nominal to ordinal) as shown in this https://jasp-stats.org/wp-content/uploads/2019/02/change_var_type-smaller-file.gif animation.

JASP 0.14.1.0 running on Windows 10.

Kind regards,
Balázs

**Comment by juliuspf** [comment] 2022-12-05 12:08
I apologize for the late reply. Would you mind uploading your dataset here @bknakker?

**Comment by bknakker** [comment] 2022-12-05 12:52
Unfortunately I don't remember which dataset I was working on back in 2021 spring and I could not reproduce the issue in JASP 0.16.4.0. I'll watch out though and check back here if I bumped into anything similar.

**Comment by juliuspf** [comment] 2022-12-05 13:01
Again, sorry for the delay :) Feel free to close this whenever you wish.

**Comment by tomtomme** [comment] 2024-01-11 20:41
@amandazhang0727 
@bknakker 
We have now edit mode in JASP. This hopefully solves this issue! 
I am closing for now. Feel free to reopen if not soved for you!

**Closed by tomtomme** 2024-01-11 20:41 UTC
