### ISSUE TITLE
Filter is better linked to a specific test/analyses 

### ISSUE THREAD

**Issue by raianali** [jasp-stats/jasp-issues#1392] opened 2021-08-22 20:14 UTC
* Enhancement: Filtering of data now applies to all the analyses/tests in the workbook file - it is better to link the filter to one or more selected analyses/tests. 

* Purpose: Different analyses/tests within the same workbook requires different filters. 
* Use-case: I may filter out those who specified Age as 'Prefer not to Say' for one ANOVA test that is relevant to Age but will return them if another ANOVA test is not relevant to age. 

**Is your feature request related to a problem? Please describe.**
 

it does make things difficult to manage if the analyses/tests of the workbook require different filters and become unmanageable. 

**Describe the solution you'd like**
 
When I apply a filter, an option shall be to link it to the current analysis, e.g. the current ANOVA test, or the whole workbook or a specific set of tests/analyses 

**Describe alternatives you've considered**
 

I know add additional columns of a filtered version of a column which then increases the number of columns to an unmanageable extent at times.  Many thanks

**Comment by vandenman** [comment] 2021-08-23 07:12
This is definitely on our radar, see also https://github.com/jasp-stats/jasp-issues/issues/1330.

**Comment by raianali** [comment] 2021-08-23 07:29
many thanks -- and yes I see the challenge in being error-prone for new users. Save Filter used it for analysis is perhaps the easy shortcut. I.e. create a filter and give it a name and then drag and drop like what we do in the data fields. I should have perhaps put this comment on that #1330

**Comment by juliuspf** [comment] 2022-09-07 07:51
I will close this as a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1330

**Closed by juliuspf** 2022-09-07 07:51 UTC
