### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by B-r-w-n** [jasp-stats/jasp-issues#1899] opened 2022-11-09 23:56 UTC
### JASP Version

0.16.4

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

Linear Modeling

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![Screenshot 2022-11-09 183609](https://user-images.githubusercontent.com/117870538/200964989-fefa7de5-cbcb-4084-b319-632628571391.png)
When I enter in the dependent and independent variables I get this error message. 

### Expected Behaviour

A plot model of the variables, a model comparisons section, and a means of categorical variables should have showed up. 

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-11-10 09:22
@B-r-w-n thanks for reporting this. It is another duplicate of https://github.com/jasp-stats/jasp-issues/issues/1849, and there is already a solution implemented in the nightly builds that will be included in the next release version.

**Closed by juliuspf** 2022-11-10 09:22 UTC
Labels: Module: jaspVisualModeling, OS: Windows 11
