### ISSUE TITLE
Increasing font size ought to increase font size for output tables too

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#1111] opened 2021-01-02 20:51 UTC
From an email:
We can use control+ and control- to change the font sizes. This works very well for the input GUI; however, (and I tried this myself and can confirm), the font sizes for the output tables hardly seem to respond at all. This is inconsistent, and it is a limitation for people with poor eyesight (like me). 

Cheers,
E.J.

**Comment by JorisGoosen** [comment] 2021-01-04 10:51
Hmm, it used to respond, but now it doesn't.
This should definitely be fixed.

**Comment by boutinb** [comment] 2021-01-04 15:10
This works on my Mac

**Comment by JorisGoosen** [comment] 2021-01-04 16:07
Did you test 0.14.1?
Because it  doesnt work on linux.

**Comment by boutinb** [comment] 2021-01-05 08:01
> Did you test 0.14.1?
> Because it doesnt work on linux.

Yes 0.14.1. Tables, notes, title, everything is scaled.

**Comment by vandenman** [comment] 2021-01-05 08:15
flatpak 0.14.1 ([sources](https://github.com/jasp-stats/jasp-desktop/commit/f2cb223fef6b15089fd6e9da54825d370c1ece57)) also also scales for me on Linux.

**Comment by JorisGoosen** [comment] 2021-01-05 09:54
Weirdly enough it now scales for me as well...

I guess we would need to get a screenshot from the OP.
@EJWagenmakers you know who this was right?

**Comment by JorisGoosen** [comment] 2021-01-18 16:09
So this turns out not to be reproducible (I suppose I was too quick in closing JASP the first time, because I *do* see a slight delay in results zooming in/out) and we have no way of contacting OP except through busy EJ so Im closing this issue.

**Closed by JorisGoosen** 2021-01-18 16:09 UTC
