### ISSUE TITLE
Bayesian quantile regression

### ISSUE THREAD

**Issue by Daniel-Sewasew** [jasp-stats/jasp-issues#308] opened 2019-02-18 09:03 UTC
I’m using Jasp recently and I like it so much. I want to analyze Bayesian quantile regression, is that possible at the current status of Jasp? I mean, I found only the frequentist/classical quartiles in the descriptive analyses option.  
Best regards 
Daniel

**Comment by vandenman** [comment] 2019-02-18 09:18
Hi, we currently don't have Bayesian (or frequentist) quantile regression. It looks like there is an R package that does it, called bayesQR (see [here for the package](https://cran.r-project.org/package=bayesQR) and [here for the pdf to the paper](https://www.jstatsoft.org/article/view/v076i07/v76i07.pdf)).

**Comment by sewasewdaniel** [comment] 2019-02-18 09:21
@vandenman Thank you for your prompt reply.
Best 
Daniel

**Comment by lindeloev** [comment] 2019-02-18 11:19
FYI, quantile regression is also implemented in the R package brms: https://github.com/paul-buerkner/brms/issues/168

**Comment by sewasewdaniel** [comment] 2019-02-18 11:40
@lindeloev Thank you for the suggestion, I'll take a look.

**Comment by tomtomme** [comment] 2023-12-20 11:02
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/64

**Closed** 2024-01-04 21:17 UTC
Labels: Module: jaspRegression, Feature Request
