### ISSUE TITLE
Need a dedicated Add-on for Econometrics Modelling in JASP to work Time Series and Panel Model

### ISSUE THREAD

**Issue by SkillTone** [jasp-stats/jasp-issues#1382] opened 2021-08-13 15:53 UTC
* Enhancement: I am from Bangladesh and would like to request to make a dedicated feature for Econometrics modelling, such as Time series analysis, Panel modelling etc. I tried to find in R commander , and found https://www.youtube.com/watch?v=iV8_G70vPNI link. But this is not working. Our students are very happy to use JASP but need this dedicated feature like Machine Learning in JASP. No existing R GUI has this. Packages like Wooldridge, and book like Florian Heiss (Using R for introductory Econometrics) can be easily followed if JASP team add this feature soon.
* Purpose: To learn Econometrics modelling easily specially, Time series and Panel analysis.
* Use-case: University level as an alternative to STATA, Eviews paid software. We can not pay STATA and Eviews for this every year when we have JASP.

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by EJWagenmakers** [comment] 2021-08-13 19:29
Thanks, these are very much on our radar!
Cheers,
E.J.

**Comment by tomtomme** [comment] 2024-02-01 22:42
@SkillTone 
Time series is finished. Can you try if this is sufficient for your needs?

**Comment by SkillTone** [comment] 2024-02-02 06:22
Thanks Jasp-Stats/Jasp-Issues. I will check it out and share with you.
Meanwhile can you please work on panel model analysis tab. It is very much
needed for all academicians. Please kindly help.

Many thanks in advance.

**Comment by tomtomme** [comment] 2024-02-02 13:28
@SkillTone 
We are working on it, but I can give not time frame. 
Thx for sharing your experiences, with the time-series module.

**Comment by tomtomme** [comment] 2024-02-13 09:17
closing now as duplicate of #1876

@SkillTone 
Your feedback on the time series module would still be very much welcome!

**Closed by tomtomme** 2024-02-13 09:17 UTC
Labels: waiting for requester, Feature Request, Module: jaspTimeSeries
