### ISSUE TITLE
Inconsistent choice of (in)dependent variable in Descriptive correlations

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#942] opened 2020-08-18 21:19 UTC
* JASP version: 0.13.1

* OS name and version: Windows 10 Home 64-bit
* Analysis: Descriptives, asking for a correlation plot and a scatter plot.
* Bug description: Using only two variables, the variables on the x- and y-axes switch between the correlation plot and scatter plot.
* Expected behaviour: In particular when only using two variables, I would expect both plots to use the same variables on the x- and y-axes. (BTW: I would also expect confidence intervals are drawn in Scatter Plots in the Correlation option of classical regression...)

#### Steps to reproduce:
1. Go to Descriptives, select two variables.
2. Click on Correlation plots and Scatter plots to produce two plots.
4. See error:
![image](https://user-images.githubusercontent.com/43278770/90566514-ea4ea780-e1a8-11ea-8eb2-832199e6d03d.png)

[birthWeight.zip](https://github.com/jasp-stats/jasp-issues/files/5092882/birthWeight.zip)

**Comment by Kucharssim** [comment] 2020-08-19 09:33
Dear @PeterKlaren,

thanks for the report, and I agree. I will look into it.

> BTW: I would also expect confidence intervals are drawn in Scatter Plots in the Correlation option of classical regression...

We have just implemented this, and it will appear in the next release!

**Comment by PeterKlaren** [comment] 2020-08-20 15:23
A simple solution perhaps is to consistently make the first listed variable the independent variable, and the other one(s) the dependent variable(s).

**Comment by tomtomme** [comment] 2024-01-11 15:04
@Kucharssim 
The switched axis are still there with 0.18.3

**Comment by tomtomme** [comment] 2024-02-10 19:08
@PeterKlaren 
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/1627
work is in progress on this one!

**Closed by tomtomme** 2024-02-10 19:08 UTC
Labels: Module: jaspDescriptives, Bug: Medium
