### ISSUE TITLE
[Feature Request]: Factor Analysis with ordinal data - CFA

### ISSUE THREAD

**Issue by richlv** [jasp-stats/jasp-issues#1723] opened 2022-05-29 12:45 UTC
Quoting from #379:

> As per the title, it would be great to have the ability to conduct FA/CFA using ordinal data. As most questionnaires are scored in this manner, I imagine it would be a feature that would get a lot of usage

On 0.16.2, this does not seem to be available yet.
As requested, creating a new issue.

**Comment by juliuspf** [comment] 2022-11-10 16:38
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/1564

**Closed** 2023-06-23 14:01 UTC
Labels: duplicate, Module: jaspFactor, Feature Request

**Comment by richlv** [comment] 2023-06-23 23:23
Looks like great news, thank you - which release has / will have this change?

**Comment by juliuspfadt** [comment] 2023-06-26 07:54
0.17.3

**Comment by richlv** [comment] 2023-07-05 11:26
I'm checking for a new release every few days, then thought about watching Github releases, then realised JASP does not use Github releases - will have to eagerly check the pages :)
Or perhaps there's an estimate on when 0.17.3 would be out?

**Comment by juliuspfadt** [comment] 2023-07-05 12:22
you might check here: https://static.jasp-stats.org/Nightlies/
although, if you are on macOS intel you will have to wait a bit

**Comment by richlv** [comment] 2023-07-05 12:34
Thanks, in this case I also wanted to share the news with other users who would benefit from a full release.

**Comment by boutinb** [comment] 2023-07-12 13:42
Due to some installer problem on Windows, we cannot yet officially release this version. But here are the links for this version:
. Windows: https://static.jasp-stats.org/JASP-0.17.3.0.msi
. Mac Intel: https://static.jasp-stats.org/JASP-0.17.3.0-macOS-x86_64.dmg
. Mac ARM: https://static.jasp-stats.org/JASP-0.17.3.0-macOS-arm64.dmg
On Windows, if the installer fails, you have first to uninstall your current version, then you can install 0.17.3. We are trying to solve this problem but it takes more time than we thought.

**Comment by juliuspfadt** [comment] 2023-07-20 12:33
@richlv it has been released :)

**Comment by richlv** [comment] 2023-07-20 12:57
Oh yay, thank you so much and congratulations on the release :)
