### ISSUE TITLE
[Feature Request]: FIML for missing data in ANOVA etc.

### ISSUE THREAD

**Issue by mjkofler** [jasp-stats/jasp-issues#2133] opened 2023-05-11 18:56 UTC
### Description

Implementing missing data handling, particularly FIML

### Purpose

Handling missing data natively in JASP

### Use-case

Every dataset that has missing data

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

Option to natively account for missing data using FIML, if possible along with info on missingness (e.g., little's MCAR)

### Describe alternatives that you have considered

export data to SPSS. run missing value analysis. impute missing values. import updated dataset back into JASP. run analyses.

**Comment by EJWagenmakers** [comment] 2023-05-11 20:55
This is very much on our radar!
EJ

**Comment by tomtomme** [comment] 2024-02-08 09:40
@mjkofler 
This seems to be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2437
Lets discuss there.
Pls reopen if I am mistaken. Thx!

**Closed** 2024-02-08 09:40 UTC
Labels: Module: jaspAnova, Feature Request
