### ISSUE TITLE
Latent class analysis

### ISSUE THREAD

**Issue by andremonezi** [jasp-stats/jasp-issues#1157] opened 2021-02-09 12:59 UTC
Dear all, 

It would be exciting to add a feature to run a latent class analysis. With these techniques, we would estimate latent nominal classes in addition to the latent interval factors approximated by factor analysis.

**Comment by tomtomme** [comment] 2023-12-23 14:12
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/397
Can be closed

**Closed** 2024-01-03 12:17 UTC
Labels: Module: jaspSem, Feature Request
