### ISSUE TITLE
Can't change scalar data to ordinal

### ISSUE THREAD

**Issue by teapot81** [jasp-stats/jasp-issues#1374] opened 2021-07-30 16:24 UTC
* JASP version: 0.14.1
* OS name and version: Mac 11.4
* Analysis: Not got far enough to do any analysis
* Bug description: See title
* Expected behaviour: It should just work

#### Steps to reproduce:
1. Have an ordinal dataset of 1, 1.5, 2, 2.5 etc. (These are ordinal categories of disability).
2. Try to change it from Scale to Ordinal
3. Despair when nothing happens

<img width="73" alt="Screenshot 2021-07-30 at 17 22 19" src="https://user-images.githubusercontent.com/81442218/127682598-b2dbb9be-c0db-47c6-b4c0-65721ba9b7c6.png">

<img width="83" alt="Screenshot 2021-07-30 at 17 24 32" src="https://user-images.githubusercontent.com/81442218/127682825-0d5e76ff-8711-4752-841f-560b0555135d.png">

**Comment by vandenman** [comment] 2021-07-30 19:03
So the latest development version at least shows an error message when I try to change contOrdinal from `Scale` to `Ordinal`:
![image](https://user-images.githubusercontent.com/21319932/127699005-d23cd472-9130-47e2-ae27-7d61ea00cc1c.png)

The issue is with the decimal values. A workaround is recoding the column into consecutive integers. To do so, click `Computed Column`:

![image](https://user-images.githubusercontent.com/21319932/127699122-608feeed-93ff-41df-bea9-c02749266d10.png)

next, give the column a name, specify R code, and make sure to select `Ordinal` as the column type:

![image](https://user-images.githubusercontent.com/21319932/127699248-f0c35a0b-ca78-48da-8b76-1687b10e81bc.png)

as R code, enter `match(contOrdinal, sort(unique(contOrdinal)))` and click on `Compute column`:

![image](https://user-images.githubusercontent.com/21319932/127699559-6448d8c8-6f1e-4a7b-a3a3-7eaffc1a661b.png)

this creates a new column that maps the values from the lowest to highest to consecutive integers. In your example, we'd map 1 -> 1, 1.5 -> 2, 2 -> 3, 2.5 -> 4, etc. You should obtain something like this:

![image](https://user-images.githubusercontent.com/21319932/127699878-39f46cf4-67e6-40cb-8086-b937bcd1b786.png)

Now, you can use the new column in your analyses.


I hope that helps!

**Comment by teapot81** [comment] 2021-08-19 11:34
Wow, thanks! I didn't expect there to be a fix.

**Comment by vandenman** [comment] 2021-08-19 11:42
Happy to help, I'm closing this now but if there is anything else feel free to open another issue!

**Closed by vandenman** 2021-08-19 11:42 UTC
