### ISSUE TITLE
[Feature Request]: Missing Values Analysis and Fixing error in Robust Estimation in CFA 

### ISSUE THREAD

**Issue by UsamaSyedIITK** [jasp-stats/jasp-issues#2161] opened 2023-05-24 02:12 UTC
### Description

Little's Test for Missing values analysis

### Purpose

To analyse the missingness in the data.

### Use-case

Whether the data is missing randomly or non-randomly.

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

Inclusion of new Module. Module could be named as Ancillary Data Analysis. 

### Describe alternatives that you have considered

As of now, I'm depend on SPSS only for this.

**Comment by tomtomme** [comment] 2024-02-08 10:30
@UsamaSyedIITK 
duplicate of https://github.com/jasp-stats/jasp-issues/issues/2437
Pls reopen, if I am mistaken.

**Closed by tomtomme** 2024-02-08 10:30 UTC
Labels: Feature Request
