### ISSUE TITLE
[Feature Request]: PCA biplot and loadings

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#2813] opened 2024-07-05 13:36 UTC
### Description

Display PCA results with a biplot and loading vectors

### Purpose

To make a conventional display of PCA results possible

### Is your feature request related to a problem?

No.

### Is your feature request related to a JASP module?

Factor

### Describe the solution you would like

An output option to display a biplot with/without loadings.

### Describe alternatives that you have considered

The path diagram is not conventional in some disciplines, for example the life sciences.

### Additional context

It also is conventional to abbreviate principal components as PC. RC (rotated component?) is not that common in use.

**Comment by tomtomme** [comment] 2024-07-05 14:18
@PeterKlaren 
Thx for the request. This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2501
Please reopen, if you disagree!

**Closed by tomtomme** 2024-07-05 14:18 UTC
Labels: Module: jaspFactor, Feature Request
