### ISSUE TITLE
[Bug]: "Failed to initialize graphics backend for OpenGL."

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-issues#1690] opened 2022-04-20 02:14 UTC
### JASP Version

0.16.2

### What OS are you seeing the problem on?

Windows 10

### Bug Description

JASP 0.16.2 will not run at all. Upon attempted launch, the error message is: 

**"Failed to initialize graphics backend for OpenGL."**

![image](https://user-images.githubusercontent.com/16230091/164132352-26baa430-5832-4ca7-85d4-f0dee05ef2e9.png)

### Expected Behaviour

Failure should not have occurred.

### Steps to Reproduce

Launch JASP 0.16.2

### Log (if any)

Logs cannot be accessed because the JASP 0.16.2 will not run. 

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment] 2022-04-20 07:44
I'm not as familiar with the Windows stack, and its special graphic modes; but maybe @boutinb could help? In the meantime, if you don't mind trying, I wonder what would happen if instead of upgrading JASP, you remove JASP and install it again. With this, I'm hopping that a freshly installed version can navigate its way without interference from the old version.

**Comment by boutinb** [comment] 2022-04-20 09:55
@R180, can you start JASP from the command line where JASP is installed (usually in C:\Program Files\JASP):
```
cd "C:\Program Files\JASP"\
jasp --safeGraphics
```

**Comment by tomtomme** [comment] 2024-01-17 10:20
@R180 
can you re-test with current jasp 0.18.3? And with maybe updated graphics drivers?

**Comment by R180** [comment] 2024-01-17 10:40
I've been using jasp 0.18.1 and the initialization-failure happens only about 1/7th of the time. I'll try 0.18.3, but I'll only have that computer for two more weeks, at which point I'll be issued a new one.

Richard B. Anderson
Professor, Department of Psychology
Bowling Green State University
***@***.***
My BGSU personal Zoom link for telemeetings: https://bgsu-edu.zoom.us/j/2918069564
Complex Cognition Lab: https://sites.google.com/view/complexcognitionlab-bgsu/

[signatureImage]
________________________________
From: Thomas Langkamp ***@***.***>
Sent: Wednesday, January 17, 2024 5:20:29 AM
To: jasp-stats/jasp-issues ***@***.***>
Cc: Richard Anderson ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [jasp-stats/jasp-issues] [Bug]: "Failed to initialize graphics backend for OpenGL." (Issue #1690)


@R180<https://github.com/R180>
can you re-test with current jasp 0.18.3? And with maybe updated graphics drivers?

**Comment by tomtomme** [comment] 2024-01-17 15:20
@R180 
ok thx. Since the error is not really reproducable, do you agree that we can close this issue?

**Comment by R180** [comment] 2024-01-18 00:24
Yes. Thanks.

**Closed** 2024-01-18 08:33 UTC
Labels: OS: Windows 10, Bug: High

**Comment by boutinb** [comment] 2024-01-22 11:18
Just to be sure, do you have the 'Safe graphics mode' on (in the Preferences/Interface/Miscellaneous options) ?

**Comment by R180** [comment] 2024-01-22 13:22
Yes I do.

**Comment by boutinb** [comment] 2024-01-22 14:01
If this error occurs, it would be nice also to have the log files (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md), maybe it tells a bit more about the error.
You could also try to use JASP with this 'Safe graphics mode' off: this setting forces the use of the OpenGL implementation, and your error is precisely an OpenGL error.
