### ISSUE TITLE
[Feature Request]: Colours in plots

### ISSUE THREAD

**Issue by MenimadimAnna** [jasp-stats/jasp-issues#2890] opened 2024-09-02 08:26 UTC
### Description

Request for colour options in distribution plots and flex plots

### Purpose

aesthetics

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

(More) colour options for basic plots and flexplots

### Additional context

1) Distribution plots

[https://forum.cogsci.nl/uploads/380/KQC9K2PN1Q5Y.png](url)
It would be great if there was a colour option not just for customizable plots but also for basic plots

2) Flexplots (from the Visual Modeling module)
[https://forum.cogsci.nl/uploads/136/0AYJEJWVNUVZ.png](url)

Red or greyscale seem to be the only options across themes and palettes. It would be nice to have more colours to choose from.

**Comment by tomtomme** [comment] 2024-09-04 07:01
@MenimadimAnna 
thx for the request.
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2122
Lets discuss there.
Please reopen this issue, if you disagree!

**Closed by tomtomme** 2024-09-04 07:01 UTC
Labels: Module: jaspVisualModeling, Module: jaspDescriptives, Feature Request, Component: Plot Editing
