### ISSUE TITLE
Mediation analysis termination

### ISSUE THREAD

**Issue by khanson002** [jasp-stats/jasp-issues#480] opened 2019-09-11 10:50 UTC
* JASP version: 10.2
* OS name and version: MacOS Mojave 10.14.5
* Analysis: Mediation
* Bug description: 
Have been using the same data for a number of regressions in JASP with no issues. Mediation analysis attempt: two scaled predictors, two scaled mediators, one scaled outcome, received this message:
This analysis terminated unexpectedly.

Error in rawToChar(as.raw(out)): embedded nul in string: 'X0/x80'

Tried the same predictors and mediators (no error message when only these are entered), with an ordinal outcome. Error message:
Estimation failed
Message:
lavaan ERROR: missing = “fiml” not available in the categorical setting

* Add JASP files as a zip:
* Screenshot: 
<img width="1422" alt="Screenshot 2019-09-11 at 11 44 04" src="https://user-images.githubusercontent.com/55188449/64691178-ff479480-d489-11e9-97e6-b9538530c97b.png">

* Expected behaviour:
* Steps to reproduce: 1. select mediation analysis, 2. drag over selected variables 3. see error

**Comment by AlexanderLyNL** [comment] 2019-09-11 11:24
Could you please add the jasp file as a zip to this thread?

**Comment by TimKDJ** [comment] 2019-09-11 11:27
This is a duplicate of #465 
A fix for this will \*hopefully\* be available by next week in JASP 0.11

**Closed by TimKDJ** 2019-09-11 11:27 UTC
Labels: Waiting for requester

**Comment by khanson002** [comment] 2019-09-11 11:28
That’s great, thank you!

On 11 Sep 2019, at 12:27, Tim de Jong <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a duplicate of #465<https://github.com/jasp-stats/jasp-issues/issues/465>
A fix for this will *hopefully* be available by next week in JASP 0.11

**Comment by AlexanderLyNL** [comment] 2019-09-11 11:29
It would nonetheless be good to try it out with a test case so we can confirm that it's indeed fixed.

**Comment by mebuenaventura** [comment] 2019-09-18 18:29
Hi! Is this fixed already?

**Comment by AlexanderLyNL** [comment] 2019-09-21 09:42
Hi medbuenaventura, 

It's solved. I've even tested this with the jasp files that were included in the issues. If you send me yours I can double check for you as well. 

Cheers,
Alexander
