### ISSUE TITLE
Saving residuals and factor scores

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#151] opened 2018-04-14 11:50 UTC
From the forum:

"Can I save factor score, regression residuals, ... in JASP ? I did not see the function, but maybe it is well hidden ?"

Would be useful. Perhaps we can address it once we have "compute columns" working. @JorisGoosen @vankesteren 

E.J.

**Comment by freckledude** [comment] 2020-04-29 05:32
I also support this feature!

**Comment by juliuspfadt** [comment] 2023-03-29 07:51
duplicate of https://github.com/jasp-stats/jasp-issues/issues/101

**Comment by tomtomme** [comment] 2023-12-23 19:07
can be closed, since its a duplicate

**Closed** 2023-12-23 19:51 UTC
Labels: Module: jaspFactor, Feature Request
