### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RuSMay238** [jasp-stats/jasp-issues#2936] opened 2024-09-28 18:00 UTC
### JASP Version

0.19.0

### JASP Module

SEM

### What OS are you seeing the problem on?

Windows 10

### Bug Description

![image](https://github.com/user-attachments/assets/2c74e11b-3be7-48e3-baf0-37dfd0359b0f)
Error in if (nrow(originalSyntaxTable[originalSyntaxTable$op = ':=', : argument is of length zero
![Screenshot 2024-09-29 014730](https://github.com/user-attachments/assets/f5a0f6b7-23fe-4d01-b4bd-bb74770202cd)

### Expected Behaviour

N/a

### Steps to Reproduce

1.
2.
3.
...
![Screenshot 2024-09-29 015908](https://github.com/user-attachments/assets/bb969a82-cb3d-4de5-bc95-bc43bb050800)

### Log (if any)

![Screenshot 2024-09-29 015908](https://github.com/user-attachments/assets/24347880-60d1-4c32-a813-c51d07802149)

### More Debug Information

![Screenshot 2024-09-29 015706](https://github.com/user-attachments/assets/fb67435a-4204-49f5-a62c-2045002458b6)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2024-09-30 05:22
thanks for creating the issue, this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2879 and will be fixed in the next release

**Closed by juliuspfadt** 2024-09-30 05:22 UTC
Labels: Module: jaspSem, OS: Windows 10, Bug

**Comment by juliuspfadt** [comment] 2024-10-01 17:24
I would suggest you check out a development-nightly from here https://static.jasp-stats.org/Nightlies/. However, the sem module is currently not available in there, but we are working on a fix
