### ISSUE TITLE
[Feature Request]: Use correlation matrix as input

### ISSUE THREAD

**Issue by glcanivez** [jasp-stats/jasp-issues#1802] opened 2022-08-15 15:07 UTC
### Description

Factor Analysis from Correlation Matrix

### Purpose

To run factor analysis using a correlation matrix rather than raw data

### Is your feature request related to a problem?

No, the current EFA/CFA seems to operate similarly to other statistics programs

### Describe the solution you would like

It would be very useful to be able to input a correlation matrix and run factor analysis (EFA and CFA) from that matrix when one does not have raw data as input.

### Describe alternatives that you have considered

In SPSS I use Syntax to input correlation matrices and in EQS I can input a correlation matrix, means, and standard deviations to reconstruct a covariance matrix for CFA

### Additional context

This feature would also be helpful for second-order/higher-order EFA using first-order factor pattern coefficients and the factor correlations. I have also used SPSS syntax for this and third-party freeware (Watkins) to conduct these.

**Comment by juliuspf** [comment] 2022-08-17 12:49
Hi @glcanivez, thanks for the request. @AlexanderLyNL is there anything on the horizon regarding covariance/correlation matrices as input instead of the data matrix?

**Comment by mww10** [comment] 2024-10-10 18:03
Several have requested correlation matrix input for EFA and correlation/standard deviation input for CFA. #2174 is marked as closed. This option is not available in JASP 0.19.1 for my Apple silicon machine. Why was this request closed if it was not implemented?

**Comment by juliuspfadt** [comment] 2024-10-10 20:45
Looking into https://github.com/jasp-stats/jasp-issues/issues/2174, I see that it was marked as a duplicate which is why it was closed. The issue is still relevant.

**Comment by mww10** [comment] 2024-10-10 21:01
Thanks. Correlation matrix and correlation matrix/standard deviations for
EFA and CFA, respectively, would greatly increase utility of JASP for me
and other colleagues who frequently conduct EFA and CFA in measurement
studies.

Marley

**Comment by juliuspfadt** [comment] 2024-10-11 06:08
you are right. I should get on this :)

**Comment by mww10** [comment] 2024-10-11 17:58
Thank you. I appreciate your support. After this is done I will contact my
publisher to recommend a new book on factor analysis using JASP.

Marley

**Closed** 2024-10-16 12:44 UTC
Labels: Module: jaspFactor, Feature Request

**Comment by glcanivez** [comment] 2024-10-16 13:50
Thank you for your work on this. I look forward to the JASP update where this will be available.

Cheers, Gary

Gary L. Canivez, Ph.D.
Professor of Psychology
Senior Editor, School Psychology Review
Former Associate Editor for Psychological Assessment and
Archives of Scientific Psychology
Department of Psychology
600 Lincoln Avenue
Eastern Illinois University
Charleston, IL 61920

217-581-6413 (ph)
217-581-6764 (fax)

email: ***@***.***
web site: www.ux1.eiu.edu/~glcanivez
LinkedIn: www.linkedin.com/in/glcanivez
Research Gate: https://www.researchgate.net/profile/Gary_Canivez
Google Scholar: https://scholar.google.com/citations?user=tWsy9SMAAAAJ&hl=en


“It is easier to fool people than to convince them that they have been fooled.”  Mark Twain


On Oct 16, 2024, at 7:44 AM, Julius Pfadt ***@***.***> wrote:



Closed #1802<https://github.com/jasp-stats/jasp-issues/issues/1802> as completed via jasp-stats/jaspFactor#239<https://github.com/jasp-stats/jaspFactor/pull/239>.

**Comment by glcanivez** [comment] 2025-09-21 03:44
Yes, I was able to enter a correlation matrix into a new data sheet in JASP and specify the sample size and it worked. I need to play around with all the features but nice to know that feature is working. Maybe the radio button in the Analyses section can also designate Correlation Matrix too. My colleague Marley verified it worked for him too so he may now go ahead and see about extending his EFA books to now also include JASP.

Thanks so much for your work and all JASP is becoming.

Cheers, Gary

Gary L. Canivez, Ph.D.
Professor of Psychology
Senior Editor, School Psychology Review
Former Associate Editor for Psychological Assessment and
Archives of Scientific Psychology
Department of Psychology
600 Lincoln Avenue
Eastern Illinois University
Charleston, IL 61920

217-581-6413 (ph)
217-581-6764 (fax)

email: ***@***.***
web site: www.ux1.eiu.edu/~glcanivez
LinkedIn: www.linkedin.com/in/glcanivez
Research Gate: https://www.researchgate.net/profile/Gary_Canivez
Google Scholar: https://scholar.google.com/citations?user=tWsy9SMAAAAJ&hl=en


“It is easier to fool people than to convince them that they have been fooled.”  Mark Twain


[Canivez(2025)_c1.jpeg]
https://www.bloomsbury.com/us/assessing-psychometric-fitness-of-intelligence-tests-9781538145722/





On Sep 20, 2025, at 4:33 PM, Julius Pfadt ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/38500953?s=20&v=4]juliuspfadt left a comment (jasp-stats/jasp-issues#1802)<https://github.com/jasp-stats/jasp-issues/issues/1802#issuecomment-3315275446>

@glcanivez<https://github.com/glcanivez>, a correlation matrix works perfectly fine as input. In a sense every correlation matrix is a covariance matrix. In the background a "pure" covariance matrix is actually transformed to a correlation matrix, whereas a correlation matrix just stays the same.
