### ISSUE TITLE
[Feature Request]: Assumption check for normality in ANOVA

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#2363] opened 2023-10-24 13:16 UTC
### Description

Include Shapiro-Wilk's test in ANOVA to test the normality assumption

### Purpose

Check assumptions of a parametric ANOVA

### Is your feature request related to a problem?

Not applicable.

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

An option "normality tests" under the drop-down menu Assumption Checks.

### Describe alternatives that you have considered

Check normality in the Descriptives module

### Additional context

Give a full set of assumption checks: homoskedasticity and normality. It would be preferable when these checks are selected by default (as they also could be in the T-Tests module).

**Comment by JoKeyser** [comment] 2023-10-24 15:08
I wonder if a useful, generic solution to this kind of request would be an option to add the residuals of a model to the data set. Then people could do their checks, graphing, etc. with a generic analysis module?

**Comment by chantelanuit** [comment] 2023-10-24 16:35
I really like the suggestion made by JoKeyser. The possibility that you suggest would add a lot of flexibility to personalize the assumptions related to the analyses.

**Comment by EJWagenmakers** [comment] 2023-10-24 19:02
My two cents:
1. Yes we should add the tests for normality under assumption checks.
2. Yes we should add the option to add the residuals to the data set (I think we have options such as these for other analyses, so it is possible)
3. I don't want to have these tests turned on by default, as this goes against our philosophy of progressive disclosure and would move us to the SPSS model where the user is presented with a ton of analyses which then have to be sifted through. We could however issue a warning underneath the standard ANOVA table in case of violations.

**Comment by PeterKlaren** [comment] 2023-10-24 19:55
I am thinking of my first-year biology students I am currently teaching using JASP... For sure the residuals to a data set are useful, and/but I think for a more advanced statistics user only. I currently treat residuals in the context of assessing the quality of a linear regression in different data sets (think of the Anscombe quartet). To take residuals a step further would require quite some time and effort from both lecturer and students.

Beginning users of statistics likely "play by the book", and would look for the assumptions checks that the books tell them to do. Adding a normality check next to the homogeneity check is the logical place where one would look to perform one.

**Comment by EJWagenmakers** [comment] 2023-10-24 20:27
Yes, and that would be straighforward to add. Saving the residuals can also be done of course -- always a matter of adding functionality without confusing the student

**Comment by tomtomme** [comment] 2024-02-08 16:13
Closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/490
I included option b) to save residuals everywhere in #490

**Closed by tomtomme** 2024-02-08 16:13 UTC
Labels: Module: jaspAnova, Feature Request
