### ISSUE TITLE
[Bug]: Audit module - selection and Maximum Likely Error seem different from version 0.15 and onwards

### ISSUE THREAD

**Issue by jordir93** [jasp-stats/jasp-issues#1588] opened 2022-01-26 08:38 UTC
### JASP Version

0.16

### JASP Module

jaspAudit

### What analysis are you seeing the problem on?

Audit - Selection and Evaluation

### What OS are you seeing the problem on?

Windows 10 and 11

### Bug Description

Firstly, when calculating the MLE in the audit module of JASP, we encoutered some changes in the MLE starting in version 0.15.
With the same sample it first was about 33.000 and after it was -168.000. Were there any changes in the calculation of this error or is this wrongly calculated? If there were some changes, what were those changes? 
The changes in MLE can be seen in the pictures.
Version 0.14:
![MLE version 0 14](https://user-images.githubusercontent.com/78072959/151128241-5123a1ba-8fc2-4d9d-8cb2-25efcedcc083.png)
Version 0.15:
![MLE version 0 15](https://user-images.githubusercontent.com/78072959/151128236-e37d78ea-f741-4054-83a7-3b7ff9d1f816.png)
Version 0.16:
![MLE version 0 16](https://user-images.githubusercontent.com/78072959/151128240-2d33e2de-1958-47a3-84e5-ffd522240036.png)

Secondly, when taking a sample we sometimes saw observation getting selected multiple times when drawing observations randomly. In version 0.14 this was not the case. Was there a change in the way the sample is drawn? 

### Expected Behaviour

We think the MLE should be calculated the way it was in 0.14.
When drawing a random sample, we should not get observations more than once in the sample.
Maybe add a button so people can choose if they want observations more than once in their sample.

### Steps to Reproduce

1. Open JASP
2. Load data
3. Open Audit module - sampling workflow
4. Do the planning as usual. 
5. Make selection (make sure it is on random sampling) - here is the selection "bug"
6. Do the evaluation - Here is the Maximum Likely Error - different from version 0.15 an onwards

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment] 2022-01-26 08:53
Hi @jordir93, 

I will investigate the discrepancies between these screenshots. Are you able to provide the .jasp file (you can zip it and add it to your comment) that these analyses are made with?

**Comment by jordir93** [comment] 2022-01-26 09:10
Hi @koenderks 
Yes I do. Here they are:
[Evaluations in JASP.zip](https://github.com/jasp-stats/jasp-issues/files/7940301/Evaluations.in.JASP.zip)

**Comment by koenderks** [comment] 2022-01-26 10:03
Hi @jordir93,

I can see from your file `Jasp voorraad evaluatie in 0.14.jasp` that you have set the variable `Werkelijke waarde` as the `Ist position` (called `Book values` in 0.16) and your variable `Waarde vrd.` as the `Soll position` (called `Audit values` in 0.16). With the variable definitions like this, I can reproduce your results from the 0.14 screenshot.

![image](https://user-images.githubusercontent.com/25059399/151138714-a81e010a-df36-45f2-bbc7-a2e267177552.png)

This explains the discrepancy between the screenshots of 0.14 and 0.15, since in the 0.15 .jasp file I see that `Werkelijke waarde` corresponds to `Audit values` and `Waarde vrd.` corresponds to `Book values`. It seems like these have been switched around, explaining why there is a positive taint in the 0.14 screenshot and a negative taint in the 0.15 screenshot. I think you probably want to have the variable definitions the "0.15 way" though, since there is an understatement of the true value of this inventory if I'm correct?

About the 0.16 screenshot, I cannot reproduce your results by opening the .jasp `Verschillen steekproef in 0.16.jasp`. When I open the file in JASP 0.16, I get a different screenshot than you? For example, I see that in your screenshot there are only 15 errors.

![image](https://user-images.githubusercontent.com/25059399/151140659-28dd994b-f808-4a14-8b46-d5df85724f65.png)

```


Finally, about the sampling. There has been a change in the sampling that allows for items to be selected multiple times, and it is currently always on. I realize that this is not always useful (especially in the case where you are selecting items instead of monetary units). You are right that it is probably useful to have a button that allows to exclude this, I will get on it for 0.17.

**Comment by koenderks** [comment] 2022-01-26 11:07
Hi @jordir93,

I can see from your file `Jasp voorraad evaluatie in 0.14.jasp` that you have set the variable `Werkelijke waarde` as the `Ist position` (called `Book values` in 0.16) and your variable `Waarde vrd.` as the `Soll position` (called `Audit values` in 0.16). With the variable definitions like this, I can reproduce your results from the 0.14 screenshot.

![image](https://user-images.githubusercontent.com/25059399/151138714-a81e010a-df36-45f2-bbc7-a2e267177552.png)

This explains the discrepancy between the screenshots of 0.14 and 0.15, since in the 0.15 .jasp file I see that `Werkelijke waarde` corresponds to `Soll position` and `Waarde vrd.` corresponds to `Ist position`. It seems like these have been switched around, explaining why there is a positive taint in the 0.14 screenshot and a negative taint in the 0.15 screenshot. I think you probably want to have the variable definitions the "0.15 way" though, since there is an understatement of the true value of this inventory if I'm correct?

![image](https://user-images.githubusercontent.com/25059399/151150653-654b6bf6-bf0c-42a1-9dd3-37baefa0ba7d.png)

We can verify this calculation / result using the `jfa` package in R using the following code:
```
> x <- read.csv(file = "Verschillen steekproef.csv", sep = ";")
> xsub <- x[complete.cases(x), ]
> jfa::evaluation(materiality = 10500 / sum(x$Waarde.vrd.), data = xsub, values = "Waarde.vrd.",
+                 values.audit = "Werkelijke.waarde", method = "stringer.lta", N.items = 1710, 
+                 alternative = "less", conf.level = 0.9167)

	Classical Audit Sample Evaluation

data:  xsub
number of errors = 16, number of samples = 39, taint = -3.8601
91.67 percent confidence interval:
  0.00000000 -0.03210522
estimate:
 -0.09897615 
estimates obtained via method 'stringer.lta'
> mle <- -0.09897615 * sum(x$Waarde.vrd.)
> mle
[1] -168938.3
> 
> ub <- -0.03210522 * sum(x$Waarde.vrd.)
> ub
[1] -54799.08
```

Until now these differences are explainable. However, I cannot reproduce your results by opening the .jasp `Verschillen steekproef in 0.16.jasp`. When I open the file in JASP 0.16, I get a different screenshot than you? For example, I see that in your screenshot there are only 15 errors. 

However, there is a bug in 0.16 where the LTA adjustment is not applied (thank you for noticing this!) and therefore the upper bound is calculated without the LTA adjustment. I will fix this right away.

![image](https://user-images.githubusercontent.com/25059399/151140659-28dd994b-f808-4a14-8b46-d5df85724f65.png)

The main conclusion is that the calculations from 0.14 and 0.15 are both correct. However, only the way you have provided the variables in 0.15 (`Waarde.vrd` as `Book values` and `Werkelijke.waarde` as `Audit values`) gives the correct result. JASP 0.16.1 will provide this result like this as well:

![image](https://user-images.githubusercontent.com/25059399/151152500-913d9f9b-567c-4f9d-b97e-a73c59ec837a.png)

Finally, about the sampling. There has been a change in the sampling that allows for items to be selected multiple times, and in 0.16 this option is always on. I realize that this is not always useful (especially in the case where you are selecting items instead of monetary units). You are right that it is probably useful to have a button that allows to exclude this, I will get on it for 0.17.

**Comment by juliuspf** [comment] 2022-09-01 08:10
@jordir93 Do you consider this issue fixed? Feel free to close it then.

**Closed** 2023-04-06 06:36 UTC
Labels: Module: jaspAudit
