### ISSUE TITLE
[Bug]: Application crashes when filtering column values on Linux

### ISSUE THREAD

**Issue by jl-a** [jasp-stats/jasp-issues#1678] opened 2022-04-08 06:56 UTC
### JASP Version

0.16.1

### What OS are you seeing the problem on?

Linux (Manjaro, KDE Plasma 5.14.3, kernel 5.16.14-1)

### Bug Description

When filtering column values by clicking on the column label and then un-checking any of the values, the application hangs for a few seconds and then crashes. This only occurs under Linux.

When running from the command line (`flatpak run org.jaspstats.JASP`) the output is
`qrc:/components/JASP/Widgets/FilterWindow.qml:316:7: QML RectangularButton: Binding loop detected for property "width"`
before the application quits.

### Expected Behaviour

The application should not crash and the column values should be filtered.

### Steps to Reproduce

1. Install Jasp through Flatpak under Linux (I use Arch base)
2. Open a CSV
3. Click any column label and then click the check mark for any Filter value
4. Observe the application crash

### Log (if any)

[JASP 2022-04-08 16_24_15 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/8449308/JASP.2022-04-08.16_24_15.Desktop.log)
[JASP 2022-04-08 16_24_15 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/8449310/JASP.2022-04-08.16_24_15.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2022-04-08 09:53
This is a known bug. It should be fixed with the upcoming 0.16.2 version

**Comment by juliuspf** [comment] 2022-04-21 14:41
Hi @jl-a. thanks again for reporting. Could you try this again with the new released version 0.16.2 https://jasp-stats.org/download/ ?

**Comment by tomtomme** [comment] 2022-05-20 06:51
This works now for me in flatpak beta 0.16.3 :D

**Comment by vandenman** [comment] 2022-05-20 07:51
I can confirm that this is fixed in the beta version of 0.16.3. Given that the next release won't be long I'm closing the issue (but feel free to reopen it in case it turns out it isn't fixed in the released version).

**Closed by vandenman** 2022-05-20 07:51 UTC
Labels: OS: Linux / Flatpak, filtering
