### ISSUE TITLE
[Feature Request]: RM ANOVA Confidence Intervals

### ISSUE THREAD

**Issue by maximusmontis** [jasp-stats/jasp-issues#2143] opened 2023-05-16 14:37 UTC
### Description

Currently, RM ANOVA plots by default show normalized standard errors or confidence intervals (this is explained only in the help file). This procedure should be optional, as we might also want to report non-normalized confidence intervals or standard errors. Secondly, it should be made more salient that the confidence intervals and standard errors are normalized. Without looking at the help file, this is indicated nowhere.

### Purpose

Improves JASP comparability with other statistical software; reduces risk for misunderstandings

### Use-case

All RM ANOVA plots

### Is your feature request related to a problem?

https://github.com/jasp-stats/jasp-issues/issues/2127

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

Currently, RM ANOVA plots by default show normalized standard errors or confidence intervals (this is explained only in the help file). This procedure should be optional, as we might also want to report non-normalized confidence intervals or standard errors. Secondly, it should be made more salient that the confidence intervals and standard errors are normalized. Without looking at the help file, this is indicated nowhere.

**Comment by JohnnyDoorn** [comment] 2023-05-16 14:48
Thanks @maximusmontis , I will try to have this in the next JASP release!

**Comment by EJWagenmakers** [comment] 2023-05-16 15:17
Yes good idea!

**Comment by maximusmontis** [comment] 2023-08-02 09:59
@JohnnyDoorn, any update on this? As far as I can see in the latest changelog, this has not yet been included.

**Comment by JohnnyDoorn** [comment] 2023-08-02 12:02
Hi @maximusmontis no I'm sorry, I could not get to this before the break.

**Comment by maximusmontis** [comment] 2023-12-06 12:10
Hi @JohnnyDoorn , have you gotten around to include this in the next release (or any kind of timeline)? No worries if not, just wanted to follow up!

**Comment by JohnnyDoorn** [comment] 2023-12-06 13:34
Hi @maximusmontis,

I am planning a bigger upgrade to the ANOVA and regression (after teaching a big stats course myself, I discovered some nice opportunities, like being able to export model residuals/predictions), and this will definitely be included! This will only be for earlier next year though, since I am still wrapping up my teaching. 

Cheers,
Johnny

**Comment by tomtomme** [comment] 2024-03-01 12:05
@maximusmontis 
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/1227
Please reopen if you disagree!

**Closed by tomtomme** 2024-03-01 12:05 UTC
Labels: Module: jaspAnova, Feature Request
