### ISSUE TITLE
cfa[Bug]: 

### ISSUE THREAD

**Issue by ajames0001** [jasp-stats/jasp-issues#2865] opened 2024-08-07 19:36 UTC
### JASP Version

0.19.0

### JASP Module

Factor

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

 CFA  stopped 
![image](https://github.com/user-attachments/assets/fc77a671-9904-4b63-a708-7a8b42aca516)

### Expected Behaviour

CFA OUTPUT

### Steps to Reproduce

1. RE-RUN happens every time
2.
3.
...

### Log (if any)

<div class="jasp-toolbar jasp-title-toolbar h2-toolbar" style="display: block; color: rgb(0, 0, 0); font-family: &quot;Lucida Grande&quot;, Helvetica, Arial, sans-serif, &quot;Helvetica Neue&quot;, freesans; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 class="in-toolbar toolbar-clickable" style="font-size: 18px; cursor: pointer; min-width: 1em; display: inline-block; vertical-align: middle;"><br class="Apple-interchange-newline">Confirmatory Factor Analysis</h2><div class="toolbar-button toolbar-clickable jasp-menu" style="width: 16px; height: 16px; margin-left: 4px; cursor: pointer; background: url(&quot;images/lightTheme/menu-indicator.svg&quot;) center center / 70% no-repeat; display: inline-block; vertical-align: middle; font-size: 18px;"></div><div class="status fatalError" style="width: 16px; height: 16px; background-size: 100%; display: inline-block; margin-left: 6px; visibility: hidden; vertical-align: middle;"></div></div><div class="jasp-progressbar-container" style="min-height: 1.25em; color: rgb(0, 0, 0); font-family: &quot;Lucida Grande&quot;, Helvetica, Arial, sans-serif, &quot;Helvetica Neue&quot;, freesans; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div id="id-8" class="jasp-analysis" style="color: silver; font-family: &quot;Lucida Grande&quot;, Helvetica, Arial, sans-serif, &quot;Helvetica Neue&quot;, freesans; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; opacity: 1;"><div class="jasp-display-item jasp-collection jasp-view" style="margin-top: 0.1em; margin-bottom: 0.6em; padding-left: 0.6em; margin-right: 0.6em; padding-right: 0.6em; background-color: rgba(224, 224, 224, 0); border: 1px solid rgba(105, 105, 105, 0); border-radius: 6px;"><div class="jasp-toolbar h3-toolbar" style="display: block;"><h3 class="in-toolbar toolbar-clickable" style="font-size: 15px; margin-top: 0.5em; margin-bottom: 0.5em; cursor: pointer; min-width: 1em; display: inline-block; vertical-align: middle;">Model fit</h3><div class="toolbar-button toolbar-clickable jasp-menu jasp-hide" style="display: inline-block; visibility: hidden; width: 16px; height: 16px; margin-left: 4px; cursor: pointer; background: url(&quot;images/lightTheme/menu-indicator.svg&quot;) center center / 70% no-repeat; vertical-align: middle; font-size: 15px; margin-top: 0.5em; margin-bottom: 0.5em;"></div></div><div class="object-body"><div class="jasp-display-item jasp-collection-table jasp-table jasp-view jasp-indent jasp-collection-item jasp-collection-table jasp-collapsible jasp-display-item-flat" style="margin-top: 0.1em; margin-bottom: 0.6em; padding-left: 0px; margin-right: 0.6em; padding-right: 0.6em; background-color: rgba(224, 224, 224, 0); border: 1px solid rgba(105, 105, 105, 0); border-radius: 6px;"><div class="object-body"><div class="jasp-table-primitive jasp-display-primitive" style="padding-left: 0.6em;">
Chi-square test
--

Baseline model |   | 85742.086 |   | 276 |   |   |   |  
Factor model |   | 4366.981 |   | 249 |   | < .001 |  
 
Note. The estimator is DWLS and the test statistic is scaled.shifted because there are categorical variables in the data. You may consider changing the standard error method to 'robust'.

</div></div></div></div><div class="fatalError analysis-error-message error-message-box ui-state-error" style="border: 3px double rgb(241, 168, 153); background: rgb(253, 223, 223); color: rgb(95, 63, 63); min-width: 300px; max-width: 1000px; position: absolute; top: 60px; left: 50px; margin-right: 50px; z-index: 100; padding: 1em; border-radius: 0.4em; white-space: normal; font-family: &quot;Lucida Grande&quot;, Helvetica, Arial, sans-serif, &quot;Helvetica Neue&quot;, freesans; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="ui-icon ui-icon-alert" style="display: inline-block; vertical-align: middle; margin-top: -0.25em; position: relative; text-indent: -99999px; overflow: hidden; background-repeat: no-repeat; width: 16px; height: 16px; background-image: url(&quot;images/ui-icons_cc0000_256x240.png&quot;); background-position: 0px -144px; float: left; margin-right: 0.3em;"></span>This analysis terminated unexpectedly.<br><br>Error in diag(scales) %*% truevar: non-conformable arguments<br><br><div class="stack-trace-selector"><span style="cursor: pointer; display: inline-block; vertical-align: middle;">Stack trace</span><div class="stack-trace-arrow" style="width: 16px; height: 16px; margin-left: 2px; background: url(&quot;images/lightTheme/expand.png&quot;) center center / 70% no-repeat; cursor: pointer; display: inline-block; vertical-align: middle;"></div></div><div class="stack-trace" style="display: block;">tryCatchOne(expr, names, parentenv, handlers[[1]])<br><br>doTryCatch(return(expr), name, parentenv, handler)<br><br>withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)<br><br>analysis(jaspResults = jaspResults, dataset = dataset, options = options)<br><br>.cfaTableReliability(jaspResults, options, cfaResult)<br><br>semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)<br><br>omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])</div><br>To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-report</div>

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2024-08-08 07:47
@ajames0001 thanks for creating the issue. This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2294. We cant fix if the maintainer of the R-package does not fix it.

**Closed by juliuspfadt** 2024-08-08 07:47 UTC
Labels: Module: jaspFactor, OS: macOS Silicon, Bug
