### ISSUE TITLE
Impossible to specify a contrast-specific error term in custom contrasts for within-subjects ANOVA (BUG)

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#1221] opened 2021-03-23 10:31 UTC
Hi,
In within-subjects designs, it is usually recommended to use a contrast-specific error term, because any degree of violation of the sphericity assumption will make the error term too small or too large for some comparisons (e.g., Boik, 1981). However, it is currently (JASP 14.1) impossible to use a contrast-specific error term when specifying custom contrasts. Unchecking 
 "Assume equal variances" (it might be better to call this option "Pool error term", similar to the Simple Main Effects menu) returns "Unequal variances only available for main effects of within-subjects factors" (see attached file). 

[BlanchardprepJASP.zip](https://github.com/jasp-stats/jasp-issues/files/6188882/BlanchardprepJASP.zip)

Best,
Mathieu

**Comment by bknakker** [comment] 2023-06-23 08:05
I second this, this is still relevant! It's not a bug from a software engineering perspective, but rather a feature implementation that contradicts good pracitice (or a "stats bug"?). I don't know if reclassifying this as a feature request would give it a push, but maybe a comment does a little?

**Comment by tomtomme** [comment] 2024-01-16 20:13
Tested with 0.18.3 - still relevant.

**Comment by tomtomme** [comment] 2024-02-14 18:44
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/1642
Johnny is already working on a fix.
lets discuss there.

**Closed by tomtomme** 2024-02-14 18:44 UTC
Labels: Module: jaspAnova, Feature Request
