### ISSUE TITLE
[Bug]: JASP 'Not responding' 

### ISSUE THREAD

**Issue by themida2000** [jasp-stats/jasp-issues#2730] opened 2024-05-20 16:46 UTC
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Edit data 

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I have quite a big dataset. 52 patients (rows) with around 80 variables each (columns).  I am trying to edit the data but JASP is constantly freezing and 'Not responding'. 
[Dataset ARCTIC.csv](https://github.com/jasp-stats/jasp-issues/files/15379731/Dataset.ARCTIC.csv)
![image](https://github.com/jasp-stats/jasp-issues/assets/170351455/d6a9a02a-373b-4e30-b7a2-6ed8501792ee)

### Expected Behaviour

Be able to edit data without any 'non responding' delays and freezing 

### Steps to Reproduce

1. Open a big data set in JASP 
2. Try any editing (change name, change value) 
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment] 2024-05-21 07:52
I cannot reproduce the behavior on my Windows or linux machine even when restricting it to 4 GB.
Are you sure you systems resources are not used up by other software? JASP will require around 500 MB of RAM to load and edit your dataset (+150 MB per analysis). 
Could you provide the Memory usage per process (the three squares button in the left menu).

**Comment by boutinb** [comment] 2024-05-21 07:52
Hi @themida2000, It is quite strange, because your dataset is not big at all: 48 KB should be really easy to load. Can you load a dataset from the Data Library (Open/Data Library/1-Descriptives/Sleep for example)?

**Comment by themida2000** [comment] 2024-05-21 10:20
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
Here I have included all the processes that consume memory. When I open
JASP, I have only around 500 MB RAM left and when I close it it gets to 2
GB.  Let me know if there is another software that interferes, but I
haven't identified any.


Στις Τρί 21 Μαΐ 2024 στις 9:52 π.μ., ο/η RensDofferhoff <
***@***.***> έγραψε:

**Comment by tomtomme** [comment] 2024-05-21 10:26
Thx. You tried sending images via mail. That sadly does not work. Can you upload them directly on github issue-webpage? thx

**Comment by themida2000** [comment] 2024-05-21 10:32
![image (14)](https://github.com/jasp-stats/jasp-issues/assets/170351455/8c87de62-8771-41a1-8308-0386753f310e)
![image (13)](https://github.com/jasp-stats/jasp-issues/assets/170351455/0be8ae7c-3b3f-426e-b049-39d9e7cfff21)
![image (12)](https://github.com/jasp-stats/jasp-issues/assets/170351455/ccb60604-7560-430d-92d1-92570bbd7465)
![image (11)](https://github.com/jasp-stats/jasp-issues/assets/170351455/77b16e35-e67d-436b-a78e-6d6a6db450ef)
![image (10)](https://github.com/jasp-stats/jasp-issues/assets/170351455/ca324d84-093c-45b7-843d-7c9f76d52c17)
![image (9)](https://github.com/jasp-stats/jasp-issues/assets/170351455/d53b9788-7aec-4962-9b94-8e7a49f82e53)
![image (8)](https://github.com/jasp-stats/jasp-issues/assets/170351455/3128a55e-f145-456a-93b4-66f6ec934d2d)
![image (7)](https://github.com/jasp-stats/jasp-issues/assets/170351455/1f375d9a-1abd-4ce3-90e6-1e6daf68b837)
![image (6)](https://github.com/jasp-stats/jasp-issues/assets/170351455/3318aae0-9c13-4237-bd1e-05d6a5b80118)
![image (5)](https://github.com/jasp-stats/jasp-issues/assets/170351455/03588b5e-a107-4299-a43c-634f4398f1e3)
![image (4)](https://github.com/jasp-stats/jasp-issues/assets/170351455/2e0e7528-c6a7-4fbd-b365-0fab3a0185f1)
![image (3)](https://github.com/jasp-stats/jasp-issues/assets/170351455/0c53a8a7-6772-4e55-a02a-5b907e002603)
![image (2)](https://github.com/jasp-stats/jasp-issues/assets/170351455/2e32942b-8adf-4ef4-b14d-f2c19f796a5f)
![image (1)](https://github.com/jasp-stats/jasp-issues/assets/170351455/0cae34fb-8054-4937-9b15-82f5a2745b63)
![image](https://github.com/jasp-stats/jasp-issues/assets/170351455/14e8de6d-9511-44c8-8127-d741df527374)

**Comment by themida2000** [comment] 2024-05-21 10:33
Better look at the processes from down to up.

**Comment by tomtomme** [comment] 2024-05-21 10:53
mmmh ... McAffee again. That one caused problems in the past. Can you disconect your PC from the internet and den disable McAffee for some minutes to see if that helps? If so, my personal advice would be to uninstall McAffee and use Microsoft Defender, which is included in Win 10 and 11 out of the box and is better in many cases. You just need to activate it after uninstalling McAffee.
Also you could try closing Edge to free up some memory (RAM)

**Comment by RensDofferhoff** [comment] 2024-05-21 10:56
JASP is not using strange amounts of memory but there is very little RAM resources left on your pc.

**Comment by tomtomme** [comment] 2024-05-24 10:55
@themida2000 
Did some of our suggestions help?

**Comment by tomtomme** [comment] 2024-05-24 10:56
You could also try this beta version: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-eaf4ba837e4fa817ec87fd8acd11c52ab0e64739.msi

**Comment by themida2000** [comment] 2024-05-31 11:24
It helped removing the McAfee, because it freed up some memory space. But still for JASP to work without freezing, it needs to be opened with 50% RAM left and it then uses around 1,5- 2GB itself. So now I can use it, but I need to not open any other apps or open any internet windows. 
To free up more space I also fixed memory usage in Microsoft Edge. That helped also. 
- I closed resource- intensive processes, through the task manager 
- Enable edge efficiency mode 
- Check for browser malware 
- Disable browser extensions

**Comment by tomtomme** [comment] 2024-05-31 11:37
Thx for the feedback.
You could also check if background apps like citrix, gamebar, lenovo vantage etc. are really needed always and disable that they autostart.
And you could check if your laptop has a free RAM slot to upgrade its memory capacity. 
Other than that I am afraid that there is not much we can do. Big data sets and its analysis in JASP will always require quite some memory. So I am closing this one for now!

**Closed by tomtomme** 2024-05-31 11:37 UTC
Labels: Waiting for requester, OS: Windows 11
