### ISSUE TITLE
reliability analyses crashing

### ISSUE THREAD

**Issue by alliemariemann** [jasp-stats/jasp-issues#1122] opened 2021-01-09 20:23 UTC
* JASP version: 0.14.1

* OS name and version: Windows 10
* Analysis: Classical Single-Test Reliability Analysis
* Bug description:  This is the error messege: "This analysis terminated unexpectedly. 

Error in `*tmp*`[['freq']]: subscript out of bounds

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistReliabilityMainResults(jaspResults, dataset, options)"
* Expected behaviour: getting results in the output

#### Steps to reproduce:
1. Go to '...' Reliability
2. Click on '....' Classical Single-Test Reliability Analysis
3. Select 9 variables in variables column (data set has 11 cases)

**Comment by boutinb** [comment] 2021-01-11 08:58
Hi @alliemariemann To be able to understand what goes wrong, we need to have a precise reproduction path. The best would be to have your dataset (or your JASP file), and explain us exactly what you did to get the error.

**Comment by lk95wefo** [comment] 2021-01-18 13:10
I use Windows 10, JASP version 0.14.1.0.

The same happens to me, too. I can calculate 5 out of 6 items with Cronbach's alpha (could use other calculation options in that list) but as soon as I put the 6th item to the right side (in the input), the calculation crashes with the same error as described above. If I try it out with another combination out of my 6 items, it works as well with 4 or 5 items before it crashes.

**Comment by JorisGoosen** [comment] 2021-01-18 13:36
@lk95wefo maybe you could upload your datafile?
Or maybe @alliemariemann will respond at some point...

**Comment by lk95wefo** [comment] 2021-01-18 13:44
[JASP_ESM-Datensatz_Befragung_Mittelwerte_Personen.zip](https://github.com/jasp-stats/jasp-issues/files/5830496/JASP_ESM-Datensatz_Befragung_Mittelwerte_Personen.zip)

**Comment by JorisGoosen** [comment] 2021-01-18 14:41
Thank you!

**Comment by JorisGoosen** [comment] 2021-01-18 14:45
I can confirm the crash, @juliuspf can you have a look at this?
And if it isn't too large a fix we should also fix it in `stable` so we can release it a bit quicker with 0.14.2.

**Comment by juliuspf** [comment] 2021-01-18 16:26
@lk95wefo thanks for sharing the data. I can track the error to the associated R-package, which has some issues with covariance matrices that are not invertible. This happens probably because with small sample size, the bootstrap produces weirder data. A quick fix for your data would be to delete the empty row, because JASP interprets that as missing data (I suppose that is not your intention). Then the analysis should work fine. Let me know if that helps

**Comment by arturojuarezg** [comment] 2021-02-28 03:25
Hi everyone, I am a simple user and zero knowledge in programming. I got the same message "This analysis terminated unexpectedly. Error in *tmp*[['freq']]: subscript out of bounds" when calculating alpha. Is there yet any solution without the necessity of programming?

**Comment by juliuspf** [comment] 2021-03-01 09:26
Dear @arturojuarezg, can you provide a Jasp-file for your problem? The bug in the analysis will be fixed in the next release, and probably even sooner in one of the nightlies (development JASP versions). Cheers, Julius

**Closed** 2021-04-30 09:58 UTC
