### ISSUE TITLE
Question: why is my factor loading estimate abnormally high? where is the factor loading sorting function?

### ISSUE THREAD

**Issue by amandazhang0727** [jasp-stats/jasp-issues#1568] opened 2022-01-10 06:36 UTC
### JASP Version

0.16

### Commit ID

/

### JASP Module

jaspFactor

### What analysis are you seeing the problem on?

Confirmatory Factor Analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Sorry, I don't whether this is a bug or not. But I know JASP 0.15 has the function of sorting factor loading. 
I am doing a CFA analysis, and all the model fit indices suggest that my model was not a good fit. I observed the data and found the factor loading estimates were abnormally high (I think it's normally lower than 1, mine is above 20!).
Would you help me look at what's wrong with my data file?

### Expected Behaviour

/

### Steps to Reproduce

Please see the attached data file:
[DataForAnalysis.CSV](https://github.com/jasp-stats/jasp-issues/files/7837121/DataForAnalysis.CSV)

1. Create a confirmatory factor analysis
2. 
![jasp](https://user-images.githubusercontent.com/74722386/148726264-3c465f9c-5f7c-474d-b7b9-df2d68ec6791.PNG)

### Log (if any)

```bash
See the attached picture in the above box.
```

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-01-14 09:11
Hi @amandazhang0727 , thank you for making the issue. I think this would be rather a question for the forum (https://forum.cogsci.nl/categories/jasp-bayesfactor) since it is not a bug but an analysis question. In short, the loadings can be seen as regression coefficients where the manifest variables are explained by the factors. In the unstandardized case and having the factor variance be 1, this means that the loading adopts the same scale as the manifest variable it points to. And I assume your the scale of your variables fits those loadings. If you go to "Advanced > Standardization > All" you will obtain also standardized loadings in your table.

**Comment by juliuspf** [comment] 2022-01-24 09:24
I am going to close this. If you think your question has not been answered, feel free to open it again :)

**Closed by juliuspf** 2022-01-24 09:24 UTC
Labels: waiting for requester, Module: jaspFactor
