### ISSUE TITLE
[Feature request]: Bayesian logistic regression.

### ISSUE THREAD

**Issue by janderuiter** [jasp-stats/jasp-issues#108] opened 2017-11-06 18:59 UTC
Could we have a Bayesian version of logistic regression as well? That would be SO cool! Thanks in advance for considering. 

JP

**Comment by TESmith868** [comment] 2018-11-14 09:59
Hi, any updates on implementations if Logistic Regression in JASP?

May or may not be the right place to ask. But new to Bayesian. Is their an alternative Bayesian method in JASP for risk modeling of the dependent variable is dichotomous with several covariates?

**Comment by dloschelder** [comment] 2022-05-16 16:25
I second this request. Would be a wonderful addition to JASP. Any ideas, when this could possibly be implemented? Thank you all for your terrific work.

**Comment by boutinb** [comment] 2023-01-27 16:41
@fqixiang Are you planning to do this?

**Comment by fqixiang** [comment] 2023-01-30 11:41
sorry, i couldn't finish this. i just removed it from the 0.17 release.

**Comment by janderuiter** [comment] 2023-01-30 11:52
Is it then "completed"? Should I enter a new request?

**Comment by fqixiang** [comment] 2023-01-30 11:59
@janderuiter you're right - i shouldn't have closed it. i'm still working on it and it should become available probably in the next release.

**Comment by janderuiter** [comment] 2023-01-30 12:39
Thanks! It would be a really cool feature that would make it a lot easier
to convince people to use JASP (at least where I work)!

JP

**Comment by tomtomme** [comment] 2023-12-22 21:54
this is finished since 0.17.2.
issue can be closed

**Closed** 2024-01-03 10:25 UTC
Labels: Module: jaspRegression, Feature Request
