### ISSUE TITLE
[Feature Request]: 95% confidence interval for standardized values 

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#2001] opened 2023-02-08 14:43 UTC
### Description

 standardized 95% CI values

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

SEM

### Describe the solution you would like

adding a new, or even replacing the old, option

### Describe alternatives that you have considered

Add standardized 95% CI values or make them the default.

### Additional context

Thank you for the continued improvement of the CFA and SEM modules.

I notice that all 95% confidence intervals (CI) in the modules are all for the "unstandardized" coefficients. Typically, in SEM (including CFA and ESEM) we are more concerned with the standardized values and only report them. So, it will be much appreciated if standardized 95% CI values are added to the tables. Indeed, I recommend that this be the default option rather than the unstandardized one.
In lavaan, we get the 95% CI by requesting the following code: standardizedsolution(out, level=.95)

Thanks

**Comment by juliuspfadt** [comment] 2023-02-08 15:00
this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1102

**Closed by juliuspfadt** 2023-02-08 15:00 UTC
Labels: Module: jaspSem, Feature Request

**Comment by areeq1** [comment] 2023-02-08 15:06
Thanks, @juliuspfadt for referring to that article. However, it is still not resolved. Hope that team adds this function, It is quite easy.
