### ISSUE TITLE
[Feature Request]: Ability to set specific dimensions on plots

### ISSUE THREAD

**Issue by scottastone** [jasp-stats/jasp-issues#1674] opened 2022-03-29 21:36 UTC
### Description

Ability to set specific dimensions on plots

### Purpose

Set size of the plots for export and further editing in vector editing programs like Illustrator

### Use-case

Exporting multiple plots that are supposed to be the same size

### Describe the solution you would like

In Edit Image, you should be able to set the size of the bounds (or match to another plot in the same analysis).

### Describe alternatives that you have considered

Resizing manually by dragging from the corner

### Additional context

I'm exporting some figures from JASP and cannot find an obvious way to ensure all of my plots are the same size. I can manually drag them, but then I have to do it by eye, which makes the plots off by a few pixels in one of the dimensions. The ability to set both plots to be the same size (or at least see how big they are) would make this infinitely easier when I post-edit them in Illustrator.

**Comment by scottastone** [comment] 2022-03-30 17:23
Just to add, if it was possible to get out the R command used to generate the plot, that would be immensely helpful. Is there a hacky was to do this currently?

Recreating the plots is more difficult because I would have to manually calculate the standard error / 95%ile.

**Comment by vandenman** [comment] 2022-04-01 10:52
There is no straightforward way to get the R command used to generate the plot (it's possible but it's not easy). However, you can access the plot objects saved in the state the following hacky way:

- unzip the .jasp file, let's assume it's now called "unzipped_jasp" 
- in R, do `load("unzipped_jasp/resources/0/state")`. Here 0 is an analysis number, if there are multiple analyses then these all have their own state. So you may need to adjust `0` to something else. There are png files in each folder which should help you find the plot of interest.
- after `load` there is now an object called `state`. You can access the plot objects in there via ``state$figures$`resources/0/_0_t1646864985384.png`$obj`` Here `resources/0/_0_t1646864985384.png` is actually the name of the png file that you want to save differently.
- Once you've found the plot you're interested in, you can resave it in the usual way:
```r
pdf(file, width, height)
print(plot) # assuming the plot object is a ggplot object
dev.off()
```

I hope that helps!

**Comment by tomtomme** [comment] 2023-12-20 15:13
@scottastone 
We have R-Syntax-Mode since March. Does this suffice for your needs?

**Comment by tomtomme** [comment] 2024-01-19 21:54
I just saw an even older issue thats a duplicate of this one here: https://github.com/jasp-stats/jasp-issues/issues/1444
So we will track this feature there.

**Closed by tomtomme** 2024-01-19 21:54 UTC
Labels: Feature Request, Plot Editing
