### ISSUE TITLE
[Feature Request]: To be able to add 95% CI to QQ-plots

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1763] opened 2022-06-27 13:34 UTC
### Description

 To add 95% CI to QQ-plots (in Descriptive, ANOVA  and Regression) 

### Purpose

I think it could be very useful to have the option to add (by clicking) a 95% confidence interval for QQ-plots in in the descriptive- , ANOVA-   and Regression module). 

### Is your feature request related to a problem?

No but an enhancement!

### Describe the solution you would like

This i possible in R: https://www.tutorialspoint.com/how-to-create-a-qqplot-with-confidence-interval-in-r

**Comment by tomtomme** [comment] 2024-02-08 07:33
Taran mentioned in the duplicate: 

> Relatedly, this also seems useful:
> 
> Weine, E., McPeek, M. S., & Abney, M. (2023). Application of Equal Local Levels to Improve Q-Q Plot Testing Bands with R Package qqconf. Journal of Statistical Software, 106, 1–31. https://doi.org/10.18637/jss.v106.i10

**Comment by tomtomme** [comment] 2024-02-08 16:20
Closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/490

**Closed by tomtomme** 2024-02-08 16:20 UTC
Labels: Graphs/Plots, Module: jaspDescriptives, Module: jaspRegression, Module: jaspAnova, Feature Request
