### ISSUE TITLE
[Feature Request]: Splitting an analysis by categorical variable

### ISSUE THREAD

**Issue by KyleSBeyer** [jasp-stats/jasp-issues#2126] opened 2023-05-08 14:54 UTC
### Description

I would like the ability to have an analysis run, but split by a categorical variable (ie: gender). So for example, when running an ANOVA, splitting the file by gender so that we get results for men and women separately. I know we can filter by the categorical variable, but that will only provide the data for those not filtered out, and the results go away once the filter is removed.

### Use-case

Running any analysis with results for each level of a categorical variable displayed separately.

### Describe alternatives that you have considered

Filtering will run the analysis for each level of a categorical variable, but the results do not exist once the data is unfiltered.

**Comment by tomtomme** [comment] 2024-02-01 22:23
Closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/1379

**Closed by tomtomme** 2024-02-01 22:23 UTC
Labels: Feature Request
