### ISSUE TITLE
[Bug]: Flexplot with categorial variables shows absolute Differences now

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2423] opened 2023-11-21 10:17 UTC
### JASP Version

according to @m1ke95 since 0.17 and still valid for 0.19 beta

### What analysis are you seeing the problem on?

Flexplot

### Bug Description

Former versions of JASPs Flexplot showed this:
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/ff747908-8ee7-4db4-82e1-64c5cc06f038)

Current versions of JASPs Flexplot show this:

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/744b7005-bd8e-487c-b8c3-97561788c62b)

I argue, that the new graph is way less informative - I will explain below. Thus I consider this a lost feature or a bug.
Both graphs visualize this crosstab:
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/8e8c8b9c-f636-4cf8-bd37-3f1e40e41104)

The lower/newer plot just shows the difference between empirical absolute counts and expected absolute counts.
The upper/older plot showed the relative difference between the two. For example: In the second cell of the table we have "count = 16" and "expected count = 24". The difference of 8 corresponds to 33% less empirically counted than expected if both variables are independent. This is what flexplot shows in earlier versions: A bar at -33% aka -0.33.
And this is way more informative than absolute differences, which tell you nothing about which cells contribute the most to Chi² and Cramers V.

### Expected Behaviour

JASPs Flexplot should revert to the old visualisation-logic for categorial variables.

### Steps to Reproduce

1. produce a flexplot with an old JASP version (maybe 0.17.1 maybe older)
2. produce a flexplot with a newer JASP version
3. compare

**Comment by tomtomme** [comment] 2023-12-13 19:40
@shun2wang - can you assign someone to this request?

**Comment by shun2wang** [comment] 2023-12-14 08:48
@dustinfife Could you please have a look?🍻

**Comment by dustinfife** [comment] 2023-12-15 04:22
That's odd. I don't remember intentionally changing anything. What version was the original plot from?

**Comment by tomtomme** [comment] 2023-12-17 12:01
I will try to find out. From my rough memory the change might have accured around a year ago. I never came around reporting it until now. But I will install older versions to find out, exactly when. Next week I have some spare time.

**Comment by boutinb** [comment] 2024-01-11 09:39
Maybe this work on 0.18.3?

**Comment by tomtomme** [comment] 2024-01-11 10:18
Sadly not. It still does just show the difference between empirical absolute counts and expected absolute counts. Before it showed the much more informative _relative_ difference between the two.

**Comment by tomtomme** [comment] 2024-01-11 10:20
Since I have no flatpak-version archive I cannot bisect the version, the change occured. I tried the windows-versions, but most of them do not run under wine. I have windows machines at work that I tried, but those are very slow machines. I do not know when I will find time to work with those.

**Comment by tomtomme** [comment] 2024-04-16 06:12
Thanks @m1ke95 for finding the last version it worked!! Very nice work!

**Comment by m1ke95** [comment] 2024-04-16 07:25
Short followup since I took a larger step from 0.17.1 to 0.16.0 when searching for a version that works after having no luck with all the .18 and .17 versions. 
The feature **still works as intended in 0.16.4** and **stops working in 0.17.0 (rar version).**
The 0.17.0 .msi installer is blocked by windows for "security reasons" so I tried the preinstalled rar-version. 
In .msi-installed jasp the bug occurs, as OP estimated in 0.17.1.

**Comment by boutinb** [comment] 2024-04-16 09:01
@dustinfife We are planning to release a new version soon, with the flexplot analysis in the Descriptives module. So it would be nice to solve this issue this week.

**Comment by dustinfife** [comment] 2024-04-30 23:03
Sorry, it's been very busy. I'm looking at this now.

**Comment by dustinfife** [comment] 2024-05-01 00:53
This is fixed with [the most recent commit.](https://github.com/dustinfife/flexplot/commit/db91cac72c70f8fa3fbd8c8ce2f577e73208dd3c)

**Comment by boutinb** [comment] 2024-05-02 07:35
This should be automatically fixed with the next nightly.

**Comment by boutinb** [comment] 2024-05-15 08:47
@dustinfife If I had a look at the results with the same data with different JASP versions (and different flexplot versions), and here is what I get
. in JASP 0.16.3 (flexplot Version: 0.13.3):
<img width="1296" alt="Screenshot 2024-05-15 at 10 38 38" src="https://github.com/jasp-stats/jasp-issues/assets/503332/64526fb8-6fb5-428f-8a95-904bb0c3c825">
. in JASP 0.18.3 (flexplot Version: 0.20.3):
<img width="1319" alt="Screenshot 2024-05-15 at 10 40 30" src="https://github.com/jasp-stats/jasp-issues/assets/503332/950542ed-86a4-48b9-b861-1cf0493c5dc8">
. in JASP 0.19.0 Beta (flexplot Version: 0.20.7)
<img width="1318" alt="Screenshot 2024-05-15 at 10 42 00" src="https://github.com/jasp-stats/jasp-issues/assets/503332/52c78931-8bf4-447a-950d-3e2ae1b0274f">

I use the Dancing Cats data file:
[Dancing Cats.csv](https://github.com/jasp-stats/jasp-issues/files/15318829/Dancing.Cats.csv)

**Closed** 2024-05-15 14:32 UTC
Labels: Module: jaspVisualModeling, Bug: Critical

**Comment by tomtomme** [comment] 2024-05-23 11:33
@boutinb 
This location does not exist on my manjaro machine. What comes close is:

- /var/lib/flatpak/app/org.jaspstats.JASP/current/active/files/Modules/jaspVisualModeling/jaspVisualModeling/
- /var/lib/flatpak/app/org.jaspstats.JASP/x86_64/stable/active/files/Modules/jaspVisualModeling/jaspVisualModeling/
- /var/lib/flatpak/app/org.jaspstats.JASP/x86_64/beta/active/files/Modules/jaspVisualModeling/jaspVisualModeling/

the DESCRIPTION files there are all missing a flexplot version info

**stable**
> Package: jaspVisualModeling
> Type: Package
> Title: Visual Modeling Module for JASP
> Version: 0.18.3
> Date: 2022-10-05
> Author: Dustin Fife
> Website: github.com/dustinfife/flexplot
> Maintainer: Dustin Fife <fife.dustin@gmail.com>
> Description: Graphically explore the dependencies between variables
> License: GPL (>= 2)
> Imports: flexplot, jaspBase, jaspGraphs
> Remotes: dustinfife/flexplot, jasp-stats/jaspGraphs,
>         jasp-stats/jaspBase
> Built: R 4.3.2; ; 2024-01-11 19:07:03 UTC; unix

**beta**
> Package: jaspVisualModeling
> Type: Package
> Title: Visual Modeling Module for JASP
> Version: 0.19.0
> Date: 2022-10-05
> Author: Dustin Fife
> Website: github.com/dustinfife/flexplot
> Maintainer: Dustin Fife <fife.dustin@gmail.com>
> Description: Graphically explore the dependencies between variables
> License: GPL (>= 2)
> Imports: flexplot, jaspBase, jaspGraphs, jaspDescriptives
> Remotes: dustinfife/flexplot, jasp-stats/jaspGraphs,
>         jasp-stats/jaspBase, jasp-stats/jaspDescriptives
> Built: R 4.4.0; ; 2024-05-18 15:39:32 UTC; unix
>

**Comment by boutinb** [comment] 2024-05-23 13:24
@tomtomme You are looking at the jaspVisualModeling package. I have no linux machine, but on Mac or Windows, the flexplot package should be just beside, in Modules/jaspVisualModeling/flexplot: this is soft link to the renv cache.

**Comment by shun2wang** [comment] 2024-05-23 13:34
Hi @tomtomme what you referred is `jaspVisualModeling` packages which is wrapped modules in JASP. so if you look at `flexplot` path such like: `Modules/renv-cahe/v5/flexplot/...` then the flexplot version is `0.20.8` so this was fixed already.

thanks.

**Comment by tomtomme** [comment] 2024-05-23 18:03
got it! Thx!

`/app/lib64/renv-cache/v5//flexplot/0.20.3/`
