### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#2393] opened 2023-11-08 08:16 UTC
### Description

Include MLR estimator in the CFA and SEM

### Purpose

MLR estimator is an alternative to ML estimator that assumes the normality of the data

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

SEM

**Comment by juliuspfadt** [comment] 2023-11-08 11:56
thanks for the request @areeq1 . Additional SEM estimators will be fixed with this PR https://github.com/jasp-stats/jaspSem/pull/122. At the moment you can get the MLR estimator by choosing robust standard errors and the Yuan Bentler under "model test". For the CFA your request is still relevant although a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2162, so I am going to go ahead and close this.

**Closed by juliuspfadt** 2023-11-08 11:56 UTC
Labels: Module: jaspSem, Feature Request

**Comment by areeq1** [comment] 2023-11-08 13:20
Hi @juliuspfadt ,

It would be OK if using Yuan Bentler under "model test" could do anything! From my experiment. All options do not change anything in the chi-squared or other fits. Only error calculation options (selecting Robust) can change the model parameters. Can you please fix it for now?

Thanks

**Comment by juliuspfadt** [comment] 2023-11-08 13:42
I think that issue will also be fixed by the mentioned PR. thanks for checking, though :)

**Comment by areeq1** [comment] 2023-11-08 13:57
What does PR refer to?

**Comment by juliuspfadt** [comment] 2023-11-08 16:27
I am sorry, PR is pull-request, aka a proposed change in the code.

**Comment by juliuspfadt** [comment] 2023-11-09 08:53
actually this was already fixed by the code I changed at the end of September: https://github.com/jasp-stats/jaspSem/pull/182. Unfortunately that did not make it into the release. You could download one of the latest nightly versions https://static.jasp-stats.org/Nightlies/ and check it out.

**Comment by areeq1** [comment] 2023-11-09 23:01
I downloaded the latest version the 9 Nov version but has the same issue. Using different model test does not change any thing

**Comment by juliuspfadt** [comment] 2023-11-10 10:03
I apologize, you are correct. The change I made there was not sufficient. I have tried this with the code change I linked above https://github.com/jasp-stats/jaspSem/pull/122, and there the issue is fixed. Unfortunately, this is a somewhat bigger change, and we may not manage to get it into the next release. I appreciate your input though, thanks :)
