### ISSUE TITLE
[Feature Request]: Homogeneity of variances: Levene's test for medians and trimmed means

### ISSUE THREAD

**Issue by EmeraldBarin** [jasp-stats/jasp-issues#2326] opened 2023-10-05 09:34 UTC
### Description

Please add Levene's test for medians and trimmed means in the ANOVA module

### Purpose

Expand the library of statistical tools in Jasp

### Is your feature request related to a problem?

Only one test for homogeneity of variances is not suitable for all purposes

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

All three versions of Levene's test (means, medians and trimmed means) in the ANOVA module, section "Assumptions check", checkbox "Homogeneity tests". Output: three p-values to choose from instead of just one.

### Describe alternatives that you have considered

Use other statistical software to run the test

### Additional context

The only homogeneity test currently used in Jasp in the ANOVA module is the Levene's homogeneity test based on means. However, in some cases, Levene's test based on medians or trimmed means works better, as all three options have different robustness and power. More theory on this statistical test can be found here in the textbook: https://www.itl.nist.gov/div898/handbook/eda/section3/eda35a.htm or elsewhere.
Several statistical programs, like PAST or Minitab, offer those tests as well. Please, add them in Jasp too)

**Comment by TarandeepKang** [comment] 2023-10-05 10:00
Available here with references: https://search.r-project.org/CRAN/refmans/lawstat/html/levene.test.html

**Comment by tomtomme** [comment] 2024-02-09 10:51
This is now a duplicate of https://github.com/jasp-stats/jasp-issues/issues/490
I am gathering all issues about missing assumption tests there.

**Closed by tomtomme** 2024-02-09 10:51 UTC
Labels: Module: jaspAnova, Feature Request
