### ISSUE TITLE
[Bug]: You create a block regression, save it, load it, the blocks disappear

### ISSUE THREAD

**Issue by bmatyasb** [jasp-stats/jasp-issues#3068] opened 2024-12-08 11:52 UTC
### JASP Version

0.19.1

### JASP Module

Other

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I created a logistic regression with a hierarchical, block layout. There were 4 blocks, each block with different variables entered one after the other - as they should be. 
I was pleased with how nicely I had worked it out. I saved the JASP file, then opened it again the next day. The blocks remained, but JASP rerun the whole analysis, putting all the variables into each block, and I could start all over again. I think this is a pretty big problem.

### Expected Behaviour

JASP should "remember" which block which variables are in which block, and re-run the analysis that way. or not re-run it at all.

### Steps to Reproduce

just do a block regression with the simplest data series. 
block 1 should have one variable, block 2 should have two variables. save it, open it, and you will see that both blocks will have 2 variables.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-12-08 15:52
@bmatyasb 
thx for the report. I can confirm the behaviour for 0.19.1. 
Thankfully this has been fixed already within 0.19.2 beta.
You can check via our (probably unstable) nightlies: https://static.jasp-stats.org/Nightlies
Thus I am closing the issue for now. Please reopen, if this is not fixed on your end since I am not testing on windows and sometimes issues are OS specific.

**Closed by tomtomme** 2024-12-08 15:52 UTC
Labels: Waiting for requester, OS: Windows 11, Bug

**Comment by bmatyasb** [comment] 2024-12-08 16:45
thanks a lot! everything is fine now! I'm glad I got a sneak preview of
19.2... :D I really hope you finally implement something like rain cloud
plots for scatter plots ... or implement specific scale sizes for each
figure type for easier publication.

**Comment by tomtomme** [comment] 2024-12-08 18:13
@bmatyasb 
specific scale sizes? Could you elaborate possibly best in a separate feature request?
And with raincloud-plots for scatterplots you are thinking of a replacement for the histograms or density plots that surround scatterplots currently? Would also be cool for a feature request I think. But may take some time with all the other requests we have.

**Comment by bmatyasb** [comment] 2024-12-08 18:55
Sorry if I wrote in a confusing way. I meant that with each plot, you could
click on "edit plot" to set a specific height and width. But I've written
about this many, many times on github, so I hope it will be implemented one
day, so that we can specify the size of the plots with numbers, and not
just for the raincloud plot. :) but I have many other ideas, e.g. to be
able to save the Cook distances (like residuals) in the data for regression
analysis. Obviously this would make it quite easier to remove
multidimensional outliers in large data sets. I will compile these ideas in
the coming days and request them on github.

Thomas Langkamp ***@***.***> ezt írta (időpont: 2024. dec.
8., V 19:14):
