### ISSUE TITLE
separate filter per analysis

### ISSUE THREAD

**Issue by gkfb** [jasp-stats/jasp-issues#385] opened 2019-06-13 11:38 UTC
First of all, thank you very much for this great tool and the constant improvements. We have implemented JASP as primary source for teaching undergraduate courses. We encountered one issue about filters applying globally to all analyses. 

 
* Enhancement: implement a filter option that only applies to one specific analysis step
* Purpose: retain functionality of and avoid errors in previous analyses
* Use-case: for example, conducting a t-test with subsample, and a subsequent analysis with full sample

**Is your feature request related to a problem? Please describe.**
 
E.g. a t-test requires exactly 2 factor levels. If I want to compare two levels of a three-level factor (e.g. I have "other" as third gender and want to compare male vs. female), I deselect "other".
![with_filter](https://user-images.githubusercontent.com/51785159/59429124-5ed8ca00-8ddf-11e9-9a22-591114e6bca4.JPG)

In the next analysis step, I want to use the full sample, i.e. include "other". This leads to the problem that the t-test calculated before above returns an error. 
![without_filter](https://user-images.githubusercontent.com/51785159/59429131-6304e780-8ddf-11e9-87b5-4aea8323e28e.JPG)

**Describe the solution you'd like**
 
It would be great if it is possible to choose if a filter applies globally to all analyses, or if it should only apply to a specific analysis step (e.g. the mentioned t-test, but also many other scenarios). 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by JorisGoosen** [comment] 2019-06-14 13:10
This could be combined with https://github.com/jasp-stats/jasp-issues/issues/333

Perhaps one could specify multiple filters (tabbed or otherwise) and then add an option to the analysis-options where you could select the filter to use. And then if nothing is selected just use the "default" filter, which you could specify in the filters themselves somehow.

**Comment by ajestudillo** [comment] 2019-07-24 02:36
I would love to see a feature like that implemented.

**Comment by juliusverrel** [comment] 2020-11-18 12:37
this would be extremely helpful, helping to avoid having a separate file for each sub-analysis (as described above by @gkfb )

**Comment by juliusverrel** [comment] 2021-11-30 09:21
Any chance you might implement this in the near future? Implementing parallel filters with full functionality might be difficult. A more feasible solution might be to allow only (analysis-specific) filters defined by one column: i.e., per analysis select a column name and allowed values. Or, even simpler: implement it only for binary columns which can be selected as a filter (1=include, 0=exclude).

As stated by several users here and in [#333](https://github.com/jasp-stats/jasp-issues/issues/333), this would be an extremely helpful addition to this great tool.

**Comment by JorisGoosen** [comment] 2021-11-30 10:01
This is not on the roster at the moment but a big rewrite for the data-backend of JASP is upcoming and that will make adding separate filters feasible, so hopefully in the coming year!

**Comment by iandol** [comment] 2022-07-18 20:00
This really would be a wonderful ability to improve analysis flexibility. Thank you for all your hard work on making such a great and useful package!

**Comment by Andre3582** [comment] 2022-07-29 11:51
Yes! I just want to state that this function would be really nice to have! Keep up the great work JASP team!

**Comment by juliuspfadt** [comment] 2023-03-03 10:27
Let's all track this here: https://github.com/jasp-stats/jasp-issues/issues/1330

**Comment by tomtomme** [comment] 2023-12-25 17:19
can be closed, since duplicate of 
https://github.com/jasp-stats/jasp-issues/issues/333
https://github.com/jasp-stats/jasp-issues/issues/635
https://github.com/jasp-stats/jasp-issues/issues/1330

**Closed** 2023-12-25 20:24 UTC
Labels: Feature Request
