### ISSUE TITLE
Bayesian Linear regression Bug

### ISSUE THREAD

**Issue by Kev025** [jasp-stats/jasp-issues#677] opened 2020-04-14 19:30 UTC
* JASP version: 0.12

* OS name and version: MacOS Mojave 10.14.6 
* Analysis: Bayesian Linear Regression
* Bug description: An error message is displayed when I compute Bayesian Linear Regression
* Expected behaviour: Corrected it if possible

#### Steps to reproduce:
1. Go to 'Regression/Bayesian Linear Regression'
2. Click on 'Variables and Covariates '

[Bug report.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4477329/Bug.report.jasp.zip)

**Comment by vandenman** [comment] 2020-04-15 06:55
Additional information from #676:

Hi, I'm conduction bayesian linear regression with new JASP version. But there is the error message
![Capture d’écran 2020-04-14 à 20 06 55](https://user-images.githubusercontent.com/62613088/79258550-985ce480-7e8b-11ea-9608-6e74d244cfc3.png)

**Comment by vandenman** [comment] 2020-04-15 06:57
@JorisGoosen I think you know most about this error.

**Comment by FransMeerhoff** [comment] 2020-04-15 08:02
HI @JorisGoosen 
I tried this on the latest development version (which is still equal to the stable branch) and it seems OK there? I look further.

**Comment by JorisGoosen** [comment] 2020-04-15 08:38
@FransMeerhoff can you check it out with the released installer?
Because in the error it seems like `libgfortran.3.dylib` is not signed somehow?
Which seems unlikely as Im signing basically everything...

**Comment by boutinb** [comment] 2020-04-15 08:40
I have tried on my machine (High Sierra), and it works without problem.
But the error message says that it looks for the libgfortran.3.dylib in the root library and not in the JASP R framework. This link is not ok.

**Comment by FransMeerhoff** [comment] 2020-04-15 08:43
Hi @JorisGoosen 
Yes I tested it with the released installer too, and I then can reproduce it.

**Comment by JorisGoosen** [comment] 2020-04-15 08:44
Ok, so the link in libgfortran.3.dylib needs to be fixed, @FransMeerhoff can you do this?

**Comment by AlexanderLyNL** [comment] 2020-04-15 08:45
The problem doesn't occur on High Sierra. Is someone on who can check whether this occurs on Catalina?

**Comment by JorisGoosen** [comment] 2020-04-15 08:52
Frans is on Catalina, but there is just a small error in the dylib. I will fix it.

**Comment by JorisGoosen** [comment] 2020-04-15 09:07
This should fix it

**Comment by boutinb** [comment] 2020-04-15 09:12
This is I think worth a hotfix release.

**Comment by JorisGoosen** [comment] 2020-04-15 09:38
Yes for sure, I already built a new version, I can sign it and upload it?

**Comment by boutinb** [comment] 2020-04-15 09:52
Yes, and @Kev025 can test it.

**Comment by JorisGoosen** [comment] 2020-04-15 13:47
@Kev025 can you test https://static.jasp-stats.org/JASP-0.12.1.0.dmg ?
It should fix the problem.

**Comment by AlexanderLyNL** [comment] 2020-04-15 14:05
@Kucharssim Do you know who's in charge of a Bayesian linear regression example file? This can then be added to our automated check.

**Comment by Kucharssim** [comment] 2020-04-15 14:27
> @Kucharssim Do you know who's in charge of a Bayesian linear regression example file? This can then be added to our automated check.

That would be me, but I am not sure whether I follow your idea of how to add this to our automated checks.

**Comment by AlexanderLyNL** [comment] 2020-04-15 14:30
The data library is used for automatic testing, and it should have caught this bug. (That's correct isn't it @FransMeerhoff?) This raises my suspicion that there isn't a good Bayesian linear regression example in the data library. Hence, all you need to do is add a Bayesian linear regression example, then the testing is handled by the system itself.

**Comment by JorisGoosen** [comment] 2020-04-15 14:33
Yes @boutinb did that before release.

@Kucharssim just add a nice example JASP file to the regression part of the data library, then next time we catch.

But, only if we run the automatic tests on a Mac...

**Comment by Kev025** [comment] 2020-04-15 14:50
@JorisGoosen I'm testing and that's work !!! 

Thank you very much to have solve this problem. It is a pleasure to use JASP !

**Comment by JorisGoosen** [comment] 2020-04-15 14:51
Great, we will release a version with this fix (and another little one) later today or tomorrow. 
You can keep using this one if you'd like, the other little fix isn't in there but will only affect you if you switch languages.

**Comment by Kucharssim** [comment] 2020-04-15 15:18
> The data library is used for automatic testing, and it should have caught this bug. (That's correct isn't it @FransMeerhoff?) This raises my suspicion that there isn't a good Bayesian linear regression example in the data library. Hence, all you need to do is add a Bayesian linear regression example, then the testing is handled by the system itself.

I understand that, but we have a Bayesian linear regression example in the Data Library. I am not able to reproduce the bug, so I don’t know how to create an example file that would “catch it”, since I don’t know what I should be aiming at. I can of course create a bunch of examples randomly and hope that it covers this bug, but I am not sure whether this is the best approach.

**Comment by AlexanderLyNL** [comment] 2020-04-15 15:22
No need to reopen. I thought that we didn't have a Bayesian linear regression example, but it seems that we do. You don't have to do anything.

**Closed by AlexanderLyNL** 2020-04-15 15:22 UTC

**Comment by boutinb** [comment] 2020-04-15 15:52
I have tested the JASP Data Library, and per chance/malchance it worked on my machine because the reference of the BAS.so library pointed to a fortran library I have in my own R framework.
