### ISSUE TITLE
Add predicted values to data

### ISSUE THREAD

**Issue by hcommenges** [jasp-stats/jasp-issues#1191] opened 2021-03-03 06:21 UTC
* Enhancement: add predicted values to data
* Purpose: for Hierarchical Clustering it is possible to add predicted clusters to data, it would be useful to add this feature to other modules
* Use-case: in my case (spatial statistics) I often have to work with predicted values and sometimes draw a map of it. It is very useful in two main cases: 1/ analyze and map residuals from linear regression (to check spatial autocorrelation for example); 2/ analyze and map individuals' coordinates from PCA analysis

**Describe the solution you'd like**
Add a button just like the existing one for Hierarchical clustering

**Comment by boutinb** [comment] 2021-03-03 08:51
@koenderks Can you answer this request?

**Comment by koenderks** [comment] 2021-03-03 08:54
This should be possible. Probably some work for the maintainer of the regression module.

**Comment by vandenman** [comment] 2021-03-03 08:58
Hi @hcommenges, is this specifically about factor scores of EFA and PCA? For the machine learning analyses, it is already possible to export the predicted values.

**Comment by hcommenges** [comment] 2021-03-03 20:14
Hi, for my research and classes (but I think the need is common among geographers) it is very common to plot and map residuals from linear models, clusters from clustering methods and coordinates from PCA. Regarding hierarchical clustering I noticed that JASP already offers the option to export the clusters, but I think it would be useful to extend this possibility.

Few years ago I developed a shiny app for my students, waiting for something like your software. Here is the link to the code (https://gitlab.huma-num.fr/hcommenges/ExploratR) and the link to the app (https://analytics.huma-num.fr/geographie-cites/ExploratR/). 

For linear regression I export the $residuals from the lm object
For PCA I export the $li from the dudi object - function ade4::dudi.pca(). In my partial experience keeping 3 or 4 components is always sufficient.

I hope you'll find interest (and time) to answer this request.
Thanks!
Hadrien

**Comment by boutinb** [comment] 2021-03-04 09:21
Hi @hcommenges We may implement your suggestions, but as you have apparently already programming experience in R, and that we have made JASP modulaire so that it makes much easier for external people to contribute to JASP, would you be interested to implement self this feature? If yes, we can have a zoom session.

**Comment by hcommenges** [comment] 2021-03-04 09:46
Ok I'm interested. I'm available tomorrow morning, monday 8th morning, tuesday 9th morning, thursday 11th. Would on of these dates be convenient for you?

**Comment by boutinb** [comment] 2021-03-04 12:34
I prefer to continue via email to make an appointment. Did you receive it?

**Comment by hcommenges** [comment] 2021-03-04 20:14
Yes I received your mail at hadrien.commenges@univ-paris1.fr, I'm waiting for your zoom link for tomorrow.

**Comment by juliuspf** [comment] 2022-11-17 08:04
So how are we doing on this issue @boutinb, @hcommenges ?

**Comment by tomtomme** [comment] 2024-01-15 14:03
@hcommenges 
Saving factor scores is also tracked here
https://github.com/jasp-stats/jasp-issues/issues/101
https://github.com/jasp-stats/jasp-issues/issues/1319

So I am closing this one. If I misunderstood something, feel free to reopen.

**Closed by tomtomme** 2024-01-15 14:03 UTC
Labels: Module: jaspRegression, Feature Request

**Comment by pwg312** [comment] 2024-01-25 18:17
question on original request to add predicted values to data--is it possible to save predicted values and residuals to the data file in Linear Regressions (similar to SPSS)?

**Comment by tomtomme** [comment] 2024-01-26 20:42
This is in the works more broadly, since also needed for pca etc. For progress see the linked issues
