### ISSUE TITLE
Flatpak build file is missing jasp-stats/jasp-desktop git commit hash

### ISSUE THREAD

**Issue by markovendelin** [jasp-stats/jasp-issues#285] opened 2019-01-07 17:36 UTC
As currently provided, JASP section in https://github.com/jasp-stats/jasp-desktop/blob/development/Tools/flatpak/org.jasp.JASP.json doesn't provide current commit id after 
[url](https://github.com/jasp-stats/jasp-desktop/blob/development/Tools/flatpak/org.jasp.JASP.json). This prevents to make reproducible builds outside of JASP infrastructure. Please add `commit` and update it with every release for which you release the flatpak. So, for current version, the last section would read

```json
		{
			"name": "jasp",
			"buildsystem": "qmake",
			"config-opts": [],
			"build-options": {
				"append-ld-library-path": "/app/lib;/app/lib64/R/lib",
				"ldflags": "-rpath-link -L/usr/lib/sdk/gfortran-62/lib",
				"env": {
					"GIT_DISCOVERY_ACROSS_FILESYSTEM": "true",
					"R_HOME": "/app/lib64/R/",
					"PREFIX": "/app"
				},
				"build-args": ["--share=network"]
			},
			"sources":[
				{
					"type":"git",
					"branch": "master",
                                        "commit": "76f9dc8fb52659ce5492230d9fa9872329337b41",
					"url": "https://github.com/jasp-stats/jasp-desktop"
				},
				{
					"type": "shell",
					"commands": 
					[ 
						"echo \"Now we will try to install all JASP's R packages!\"",
						"R CMD INSTALL ./JASP-Engine/JASP",
						"echo \"And building JASP is probably a nice plan as well\""
					]
				}
			]
		}
```

User case: I have some strange crash on start of flathub-provided JASP. This could be in theory due to some weird interaction between nvidia driver and flatpak. So, I was thinking to rebuild flatpak using your scripts and up to date flathub platforms. For making reproducible build, commit id would be needed. I can also add that ID, but then I realized that its actually not clear which commit id was used for your builds.

In related issue, do you plan to provide JASP via Flathub? Should I open issue for that?

**Comment by markovendelin** [comment] 2019-01-07 17:40
In addition, would be great to know whether current Flatpak JSON is up to date. Last time it was updated 4 month ago.

**Comment by JorisGoosen** [comment] 2019-02-08 15:03
The current build of flatpak JASP is based on [version_0_9_2 branch](https://github.com/jasp-stats/jasp-desktop/tree/version_0_9_2), although the commit-id is not added there this branch has not been changed since release.

As far as flathub goes, I had actually planned on doing this and did some preliminary work. Sadly enough though it isn't reasonable right now to do this. Flathub requires a package to use specific versions of all components that go into the package.

However, we use a considerable number of R-packages and these are included in our flatpak-repo. These are taken from [CRAN](https://cloud.r-project.org/) and while I could add specific versions for all packages they want me to specifically refer to all repositories/tarballs/whatever.

The `requiredRpackages_*` segments of the flatpak json you linked to show you the specific versions used and these lists are relatively trivial to generate in combination with some scripts we have. But to get all repositories/tarballs would require a large amount of manual labor. This did not seem worth it to me.

If you have a better suggestion however, I am all ears!

**Comment by markovendelin** [comment] 2019-02-09 17:30
@JorisGoosen, so it sounds like Flathub will not be able to guarantee reproducible builds with the current install script. Usually the will want to have some kind of hash that would allow to verify the download. I am not familiar enough with R - maybe there is some kind of option in `install_version` which would be able to serve this purpose. Probably just specification of the version is insufficient, although that could be argued for. 

Usually, Flathub devs are responding rather quickly and maybe the easiest way to get constructive feedback would be to just submit the current JSON script for review. Process is rather simple (submitting PR against the main repo) and its always an option to back off if its too much work. You could also just notify Flathub developers that you are not 100% sure whether you will pull it through. If they will manage to find the solution (iff it is a problem) and you get it to flathub, further releases are dead easy for you and users (all infrastructure is set for it).

**Comment by JorisGoosen** [comment] 2019-02-10 11:52
@markovendelin yeah, that's what I tried already, see PR: https://github.com/flathub/flathub/pull/446 

One of the main problems is that dependency resolution for R-packages is done by R itself which requires network access. Which is something flathub doesn't want on their build-computers and I can understand that.

The problem is then that I would have to create a list of all specific R packages + dependencies and then their specific commits in all their repositories.

Although now that I am thinking about it, since then we do have https://github.com/jasp-stats/jasp-required-files which contains all necessary R packages + binaries for Windows & Mac. We could use that to also create a specific branch of all the required R-packages for flatpak.

That would solve the problem quite nicely. I will have take a look at that from beginning of March onwards.

**Comment by markovendelin** [comment] 2019-02-10 15:10
Great, you're few steps ahead already! I can see that the network access is
refused in the build servers and allowed only while fetching the packages.
Good luck with the setup or the repository. Indeed, github archive feature
should fit nicely and allow you to ship all the required files.

**Comment by JorisGoosen** [comment] 2019-07-02 15:47
So I've been trying hard to get flathub to accept JASP in: https://github.com/flathub/flathub/pull/1035
There seems to be a problem with the screenshots there, but hopefully this will be fixed and at that point it will also be clear what version was used to build the current JASP version.

But I figure this issue can be closed now.

**Closed by JorisGoosen** 2019-07-02 15:47 UTC

**Comment by markovendelin** [comment] 2019-07-02 17:08
Good luck with building for Flathub! Thank you very much for doing it!
