### ISSUE TITLE
JASP doesn't display graphs on analysis file after saving and reopening the analysis

### ISSUE THREAD

**Issue by ozge-b** [jasp-stats/jasp-issues#313] opened 2019-02-21 13:45 UTC
* JASP version: both tried 0.8.1.0 and the latest version
* OS name and version: windows 10, 1803
* Analysis: ANOVA / all types
* Bug description: After conducting an analysis and producing graphs on JASP, I save the file and close the jasp. In every time I reopen the analysis again, I cannot see the graphs. They are all corrupted. I sent them to my professor, she could not see graphs either in her computer. They only appear after I reconduct analysis or reproduce the graphs.
* JASP files as a zip:[sample analysis.zip](https://github.com/jasp-stats/jasp-issues/files/2889472/sample.analysis.zip)
* Screenshot: ![example](https://user-images.githubusercontent.com/47679878/53172257-ee225d80-35f5-11e9-9d0b-c8b4c433b29e.jpg)

**Comment by TimKDJ** [comment] 2019-03-06 09:58
Normally the .jasp file contains a Resources folder with the actual png's.
Your .jasp file does not contain the Resources folder and so JASP cannot find any images.
@boutinb do you have an idea what could cause this?

**Comment by boutinb** [comment] 2019-03-11 12:43
@ozge-b JASP should indeed add the resources in the jasp file. It does not do it in your environment. To try to understand what happens, can you check already the following:
when you open JASP, and makes some analysis with a plot, can you check that in your C:\Documents and Settings\<username>\Local Settings\Application Data\JASP\temp a folder is created with a integer name. If you go to this folder, can you see a 'resources\0' subfolder, with inside _0.png plot? If you open this png file, is it the same plot you see in JASP?
Bruno

**Comment by ozge-b** [comment] 2019-03-11 13:16
Thank you for your response @boutinb . I conduct an analysis. In documents folder, there is no speciifc folder or file for jasp. In " C:\Users\-my username-\AppData\Local\JASP\temp\10620\resources\0" folder, there is a png file as you said and it  is same with the one that i am seeing in the jasp.

**Comment by boutinb** [comment] 2019-03-14 14:51
Hi @ozge-b I think the way is to send you a (beta) version with some extra log so that I can understand what's happening on your computer. I will do that tomorrow

**Comment by boutinb** [comment] 2019-03-19 14:42
Hi @ozge-b I have made a special setup for windows 64: https://static.jasp-stats.org/JASP-0.9.3.0-Special.msi
I have built it on from our development code: this is NOT a official release version. It is not well tested yet. But in this version I have added some log when the JASP file is created. So install it, and start it from the command line in c:\Program Files\JASP, by typing "JASP > c:\temp\jasp.log" (replace c:\temp by any folder where you can write permission). Then send me this jasp.log

**Comment by boutinb** [comment] 2019-03-26 08:22
Hi @ozge-b Did you try the setup I sent you? We will release soon a new version, and it would quite nice to include a fix for your problem

**Comment by ozge-b** [comment] 2019-03-26 14:01
@boutinb thank you for your attention. I tried, I downloaded the version you sent me but I could not start it from the command line. I tried to give writing permission for some folders on my computer. However, when i tried the this command: ""JASP > c:\myfolder\jasp.log" it says access denied. I am not sure what is the problem.

**Comment by boutinb** [comment] 2019-03-26 14:35
@ozge-b This is quite strange... Are you admin of your PC? If yes, can you start a command prompt as administrator (right-click a command prompt icon, and select Run as Administrator), and try to start JASP as explained above?
If you are not admin of your PC, is it possible to get the permission temporary?

**Comment by ozge-b** [comment] 2019-03-26 15:11
@boutinb I am not that much familar with the command prompt, so i am sending screenshots about what I have tried with running as administrator cmd.
![Screenshot_1](https://user-images.githubusercontent.com/47679878/55008648-55b33a80-4ff2-11e9-82d8-b3c38a4f3278.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/47679878/55008649-564bd100-4ff2-11e9-9b5d-e05eab43d5cc.jpg)

**Comment by boutinb** [comment] 2019-03-26 15:43
Hi @ozge-b 
What you have to do is:
cd "Program Files\JASP"
JASP > "c:\myfolder\log.txt"

Can you control also that if you start JASP as administrator, then the problem still occurs?

**Comment by ozge-b** [comment] 2019-03-26 16:22
@boutinb It works! I added the log file. Thank you:)

[log.txt](https://github.com/jasp-stats/jasp-issues/files/3009101/log.txt)

**Comment by boutinb** [comment] 2019-03-26 16:28
Hi @ozge-b Can you do the same thing with adding an analysis with a plot and save it to a JASP file?
Can you check then if the plot is still present when you load the JASP file?

**Comment by ozge-b** [comment] 2019-03-26 18:19
@boutinb I conducted an analysis. When I reopened it, graphs did not appear. I am sending bot text file and the analysis file. 

Also I checked the temp png file from this path: C:\Users\username\AppData\Local\JASP\temp\11956\resources\0  and there is png file which belongs to the graph I created. But it disapperaed when I close the jasp.
[sample analysis 2.zip](https://github.com/jasp-stats/jasp-issues/files/3009621/sample.analysis.2.zip)

[log.txt](https://github.com/jasp-stats/jasp-issues/files/3009617/log.txt)

**Comment by boutinb** [comment] 2019-03-29 16:39
@ozge-b The log file you sent is really interesting, and I try to reproduce your error on a (virtual) machine, but I am currently have problem with this machine... Next week I will have more information.

**Comment by ozge-b** [comment] 2019-03-29 20:41
@boutinb I am really appriciated. I conducted that analysis with a data from jasp's data library if it is important.

 I guess there is something wrong or missing in my computer but i don't know what it is. For instance, I have tried the latest official version, 9.2. However, when I attempt to open a jasp analysis file by double clinking it, a warning message appears. I am not sure it is related to graph problem but in case it is related, I am sending the screenshot of the message. 
![error1](https://user-images.githubusercontent.com/47679878/55261314-a8ebee00-527b-11e9-82b4-68787cff1ba1.jpg)

**Comment by JorisGoosen** [comment] 2019-07-02 15:02
I am closing this issue because I am assuming the latest release of JASP (0.10.0.0) should work for you.

If not, feel free to reopen this issue.

**Closed by JorisGoosen** 2019-07-02 15:02 UTC

**Comment by alexpdys** [comment] 2023-02-07 17:49
Hello, I have the same problem, running on a Mac 11.8. When I save the JASP file then reload it, all the images have disappeared. Any advice would be appreciated.

**Comment by shun2wang** [comment] 2023-02-08 02:21
Hi @alexpdys Could you open a new issue here https://github.com/jasp-stats/jasp-issues/issues/new?assignees=&labels=Bug&template=bug-report.yml&title=%5BBug%5D%3A+

Because this issue was closed and out of date. with thanks.

**Comment by boutinb** [comment] 2023-02-08 10:11
I also cannot reproduce this on my mac...

**Comment by shun2wang** [comment] 2023-02-08 10:32
As @ozge-b 's pic we can see this may caught by Unicode username(fixed in 0.16.4) and I don't think this on Mac.
![image](https://user-images.githubusercontent.com/10348402/217504965-23db6add-2e31-493e-ac84-de9cf305c43d.png)

If so , what version of JASP do you use? @alexpdys you can open another issue and give us more information.

**Comment by alexpdys** [comment] 2023-02-08 11:48
Thank you. I have started another issue. I am using JASP 0.17 (Intel) on Mac.

From: Shun Wang ***@***.***>
Date: Wednesday, 8 February 2023 at 10:33
To: jasp-stats/jasp-issues ***@***.***>
Cc: Alex Salam ***@***.***>, Mention ***@***.***>
Subject: Re: [jasp-stats/jasp-issues] JASP doesn't display graphs on analysis file after saving and reopening the analysis (#313)

As @ozge-b<https://github.com/ozge-b> 's pic we can see this may caught by Unicode username(fixed in 0.16.4) and I don't think this on Mac.
[image]<https://user-images.githubusercontent.com/10348402/217504965-23db6add-2e31-493e-ac84-de9cf305c43d.png>

If so , what version of JASP do you use? @alexpdys<https://github.com/alexpdys> you can open another issue and give us more information.
