### ISSUE TITLE
[Feature Request]: Text analysis in JASP

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#1587] opened 2022-01-25 15:17 UTC
### Description

Add a text analysis function in JASP

### Purpose

Capture all course functions "one stop shop" for all statistics needs

### Use-case

Consider open source "Seance" as model https://www.linguisticanalysistools.org/seance.html

### Is your feature request related to a problem?

No

### Describe the solution you would like

Import text files run analysis function i.e. polarity, emotional measures.

### Describe alternatives that you have considered

using Seance open source text analysis tool

### Additional context

![Seance](https://user-images.githubusercontent.com/33431829/151004423-180b7385-228e-484e-ac24-7c5beb708231.PNG)

**Comment by tomtomme** [comment] 2024-02-01 20:13
closing since duplicate of https://github.com/jasp-stats/jasp-issues/issues/2398

**Closed by tomtomme** 2024-02-01 20:13 UTC
Labels: Feature Request
