### ISSUE TITLE
[Bug]: RM ANOVA does not show any results when variables are entered. 

### ISSUE THREAD

**Issue by giovannadelsordo** [jasp-stats/jasp-issues#1996] opened 2023-02-06 20:10 UTC
### JASP Version

0.17.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

RM ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

I recently downloaded JASP version 0.17 on a MacBook Air running on macOS Ventura 13.2. I open my datafile into JASP and then try to run a repeated measures ANOVA (3 repeated measures, 2 between factors). When I enter the variables into the correct boxes, the output stays completely blank (see attached image). 
I tried to troubleshoot: when I am running a one-way independent ANOVA, it works; I downloaded the same JASP 0.17 version on a Windowns PC and I run into the same problem. 
![Screenshot RM ANOVA issue](https://user-images.githubusercontent.com/124626644/217074246-4cc3c200-f98e-461a-8fe0-5492bd1fda15.jpg)

### Expected Behaviour

What should have happened is for the results of the RM ANOVA to be displayed in the results section. 

### Steps to Reproduce

1. Open JASP version 0.17 (Mac or Windows)
2. Open a data file
3. Click on Repeated Measures ANOVA
4. Enter the levels of the repeated measures (3 variables)
5. Enter the between subject factors (2 factors)
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2023-02-07 08:56
Hi @giovannadelsordo, we know this problem and there will be soon a version that solves this. What happens is that the factor is not automatically set in the Model Terms: if you open the Model section of the analysis, you can set the factor as model term and the analysis will be run.
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/1987

**Closed by boutinb** 2023-02-07 08:56 UTC
Labels: Module: jaspAnova, OS: macOS Intel, Bug
