### ISSUE TITLE
Error in numeric(selectionState[['N.items']]): invalid 'length' argument

### ISSUE THREAD

**Issue by SanneAndriesRahul** [jasp-stats/jasp-issues#2316] opened 2023-10-02 12:06 UTC
### JASP Version

0.17.1

### JASP Module

Audit

### What analysis are you seeing the problem on?

Workflow

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This analysis terminated unexpectedly.

Error in numeric(selectionState[['N.items']]): invalid 'length' argument

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.jfaWorkflowAnalysis(options, jaspResults)

.jfaExecutionStage(options, jaspResults)

numeric(selectionState[['N.items']])

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

A report shoud have been provided 

### Steps to Reproduce

1. 
2.
3.
...

### Log (if any)

This analysis terminated unexpectedly.

Error in numeric(selectionState[['N.items']]): invalid 'length' argument

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.jfaWorkflowAnalysis(options, jaspResults)

.jfaExecutionStage(options, jaspResults)

numeric(selectionState[['N.items']])

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment] 2023-10-02 12:23
Hi!

Thanks for reporting this. This is a known issue that sometimes occurs when the analysis cannot refresh properly. Can you try to refresh the analysis via the black arrow next to the analysis output? In my experience, that should make it work again. Let me know if that works!

Best,
Koen

**Comment by SanneAndriesRahul** [comment] 2023-10-02 14:37
Hi,

***@***.***I do not see a back arrow. Can you provide me with a screenprint or something? I tried refesh which is provided on the right site of the screen (aka output)) by “Results”

This is however  not working

***@***.***


Thanks!

Rahul Ravesteijn
Financieel Adviseur Rechtmatigheid

Gemeente Capelle aan den IJssel
Rivierweg 111, 2903 AR Capelle aan den IJssel
Postbus 70, 2900 AB Capelle aan den IJssel
T 06 – 29 68 06 35
E ***@***.******@***.***>
I www.capelleaandenijssel.nl<http://www.capelleaandenijssel.nl/>

Van: Koen Derks ***@***.***>
Verzonden: maandag 2 oktober 2023 14:23
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Rahul Ravesteijn ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] Error in numeric(selectionState[['N.items']]): invalid 'length' argument (Issue #2316)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Hi!

Thanks for reporting this. This is a known issue that sometimes occurs when the analysis cannot refresh properly. Can you try to refresh the analysis via the black arrow next to the analysis output? In my experience, that should make it work again. Let me know if that works!

Best,
Koen

**Comment by koenderks** [comment] 2023-10-03 05:21
Hi!

The menu I was referring to is visible once you click the black arrow next to "Results", and then you can select "Refresh all". 

<img width="630" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/25059399/65f5e272-6e70-45d2-bdcc-5a81f65cc772">

However, it seems like you have already found this. Can you post a screenshot of the input and output screen so that I have a little more information about what the problem is. Also, can you try doing the analysis again using the latest version of JASP (0.18.1). Thanks!

**Comment by koenderks** [comment] 2023-10-03 05:23
There was a known issue (https://github.com/jasp-stats/jasp-test-release/issues/2363) with this error message that got fixed in the latest release.

**Comment by koenderks** [comment] 2023-10-03 08:35
Did upgrading JASP solve the problem? If not, we can look further into it!

**Comment by koenderks** [comment] 2023-10-09 06:08
Hi @SanneAndriesRahul,

Just a ping to understand if updating JASP solved the problem. If that is the case, this issue can be closed. If not, then we can look further into it.

Best,
Koen

**Comment by SanneAndriesRahul** [comment] 2023-10-09 06:46
Hi,

I’ve tried the csv on version 18.1 this weekend. I received the same remark as with verseion 17.1.

Rahul

Rahul Ravesteijn
Financieel Adviseur Rechtmatigheid

Gemeente Capelle aan den IJssel
Rivierweg 111, 2903 AR Capelle aan den IJssel
Postbus 70, 2900 AB Capelle aan den IJssel
T 06 – 29 68 06 35
E ***@***.******@***.***>
I www.capelleaandenijssel.nl<http://www.capelleaandenijssel.nl/>

Van: Koen Derks ***@***.***>
Verzonden: maandag 9 oktober 2023 08:09
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Rahul Ravesteijn ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] Error in numeric(selectionState[['N.items']]): invalid 'length' argument (Issue #2316)


Hi @SanneAndriesRahul<https://github.com/SanneAndriesRahul>,

Just a ping to understand if updating JASP solved the problem. If that is the case, this issue can be closed. If not, then we can look further into it.

Best,
Koen

**Comment by koenderks** [comment] 2023-10-09 06:57
Hi Rahul,

Thanks for the info. Is it possible to share a screenshot of the input options (you can just upload the screenshot in the issue repository at https://github.com/jasp-stats/jasp-issues/issues/2316#issuecomment-1752428326, replying via email will not show the screenshot unfortunately). Also, is it possible to share the data file (or a similar file, can of course be anonymised) so that I can try to reproduce the problem? Any information about what steps you performed to get this error would be useful!

Thanks in advance

**Comment by SanneAndriesRahul** [comment] 2023-10-09 07:01
Hi,

I will perform the steps later this morning as I have a meeting now. I will include the steps and make screenshots.

Thanks for your help!

Kind regards!

Rahul

Rahul Ravesteijn
Financieel Adviseur Rechtmatigheid

Gemeente Capelle aan den IJssel
Rivierweg 111, 2903 AR Capelle aan den IJssel
Postbus 70, 2900 AB Capelle aan den IJssel
T 06 – 29 68 06 35
E ***@***.******@***.***>
I www.capelleaandenijssel.nl<http://www.capelleaandenijssel.nl/>

Van: Koen Derks ***@***.***>
Verzonden: maandag 9 oktober 2023 08:58
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Rahul Ravesteijn ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] Error in numeric(selectionState[['N.items']]): invalid 'length' argument (Issue #2316)


Hi Rahul,

Thanks for the info. Is it possible to share a screenshot of the input options (you can just upload the screenshot in the issue repository at #2316 (comment)<https://github.com/jasp-stats/jasp-issues/issues/2316#issuecomment-1752428326>, replying via email will not show the screenshot unfortunately). Also, is it possible to share the data file (or a similar file, can of course be anonymised) so that I can try to reproduce the problem? Any information about what steps you performed to get this error would be useful!

Thanks in advance

**Comment by koenderks** [comment] 2023-10-09 10:18
Hi Rahul,

No I cannot. You have to manually drag the documents into the writing box on the page of this issue (https://github.com/jasp-stats/jasp-issues/issues/2316), or you can email the files to k.derks@nyenrode.nl. Then I'll take a look.

**Comment by SanneAndriesRahul** [comment] 2023-10-09 10:21
The [error] is still occurring. Please find attached the various docs
[Steekproef Capelle Q3 2023.csv](https://github.com/jasp-stats/jasp-issues/files/12844877/Steekproef.Capelle.Q3.2023.csv)
[Steekproef Capelle Q3 2023.txt](https://github.com/jasp-stats/jasp-issues/files/12844879/Steekproef.Capelle.Q3.2023.txt)
[Upload the file.docx](https://github.com/jasp-stats/jasp-issues/files/12844881/Upload.the.file.docx)

**Comment by SanneAndriesRahul** [comment] 2023-10-09 10:22
Hi Koen,

the docs are now attached in issue #2316.

Thanks!

Rahul Ravesteijn
Financieel Adviseur Rechtmatigheid

Gemeente Capelle aan den IJssel
Rivierweg 111, 2903 AR Capelle aan den IJssel
Postbus 70, 2900 AB Capelle aan den IJssel
T 06 – 29 68 06 35
E ***@***.******@***.***>
I www.capelleaandenijssel.nl<http://www.capelleaandenijssel.nl/>

Van: Koen Derks ***@***.***>
Verzonden: maandag 9 oktober 2023 12:19
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Rahul Ravesteijn ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] Error in numeric(selectionState[['N.items']]): invalid 'length' argument (Issue #2316)


Hi Rahul,

No I cannot. You have to manually drag the documents into the writing box on the page of this issue (#2316<https://github.com/jasp-stats/jasp-issues/issues/2316>), or you can email the files to ***@***.******@***.***>. Then I'll take a look.

**Comment by koenderks** [comment] 2023-10-09 10:32
Hi Rahul,

I got your files but deleted the comment. In the docx file that you send you show some images, but based on the pictures it seems like you are not using version 0.18.1 in which the supposed bug is fixed. You can download the most recent version [here](https://jasp-stats.org/download/). I also recommend adding a column to your data set in excel that is just 1 ... n (being the number of rows) and using that as the Item ID variable. Right now you cannot use the Crediteurnaam variable as the item ID because there are double entries. 

I have done this for you in this file ([Steekproef.Capelle.Q3.2023.csv](https://github.com/jasp-stats/jasp-issues/files/12844955/Steekproef.Capelle.Q3.2023.csv) so that you have an example of what that should look like, I removed the actual creditor names but you can remake this in excel yourself).


Using those changes to the file and using version 0.18.1 I get no error. Let me know if that works!

<img width="1248" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/25059399/43e03f87-2139-4ebe-9445-2aae71b43433">

**Comment by SanneAndriesRahul** [comment] 2023-10-09 13:17
Dear Koen,

The perfect solution! Thanks very much veru for your help!

Rahul

Rahul Ravesteijn
Financieel Adviseur Rechtmatigheid

Gemeente Capelle aan den IJssel
Rivierweg 111, 2903 AR Capelle aan den IJssel
Postbus 70, 2900 AB Capelle aan den IJssel
T 06 – 29 68 06 35
E ***@***.******@***.***>
I www.capelleaandenijssel.nl<http://www.capelleaandenijssel.nl/>

Van: Koen Derks ***@***.***>
Verzonden: maandag 9 oktober 2023 12:33
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Rahul Ravesteijn ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] Error in numeric(selectionState[['N.items']]): invalid 'length' argument (Issue #2316)


Hi Rahul,

I got your files but deleted the comment. In the docx file that you send you show some images, but based on the pictures it seems like you are not using version 0.18.1 in which the supposed bug is fixed. You can download the most recent version here<https://jasp-stats.org/download/>. I also recommend adding a column to your data set in excel that is just 1 ... n (being the number of rows) and using that as the Item ID variable. Right now you cannot use the Crediteurnaam variable as the item ID because there are double entries.

I have done this for you in this file (Steekproef.Capelle.Q3.2023.csv<https://github.com/jasp-stats/jasp-issues/files/12844955/Steekproef.Capelle.Q3.2023.csv> so that you have an example of what that should look like, I removed the actual creditor names but you can remake this in excel yourself).

Using those changes to the file and using version 0.18.1 I get no error. Let me know if that works!
[image]<https://user-images.githubusercontent.com/25059399/273559452-43e03f87-2139-4ebe-9445-2aae71b43433.png>

**Comment by koenderks** [comment] 2023-10-09 13:21
Hi Rahul,

Glad to hear that it works now! I will mark this issue as resolved. If you encounter anymore bugs in the future, feel free to open a new one!

**Closed by koenderks** 2023-10-09 13:21 UTC
Labels: Module: jaspAudit, OS: Windows 10, Bug
