### ISSUE TITLE
unexpected input error

### ISSUE THREAD

**Issue by DocGavin** [jasp-stats/jasp-issues#577] opened 2020-01-05 03:49 UTC
JASP v0.11.1; windows 10 64-bit
SEM Module
enter lavaan syntax. copied text from functioning syntax in a notepad++ file
got unexpected input error for the last line of syntax
syntax is
'
Bad =~ bd1 + bd2 + bd3 + bd4 + bd5
CE =~ ce1 + ce2 + ce3 + ce4 + ce5 + ce6
IG =~ ig1 + ig2 + ig3
PE =~ pe1 + pe2
SF =~ sf1 + sf2 + sf3
SI =~ si1 + si2 + si3 + si4 + si5
SQ =~ sq1 + sq2
TI =~ ti1 + ti2 + ti3 + ti4 + ti5 + ti6
'

![Annotation 2020-01-05 164812](https://user-images.githubusercontent.com/59521464/71774870-37e02080-2fdb-11ea-9ecd-c0fc04614c83.jpg)

**Comment by vankesteren** [comment] 2020-01-06 08:48
does removing the quotation marks help?

**Comment by DocGavin** [comment] 2020-01-06 20:24
Hi Erik
Thanks for suggestion
I removed the quote marks and JASP seemed to like that but it then crashed
Again windows 10, 64-bit; v0.11.1 JASP
What other information might you want?
Here is the lavaan syntax I used. It’s a bifactor model that has run in RStudio

BD =~ bd1 + bd2 + bd3 + bd4 + bd5
IG =~ ig1 + ig2 + ig3
SI =~ si1 + si2 + si3 + si4 + si5
TI =~ ti1 + ti2 + ti3 + ti4 + ti5 + ti6
CE =~ ce1 + ce2 + ce3 + ce4 + ce5 + ce6
PE =~ pe1 + pe2
SQ =~ sq1 + sq2
SF =~ sf1 + sf2 + sf3
general =~ bd1 + bd2 + bd3 + bd4 + bd5 + ce1 + ce2 + ce3 + ce4 + ce5 + ce6 + ig1 + ig2 + ig3 + pe1 + pe2 + sf1 + sf2 + sf3 + sf4 + si1 + si2 + si3 + si4 + si5 + sq1 + sq2 + ti1 + ti2 + ti3 + ti4 + ti5 + ti6

# specific factors are uncorrelated with general factor
     general ~~ 0*BD + 0*CE + 0*IG + 0*PE + 0* SF + 0*SI + 0*SQ +0*TI


Prof. Gavin T L Brown, PhD
Associate Dean Postgraduate Research (ADPG)
Director Quantitative Data Analysis and Research Unit
Faculty of Education & Social Work
The University of Auckland
Tel: +64 9 3737599 ext. 48602
Mob: +64 22 108 7253
[EdUHK_logo]Honorary Professor, Dept. of Curriculum & Instruction, Education University of Hong Kong
[umu-logo-crest only small] Affiliated Professor, Dept. of Applied Educational Sciences, University of Umea, Sweden
[frontiers_logo]Frontiers in Education Chief Section Editor: Assessment, Testing, and Applied Measurement
[routledge_logo]Routledge author: https://www.routledge.com/authors/i14875-gavin-brown

**Comment by vankesteren** [comment] 2020-01-08 09:50
I don't see any problems with the SEM code indeed, I'm going to need more information about the crash. Did all of JASP simply crash or did you get an error message? Could you send the error message? If you are able to share data, you may also attach the .jasp file for this project. If not, we'll attempt to solve this without :)

**Comment by DocGavin** [comment] 2020-01-08 20:44
Hi Jan-Erik
Unfortunately the error forced JASP to close. No error log was provided.
The screen shot is all the error message generated.
Attached is the jasp data file I was using

Prof. Gavin T L Brown, PhD
Associate Dean Postgraduate Research (ADPG)
Director Quantitative Data Analysis and Research Unit
Faculty of Education & Social Work
The University of Auckland
Tel: +64 9 3737599 ext. 48602
Mob: +64 22 108 7253
[EdUHK_logo]Honorary Professor, Dept. of Curriculum & Instruction, Education University of Hong Kong
[umu-logo-crest only small] Affiliated Professor, Dept. of Applied Educational Sciences, University of Umea, Sweden
[frontiers_logo]Frontiers in Education Chief Section Editor: Assessment, Testing, and Applied Measurement
[routledge_logo]Routledge author: https://www.routledge.com/authors/i14875-gavin-brown

**Comment by juliuspfadt** [comment] 2023-02-09 08:12
@DocGavin, sorry for the late reply. Does the error persist with the latest JASP version?

**Comment by DocGavin** [comment] 2023-02-09 19:28
Apologies
I've been on leave
I'll update jasp and run a test when I can make it a priority and will let you know

Ahorangi / Prof. Gavin T L Brown, PhD, FAPS
Manutaki / Director Quantitative Data Analysis and Research Unit
Te Kura Akoranga me Te Tauwhiro Tangata/ Faculty of Education & Social Work
Waipapa Taumata Rau / The University of Auckland
Tel: +64 9 3737599 ext. 48602
Associerad Professor, Dept. of Applied Educational Sciences, Umeå Universitet, Sweden
Bualuang ASEAN Chair Professor, Thammasat University, Thailand
Honorary Professor, Dept. of Curriculum & Instruction, Education University of Hong Kong
Frontiers in Education Chief Section Editor: Assessment, Testing, and Applied Measurement
I am working virtually and if I send you an email outside your reasonable work hours, please note that I am doing so because it works for me in managing my work / life balance. I do not expect that you will read, respond or take action outside of your normal working hours.

**Comment by juliuspfadt** [comment] 2023-02-10 07:41
No need to apologize. We have been the ones forgetting this issue.

**Comment by tomtomme** [comment] 2024-01-01 20:45
@DocGavin 
Could you try uploading the .jasp file again? It was not attached. You may have to zip it first or just change the .jasp to .zip before uploading it.

If the issue is fixed with the current JASP version, please close this issue

**Closed** 2024-02-12 14:04 UTC
Labels: waiting for requester, Module: jaspSem
