### ISSUE TITLE
Enable posterior distributions with raw units.

### ISSUE THREAD

**Issue by jamessteeleii** [jasp-stats/jasp-issues#437] opened 2019-07-31 08:48 UTC
Currently posterior distributions are presented with standardised effect sizes e.g. Cohen's d. I am a new user of Bayesian approaches and like the potential of it for estimation based approaches. As a result, often I am interested in presenting my point estimates and precision in the raw units used for the variable measured. Though I am learning how to conduct more complex modelling with other software, as JASP is so user friendly I use it for more simple models (e.g. t-tests, ANOVA, ANCOVA) and it would be great to be able to calculate and present the posterior distributions for effects in their raw units.

**Is your feature request related to a problem? Please describe.**
See above

**Describe the solution you'd like**
Enable posterior distributions to be presented in the raw units of measurement for t-test, ANOVA, and ANCOVA designs. 

**Describe alternatives you've considered**
I've been looking at doing this in R, but it would be a great benefit to be able to conudtc it more quickly and simply in JASP and would enable members of my team who do not code to be able to replicate this. 

**Additional context**

**Comment by tomtomme** [comment] 2023-12-28 19:08
related: https://github.com/jasp-stats/jasp-issues/issues/1555

**Comment by tomtomme** [comment] 2024-02-13 10:16
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/1664
will add the anova part there.

**Closed by tomtomme** 2024-02-13 10:16 UTC
Labels: Module: jaspTTests, Module: jaspAnova, Feature Request
