### ISSUE TITLE
Can't view on or donwload JASP files from OSF

### ISSUE THREAD

**Issue by OliverSchultheiss** [jasp-stats/jasp-issues#992] opened 2020-10-01 14:33 UTC
* JASP version: 13

* OS name and version: Windows 10
* Analysis: Any
* Bug description: Can't view or open JASP files on OSF
* Expected behaviour: JASP files should be viewable and I should be able to open them after downloading from OSF

#### Steps to reproduce:
1. Go to https://osf.io/84usb/
2. Click on MotAct_Rep_All_JASP_results_part_1.jasp
3. See error: File can't be viewed in OSF. If you try to download and open it in JASP, JASP crashes. The only way I seem to be able to access this and some other (but not all) JASP files on this OSF project is by logging into OSF from within JASP. But that defeats the purpose of OSF -- others should be able to view my analysis steps and, after downloading, look at them and modify them from within their own JASP software.

**Comment by JorisGoosen** [comment] 2020-10-01 16:10
As far as OSF go I will see if we can get back in contact with them on how the file should be rendered because it is disappointing the larger files don't work.

**Comment by JorisGoosen** [comment] 2020-10-01 17:09
Well, to test this I've just installed the x64 version of 13.1 here on my own windows 10 laptop.
So I'm guessing that that won't be the difference.

Maybe you could help me out a bit and upload the logfiles for JASP? Maybe I can see something there that explains why your JASP crashes while mine chugs on happily.

In case you do not know where or how to get to these logfiles: Logging to file can be enabled under `File Menu (aka the blue hamburger left top) -> Preferences -> Advanced -> Logging`. There you can turn logging on if it wasn't yet.
The cleanest thing to do here would be to close JASP after making sure logging is on, then starting JASP and then only try to download/open that file from OSF.
Then you can open the folder where the logfiles are (there is a button for it next to where you enable logging) and if you could attach the latest desktop + 4 engine logs here we can see what's in them.

**Comment by OliverSchultheiss** [comment] 2020-10-01 18:25
I did what you suggested (after getting the kids to go to bed – sorry for the wait). I’ve attached the zipped log files.

I hope this will give you some clues.

Best wishes,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@fau.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

Keep yappin'.
-- Joe Biden, Presidential debate, September 29 2020
**************************************************************************************************

Von: Joris Goosen <notifications@github.com>
Gesendet: Donnerstag, 1. Oktober 2020 19:10
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Schultheiss, Oliver <oliver.schultheiss@fau.de>; Author <author@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Can't view on or donwload JASP files from OSF (#992)


Well, to test this I've just installed the x64 version of 13.1 here on my own windows 10 laptop.
So I'm guessing that that won't be the difference.

Maybe you could help me out a bit and upload the logfiles for JASP? Maybe I can see something there that explains why your JASP crashes while mine chugs on happily.

In case you do not know where or how to get to these logfiles: Logging to file can be enabled under File Menu (aka the blue hamburger left top) -> Preferences -> Advanced -> Logging. There you can turn logging on if it wasn't yet.
The cleanest thing to do here would be to close JASP after making sure logging is on, then starting JASP and then only try to download/open that file from OSF.
Then you can open the folder where the logfiles are (there is a button for it next to where you enable logging) and if you could attach the latest desktop + 4 engine logs here we can see what's in them.

**Comment by JorisGoosen** [comment] 2020-10-01 19:15
Aah thank you, and no worries about any wait. I'm not really working right now, mostly doing household stuff and playing videogames atm.

But, as far as the attached files go, I'm sorry, but you'll actually have to go to the issue at https://github.com/jasp-stats/jasp-issues/issues/992 because GitHub works quite well for normal email-replies but it won't upload attached files from email to this issue. So if you could upload them there I can have a look at them tomorrow or later.

**Comment by OliverSchultheiss** [comment] 2020-10-02 06:35
[
[Logs.zip](https://github.com/jasp-stats/jasp-issues/files/5316300/Logs.zip)
](url)

**Comment by OliverSchultheiss** [comment] 2020-10-02 06:36
Hi Joris,
Hi Joris,

Hope this works...

Oliver

**Comment by JorisGoosen** [comment] 2020-10-02 10:44
Hallo Oliver,

This worked fine, I'm not sure why you closed the issue though, but I'll reopen it for you.

**Comment by OliverSchultheiss** [comment] 2020-10-02 10:54
Sorry – my bad. Didn’t realize that I closed it…

Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@psy.phil.uni-erlangen.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

"As long as I can remember, I've had memories."
-- Colin Mochrie

**************************************************************************************************

Von: Joris Goosen <notifications@github.com>
Gesendet: Freitag, 2. Oktober 2020 12:45
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Schultheiss, Oliver <oliver.schultheiss@fau.de>; State change <state_change@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Can't view on or donwload JASP files from OSF (#992)


Hallo Oliver,

This worked fine, I'm not sure why you closed the issue though, but I'll reopen it for you.

**Comment by JorisGoosen** [comment] 2020-10-02 11:10
Hmm, the log seems to indicate that the downloading of the file actually works, and it initializes all of your analyses.
But then after that one of the engines crashes. Also a colleague of mine had the same problem with the 0.13.1 version on linux.

We are currently in the testing phase of releasing 0.14 and opening the file seems to work fine with that.
Perhaps you could give a beta-version a try?
This one for instance: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-6f959f47066f948eba429f5f29340dfb44bcbafa.msi

I would caution against using it for working with fulltime because we are still going through everything and making sure stuff is alright.

But it would be good to know if your problem has already been solved or not, because it certainly seems so.

**Comment by OliverSchultheiss** [comment] 2020-10-02 15:48
Hi Joris,

I’ve installed JASP 14 & it worked. When I tried to download the part_1 file from OSF, JASP keeps snapping shut just as the progress bar reaches the right-side end, just as before. But if I save it to the desktop first and then try to open it, it works (unlike before). It even works with the 300+ MB motherfile that I split into Part_1 and Part_2.

So it looks there is something going on with Firefox allowing me to download & open the file in JASP. If I do that, I have problems. If I download & save it first and THEN try to open it via JASP, everything works fine, even for big files.

I hope that this may provide a helpfule clue. As far as I am concerned, I’m ok with the prospect of JASP 14 allowing to open JASP files after downloading & saving them from OSF. But maybe this is an issue that needs to be resolved for other users, too. You’ll be the judge.

In any event, thanks a lot for your support in this matter. I wish you a happy & relaxing weekend!

Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@fau.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

Keep yappin'.
-- Joe Biden, Presidential debate, September 29 2020
**************************************************************************************************

Von: Joris Goosen <notifications@github.com>
Gesendet: Freitag, 2. Oktober 2020 13:10
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Schultheiss, Oliver <oliver.schultheiss@fau.de>; State change <state_change@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Can't view on or donwload JASP files from OSF (#992)


Hmm, the log seems to indicate that the downloading of the file actually works, and it initializes all of your analyses.
But then after that one of the engines crashes. Also a colleague of mine had the same problem with the 0.13.1 version on linux.

We are currently in the testing phase of releasing 0.14 and opening the file seems to work fine with that.
Perhaps you could give a beta-version a try?
This one for instance: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-6f959f47066f948eba429f5f29340dfb44bcbafa.msi

I would caution against using it for working with fulltime because we are still going through everything and making sure stuff is alright.

But it would be good to know if your problem has already been solved or not, because it certainly seems so.

**Comment by JorisGoosen** [comment] 2020-10-05 14:26
Hi Oliver,

That was quite a relaxing weekend, thanks for the good wishes.

As far as this issue goes, I'm happy you open the files at least, a lot better than nothing.
But it would of course be a shame if the OSF support in JASP breaks on large files (if that is what is happening).

I would be curious to hear what happens if:
- You take one of those large files that now opens when selected locally
- Upload it to OSF (temporarily and under a different name)
- Open it from OSF (does it work then?)

In the meantime I will of course try to get this reproducible for me so that I can see what exactly is going wrong or went wrong.

**Comment by OliverSchultheiss** [comment] 2020-10-06 18:21
Hi Joris,

I finally got a chance to try what you suggested. I renamed the downloaded file, uploaded it again to OSF, and tried to access it by downloading it into JASP 14. Same story: progress bar reaches end, JASP shuts down.

You can try it for yourself – the file’s name is
Renamed_JASP-file_test.jasp

Best wishes,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@fau.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

Keep yappin'.
-- Joe Biden, Presidential debate, September 29 2020
**************************************************************************************************

Von: Joris Goosen <notifications@github.com>
Gesendet: Montag, 5. Oktober 2020 16:27
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Schultheiss, Oliver <oliver.schultheiss@fau.de>; State change <state_change@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Can't view on or donwload JASP files from OSF (#992)


Hi Oliver,

That was quite a relaxing weekend, thanks for the good wishes.

As far as this issue goes, I'm happy you open the files at least, a lot better than nothing.
But it would of course be a shame if the OSF support in JASP breaks on large files (if that is what is happening).

I would be curious to hear what happens if:

  *   You take one of those large files that now opens when selected locally
  *   Upload it to OSF (temporarily and under a different name)
  *   Open it from OSF (does it work then?)

In the meantime I will of course try to get this reproducible for me so that I can see what exactly is going wrong or went wrong.

**Comment by JorisGoosen** [comment] 2020-10-07 16:36
Hello Oliver,

Well, if you find some time again, could you download this new beta version of JASP: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-64eb9d074ab1554d397c48a4b0c4360e2cb13e96.msi

I've added a set of new logstatements around the part of the code where JASP seems to crash for you. (It still won't crash on my pc though, but we'll figure out why).

If you could download that `Renamed_JASP-file_test.jasp` and then send me the resulting logs after it crashes I can hopefully narrow down where&what the bug is.

**Comment by OliverSchultheiss** [comment] 2020-10-08 09:57
Hi Joris,

I hope to get that done tonight or tomorrow – I can only do this on my home office PC. My regular office PC is under the control of our IT folks, and installing stuff usually is a major hassle for them and for me.

But apparently the issue I’ve encountered appears to be more widespread:

https://forum.cogsci.nl/discussion/6531/jasp-files-not-opening

I’ll get back to you as soon as I’ve tested the new beta version of JASP in the manner you suggested.

Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@psy.phil.uni-erlangen.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

Take heart.
https://projects.economist.com/us-2020-forecast/president
**************************************************************************************************

Von: Joris Goosen <notifications@github.com>
Gesendet: Mittwoch, 7. Oktober 2020 18:37
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Schultheiss, Oliver <oliver.schultheiss@fau.de>; State change <state_change@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Can't view on or donwload JASP files from OSF (#992)


Hello Oliver,

Well, if you find some time again, could you download this new beta version of JASP: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-64eb9d074ab1554d397c48a4b0c4360e2cb13e96.msi

I've added a set of new logstatements around the part of the code where JASP seems to crash for you. (It still won't crash on my pc though, but we'll figure out why).

If you could download that Renamed_JASP-file_test.jasp and then send me the resulting logs after it crashes I can hopefully narrow down where&what the bug is.

**Comment by JorisGoosen** [comment] 2020-10-08 10:43
Well, I've added per-user support in the 0.14 installer (under "Advanced") and that should allow you to install it to your documents folder. And [this zipfile](https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-64eb9d074ab1554d397c48a4b0c4360e2cb13e96.zip) also contains JASP and can just be downloaded, unpacked and you can start JASP straight from there. 

So no need to install anything, but I am in no hurry, so do it whenever you have time for it.

**Comment by OliverSchultheiss** [comment] 2020-10-15 13:36
Sorrym – wrong log file. Here’s the most recent one.

Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@fau.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

Keep yappin'.
-- Joe Biden, Presidential debate, September 29 2020
**************************************************************************************************

Von: Schultheiss, Oliver
Gesendet: Donnerstag, 15. Oktober 2020 15:30
An: 'jasp-stats/jasp-issues' <reply@reply.github.com>
Betreff: AW: [jasp-stats/jasp-issues] Can't view on or donwload JASP files from OSF (#992)

Hi Joris,

I just installed JASP 14 from the JASP website. It works ok even with the big results file if I try to open the file after saving it to my desktop, but it crashes if I try to download and open it directly from OSF. I’ve attached the log that was generated by this. Hope this provides further clues…

Best,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@fau.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

Keep yappin'.
-- Joe Biden, Presidential debate, September 29 2020
**************************************************************************************************

Von: Joris Goosen <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Donnerstag, 8. Oktober 2020 12:44
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com<mailto:jasp-issues@noreply.github.com>>
Cc: Schultheiss, Oliver <oliver.schultheiss@fau.de<mailto:oliver.schultheiss@fau.de>>; State change <state_change@noreply.github.com<mailto:state_change@noreply.github.com>>
Betreff: Re: [jasp-stats/jasp-issues] Can't view on or donwload JASP files from OSF (#992)


Well, I've added per-user support in the 0.14 installer (under "Advanced") and that should allow you to install it to your documents folder. And this zipfile<https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-64eb9d074ab1554d397c48a4b0c4360e2cb13e96.zip> also contains JASP and can just be downloaded, unpacked and you can start JASP straight from there.

So no need to install anything, but I am in no hurry, so do it whenever you have time for it.

**Comment by JorisGoosen** [comment] 2020-10-15 16:00
Aah, sorry about this, but the email->github-issue conversion drops all attachments Im afraid.
Perhaps you could attach it here directly: https://github.com/jasp-stats/jasp-issues/issues/992
(Zipped because github is finicky like that)

**Comment by OliverSchultheiss** [comment] 2020-10-15 16:57
[Logs.zip](https://github.com/jasp-stats/jasp-issues/files/5386557/Logs.zip)

**Comment by JorisGoosen** [comment] 2020-10-16 10:19
Thank you, that worked!

Im going on vacation for a week, so Im posting the following excerpt from your log here so I can see in the future where I now think the problem occurs:
```

00:00:07.690: Loading analyses seems to have worked out fine.
00:00:07.719: message received from engine #0: {
   "typeRequest" : "settings"
}
...
00:00:07.719: message received from engine #1: {
   "typeRequest" : "settings"
}
...
00:00:07.720: message received from engine #2: {
   "typeRequest" : "settings"
}
...
00:00:07.720: message received from engine #3: {
   "typeRequest" : "settings"
}
...
00:00:09.276: No checked button found in radio buttons chartType
00:00:09.277: No checked button found in radio buttons chartValues
00:00:09.311: No checked button found in radio buttons chartType
00:00:09.311: No checked button found in radio buttons chartValues
00:00:09.981: TempFiles::deleteOrphans started
00:00:09.981: looking at file C:/Users/Oliver/AppData/Local/JASP/temp\4100
00:00:09.981: looking at file C:/Users/Oliver/AppData/Local/JASP/temp\8556
00:00:12.287: informing engine #0 that it ought to stop
00:00:12.287: sending to jaspEngine: {
   "typeRequest" : "stopRequested"
}
```

**Comment by OliverSchultheiss** [comment] 2020-10-16 10:28
Enjoy your vacation & stay safe & healthy!

Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: Oliver.Schultheiss@fau.de<mailto:Oliver.Schultheiss@fau.de>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

Winter is coming.
---C. Orona
**************************************************************************************************

Von: Joris Goosen <notifications@github.com>
Gesendet: Freitag, 16. Oktober 2020 12:20
An: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
Cc: Schultheiss, Oliver <oliver.schultheiss@fau.de>; State change <state_change@noreply.github.com>
Betreff: Re: [jasp-stats/jasp-issues] Can't view on or donwload JASP files from OSF (#992)


Thank you, that worked!

Im going on vacation for a week, so Im posting the following excerpt from your log here so I can see in the future where I now think the problem occurs:



00:00:07.690: Loading analyses seems to have worked out fine.

00:00:07.719: message received from engine #0: {

   "typeRequest" : "settings"

}

...

00:00:07.719: message received from engine #1: {

   "typeRequest" : "settings"

}

...

00:00:07.720: message received from engine #2: {

   "typeRequest" : "settings"

}

...

00:00:07.720: message received from engine #3: {

   "typeRequest" : "settings"

}

...

00:00:09.276: No checked button found in radio buttons chartType

00:00:09.277: No checked button found in radio buttons chartValues

00:00:09.311: No checked button found in radio buttons chartType

00:00:09.311: No checked button found in radio buttons chartValues

00:00:09.981: TempFiles::deleteOrphans started

00:00:09.981: looking at file C:/Users/Oliver/AppData/Local/JASP/temp\4100

00:00:09.981: looking at file C:/Users/Oliver/AppData/Local/JASP/temp\8556

00:00:12.287: informing engine #0 that it ought to stop

00:00:12.287: sending to jaspEngine: {

   "typeRequest" : "stopRequested"

}

**Comment by JorisGoosen** [comment] 2020-10-16 11:34
Will do!

**Comment by JorisGoosen** [comment] 2020-11-02 13:03
Hello Oliver,

I've been looking at your logfiles and our code and I think I might have figured out what was going wrong.
If you could help me out by testing: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-helpingOliver-16ef077c9af29bde37ee146490e0ccea36d6bcf7.msi

Then maybe we can get the fix into the next release.

**Comment by JorisGoosen** [comment] 2021-06-07 12:17
Well, in case @OliverSchultheiss sees this, any nightly from https://static.jasp-stats.org/Nightlies/ should now contain the fix and I assume this was actually a fix and Ill close this issue now.

**Closed by JorisGoosen** 2021-06-07 12:17 UTC
