### ISSUE TITLE
Include reliability output in SEM and factor module

### ISSUE THREAD

**Issue by AlejandroPeru** [jasp-stats/jasp-issues#898] opened 2020-07-22 10:15 UTC
He observado la nueva función de fiabilidad, es muy buena, me puse a pensar que sería interesante y muy útil que la confiabilidad fuese como un output del análisis de la estructura del instrumento, sería más escalrecedor de en qué se basa el programa para estimar las medidas de fiabilidad, además de darnos indicios de la calidad del modelo. Así mismo la oportunidad de incluir situaciones como cuando se presentan errores relacionados o estructuras multifactoriales (Existen fórmulas del omega y alfa al respecto). Así mismo insisto con la importncia de incluir la matriz policórica, actualmente la tendencia es utilizar el omega ordinal y alfa ordinal, debido al nivel de medición de los ítems en escala likert.

**Comment by EJWagenmakers** [comment] 2020-07-22 12:45
Google translate:
"I have observed the new reliability function, it is very good, I thought that it would be interesting and very useful if the reliability were as an output of the analysis of the structure of the instrument, it would be more scanty of what the program is based on. estimate the reliability measures, in addition to giving us indications of the quality of the model. Likewise, the opportunity to include situations such as when there are related errors or multifactorial structures (there are omega and alpha formulas in this regard). Likewise, I insist with the importance of including the polychoric matrix, currently the tendency is to use the ordinal omega and ordinal alpha, due to the level of measurement of items on the likert scale."

Any concrete references to literature or R packages would be welcome!
@juliuspf  @vandenman  @vankesteren

**Comment by AlejandroPeru** [comment] 2020-07-22 20:25
Sobre omega corregido cuando existen errores relacionados: https://journals.sagepub.com/doi/abs/10.1177/01466216010251005

**Comment by AlejandroPeru** [comment] 2020-07-22 20:50
@EJWagenmakers  sobre alfa ordinal http://www.psicothema.com/psicothema.asp?id=3572

**Comment by juliuspf** [comment] 2020-07-27 08:47
I am identifying three issues here (correct me if I am wrong): 

1. Put reliability analysis within structural equation modelling
2. Add reliability statistics for correlated errors
3. Add versions of the reliability statistics for ordinal data

**Comment by juliuspf** [comment] 2020-07-27 08:55
1. We mix two types of reliability statistics, on the one hand, alpha etc are lower bounds and based on CTT, on the other hand, omega is a factor analytic measure. Thus, I do not recommend the move of the reliability statistics, however, it might be an option to display omega for a factor model in the CFA module. Keep in mind though, when we leave unidimensionality, we have to implement omega-hierarchical and omega-total (both are not in JASP yet)

2. This might be an idea for the future. Since Klaas and I are currently working on a paper about alpha and correlated errors, I would recommend to wait with this (at least for the lower bounds). For omega this might be an option. Having correlated errors is something people do not necessarily notice in a simple reliability analysis, so again, this might have to go into the CFA module. 

3. Definitely something to look into.

**Comment by AlejandroPeru** [comment] 2020-08-04 06:18
Muchas gracias, sería un gran avance que lo tengan en cuenta.

**Comment by AlejandroPeru** [comment] 2020-08-04 06:20
@juliuspf sobre el artículo en el que estás trabajando me gustaría poder leerlo cuando ya lo tengas listo. una ultima consulta, tendrásbilbiografía sobre la fiabilidad con métodos bayesianos como ahora  ha incluido jasp, te agradecería que me compartas.

**Comment by brianmsm** [comment] 2020-11-12 04:16
The `reliability` function from `semTools` package can do this, include omega for correlated errors.

**Comment by juliuspf** [comment] 2023-01-16 09:31
this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/754

**Closed** 2023-04-14 08:29 UTC
Labels: duplicate, Module: jaspReliability, Module: jaspFactor, Feature Request
