### ISSUE TITLE
multigroup CFA don´t working well.

### ISSUE THREAD

**Issue by alexsandro-DeAndrade** [jasp-stats/jasp-issues#583] opened 2020-01-09 13:49 UTC
I always have a bug when a try this analysis procedure. How I can fix this problem?

**Comment by boutinb** [comment] 2020-01-09 17:16
Hi @alexsandro-DeAndrade 
Can you be more explicit? Can you describe the exact steps you do, give for example a screenshot of the error, and also a JASP file where this error occurs?
Kind regards,
Bruno

**Comment by FransMeerhoff** [comment] 2020-01-22 08:24
Hi @alexsandro-DeAndrade ,

We are not able to reproduce this problem, because we do not know exactly what the problem is.
If you can tell us exactly what goes wrong we can test this problem on the upcoming version JASP 0.12  which will be released very soon.

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment] 2020-03-26 11:33
Please @alexsandro-DeAndrade  reopen if this issue still occurs

**Closed by FransMeerhoff** 2020-03-26 11:33 UTC
Labels: Waiting for requester
