### ISSUE TITLE
0.11.1 Keeps Crashing

### ISSUE THREAD

**Issue by BrianFink14** [jasp-stats/jasp-issues#622] opened 2020-02-28 14:49 UTC
* JASP version: 0.11.1

* OS name and version: It is an HP computer. Just installed 0.11.1 and all it does is crash. This is very annoying. Cannot call this user-friendly when I need to be able to use this to teach a statistics . I open an SPSS dataset and that comes up. As soon as try to do any sort of analysis, the program crashes and asks me to submit a bug report. This is ridiculous. If JASP is not reliable, how can my students use it? 
* Analysis: 
* Bug description:
* Expected behaviour:

 Fix the thing!

**Comment by JorisGoosen** [comment] 2020-03-02 11:15
This is obviously a duplicate of the previous issue that you posted at https://github.com/jasp-stats/jasp-issues/issues/623 of course we want to help you. But it won't go quicker by opening more issues and shouting at us.

**Closed by JorisGoosen** 2020-03-02 11:15 UTC

**Comment by BrianFink14** [comment] 2020-03-02 18:15
No. Wrong. Download and it should work. Claiming that a new version will magically fix the problem is nonsense and you know it. Sticking with reliable programs for my students. Customer service needs as much improvement as JASP itself.











??



________________________________
