### ISSUE TITLE
Bug in Process Capability A[Bug]: 

### ISSUE THREAD

**Issue by paulchance** [jasp-stats/jasp-issues#2523] opened 2024-01-10 13:40 UTC
### JASP Version

0.18.1

### JASP Module

Quality Control

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I have this message when trying to run a capability study on JASP 18.1
Error in tablelListCombine{{'test3'}} subcript out of bounds.
![JASP](https://github.com/jasp-stats/jasp-issues/assets/156204617/bd94c843-fdb0-4544-a5ca-0b51618f5a1b)

### Expected Behaviour

This is the first time I have used this software on my laptop. It seems to work OK on other team members machines

### Steps to Reproduce

1. Copy data from excel
2. Paste into column 1 of JASP 
3. select Quality Control
4. Select capability study
5. Select column 1
6. Set subgroup to 1
7. Error message occurrs
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by JTPetter** [comment] 2024-01-10 14:19
Hi @paulchance ,
Thanks for your report! Could you try with JASP 0.18.2? I expect that this is fixed already. If not, would you mind sharing your data set?

**Comment by paulchance** [comment] 2024-01-10 15:07
Hello JTP,
I have doubled my dataset from 35 to 70. This seems to of fixed it.
Do you think this could have been the problem?
Many Thanks
Paul

Paul Chance CEng
Senior Manufacturing Engineer

Tel: +44 (0)7788 366 181
E-mail: ***@***.******@***.***>


SKF (U.K.) Limited
108 Strode Road, Clevedon, BS21 6QQ
www.skf.co.uk<http://www.skf.co.uk/>, Facebook<https://www.facebook.com/SKFGroup>, LinkedIn<https://www.linkedin.com/company/skf>, Twitter,<https://twitter.com/skfgroup> Instagram,<https://instagram.com/skfgroup/> Youtube<https://www.youtube.com/user/SKFOfficial>

**Comment by JTPetter** [comment] 2024-01-10 16:04
I suppose this bug occurred if test 3 of the Nelson Rules was violated.  So, changing the dataset might lead to test 3 not being violated anymore -- but I suppose you would want to know if it is violated. So I would suggest not changing the dataset but upgrading to 0.18.2.

Since you work at SKF the next update might take a while to be rolled out, maybe a month or so. But maybe there is some other way you can use it, I'm not sure.

**Comment by JTPetter** [comment] 2024-01-10 16:05
If you send me the dataset I can confirm that it is indeed fixed in the next version.

**Closed** 2024-01-21 11:35 UTC
Labels: Module: jaspQualityControl, OS: Windows 11, Bug
