### ISSUE TITLE
[Bug]: Can´t run "Reliability Measures" with SEM

### ISSUE THREAD

**Issue by TrendyJorge** [jasp-stats/jasp-issues#3106] opened 2024-12-23 16:51 UTC
### JASP Version

0.19.2

### JASP Module

SEM

### What analysis are you seeing the problem on?

"Reliability Measures" in SEM

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Error in diag(scales) %*% truevar: non-conformable arguments
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.semReliability(modelContainer, dataset, options, ready)
semTools::compRelSEM(modelContainer[['results']][['object']][[1]], tau.eq = FALSE, higher = higherOrder, return.total = TRUE)
omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])

### Expected Behaviour

It was expected to see the Reliability Meassures table, with the "Cronbach alfas" by latent variable and by the total.
I'm running a dataset with 

### Steps to Reproduce

1. specify and run the model
2.  select additional measures (additional fit measures, R-squared, AVE,...)
3. Reliability measures --- the analysis crash
I'm running a dataset with ordinal variables. If I change the variables to "numeric", the reliability analysis run without any problems.

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.2
Build Branch: development
Build Date: Dec  9 2024 12:31:38 (Netherlands)
Last Commit: 410d926e25afc551d362204f8e57971185234544

-------- Basic Info --------
Operating System: Windows 11 Version 24H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.26100
Architecture: x86_64
Install Path: C:/Program Files (x86)/JASP
Platfotm Name: windows
System Local: pt_PT

-------- Extra Info --------
Current code page
Active code page: 850
Active code page: 65001

Host Name:                     JORGE-VIEIRA
OS Name:                       Microsoft Windows 11 Home
OS Version:                    10.0.26100 N/A Build 26100
OS Manufacturer:               Microsoft Corporation
OS Configuration:              Standalone Workstation
OS Build Type:                 Multiprocessor Free
Registered Owner:              asus
Registered Organization:       N/A
Product ID:                    00325-97227-33231-AAOEM
Original Install Date:         04/12/2024, 07:55:41
System Boot Time:              19/12/2024, 18:29:15
System Manufacturer:           ASUSTeK COMPUTER INC.
System Model:                  VivoBook_ASUSLaptop X421UA_M433UA
System Type:                   x64-based PC
Processor(s):                  1 Processor(s) Installed.
                               [01]: AMD64 Family 23 Model 104 Stepping 1 AuthenticAMD ~1801 Mhz
BIOS Version:                  American Megatrends International, LLC. X421UA.304, 31/05/2021
Windows Directory:             C:\WINDOWS
System Directory:              C:\WINDOWS\system32
Boot Device:                   \Device\HarddiskVolume1
System Locale:                 pt;Português (Portugal)
Input Locale:                  pt;Português (Portugal)
Time Zone:                     (UTC+00:00) Dublin, Edimburgo, Lisboa, Londres
Total Physical Memory:         15 772 MB
Available Physical Memory:     6 656 MB
Virtual Memory: Max Size:      17 308 MB
Virtual Memory: Available:     2 873 MB
Virtual Memory: In Use:        14 435 MB
Page File Location(s):         C:\pagefile.sys
Domain:                        WORKGROUP
Logon Server:                  \\JORGE-VIEIRA
Hotfix(s):                     3 Hotfix(s) Installed.
                               [01]: KB5048162
                               [02]: KB5048667
                               [03]: KB5049685
Network Card(s):               4 NIC(s) Installed.
                               [01]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)
                                     Connection Name: Ethernet 2
                                     Status:          Media disconnected
                               [02]: Fortinet SSL VPN Virtual Ethernet Adapter
                                     Connection Name: Ethernet 3
                                     Status:          Hardware not present
                               [03]: Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC
                                     Connection Name: Wi-Fi
                                     Status:          Media disconnected
                               [04]: Realtek USB FE Family Controller
                                     Connection Name: Ethernet 4
                                     DHCP Enabled:    Yes
                                     DHCP Server:     192.168.1.254
                                     IP address(es)
                                     [01]: 192.168.1.99
                                     [02]: fe80::d7b2:32e6:f5ff:240a
                                     [03]: 2001:8a0:5707:4401:d16b:492c:e351:afdf
                                     [04]: 2001:8a0:5707:4401:e5fb:95fe:17d4:1ea2
Virtualization-based security: Status: Running
                               Required Security Properties:
                               Available Security Properties:
                                     Base Virtualization Support
                                     Secure Boot
                                     DMA Protection
                                     Mode Based Execution Control
                               Services Configured:
                                     Hypervisor enforced Code Integrity
                               Services Running:
                                     Hypervisor enforced Code Integrity
                               App Control for Business policy: Enforced
                               App Control for Business user mode policy: Off
                               Security Features Enabled:
Hyper-V Requirements:          A hypervisor has been detected. Features required for Hyper-V will not be displayed.

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-12-26 17:56
thx for the report. This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2294
Lets discuss there. Or reopen if you disagree!

**Closed by tomtomme** 2024-12-26 17:56 UTC
Labels: Module: jaspSem, OS: Windows 11, Bug
