### ISSUE TITLE
[Bug]: Non-parametric Repeated Measure Anova

### ISSUE THREAD

**Issue by Goocha12345** [jasp-stats/jasp-issues#1954] opened 2023-01-04 13:05 UTC
### JASP Version

0.16.4

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I tried to do a mix-model non-parametric ANOVA
it work fine with the RM factor,
but when I entered the Grouping factor I got the error massage 

**
![image](https://user-images.githubusercontent.com/121948458/210560624-675347b3-8f0d-4ab7-b6a5-d6453c93d257.png)
**

### Expected Behaviour

i should have got the result of the analysis

### Steps to Reproduce

1. I entered the relevant variables at the upper area of the procedure 
2. I turned on the nonparametric area
3. Entered the group variable to his place
4. I got the error massage

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment] 2023-01-09 15:26
Hi @Goocha12345 ,

Unfortunately this is a limitation of the analysis (similar to other analyses software/R), so I am afraid this is not a bug. You can consider an [ANOVA on the rank-transformed data](https://en.wikipedia.org/wiki/ANOVA_on_ranks#Transforming_ranks), although this is also not without limitations/pitfalls. I am closing this now, please reopen if you have further questions.

Kind regards,
Johnny

**Closed by JohnnyDoorn** 2023-01-09 15:26 UTC
Labels: Module: jaspAnova, OS: Windows 10, Bug
