### ISSUE TITLE
JASP won´t stay open, opens and immediately closes[Bug]: 

### ISSUE THREAD

**Issue by saxbcavica23** [jasp-stats/jasp-issues#1880] opened 2022-10-31 16:26 UTC
### JASP Version

0.16.4

### What OS are you seeing the problem on?

Windows 11

### Bug Description

JASP app opens and immediately closes, before I can do anything with the app, so I can´t find the logging files in JASP.

### Expected Behaviour

JASP should have stayed open - after instalation it did, but after just one day it doesn´t.

### Steps to Reproduce

1. Just open the jasp app.
2. This happened just once.
![Snímka obrazovky 2022-10-23 125122](https://user-images.githubusercontent.com/117094825/199058737-c1a408e9-2ef3-4242-8720-7335d4731c7e.jpg)

3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by saxbcavica23** [comment] 2022-10-31 17:07
Well, as JASP won´t stay open, I don´t know hot to do that

**Comment by saxbcavica23** [comment] 2022-10-31 17:11
'JASP' is not recognized as an internal or external command,
operable program or batch file.
This is what I find when I try to find the logs files.

**Comment by shun2wang** [comment] 2022-11-01 07:06
@saxbcavica23 you can do this:
1. press "⊞ Win"+"R" to open the RUN window, 
2. input `%appdata%/JASP` to open JASP folder in user path,
3. navigate to JASP/logs path and upload logs which include this crash info.

**Comment by JorisGoosen** [comment] 2022-11-01 09:53
@saxbcavica23 are you behind a proxy btw? 

And the logging folder will probably be empty if you didnt previously turn logging on.
If so you could start JASP in a command prompt as `JASP --logToFile` (You might have to run this from the folder where jasp is installed)

**Comment by saxbcavica23** [comment] 2022-11-01 16:15
Yes, I have proxy given by my university. 

Well I tried to open JASP using the command promt and this is all I got:

'JASP' is not recognized as an internal or external command,
operable program or batch file.

**Comment by saxbcavica23** [comment] 2022-11-01 16:17
> 

Thank youu, but the same text appeared: 'JASP' is not recognized as an internal or external command,
operable program or batch file.
There were no log files available

**Comment by JorisGoosen** [comment] 2022-11-01 16:30
If you turn off your internet for a bit, can you then start JASP succesfully?

**Comment by saxbcavica23** [comment] 2022-11-01 16:49
Hi, yes, when I openned it without my internet, it functioned, only it showed this
![Snímka obrazovky 2022-11-01 174728](https://user-images.githubusercontent.com/117094825/199290006-0745701a-769d-4464-b5e3-18a91782f142.jpg)

**Comment by saxbcavica23** [comment] 2022-11-01 16:49
and this
![Snímka obrazovky 2022-11-01 174741](https://user-images.githubusercontent.com/117094825/199290105-accf0b0b-7ab0-4a88-93d1-6728963692c7.jpg)

**Comment by JorisGoosen** [comment] 2022-11-01 17:33
Well im sorry about this bug and there is an issue for this at #1773 

Dont worry about those messageboxes. 
Ill make sure to fix it in the next version

**Comment by saxbcavica23** [comment] 2022-11-01 17:56
So I can continue using JASP, only I have to open it without internet connection for now?

**Comment by JorisGoosen** [comment] 2022-11-01 19:16
Im afraid so, sorry for the inconvenience

**Comment by tomtomme** [comment] 2024-01-19 20:10
since this is essentially a duplicate of #1773, we could close it.
But then again @saxbcavica23 could help us testing.

**Comment by tomtomme** [comment] 2024-02-12 15:42
@saxbcavica23 
Please reopen if you can help testing once this is fixed!

**Closed as completed** 2024-02-12 15:41 UTC
Labels: Crash, Installing, OS: Windows 11
