### ISSUE TITLE
Reopen issue #459 (Post-Hoc Testing RM ANOVA)

### ISSUE THREAD

**Issue by BiomechFlo** [jasp-stats/jasp-issues#515] opened 2019-10-08 16:20 UTC
Hi,

I just upgraded to JASP Version 0.11.1 but still get wrong numbers for the post hoc tests of the RM ANOVA. I attached the JASP file.

Kind regards 
Flo
[Updated_version.zip](https://github.com/jasp-stats/jasp-issues/files/3703440/Updated_version.zip)

**Comment by TimKDJ** [comment] 2019-10-15 08:00
Hi Flo,

The code that Johnny wrote that fixes the problem is not in 0.11.1 (the .1 upgrade was a hotfix for something unrelated). In JASP 0.12 this will be fixed. Apologies if that wasn't clear

Cheers

**Closed by TimKDJ** 2019-10-15 08:00 UTC
