### ISSUE TITLE
[Feature Request]: Confidence intervals in QQ plots in other sections apart from distributions

### ISSUE THREAD

**Issue by hrgodmann** [jasp-stats/jasp-issues#2110] opened 2023-04-28 12:12 UTC
### Description

It would be nice to also have the options to inspect the qq plots with confidence intervals in other JASP sections (especially in the Descriptives). At the moment, it is only possible in the Distributions section I think.

### Purpose

Assumption Checks

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Descriptives, Regression

**Comment by TarandeepKang** [comment] 2023-05-01 16:39
Relatedly, this also seems useful:

Weine, E., McPeek, M. S., & Abney, M. (2023). Application of Equal Local Levels to Improve Q-Q Plot Testing Bands with R Package qqconf. Journal of Statistical Software, 106, 1–31. https://doi.org/10.18637/jss.v106.i10

**Comment by tomtomme** [comment] 2024-02-08 07:32
Closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/1763
I will transfer Tarans suggestion there.

**Closed by tomtomme** 2024-02-08 07:32 UTC
Labels: Module: jaspDescriptives, Module: jaspRegression, Feature Request
