### ISSUE TITLE
[Bug]: Documentation on computing columns is gone

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2374] opened 2023-10-31 16:36 UTC
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Flatpak

### Bug Description

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/f3599cc5-16ed-4bc5-8392-c72496428f84)

![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/fd84ff45-a0d3-4290-aff7-9c5d69587025)

Hitting the blue help-buttons opened documentation on computed columns in former JASP versions. 

### Expected Behaviour

HItting the help buttons should show the documentation.

### Steps to Reproduce

1. create a computed column
2. click one of the help buttons

I also cleared all caches and config files to make sure my switching between beta and stable did not mess something up

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2023-11-01 08:22
Strange I cannot reproduce this on Mac. Maybe this is only a flatpak related issue. @tomtomme can you reproduce this on another platform?

**Comment by tomtomme** [comment] 2023-11-01 09:37
I canNOT reproduce this on Win10. So yeah, seems Flatpak only

**Comment by JorisGoosen** [comment] 2023-11-01 16:24
@tomtomme are other documentations available though?
Like for instance those in the preferencesmenus or a module like anova or something?

**Comment by tomtomme** [comment] 2023-11-01 18:06
yeah, all other documentations are fine :D

**Comment by tomtomme** [comment] 2023-11-03 08:20
Could this be linked to: https://github.com/jasp-stats/jasp-issues/issues/2296
?

**Comment by shun2wang** [comment] 2023-11-03 08:42
No that's not flatpak error but some help doc path mistake only on Linux. I think @RensDofferhoff will fix it after he come back.

**Comment by tomtomme** [comment] 2023-12-18 08:42
Bug still present in current flatpak beta of 0.18.2 from 30.11.23

**Comment by RensDofferhoff** [comment] 2023-12-18 12:45
Found the issue.
Its caused by case sensitivity of filenames on LINUX systems as opposed to mac, windows.
It will be fixed for the release! 
Thanks for the reminder!

**Closed** 2023-12-19 06:43 UTC
Labels: OS: Linux / Flatpak, Bug
