### ISSUE TITLE
Improve help files - correlation types

### ISSUE THREAD

**Issue by arciniegasdiaz** [jasp-stats/jasp-issues#1447] opened 2021-10-05 14:48 UTC
Hello good,
I have a query regarding the correlation matrix that JASP uses for its analyzes. For example, for factor analysis a type of correlation matrix is ​​needed, which depends on the type of variable and its distribution.
I use the R programming language and in this I can do all kinds of correlations and add them to my analysis. Based on this, I would like you to help me understand under what type of correlation the program is set by default and if it is possible to modify the type of correlation matrix.

Without further ado, thank you.

**Comment by daniel04bolivar** [comment] 2021-10-05 15:05
Hey friend, I also have the same doubt.
I look forward to a prompt reply.

**Comment by boutinb** [comment] 2021-10-08 10:24
@Kucharssim Could you answer this?

**Comment by tomtomme** [comment] 2024-02-01 21:31
@daniel04bolivar & @arciniegasdiaz 
There is a project that tries to improve the help files. 
Also we have a meta-bug for all missing help-files here: https://github.com/jasp-stats/jasp-issues/issues/2529

So I am closing this for now as duplicate of 2529

**Closed by tomtomme** 2024-02-01 21:31 UTC
