### ISSUE TITLE
robust ML and Satorra Bentler Chi square

### ISSUE THREAD

**Issue by Manuel-Sp1211** [jasp-stats/jasp-issues#959] opened 2020-09-01 11:59 UTC
JASP version: 0.13.1
OS name and version: Catalina 10.15.6
Analysis: SEM - Medition analysis
Bug description: Could I get the robust Maximum Likelihood with the Satorra Bentler Chi-square and other robust statistics with JASP for CFA and SEM models?
Expected behaviour:

**Comment by boutinb** [comment] 2020-09-18 12:10
@vankesteren Did you implement this in the new SEM version?

**Comment by tomtomme** [comment] 2024-01-11 14:50
@Manuel-Sp1211 
Just for your information: These features are being worked on

**Comment by juliuspfadt** [comment] 2024-02-07 11:00
Lorenzo does not work for JASP anymore. I think this must a duplicate of these things. And you are right, we are working on these implementations for now. And I think for SEM you can already find some of it if you choose robust standard errors and the Satorra Bentler model test. For the factor module we do not offer the choice of model test yet. But we should.

**Closed** 2024-09-26 07:33 UTC
Labels: Module: jaspSem, Feature Request
