### ISSUE TITLE
Response surface analysis

### ISSUE THREAD

**Issue by OliverSchultheiss** [jasp-stats/jasp-issues#1705] opened 2022-05-11 10:13 UTC
### Description

Request for option to run response surface analyses

### Additional context

It would be cool to have a JASP analysis option for response surface analysis; in particular, to get the relevant parameters and significance tests for various aspects of th response surface properties (e.g., curvature and so on). Please see this publication for an overview:

Shanock, L. R., Baran, B. E., Gentry, W. A., Pattison, S. C., & Heggestad, E. D. (2010). Polynomial Regression with Response Surface Analysis: A Powerful Approach for Examining Moderation and Overcoming Limitations of Difference Scores. Journal of Business and Psychology, 25, 543-554. 

And this paper provides a beautiful illustration:

Brandstätter, V., Job, V., & Schulze, B. (2016). Motivational Incongruence and Well-Being at the Workplace: Person-Job Fit, Job Burnout, and Physical Symptoms. Front Psychol, 7, 1153. https://doi.org/10.3389/fpsyg.2016.01153 

This could probably be put under the rider "Correlation/regression". And perhahps there is also a Bayesian variant of this approach available? I haven't seen one so far, but you guys might know more about this.

In any event, thanks for all your great work. JASP is a real gift to open-science-minded beahvioral scientists.

best wishes,
Oliver Schultheiss

**Comment by EJWagenmakers** [comment] 2022-05-11 14:13
This is interesting. Is there already an R package for this?

**Comment by juliuspf** [comment] 2022-05-11 14:20
thats the one, https://cran.r-project.org/web/packages/RSA/index.html

**Comment by koenderks** [comment] 2022-05-13 06:44
Quality control module has this!

**Comment by OliverSchultheiss** [comment] 2022-05-13 10:03
Where is this hidden? I‘m working with JASP 16.1

Best regards,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: ***@***.******@***.***>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm
**************************************************************************************************

Von: Koen Derks ***@***.***>
Gesendet: Freitag, 13. Mai 2022 08:45
An: jasp-stats/jasp-issues ***@***.***>
Cc: Schultheiss, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Response surface analysis (Issue #1705)


Quality control module has this!

**Comment by EJWagenmakers** [comment] 2022-05-13 11:18
This is a module that will be added to our upcoming release.

**Comment by OliverSchultheiss** [comment] 2022-05-13 11:27
Wonderful! Looking forward to it!

Cheers from Germany,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: ***@***.******@***.***>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm
**************************************************************************************************

Von: EJ ***@***.***>
Gesendet: Freitag, 13. Mai 2022 13:18
An: jasp-stats/jasp-issues ***@***.***>
Cc: Schultheiss, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Response surface analysis (Issue #1705)


This is a module that will be added to our upcoming release.

**Comment by JoKeyser** [comment] 2022-05-16 16:23
@OliverSchultheiss sorry to somewhat hijack this thread, but since you are clearly familiar with that terminology: Maybe you would consider to add/check the German translation of that module? (Can be done even before its released.)

All you need is a browser, then you can add/change the translations of the Process Control module at

- https://hosted.weblate.org/projects/jasp/jaspprocesscontrol-qml/de/
- https://hosted.weblate.org/projects/jasp/jaspprocesscontrol-r/de/

For an overview and an introduction to the translation process, you can read <https://jasp-stats.org/translation-guidelines>.

Feel free to ask (me) any questions, and of course it's also fine if you don't find the time for that :). (I just thought it's a good opportunity, since that module is still lacking many phrases that I'm not too familiar with (and I also haven't seen the module yet).)

**Comment by OliverSchultheiss** [comment] 2022-05-17 05:55
Hi Johannes,

I’d be happy to help, but I am struggling with a couple of problems here. The first is that the website doesn’t seem to have saved any of the suggestions I submitted yesterday. The second is that in most cases I know the technical terms only in English and not in German. So I have to look them up on the internet. The third is that the second problem becomes even harder because the website only lists single words. But I’d need to see them in their proper context to be able to come up with a good translation in German.

Best wishes,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: ***@***.******@***.***>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm


Arm the Ukraine.
Stop all Russian oil and gas imports.
Indict Putin at The Hague<https://www.icj-cij.org/>.
**************************************************************************************************

Von: Johannes Keyser ***@***.***>
Gesendet: Montag, 16. Mai 2022 18:24
An: jasp-stats/jasp-issues ***@***.***>
Cc: Schultheiss, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Response surface analysis (Issue #1705)


@OliverSchultheiss<https://github.com/OliverSchultheiss> sorry to somewhat hijack this thread, but since you are clearly familiar with that terminology: Maybe you would consider to add/check the German translation of that module? (Can be done even before its released.)

All you need is a browser, then you can add/change the translations of the Process Control module at

  *   https://hosted.weblate.org/projects/jasp/jaspprocesscontrol-qml/de/
  *   https://hosted.weblate.org/projects/jasp/jaspprocesscontrol-r/de/

For an overview and an introduction to the translation process, you can read https://jasp-stats.org/translation-guidelines.

Feel free to ask (me) any questions, and of course it's also fine if you don't find the time for that :). (I just thought it's a good opportunity, since that module is still lacking many phrases that I'm not too familiar with (and I also haven't seen the module yet).)

**Comment by JoKeyser** [comment] 2022-05-17 08:47
@OliverSchultheiss , thank you for jumping right in, your (surviving) suggestions were already very helpful and I accepted them. If you create your own account on Weblate (or login via GitHub), you can just save translations directly - I use suggestions only if I'm really unsure.

Regarding your points:

1. Sorry to hear that Weblate dropped some of your suggestions; as mentioned it should be solved if you create/conntect your GitHub account and directly save the translation instead of suggesting one.
2. Indeed, some German translations are hard to come by or may not even exist yet. Sometimes, an acronym relying on English may not make sense to translate at all. I think in such instances it's generally OK skip and think about later. Sometimes JASP itself should change to make it translatable (during development, it's hard to think about how to translate into languages you don't know). It's unlikely that it's perfect the first time, so as long as we improve it, it's a great help.
3. Context is crucial, for sure. Sometimes its better to wait to see the module in action, some strings may well be of this kind in this module. If I can only guess, I also use suggestions, to let the other translators know how far I've thought. I take translation as an iterative process; the module will likely be released as an alpha version, it's impossible to nail it the first time. I try not to let the perfect be the enemy of the good :), and often some translation is better than none. I hope the translation commmunity keeps growing to make it perfect over time.

**Comment by juliuspf** [comment] 2022-06-20 08:48
@OliverSchultheiss can you confirm that the latest release (0.16.3) has what you are looking for? And if that is the case, can you close this issue?

**Comment by juliuspf** [comment] 2022-06-21 12:44
any ideas @JTPetter?

**Comment by JTPetter** [comment] 2022-06-24 23:14
This was mainly written by @filozofXV, so he might be able to answer this. Alternatively, I think @vandenman and @koenderks are also working on extending this, so they might have an idea?

**Comment by OliverSchultheiss** [comment] 2022-10-11 09:18
Can’t check that yet, because our IT guys need to get JASP ready for distribution within the FAU system first. I’ll ask them to do this & then I’ll check & get back.
In any event, thanks for adding the response surface option.

Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: ***@***.******@***.***>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm
**************************************************************************************************

Von: Julius Pfadt ***@***.***>
Gesendet: Montag, 20. Juni 2022 10:49
An: jasp-stats/jasp-issues ***@***.***>
Cc: Schultheiss, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Response surface analysis (Issue #1705)


@OliverSchultheiss<https://github.com/OliverSchultheiss> can you confirm that the latest release (0.16.3) has what you are looking for? And if that is the case, can you close this issue?

**Comment by TarandeepKang** [comment] 2024-01-15 17:12
I would also like to request some clarifications or additional features in this analysis. Alas, I too cannot figure where some commonly used features are hidden.

Below is some illustrative literature !n possibilities:

Humberg, S., Nestler, S., & Back, M. D. (2019). Response Surface Analysis in Personality and Social Psychology: Checklist and Clarifications for the Case of Congruence Hypotheses. Social Psychological and Personality Science, 10(3), 409–419. https://doi.org/10.1177/1948550618757600
Humberg, S., Schönbrodt, F. D., Back, M. D., & Nestler, S. (2022). Cubic response surface analysis: Investigating asymmetric and level-dependent congruence effects with third-order polynomial models. Psychological Methods, 27(4), 622–649. https://doi.org/10.1037/met0000352
Nestler, S., Humberg, S., & Schönbrodt, F. D. (2019). Response surface analysis with multilevel data: Illustration for the case of congruence hypotheses. Psychological Methods, 24(3), 291–308. https://doi.org/10.1037/met0000199
Schönbrodt, F. (2024). Testing fit patterns with polynomial regression models. https://doi.org/10.31219/osf.io/ndggf
Schönbrodt, F. D., Humberg, S., & Nestler, S. (2018). Testing Similarity Effects with Dyadic Response Surface Analysis. European Journal of Personality, 32(6), 627–641. https://doi.org/10.1002/per.2169

**Comment by JTPetter** [comment] 2024-01-16 14:55
Hi @TarandeepKang ,

since this issue was created, the Response Surface Analysis has received a substantial upgrade and at least the basic functionality should be there now. You can find it in the Quality Control Module -> DoE -> Analyze Design. At the top you have a dropdown to switch to Response Surface. Let me know if this has what you're looking for, and if not, what exactly you are missing.

**Comment by OliverSchultheiss** [comment] 2024-01-19 11:09
I just checked the last version of JASP (0.18.3) -- the RSA module in Quality Control does not do what I had hoped it would do; that is, work with actual variables from a data file and do an RSA a la Schönbrodt & Co (see the references I gave above). The way it is set up now seems to be suitable as a simulation. But I don't see how it can be done with the actual data in a file -- there is no way to pick three variables for X, Y and Z and perform and graph an RSA. This may not be the most urgent issue for you guys, and that's ok. But it would be nice to have this capability in JASP one day. (You really opened up a can of worms when you started this project, didn't you? ;) )

**Comment by JTPetter** [comment] 2024-01-19 11:25
@OliverSchultheiss Thanks for taking a look. But also see my response above. It appears to me that you looked into the design functionality, not the analysis functionality. "You can find it in the Quality Control Module -> DoE -> Analyze Design. At the top you have a dropdown to switch to Response Surface.". Let me know if this at least covers the basics of what you are looking for. Happy about any feature requests for the analysis part.

**Comment by OliverSchultheiss** [comment] 2024-01-19 12:44
Got it now! You’re right – that does the trick. Please consider the case closed from my end then. And thank you so much for making this available through JASP! I really appreciate your efforts!

Best wishes,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: ***@***.******@***.***>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

„Die Angst vor den überbordenden Leidenschaften scheint eine manifeste philosophische Krankheit zu sein.“
-- Bernulf Kanitscheider (2011), „Das hedonistische Manifest“ (p. 108)
**************************************************************************************************

Von: JTPetter ***@***.***>
Gesendet: Freitag, 19. Januar 2024 12:25
An: jasp-stats/jasp-issues ***@***.***>
Cc: Schultheiss, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Response surface analysis (Issue #1705)


@OliverSchultheiss<https://github.com/OliverSchultheiss> Thanks for taking a look. But also see my response above. It appears to me that you looked into the design functionality, not the analysis functionality. "You can find it in the Quality Control Module -> DoE -> Analyze Design. At the top you have a dropdown to switch to Response Surface.". Let me know if this at least covers the basics of what you are looking for. Happy about any feature requests for the analysis part.

**Comment by JTPetter** [comment] 2024-01-19 12:55
@OliverSchultheiss Great, glad to hear. Thank you for using JASP! I'm currently working on an upgrade for this part of the module, so if you find any bugs or have ideas for features please feel free to create new issues. I might be able to include them very timely.

**Closed by JTPetter** 2024-01-19 12:55 UTC
Labels: Module: jaspRegression, Feature Request

**Comment by OliverSchultheiss** [comment] 2024-01-19 12:57
Thanks. I’ll be on the lookout and will get back to you if I can come up with suggestions.

Best wishes,
Oliver

**************************************************************************************************
Oliver C. Schultheiss, Dr. phil.
Professor of Psychology
Chair for Experimental Psychology, Motivation, and Affective Neuroscience
Institute of Psychology
Friedrich-Alexander University
Nägelsbachstr. 49 b
91052 Erlangen
Germany
Email: ***@***.******@***.***>
Phone: +49 9131 85-20880
Secretary: +49 9131 85-20879
URL: http://www.psych2.phil.uni-erlangen.de/~oschult/humanlab/index.htm

„Die Angst vor den überbordenden Leidenschaften scheint eine manifeste philosophische Krankheit zu sein.“
-- Bernulf Kanitscheider (2011), „Das hedonistische Manifest“ (p. 108)
**************************************************************************************************

Von: JTPetter ***@***.***>
Gesendet: Freitag, 19. Januar 2024 13:55
An: jasp-stats/jasp-issues ***@***.***>
Cc: Schultheiss, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] Response surface analysis (Issue #1705)


@OliverSchultheiss<https://github.com/OliverSchultheiss> Great, glad to hear. Thank you for using JASP! I'm currently working on an upgrade for this part of the module, so if you find any bugs or have ideas for features please feel free to create new issues. I might be able to include them very timely.

**Comment by Lia-UC** [comment] 2025-04-23 08:14
Hi, I tried to use the Response Surface Method in JASP
I found there was the check list of "show optimal response", however there was no result of the optimization.
If anyone know about this let me know.
Just for suggestion, it is also good if the optimization have some choice like the maximum, minimum, or other target.

**Comment by JTPetter** [comment] 2025-04-23 12:40
@Lia-UC Yes, this was a placeholder that we forgot to remove despite the functionality not being finished yet. But there will be a fully functional response optimizer in the upcoming version 0.20

**Comment by Lia-UC** [comment] 2025-04-23 12:58
Nice. thank you for the information. Happy to hear that.

**Comment by Lia-UC** [comment] 2025-05-08 15:49
I just want to make a design experiment for RSM analysis where my variables are sugars (0-20%) and Agar (0.1-1.5%). 

![Image](https://github.com/user-attachments/assets/8531675b-24c0-4688-9b8b-9465949e02c4)

The results have some minus concentration. Could you tell me what should we do for the minus treatment?
