### ISSUE TITLE
Results disappearing from table

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1281] opened 2021-05-03 18:54 UTC
* JASP version: 0.15 (commit 7b7db7df90612ba3be1e455d1ee0292ed5f74056)
* OS name and version: macOS Big Sur 11.3
* Analysis: Classical Binomial Test
* Bug description: Results disappear from table and remain gone
* Expected behaviour: Results should come back

#### Steps to reproduce:
1. Open the attached dataset titanic_clean.jasp.
2. Click on **Frequencies** > **Classical Binomial Test**.
3. Pull **pclass** and **survived** over to the Variables box; notice how the output table is filled with results.
4. Check the **Confidence interval** checkbox; notice how the output table is emptied.
5. Uncheck the **Confidence interval** checkbox; notice how the output table remains empty.

[titanic_clean.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6417006/titanic_clean.jasp.zip)

https://user-images.githubusercontent.com/5346286/116919231-42530e80-ac51-11eb-9cec-4650e97592c1.mp4

**Comment by TimKDJ** [comment] 2021-05-06 09:59
Thanks for the heads up! I'm fairly confident this is caused by the problems with our state and it should be fixed by https://github.com/jasp-stats/jasp-desktop/pull/4508. If this turns out not to be the case I'll have a closer look.

**Comment by boutinb** [comment] 2021-05-06 10:08
I can confirm this is the case. With my fix, this problem is also fixed.

**Closed** 2021-05-06 10:13 UTC
