### ISSUE TITLE
[Feature Request]: Option for Separate Lines in Raincloud Plots in ANOVA

### ISSUE THREAD

**Issue by zaeemhadi** [jasp-stats/jasp-issues#1818] opened 2022-09-05 13:41 UTC
### Description

Raincloud plots in ANOVAs do not have the option to separate data based on between subject factors. This is similar to "Separate Lines" option in Descriptive plots.

### Purpose

To see patterns of raw data based on between-subject factors.

### Use-case

I have a measure X, which is measured Y times, in Z subgroup of subjects. Raincloud plots in ANOVA can only have the option of the horizontal axis (Y Time) and separate plots (measures X). I would also like to see raw data separated based on subgroup of subjects in the same plot.

### Is your feature request related to a problem?

No
### Describe the solution you would like

As above in Use-case. Subgroups can be separated based on the shapes of points.

### Describe alternatives that you have considered

I can draw separate plots for the subgroups but I wanted to each subgroup on same plot.

**Comment by tomtomme** [comment] 2024-02-20 18:47
Closing since duplicate of https://github.com/jasp-stats/jasp-issues/issues/1757

**Closed by tomtomme** 2024-02-20 18:47 UTC
Labels: Component: Result Plots, Module: jaspAnova, Feature Request
