### ISSUE TITLE
[Bug]: Descriptive analysis with frequency tables error

### ISSUE THREAD

**Issue by matteo88mc** [jasp-stats/jasp-issues#2192] opened 2023-06-14 21:30 UTC
### JASP Version

0.17.2.1

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Descriptive analysis and frequency tables

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

i was doing some descriptive analysis of several variables of my datasets, nothing very difficoult to compute or particular. Adding a new variable to read frequency tables gave me the error. 

This analysis terminated unexpectedly.

Error in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm): Calling var(x) on a factor x is defunct.
  Use something like 'all(duplicated(x)[-1L])' to test for a constant vector.

Stack trace
.descriptivesIntervalPlot(dataset = dataset, options = options, variable = var)

aggregate(y ~ group, data = plotDat, function(x) {
    mu <- mean(x)
    err <- qnorm(0.975) * (sd(x)/sqrt(length(x)))
    c(mean = mu, lower = mu - err, upper = mu + err)
})

aggregate.formula(y ~ group, data = plotDat, function(x) {
    mu <- mean(x)
    err <- qnorm(0.975) * (sd(x)/sqrt(length(x)))
    c(mean = mu, lower = mu - err, upper = mu + err)
})

aggregate.data.frame(lhs, mf[-1], FUN = FUN, ...)

lapply(x, function(e) {
    ans <- lapply(X = unname(split(e, grp)), FUN = FUN, ...)
    if (simplify && length(len <- unique(lengths(ans))) = 1) {
        if (len = 1) {
            cl <- lapply(ans, oldClass)
            cl1 <- cl[[1]]
            ans <- if (!is.null(cl1) && all(vapply(cl, identical, NA, y = cl1)))
                do.call(c, ans)
            else unlist(ans, recursive = FALSE, use.names = FALSE)
        }
        else if (len > 1)
            ans <- matrix(unlist(ans, recursive = FALSE, use.names = FALSE), ncol = len, byrow = TRUE, dimnames = if (!is.null(nms <- names(ans[[1]])))
                list(NULL, nms))
    }
    ans
})

FUN(X[[i]], ...)

lapply(X = unname(split(e, grp)), FUN = FUN, ...)

FUN(X[[i]], ...)

sd(x)

var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm)

### Expected Behaviour

No error and result of the frequency tables. 

### Steps to Reproduce

Adding several column while using descriptive table 

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-02-08 15:52
@matteo88mc 
I tested with jasp 0.18.3 and data that included missings, but could not reproduce. Please reopen, if not fixed on your side with 0.18.3 and if you can share your jasp file by renaming to zip and drag & drop here. Thx!

**Closed by tomtomme** 2024-02-08 15:52 UTC
Labels: Module: jaspDescriptives, OS: macOS Intel, Bug
