### ISSUE TITLE
[Bug]: Equality Constraints in Group Comparisons

### ISSUE THREAD

**Issue by ChristianKandler** [jasp-stats/jasp-issues#2046] opened 2023-03-09 04:55 UTC
### JASP Version

0.17.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

Multi-group model comparisons / Measurement Invariance across groups

### What OS are you seeing the problem on?

Windows 10, Windows 11

### Bug Description

The equality constraint options do not work adequately in the multigroup SEM. 

### Expected Behaviour

If you fix some options (e.g., Residuals or Residual Covariances), then other constraints are done (e.g., constrained latent variance or covariances). Please check! This has been worked properly in the JASP version 0.16.4. 

### Steps to Reproduce

1. Run a lavaan script
2. Check a grouping variable in the multigroup SEM option
3. Run Equality Constraints --> does not equal what should be constrained
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-02-04 20:17
@ChristianKandler 
Can you provide screenshots or a more detailed description? I do not know how to reproduce this.
Also you may try jasp 0.18.3

**Comment by tomtomme** [comment] 2024-02-16 08:32
@ChristianKandler 
This seems to be a duplicate of #2225 - can you confirm?
Needs to be fixed then for sure!

**Comment by ChristianKandler** [comment] 2024-02-16 09:34
Yes, it is the same problem, still not yet fixed.

Cheers,

Christian

 

Von: Thomas Langkamp ***@***.*** 
Gesendet: Freitag, 16. Februar 2024 09:33
An: jasp-stats/jasp-issues ***@***.***>
Cc: ChristianKandler ***@***.***>; Mention ***@***.***>
Betreff: Re: [jasp-stats/jasp-issues] [Bug]: Equality Constraints in Group Comparisons (Issue #2046)

 

@ChristianKandler <https://github.com/ChristianKandler> 
This seems to be a duplicate of #2225 <https://github.com/jasp-stats/jasp-issues/issues/2225>  - can you confirm?
Needs to be fixed then for sure!

**Comment by tomtomme** [comment] 2024-02-16 10:23
Closing then, since duplicate.
Lets discuss in #2225

**Closed by tomtomme** 2024-02-16 10:23 UTC
Labels: Duplicate, Module: jaspSem, Bug: High
