### ISSUE TITLE
Two-way ANOVA 'argument is of length zero'

### ISSUE THREAD

**Issue by data-weed** [jasp-stats/jasp-issues#312] opened 2019-02-20 17:43 UTC
* JASP version: 0.9.2.0
* OS name and version: Windows 10
* Analysis: Two-way ANOVA
* Bug description: I assigned a simple analysis for a class, so all 6 students downloaded and installed JASP in the same week, and they were all working from the same data set. One student is not able to do the analysis (the other 5 completed the assignment successfully). He can do one-way ANOVAs with both of the independent variables, but when he puts them together, he gets the error message "argument is of length zero". I checked that the data loaded correctly, and we can do descriptive or frequency statistics fine. He re-installed JASP, but he still gets the same message. 
Data file: [SCEP data.zip](https://github.com/jasp-stats/jasp-issues/files/2885807/SCEP.data.zip)
Screen shot: [jasperror 2](https://user-images.githubusercontent.com/47828002/53112307-c8149480-34f3-11e9-9d5d-1f0ba2362c59.JPG)

**Comment by TimKDJ** [comment] 2019-02-25 12:22
This error appears to be caused by the interaction of your predictors. If you remove the interaction term from your model and leave only the main terms you will not get an error.
I'd venture a guess that it's caused by the fact that 19 groups (out of 153 in your interaction term) are empty or only have a single observation... However, this would not explain how 5 students were able to analyse this data (assuming they included the interaction).

Perhaps @JohnnyDoorn can shed some light on this (Johnny, the relevant message in R states: `Note: model has aliased coefficients`). The handling of this error definitely requires some attention.

**Comment by data-weed** [comment] 2019-02-25 17:05
Thanks!

Cheryl Vanier, Ph.D.
Institutional Review Board (IRB) Chair
Data & Research Analyst
Office of Institutional Effectiveness
Touro University Nevada
874 American Pacific Drive
Henderson NV 89014
702-777-4784

**Comment by JohnnyDoorn** [comment] 2019-02-26 01:27
Hi Cheryl,
Thanks for contacting us! It seems that one of the factors in the model is aliased with another, which means that all of its explained variance is explained by another predictor. In your case, this is the interaction term. If you were to do a SS type II analysis, this would not be a problem perse:
> Type-II tests are calculated according to the principle of marginality, testing each term after all others, except ignoring the term's higher-order relatives; so-called type-III tests violate marginality, testing each term in the model after all of the others."

In other words, the effect of each term is tested after accounting for all the other effects, including interaction effects, in SS type III. In R, this gives a warning message about the singular fit. JASP still tries to still make the ANOVA table, but in this case there is no Sum of Squares and DF for the "Size" variable, which makes something crash internally. I will update the code so that it will give a more informative error message, or change it so that you cannot run a SS type III on such a design with aliased factors (but a SS type II instead, for instance).

It is still interesting that your other students were able to run the tests - did they perhaps specify a different type of SS, or removed the interaction from the model? 

Kind regards,
Johnny

**Comment by JohnnyDoorn** [comment] 2019-03-26 14:48
This is fixed in [PR #3093](https://github.com/jasp-stats/jasp-desktop/pull/3093)

**Closed by JohnnyDoorn** 2019-03-26 14:48 UTC
