### ISSUE TITLE
[Bug]: reliability error message with outdated version of JASP

### ISSUE THREAD

**Issue by izzy1991** [jasp-stats/jasp-issues#1878] opened 2022-10-30 15:40 UTC
### Is your feature request related to a problem?

I've received an error message whilst trying to conduct a confirmatory analysis with Chrons Alpha. It says this: The following problem(s) occurred while running the analysis: The variance-covariance matrix of the supplied data is not positive-definite. Please check if variables have many missings observations or are collinear The covariance matrix of the data is not invertible

### Describe the solution you would like

I need some guidance on how to remove this error and carry on with my analysis! 

### Describe alternatives that you have considered

I've restarted JASP a few times, tried bringing each variable over individually

**Comment by izzy1991** [comment] 2022-10-30 15:46
I may have a bug - I don't know - the error message keeps changing
<img width="565" alt="Screenshot 2022-10-30 at 15 22 48" src="https://user-images.githubusercontent.com/117028855/198887945-837ba2e5-17b8-4324-a888-50b502419463.png">

**Comment by izzy1991** [comment] 2022-10-30 15:46
another error message: 
<img width="567" alt="Screenshot 2022-10-30 at 15 19 49" src="https://user-images.githubusercontent.com/117028855/198887968-1d0727d9-229d-41c6-9e9b-9ba23df13464.png">

**Comment by juliuspf** [comment] 2022-10-31 10:52
@izzy1991, thanks for the report. Could you try downloading the latest JASP version? The error should be fixed in that one.

**Comment by juliuspf** [comment] 2022-10-31 10:54
I also think that this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1122

**Comment by juliuspf** [comment] 2022-10-31 10:56
If the error with the variance covariance matrix remains, you will need to fix your dataset somehow. IN that case you may upload it here. For now I will close this since it was fixed in later versions of JASP and is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1122

**Closed by juliuspf** 2022-10-31 10:56 UTC
Labels: Module: jaspReliability
