### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ThushaRajendran** [jasp-stats/jasp-issues#2006] opened 2023-02-09 13:49 UTC
### JASP Version

0.17.0

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated measures ANOVA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

Unable to use the repeated measures ANOVA. Moving data columns to repeated measures cells didn't initiate any calculations. I uninstalled and use the prior version, which work perfectly

### Expected Behaviour

The calculations should been executed.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2023-02-09 13:56
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1987
You can still do the analysis if you set explicitly the model terms in the model section.
A new version of JASP should be released tomorrow containing the fix.

**Closed by boutinb** 2023-02-09 13:56 UTC
Labels: duplicate, Module: jaspAnova, OS: macOS Silicon, Bug

**Comment by ThushaRajendran** [comment] 2023-02-09 14:41
Many thanks for the workaround and I look forward to new version with fix coming out :-)
