### ISSUE TITLE
[Bug]: error when plotting path diagram for SEM

### ISSUE THREAD

**Issue by Frederikfi** [jasp-stats/jasp-issues#1806] opened 2022-08-25 08:23 UTC
### JASP Version

0.16.3

### What analysis are you seeing the problem on?

SEM

### What OS are you seeing the problem on?

macOS Big Sur

### Bug Description

when I try to create a path diagram for my SEM, the bug message appears: 

This analysis terminated unexpectedly.

Error in bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

SEM(...)

.semPathPlot(modelContainer, dataset, options, ready)

.semCreatePathPlot(modelContainer[['results']][['object']][[1]], NULL, pcont, options, ready)

.suppressGrDevice(semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE))

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

Creating path diagram

### Steps to Reproduce

1. SEM Model applied
2. Ticked the box for path diagram
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-08-25 09:21
Hi @Frederikfi, thanks for reporting this. It seems this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1629, so I will close this for now. If you think this is a separate issue, feel free to reopen it.

**Closed by juliuspf** 2022-08-25 09:21 UTC
