### ISSUE TITLE
Adding missing factor level

### ISSUE THREAD

**Issue by achroust** [jasp-stats/jasp-issues#1055] opened 2020-10-30 18:52 UTC
I am new to JASP and meta-analysis and hit a snag. When looking at effect of a factor (intervention type, two levels) the coefficient output box only lists one of the factors. I followed the steps to the best of my knowledge from the instructions (https://jasp-stats.org/2017/11/15/meta-analysis-jasp/). I recognize this is not an issue with the software but rather a user issue. If you could direct to me a more appropriate place to post it I will gladly repost. Thank you for listening.

<img width="581" alt="Screen Shot 2020-10-30 at 2 49 38 PM" src="https://user-images.githubusercontent.com/73716466/97745390-2cf10200-1abf-11eb-8753-2115f1275878.png">

**Comment by boutinb** [comment] 2020-11-25 10:28
@EJWagenmakers Did you ask Raoul? Or who do you think could answer this question?

**Comment by EJWagenmakers** [comment] 2020-11-25 14:32
I am increasing the pressure

**Comment by MFreeston** [comment] 2023-03-15 08:27
Is there a way of resolving this please?

**Comment by boutinb** [comment] 2023-03-15 09:26
@sophieberkhout Could you have a look at this issue?

**Comment by sophieberkhout** [comment] 2023-03-15 10:03
Hi all,

Sorry, I did not see that I was assigned to this.

When a categorical variable (factor) is put in, and the model includes the intercept, then the categorical variable is automatically treated as a dummy variable. Therefore, one category is treated as the reference group of which the intercept represents its coefficient. Thus, for the example given here, the estimate of the first intervention group is the intercept, or 0.105.

However, when the intercept is not included in the model, the coefficients for all groups _should_ be shown (and the coefficient for the first (reference) group would be equal to the coefficient of the intercept). Unfortunately, I see that this is not the case in JASP. This is a bug that needs to be fixed.

Though, as the model of the example above includes an intercept, this is not an issue here.

I hope this helps.

Kind regards,
Sophie

**Comment by MFreeston** [comment] 2023-03-15 13:45
Dear Sophie
Thanks for prompte response.
The issue is the fact that the coefficients for all groups are not shown.  I have successfully used earlier versions of JASP on my computer and have had no issue with getting the coefficients for all groups, although people did have the problem on other computers.
[JASP Problem with Factor Levels in Meta-Analyis.docx](https://github.com/jasp-stats/jasp-issues/files/10980439/JASP.Problem.with.Factor.Levels.in.Meta-Analyis.docx)

However, having removed the old version and installed the most recent, I now have this problem.
Please see the attached file.

Thanks for any help you can offer.
With best wishes
Mak

**Comment by sophieberkhout** [comment] 2023-03-15 17:31
Dear Mak,

Thank you for sending us this example. In the first setup, you have included the intercept, therefore only one of the two groups is shown, and the intercept represents the other (reference) group. In the second setup, indeed the coefficient for the first group is missing. As I said, this is a bug, and we are working on it (it seems to have started around four months ago, which I think is why you did not have any problems before).

As a temporary workaround, if you want to use the model without the intercept, you could fit the model with intercept and take the estimate of the intercept for the estimate of the first group, as these are equal. So in your example, 0.491 would be the estimate of the IUS-12 group, and 0.554 the estimate of the second group.

Please let me know if anything is unclear.

Kind regards,
Sophie

**Comment by tomtomme** [comment] 2024-01-11 12:49
This is fixed in 0.18.3

**Closed by tomtomme** 2024-01-11 12:49 UTC
Labels: Module: jaspMetaAnalysis, Bug: Low
