### ISSUE TITLE
RM ANOVA effect size symbols

### ISSUE THREAD

**Issue by BiomechFlo** [jasp-stats/jasp-issues#734] opened 2020-05-06 14:26 UTC
Hi!

* JASP version: 0.12.2
* OS name and version: WIN 10 Enterprise

* Bug description: Symbols for "estimates of effect size" in RM ANOVA look all the same. However in the result section the symbols are represeted in the right way. Please see the attached png File. 

Best Flo

![RM Anova symbols effect size](https://user-images.githubusercontent.com/54370593/81188620-d4302900-8fb5-11ea-8dd4-cabe626ed169.PNG)

**Comment by AlexanderLyNL** [comment] 2020-05-06 14:33
@boutinb could this be another Qt 5.14 vs 5.12 encoding problem? Do we have a testable nightly?

**Comment by boutinb** [comment] 2020-05-07 06:28
It looks for me more a fonts issue. But it's worth trying it.
@BiomechFlo: I cannot reproduce your problem on my PC. But maybe this version http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-142def8358c26741740d95b57c5f46dd848c066b.msi may solve it. Could you try it? This is not an official version (not fully tested), but it contains a fix that may solve your problem.
Thank you.

**Comment by BiomechFlo** [comment] 2020-05-07 09:33
@boutinb  the nightly works as expected. The symbols are back. 
![Nightly symbols effect size](https://user-images.githubusercontent.com/54370593/81278833-84ee0500-9056-11ea-9c88-8f89fe2e7c44.PNG)

**Comment by juliuspf** [comment] 2023-01-16 09:47
@BiomechFlo, sorry for the late reply. But I understand this is fixed in a newer version of JASP. So I will close this, feel free to reopen if your issues remains.

**Closed by juliuspf** 2023-01-16 09:47 UTC
Labels: Module: jaspAnova
