### ISSUE TITLE
[Bug]: Machine Learning-the prediction tables crashed

### ISSUE THREAD

**Issue by vladimirsim** [jasp-stats/jasp-issues#2978] opened 2024-10-19 19:38 UTC
### JASP Version

0.19.1

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Prediction

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The prediction tables did not load. 
![image](https://github.com/user-attachments/assets/2b770678-0781-4bcb-a2c5-dfcd34bb12af)

### Expected Behaviour

The prediction tables should load. 

### Steps to Reproduce

1. Open Machine learning > Prediction
2. Load a trained model based on JASP's Machine learning > Student grades internal data library. The trained model is attached. 
3. Load the features from the trained model.
4. The engine crashes right before the last feature has to be loaded.
...
[p.zip](https://github.com/user-attachments/files/17447081/p.zip)

### Log (if any)

This analysis terminated unexpectedly.

Error in `levels<-`(`*tmp*`, value = as.character(levels)): factor level [2] is duplicated

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mlPredictionsTable(model, dataset, options, jaspResults, ready, position = 2)

.mlPredictionsState(model, dataset, options, jaspResults, ready)

createJaspState(.mlPredictionGetPredictions(model, dataset))

jaspStateR$new(object = object, dependencies = dependencies)

initialize(...)

.mlPredictionGetPredictions(model, dataset)

.mlPredictionGetPredictions.gbm(model, dataset)

gbm:::predict.gbm(model, newdata = dataset, n.trees = model[['n.trees']], type = 'response')

factor(x[, i], levels = object$var.levels[[i]])

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.19.1
Build Branch: lockfiletesting
Build Date: Sep  9 2024 19:00:04 (Netherlands)
Last Commit: 8ac10c9c7aec029fdd695262d7bb4c3742a8ec89

-------- Basic Info --------
Operating System: Windows 10 Version 22H2
Product Version: 10
Kernel Type: winnt
Kernel Version: 10.0.19045
Architecture: x86_64
Install Path: E:/Program Files/JASP
Platfotm Name: windows
System Local: bg_BG

-------- Extra Info --------
Current code page
Active code page: 866
Active code page: 65001

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-11-02 19:47
@vladimirsim 
thx for the report. I can confirm the error with 0.19.1 flatpak. 

@koenderks 
Can you have a look? The error message appears the moment I add the last variable in the list, called "absences". Its the only metric one. But switching it to ordinal does also not help.

**Comment by koenderks** [comment] 2024-11-02 19:57
@tomtomme It should work if you set all ordinal variables to scale like they are in the original dataset (not sure why they are ordinal here?)

**Comment by tomtomme** [comment] 2024-11-03 09:29
I loaded the jasp File from the bib. Those are the scales I get. We had a bug in the past where changed scales we're not saved. Maybe this is it. I will investigate.

**Comment by tomtomme** [comment] 2024-11-03 09:32
@koenderks 
Jasp should indicate that scale is needed, right? But there is No scales Icon in the Box you drop the vars into.

**Comment by koenderks** [comment] 2024-11-03 09:39
The error occurs because the model is trained with these variables set to scale, so the mismatch between the trained variables which were set to scale and the current variables which are set to ordinal creates this issue.  In the next version, you can only enter scale or nominal variables in this box.

**Comment by koenderks** [comment] 2024-11-03 09:55
> I loaded the jasp File from the bib. Those are the scales I get. We had a bug in the past where changed scales we're not saved. Maybe this is it. I will investigate.

If I open this data file from the library in JASP 0.19.1 (Mac) I just get the scale measurement level for these variables

**Comment by tomtomme** [comment] 2024-11-03 17:11
With 0.19.1 or 0.19.2beta flatpak - when I open the csv or the jasp file those variables are set to ordinal. Strange.
What is your setting here?
![grafik](https://github.com/user-attachments/assets/0fbf24e2-076d-4b8a-bb4e-a153357980c5)

**Comment by tomtomme** [comment] 2024-11-03 17:12
> The error occurs because the model is trained with these variables set to scale, so the mismatch between the trained variables which were set to scale and the current variables which are set to ordinal creates this issue. In the next version, you can only enter scale or nominal variables in this box.

Will this be fixed in 0.19.2 or 0.20?

**Closed** 2024-11-03 17:11 UTC
Labels: Module: jaspMachineLearning, Bug: High

**Comment by koenderks** [comment] 2024-11-03 19:37
0.19.2 if [this PR](https://github.com/jasp-stats/jaspMachineLearning/pull/381) is merged
