### ISSUE TITLE
[Bug]: JASP quits when opening .jasp file (most of the time) 

### ISSUE THREAD

**Issue by tvantimmeren** [jasp-stats/jasp-issues#1914] opened 2022-11-23 12:48 UTC
### JASP Version

0.16.4

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

After I open the .jasp file from the finder, JASP attempts to open it and then it crashes: 'JASP quits unexpectedly'. This happens repeatedly. It (sometimes) works if I try to open the file within JASP. 
The file is >45 mb, not sure if that could be an issue? 

### Expected Behaviour

Open the file :)

### Steps to Reproduce

1. Download the file (available from https://osf.io/y3m72)
2. Double click on the file
3. JASP starts loading the data, but then quits unexpectedly

### Log (if any)

[JASP 2022-11-23 13_40_16 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/10075531/JASP.2022-11-23.13_40_16.Desktop.log)
[JASP 2022-11-23 13_40_16 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/10075532/JASP.2022-11-23.13_40_16.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2022-11-23 16:32
Hi @tvantimmeren I can reproduce your problem. I get this error:
`libc++abi: terminating with uncaught exception of type unexpectedEngineReply: Attempt to resume engine #0 made but it isn't paused, initializing or stopped`. I get that only on the released version, not or 'in development' version. I don't get the error either if I remove some analyses. The JASP file is quite big, so apparently it has something to do with the intialization of JASP when loading in the same time a big JASP file.
@JorisGoosen I can see this error message in the code, which is generated by an assert, but if I have a look at the code I cannot see how these asserts can be triggered.... but maybe you have changed the code since the last released version, because this error does not occur in the development version.

**Comment by JorisGoosen** [comment] 2022-11-23 19:52
Aah, yeah it does indeed crash when double-clicking in 0.16.4...

@boutinb I definitely changed the code since last release though, quite rigorously even.
Which means that I solved this bug already right? ^^

**Comment by boutinb** [comment] 2022-11-24 09:20
OK, so @tvantimmeren this problem is solved. You can test it in our development version (which is not at all a tested version!) here: https://static.jasp-stats.org/Nightlies/ 
A new JASP official version (0.17) should be released in January and will contain this fix. For the time being, if you use the 0.16.4 version, you have to start JASP first, and afterwards load the JASP file.

**Closed by boutinb** 2022-11-24 09:20 UTC
Labels: OS: macOS Silicon

**Comment by tvantimmeren** [comment] 2022-11-24 09:24
Hi Bruno and Joris, thanks a lot. With the workaround it's not a problem
for me, but it might be for people who download the file from osf.. Glad
it's fixed in the next version!
