### ISSUE TITLE
Multinomial test - calculation chi squared differs with variable's levels' label/name

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#740] opened 2020-05-12 15:34 UTC
* JASP version: 0.12.2
 Windows10
* OS name and version:
* Analysis: Multinomial (chi squared GOF)
* Bug description: Analysing observed and expected counts of blood types (A+, A-, B+, etc.) The calculation of chi squared differs with how I label the bloodtypes (by number: 1, 2, ..., 8; by abbreviation: A+, A-, ..., O-; by name: Apos, Aneg, ..., Oneg). As is apparent from the Descriptives table, columns with observed and predicted counts do not align correctly.
* Expected behaviour: No matter how levels of a nominal variable are labeled, calculated statistics should not differ.

[Bloodtype2020.zip](https://github.com/jasp-stats/jasp-issues/files/4616567/Bloodtype2020.zip)

#### Steps to reproduce:
1. Go to 'Frequencies'
2. Click on 'Multinomial test'

**Comment by Kucharssim** [comment] 2020-05-13 10:12
Hello @PeterKlaren,

thank you for this report and reproducible example!

The counts get mixed up because the levels in variables `Nr`, `BG`, and `Blood type` are ordered differently. If you click on the variable name and order the levels correctly, it will return the correct result. Binding the results to the order of the levels is indeed undesired behavior and needs to be fixed.

**Comment by tomtomme** [comment] 2024-01-05 12:29
@PeterKlaren 
I tested this with 0.18.2 and this seems fixed on my end. If you cannot confirm, feel free to reopen!

**Closed by tomtomme** 2024-01-05 12:29 UTC
Labels: Module: jaspFrequencies
