### ISSUE TITLE
[Bug]: The engine crashed while trying to run this analysis... I want to edit my graphs (Adding axis description) and when doing so the before mentioned bug occures. Afterwards neither the analysis, nor the editing of the graph works. How can this be fixed?

### ISSUE THREAD

**Issue by happyfeliz1** [jasp-stats/jasp-issues#2186] opened 2023-06-08 18:22 UTC
### JASP Version

0.17.2

### JASP Module

ANOVA, Descriptives, T-Tests

### What analysis are you seeing the problem on?

Editing Images

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The engine crashed while trying to run this analysis... I want to edit my graphs (Adding axis description) and when doing so the before mentioned bug occures. Afterwards neither the analysis, nor the editing of the graph works. How can this be fixed?
![244372593-448d07a8-8b15-481a-bf8d-fe2c0d2c5548](https://github.com/jasp-stats/jasp-issues/assets/135974790/9377b040-c51d-4a28-b6f8-9f2564485986)
[Thriving_Scores_best_data_27_11_ohne_mean_imputation.zip](https://github.com/jasp-stats/jasp-issues/files/11691810/Thriving_Scores_best_data_27_11_ohne_mean_imputation.zip)

### Expected Behaviour

A description of the y axis of a graph should be added

### Steps to Reproduce

1.Open Results
2.Click on the arrow to edit Image
3.Edit the graph y-axis
4. fill in: "thriving" in title
5. press Ok
6. Bug occurs
...
![244373056-67343b6b-4aee-4761-b223-fe01eba91865](https://github.com/jasp-stats/jasp-issues/assets/135974790/396ac7dd-c0a8-4bee-a5b8-141b0c8f10ca)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment] 2023-06-09 06:59
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/2185

**Closed by RensDofferhoff** 2023-06-09 06:59 UTC
Labels: Module: jaspDescriptives, Module: jaspTTests, Module: jaspAnova, OS: Windows 10, Bug
