### ISSUE TITLE
Bug: Bayesian Correlation Table: JASP does not show flagged supported correlations

### ISSUE THREAD

**Issue by glaswasser** [jasp-stats/jasp-issues#1348] opened 2021-07-02 11:05 UTC
* JASP version: 0.14.1

* OS name and version: mac os catalina 10.15.7 (19H524)
* Analysis: Bayesian Correlation
* Bug description: when copying latex code for the table, flagged supported correlations are commented out and not marked in table
* Expected behaviour: flagged supported correlations should be marked both in the table and explained below

#### Steps to reproduce:
(Take any dataset, it does not matter)
1. Go to Regression
2. Click on Bayesian Correlation
3. put some variables in (should have a supported correlation)
4. click "flag supported correlations" in additional options
5. click on the bayesian correlation table to "Copy LaTex"
6. paste inside e.g. R markdown or some latex editor
7. you already see that the flagged correlation explanations are commented out by "%"s
8. remove commenting out
3. knit
4. See error: flagged correlations are not marked by stars in table (and badly formatted below the table, which is a minor problem)

And a second error:
1. Do the steps 1-4 from above
2. remove "Report Bayes Factors" in the additional options
3. See that there are no stars inside the table anymore (not inside the JASP output, nor inside LaTex)
4. be mad at JASP for not flagging the correlations
5. write bug report

Thanks for having a look :)

**Comment by akashrajkn** [comment] 2021-07-08 21:42
Thank you for reporting the issue.

**Regarding the first issue** 

This is the output I get after uncommenting the footnotes (for reference):
![aaa_table_1](https://user-images.githubusercontent.com/6959308/124993309-7e855f80-e044-11eb-90c2-f9f66dc3d9a1.png)

I can fix it the output as follows:
![aaa_table_2](https://user-images.githubusercontent.com/6959308/124993379-95c44d00-e044-11eb-9a1b-144762ddd9e3.png)
However, because of the package we are using to display latex tables (booktabs), a very long footnote will result in a wide table
![aaa_table_3](https://user-images.githubusercontent.com/6959308/124993526-c3a99180-e044-11eb-976c-b3bd7bc286b6.png)

Hence I initially commented the footnotes so that the user can choose to format it as they please. I will check if there is a better way of generating the latex code.

**Regarding the second issue**

I could not reproduce it on the latest version in Ubuntu. Could you share the jasp file so I can debug it?

**Comment by glaswasser** [comment] 2021-07-09 07:38
For the first issue I think you missed my point. The error is in the 10th point: Not only in the legend, the flagged correlations are commented out, but IN THE TABLE, the correlations are NOT FLAGGED (as written in "10. See error: flagged correlations are not marked by stars **in table** (and badly formatted below the table, _which is a minor problem_)". There are no stars INSIDE THE TABLE even when correlations are strong / to be flagged. This is a problem in the LaTex Code that is being generated.

Stars:
![Bildschirmfoto 2021-07-09 um 09 29 27](https://user-images.githubusercontent.com/32619620/125041309-e4033b80-e098-11eb-856f-29824b5639c0.png)
no stars:
![Bildschirmfoto 2021-07-09 um 09 36 57](https://user-images.githubusercontent.com/32619620/125041662-4a885980-e099-11eb-9a70-fd7b10f2d63d.png)




For the second issue, you just have to remove "report bayes factors" IF YOU HAVE A FLAGGED CORRELATION INSIDE THE TABLE.

stars:
![Bildschirmfoto 2021-07-09 um 09 29 27](https://user-images.githubusercontent.com/32619620/125041235-d0f06b80-e098-11eb-9018-f48526c1910b.png)
no stars:
![Bildschirmfoto 2021-07-09 um 09 33 30](https://user-images.githubusercontent.com/32619620/125041152-bc13d800-e098-11eb-9a86-1e0922f9409f.png)
 
Please use some (in the bayesian way) "significant" correlated variables and try again, and you might see what I mean.

**Comment by akashrajkn** [comment] 2021-07-09 08:26
@glaswasser I see the issue now. Thank you for clarifying it - I'll take a look at it

**Comment by tomtomme** [comment] 2024-02-01 22:50
still valid for 0.18.3

**Comment by tomtomme** [comment] 2024-05-24 19:47
still valid for latest 0.19beta

**Comment by tomtomme** [comment] 2024-05-25 11:24
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/2259

**Closed by tomtomme** 2024-05-25 11:24 UTC
Labels: Module: jaspRegression, Bug: Medium
