### ISSUE TITLE
No label-edit option in Debian

### ISSUE THREAD

**Issue by oSkF** [jasp-stats/jasp-issues#1126] opened 2021-01-14 15:53 UTC
* JASP version: 0.14.1

* OS name and version: Debian 10 
* Analysis: when I try to change the label values of a column, clicking over the heading, doesn't spread the option of changing the values. Only a white "table" is spread and no option to change is shown. In Windows, this doesn't happen. I used a CSV file to start my data analysis.
* Bug description: changing labels of data is not possible. 
* Expected behaviour: spread an option of changing labels, when clicking over the heading of a column.

#### Steps to reproduce:
1. Open any database in the app (e.g. CSV file)
2. Click on the heading of any column. A white table will be spread. 
3. See error: no option to change the label.

**Comment by boutinb** [comment] 2021-01-15 10:06
This error is known, and an extra minor version should be released soon that fixes it.

**Comment by JorisGoosen** [comment] 2021-01-15 12:58
Duplicate of #1109

**Closed by JorisGoosen** 2021-01-15 12:58 UTC
