### ISSUE TITLE
Save and reuse filters

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#333] opened 2019-03-26 12:07 UTC
* Enhancement: Create and save multiple (compound) filters for reuse in different datasets.
* Purpose: Reuse filters.

Building (compound) filters takes some time, and you would also want to use multiple filters serving different functions in one JASP session/instance. Would be nice to save filters for future use.

**Describe the solution you'd like**
An option to save a filter and to open and reuse it in the same or different JASP session.

**Comment by JorisGoosen** [comment] 2019-03-27 10:36
Yeah we've thought about this as well. 
It could be nice to just edit a few of them and or be able to drag/copy them. And select one or more that you would like to use. Or something.

**Comment by tomtomme** [comment] 2023-12-25 17:19
can be closed, since duplicate of 
https://github.com/jasp-stats/jasp-issues/issues/635
https://github.com/jasp-stats/jasp-issues/issues/385
https://github.com/jasp-stats/jasp-issues/issues/1330

**Closed** 2024-01-03 12:34 UTC
Labels: Feature Request
