### ISSUE TITLE
[Bug]: Path Diagram in the SEM Module Failing

### ISSUE THREAD

**Issue by khh200** [jasp-stats/jasp-issues#1745] opened 2022-06-15 17:16 UTC
### JASP Version

0.16.2

### What analysis are you seeing the problem on?

Confirmatory Factor Analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When conducting a CFA with WLSMV, the path diagram generates an error and will not load the image. I have attached the compressed JASP file.

This analysis terminated unexpectedly.

Error in bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

SEM(...)

.semPathPlot(modelContainer, dataset, options, ready)

.semCreatePathPlot(modelContainer[['results']][['object']][[1]], NULL, pcont, options, ready)

.suppressGrDevice(semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE))

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE)

To receive assistance with this problem
[JASP path failure.zip](https://github.com/jasp-stats/jasp-issues/files/8911605/JASP.path.failure.zip)
, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

The path diagram should have appeared with relevant indicators and factors labeled.

### Steps to Reproduce

1. Go to SEM module
2. Enter Lavaan Syntax as seen in screenshot
3. Click path diagram
...
![path failure](https://user-images.githubusercontent.com/78570474/173886694-060c0ca4-4e80-4567-ae4a-ceb0d4eb630b.PNG)

### Log (if any)

This analysis terminated unexpectedly.

Error in bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

SEM(...)

.semPathPlot(modelContainer, dataset, options, ready)

.semCreatePathPlot(modelContainer[['results']][['object']][[1]], NULL, pcont, options, ready)

.suppressGrDevice(semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE))

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment] 2022-06-20 07:26
Duplicate of https://github.com/jasp-stats/jasp-issues/issues/1629

**Closed by Kucharssim** 2022-06-20 07:26 UTC
Labels: duplicate
