### ISSUE TITLE
[Feature Request]:  Move (or add) Dunn test non parametric ANOVA

### ISSUE THREAD

**Issue by vdsmagt** [jasp-stats/jasp-issues#1550] opened 2021-12-15 16:10 UTC
### Description

The postdoc test for Krusal Wallis appears to be missing

### Purpose

the Kruskal Wallis test needs a posthoc

### Use-case

This postdoc is available but at the wrong place

### Is your feature request related to a problem?

It is an interface problem (it is much less intuitive now)

### Describe the solution you would like

Move Dunn test (or also add) to non-parametrics Anova

### Describe alternatives that you have considered

not really applicable

### Additional context

The Dunn test is (if I recall correctly) the posthoc test of choice after doing a Kruskal-Wallis nonparametric ANOVA. However, when one chooses KW under non-parametric, there is no option to choose this test. 
So it seems this test is not provided. However it appears that it is but in the wrong place, under the 'posthoc tests' menu for the regular (parametric) ANOVA.

This is irregular behaviour as under the Repeated measures Friedman (nonparametric) test you do have the option of choosing Conover's posthoc test. I would like to see the same option under Kuskal Wallis.

(for me I now know where to look but it is far from intuitive)

**Comment by tomtomme** [comment] 2024-01-04 18:30
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/383

**Closed by tomtomme** 2024-01-04 18:30 UTC
Labels: Module: jaspAnova, Feature Request
