### ISSUE TITLE
Error in Means Calculated in Bayesian Paired Samples t-test

### ISSUE THREAD

**Issue by awismer7** [jasp-stats/jasp-issues#585] opened 2020-01-10 18:24 UTC
![image](https://user-images.githubusercontent.com/17439457/72176243-9de5f280-33a3-11ea-87c0-49c193d7bed7.png)

![image](https://user-images.githubusercontent.com/17439457/72176393-ddacda00-33a3-11ea-8cb8-b8ed7b219377.png)

![image](https://user-images.githubusercontent.com/17439457/72176412-e6051500-33a3-11ea-87d2-33ebec9d22fd.png)

![image](https://user-images.githubusercontent.com/17439457/72176458-fddc9900-33a3-11ea-9cde-f5c0a8f64e95.png)

![image](https://user-images.githubusercontent.com/17439457/72176475-0a60f180-33a4-11ea-9ea9-d1b4fb39308f.png)

The means calculated from a paired samples t-test and Bayesian paired samples t-test do not match. The values from the regular t-test are correct; the values from the Bayesian ones are incorrect (while the SD and SE are the same). Any idea why this is happening? It is happening for all my variables. I am running JASP 0.11.1.0 on Windows 10.

**Comment by EJWagenmakers** [comment] 2020-01-10 22:26
@JohnnyDoorn @AlexanderLyNL ?
Also, if this is indeed a bug (it's late and I didn"t check) we should also discuss how our safeguards did not detect this...

**Comment by vandenman** [comment] 2020-01-11 08:47
This looks like a duplicate of https://github.com/jasp-stats/jasp-issues/issues/529 . Factors (ordinal variables) were incorrectly translated into numeric and therefore the means were incorrect. This was fixed in https://github.com/jasp-stats/jasp-desktop/pull/3633 and the latest nightly builds should produce the correct means.

**Comment by FransMeerhoff** [comment] 2020-01-15 10:47
Hello @awismer7 

We've added a nightly development zipped version of JASP on :

http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-2388bfe76126eb88d8a6f74cc406f31d6f1eff9e.zip
 
You can use this version by unzipping the downloaded .zip file and unpack this file.
Double click in JASP/JASP on the JASP.exe (green JASP logo).
Could you confirm that this problem is solved on this version of JASP?

Kind regards 
Frans Meerhoff

**Comment by FransMeerhoff** [comment] 2020-01-15 13:35
Hi @awismer7 

Sorry but the .zip file mentioned before has been transported to:

http://static.jasp-stats.org/Nightlies/JASP-nightly-2388bfe76126eb88d8a6f74cc406f31d6f1eff9e.zip

Kind regards
Frans Meerhoff

**Comment by Luca1717** [comment] 2020-01-17 18:25
Hey all!

I had a similar problem but with the results of an independent samples t-test and the baysian version. The SD and SE were exactly the same but the calculated means were higher for the baysian t-test. I thought I am just going to add this here instead of making a new thread for that.  I am going to attach a screenshot of the different results below. If you need any more information about the problem please tell me!

Thanks and kind regards
Luca
![t-tests](https://user-images.githubusercontent.com/60013856/72636310-1548f280-395f-11ea-84c8-1deb8f201fe5.PNG)

**Comment by awismer7** [comment] 2020-01-17 19:46
Hi Frans,

Yes the problem appears solved on this version of JASP. The means are now
calculated correctly under the Bayesian test despite whether the variables
are defined as ordinal or scale. Thank you very much for your attention to
this issue.

Best,
Andrew

**Comment by awismer7** [comment] 2020-01-17 19:46
Yes the new version of JASP you attached fixes the issue. Thank you!

**Closed** 2020-01-18 10:22 UTC
