### ISSUE TITLE
[Feature Request]: i suggest to add out of bag predictions in random forest classfication in machine learning in jasp software

### ISSUE THREAD

**Issue by medoteto** [jasp-stats/jasp-issues#2903] opened 2024-09-08 23:21 UTC
### Description

i suggest to add out of bag predictions in random forest classfication in machine learning in jasp software

**Comment by tomtomme** [comment] 2024-09-09 07:00
duplicate of https://github.com/jasp-stats/jasp-issues/issues/2894

**Closed by tomtomme** 2024-09-09 07:00 UTC
Labels: Feature Request
