### ISSUE TITLE
Bug in "Descriptives Plots" function after ANCOVA error ("aliased coefficients")

### ISSUE THREAD

**Issue by FelixScholkmann** [jasp-stats/jasp-issues#527] opened 2019-10-21 15:19 UTC
* JASP version: 0.11.1.0
* OS name and version: Windows 10
* Analysis: Correlation Matrix and ANCOVA
* Bug description: 
When performing an ANCOVA analysis, sometimes the error message "**there are aliased coefficients in the model**" occurs (indicating, as far as I understand, singularities in the regression matrix). It can be fixed the removing variables from the "Fixed Factors" or "Covariates" field(s).
However, then creating then a scatter plot via "Descriptives Plots" and comparing the plots those created via "Correlation Matrix" one can see that data points are _missing_ in the ANCOVA plot:

![grafik](https://user-images.githubusercontent.com/25327628/67217025-6a3ea080-f424-11e9-99f5-1622d133a7af.png)

This is an error. Data are clearly missing in the ANCOVA scatter plot.
Also I fear that the results of the ANCOVA are not correct when the error message appears and after solving the problem by removing variables from the input fields. 
When closing JASP and performing the ANOVA analysis again, and taking care not to trigger the error message, both scatter plots are the same. The appearance of the ANCOVA error message will also affect all the plots in the subsequent JASP session and analysis (when JASP is not closed after the message appeared).

* Expected behaviour: Both scatter plots should be the same. After the error message in the ANCOVA appeared and the used resolved it be removing variables from the input field, the scatter plot should be displayed correctly (and also the analysis should be conducted correctly).

* Steps to reproduce: 
1. Load a data set with many variables (also with some that are highly linearly correlated)
2. Perform a correlation analysis with the two parameters x and y (Correlation Matrix ->click on "Correlation Matrix" in the field "Plots"
3. Load the data into ANCOVA (x as "Dependent Variable", y and some other parameters (z, ...) in "Covariates". Load all data until the error message "there are aliased coefficients in the model" appears
4. Go to "Descriptives Plots". Select "y" to be displayed at "Horizontal Axis"
5. Compare both scatter plots (they are different, but should be the same; data are missing in the ANCOVA scatter plot)

___
Update / PS: I observed now the error with the plots also when performing multiple ANCOVA sessions after another; at some times, the error with the plot appears. Data are missing in the plot. All plots generated after the first "glitch" happened are then affected. Quite worrying.

**Comment by tomtomme** [comment] 2024-01-01 19:32
@FelixScholkmann 
I could not recreate this issue in JASP 0.18.1. I tried 2 different sets of data.
Could you provide the data to reproduce this or report if this is fixed?

**Comment by tomtomme** [comment] 2024-01-01 19:36
This may be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/536

**Closed** 2024-02-12 14:03 UTC
Labels: waiting for requester, Module: jaspRegression, Module: jaspAnova
