### ISSUE TITLE
[Bug]: unexpected error in Process Capability Study of jaspProcessControl

### ISSUE THREAD

**Issue by DJ3514** [jasp-stats/jasp-issues#1817] opened 2022-09-02 14:22 UTC
### JASP Version

0.16

### JASP Module

jaspNetwork

### What OS are you seeing the problem on?

windows 7

### Bug Description

IMPOSSIBLE TO SHOW UP THE RESULTS. I NEED TO FIX IT ASAP

### Expected Behaviour

[](url)
![image](https://user-images.githubusercontent.com/112708600/188160307-586993fe-beca-4704-a27a-a179a3250d30.png)
![Capture](https://user-images.githubusercontent.com/112708600/188161500-9468c934-1ebf-4921-8030-2d067a83658c.PNG)

### Steps to Reproduce

1. 
2. 
3. 
...
![Capture](https://user-images.githubusercontent.com/112708600/188169870-52fd6a71-a10b-42a2-b9bd-198674c80df9.PNG)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment] 2022-09-02 16:01
Hi @DJ3514 thank you for your report.

is that a jaspProcessControl but not the jaspNetwork module right? it seems you are using a old unrelease version of JASP(0.16 and 'data editor),  It is not a good choice use a development version for production. you can download a latest release version (0.16.3) on https://jasp-stats.org/download/
I remember there was a similar problem may fixed (https://github.com/jasp-stats/jasp-issues/issues/1670)

cheers

**Comment by shun2wang** [comment] 2022-09-07 10:10
close as a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1670 , if you think it is different, please confirm as above and reopen it

**Closed by shun2wang** 2022-09-07 10:10 UTC
Labels: waiting for requester, Module: jaspProcessControl
