### ISSUE TITLE
[Bug]: Error in Wm.all %*% Delta.all %*% E.inv: requires numeric/complex matrix/vector arguments

### ISSUE THREAD

**Issue by mishiando** [jasp-stats/jasp-issues#2066] opened 2023-03-22 09:11 UTC
### JASP Version

0.17.1

### JASP Module

Factor

### What analysis are you seeing the problem on?

second-order CFA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Error in Wm.all %*% Delta.all %*% E.inv: requires numeric/complex matrix/vector arguments

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableMain(jaspResults, options, cfaResult)

lavaan::fitMeasures(cfaResult[['lav']])

lavaan::fitMeasures(cfaResult[['lav']])

lav_fit_measures(object = object, fit.measures = fit.measures, baseline.model = baseline.model, fm.args = fm.args, output = output)

lav_fit_cfi_lavobject(lavobject = object, fit.measures = fit.measures, baseline.model = baseline.model, standard.test = standard.test, scaled.test = scaled.test)

lav_fit_fiml_corrected(lavobject, version = version)

### Expected Behaviour

second-order CFA

### Steps to Reproduce

Error in Wm.all %*% Delta.all %*% E.inv: requires numeric/complex matrix/vector arguments

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableMain(jaspResults, options, cfaResult)

lavaan::fitMeasures(cfaResult[['lav']])

lavaan::fitMeasures(cfaResult[['lav']])

lav_fit_measures(object = object, fit.measures = fit.measures, baseline.model = baseline.model, fm.args = fm.args, output = output)

lav_fit_cfi_lavobject(lavobject = object, fit.measures = fit.measures, baseline.model = baseline.model, standard.test = standard.test, scaled.test = scaled.test)

lav_fit_fiml_corrected(lavobject, version = version)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2023-03-22 14:15
Thanks for creating the issue, I think this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2049. I will look into it.

**Closed by juliuspfadt** 2023-03-22 14:15 UTC
Labels: Module: jaspFactor, OS: Windows 11, Bug
