### ISSUE TITLE
[Feature Request]:  Fix faulty QQ plot when there multiple groups.

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-issues#2455] opened 2023-12-04 02:37 UTC
### Description

In an ANOVA, the QQ plot does not appear to properly account for unequal variances across two normally distributed sets of scores. Specifically, the QQ plot suggests non-normality despite each distribution being normal. This problem goes away if the plot is constructed from Z scores, standardized separately for each group. Consequently, I suggest that JASP use Z scores in all situations where normality is assessed.

### Additional context

[Faulty QQ normality plot when there multiple groups.zip](https://github.com/jasp-stats/jasp-issues/files/13541364/Faulty.QQ.normality.plot.when.there.multiple.groups.zip)

**Comment by EJWagenmakers** [comment] 2023-12-04 07:57
OK, so you have a DV that is normally distributed, but has a much larger variance for group=2 than for group=1. So if the DV is analyzed across the groups, or analyzed under the (incorrect) assumption that the variances are equal, then the data will appear to violate normality (because it is really a mixture of two normals). Now if the ANOVA is used that assumes equal variances, then I believe the joint analysis may be correct. However,  when the Welch correction is applied, we assume unequal variances and it seems to me that the QQ plot ought to reflect that the data are approximately normal. Maybe @JohnnyDoorn  can take a look.

**Comment by R180** [comment] 2023-12-04 12:13
Yes that's right. Welch's t (and Welch's ANOVA) assume normality but not equal variance. Altering the normality assessments to be conducted on per-group Z scores, would fix the situation for Welch's but would not hurt things for Student's t (or for non-Welch's ANOVA).

**Comment by EJWagenmakers** [comment] 2023-12-07 13:18
But if you conduct the normality tests on per-group Z scores you are effectively assuming that the variances may differ. The assumption of the standard ANOVA is that they do not differ. So the current QQ plot is helpful, because it signals that there is model misfit. This misfit may then encourage the Welch correction. So my preferred fix is that when the Welch correction is applied, the QQ plot ought to reflect those residuals -- somehow it seems it does not do this at the moment. So this is something we'll look into.

**Comment by EJWagenmakers** [comment] 2023-12-07 13:19
@JohnnyDoorn : something on the ANOVA to-do list for January :-)

**Comment by JohnnyDoorn** [comment] 2024-02-08 12:04
Hi @R180,

Sorry, just now getting to this. I think this is a feature rather than a bug. The Q-Q plot of the residuals is not just for normality, but can also indicate problems with different variances (or, in regression terms, heteroscedasticity) - where the error variances differ for different levels of your predictor variable. While the Welch correction does account for differences in variances, they only differ from the regular analyses in terms of the degrees of freedom when the sample sizes are equal across groups. Such a small difference in df (as you can see in your indep t-test table) will typically not yield qualitatively different results (perhaps for very small n, or big differences in group sizes), and so I would say this correction does not magically take away all the systematic bias in your model (i.e., heteroscedasticity) that arises from different standard deviations.

Kind regards,
Johnny

**Comment by tomtomme** [comment] 2024-03-01 21:43
@JohnnyDoorn 
is this a wontfix?

**Closed** 2024-04-03 09:41 UTC
Labels: Component: Result Plots, Waiting for requester, Module: jaspAnova
