### ISSUE TITLE
Problems with opening the JASP

### ISSUE THREAD

**Issue by wanyue-li** [jasp-stats/jasp-issues#569] opened 2019-12-18 10:57 UTC
Everytime I open the JASP, it popups an information box says that "Fatal error: unable to open the base package". 

Has anybody ever experienced this? Could you please tell me how to fix this?

Thanks a lot!

**Comment by akashrajkn** [comment] 2019-12-18 23:43
@wanyue-li thanks for reporting this. Which version of JASP are you using? And on which Operating system?

**Comment by wanyue-li** [comment] 2019-12-19 00:56
> @wanyue-li thanks for reporting this. Which version of JASP are you using? And on which Operating system?

Hi, it's the newest version of JASP(0.11.1.0). My operating system is 64-bit Windows.

**Comment by boutinb** [comment] 2020-01-03 15:48
Can you try to start JASP from the command line:
. Open a command prompt
. type cd "c:\Program Files\JASP" to go the installed JASP folder
. then type .\JASP to start JASP
Can you give me the output in the command prompt?

**Comment by Statham-jasper** [comment] 2020-01-26 16:28
Hi. Facing same error (also 0.11.1.0 with 64x). First few times I faced the error reinstalling worked, after a few times using software it wouldn't open again. I was using one of the 0.9 versions without issues last year, but now this is also giving the same issue. Neither will now open even after a fresh install. Following the above command prompt I get the following: 

Z:\>cd "c:\Program Files\JASP"

Z:\>.\JASP
'.\JASP' is not recognized as an internal or external command,
operable program or batch file.

The Jasp.exe is in the folder indicated above, just won't open.

**Comment by FransMeerhoff** [comment] 2020-01-28 09:43
Hi @wanyue-li 

We are still not able to reproduce your problem. We still like to see the results from the request that boutinb asked you to do. Could you check that again, or let us know if you have any problems with that?

@Statham-jasper 
We only do such a  request if we need  some more error message info from the command  line if any problem with JASP occurs.

Kind regards
Frans Meerhoff

**Comment by boutinb** [comment] 2020-01-30 10:31
Hi @Statham-jasper 
You have apparently some problem during the installation of JASP. Could you try to download the ZIP version (in the Download JASP page, there is a link to download the 'pre-installed' Windows version)?

**Comment by FransMeerhoff** [comment] 2020-02-19 08:45
HI @Statham-jasper 

We are in the testing phase of releasing JASP 0.12
Please wait till this version is released and check your problem on this version. Reopen it if the problem still occurs.
Because we are not able to reproduce this issue we close this issue for now.

Kind regards
Frans Meerhoff

**Closed by FransMeerhoff** 2020-02-19 08:45 UTC
Labels: Waiting for requester
