### ISSUE TITLE
[Feature Request]: Group descriptives in non-parametric t-tests

### ISSUE THREAD

**Issue by lbridgeman82** [jasp-stats/jasp-issues#1907] opened 2022-11-16 19:51 UTC
### Description

Group descriptives in non-parametric t-tests

### Purpose

Being able to see other descriptive and not just the mean and SD when running t-tests

### Is your feature request related to a problem?

n/a

### Is your feature request related to a JASP module?

T-Tests

### Describe the solution you would like

When running a non parametric t-test (Mann-Whitney or Wilcoxon) being able to select the median and IQR for example in the descriptives in the test itself instead of defaulting to the mean and SD

### Additional context

Having this option would make it easier to see all the information for the test in one place rather than having to go back and run this in from the descriptives drop down.

**Comment by tomtomme** [comment] 2024-01-01 20:07
This is also a duplicate of https://github.com/jasp-stats/jasp-issues/issues/383
and can be closed.

**Closed** 2024-01-03 13:05 UTC
Labels: Module: jaspTTests, Feature Request
