### ISSUE TITLE
Feature request: Adjusting plot's XY axes limits and more

### ISSUE THREAD

**Issue by piotrdzwiniel** [jasp-stats/jasp-issues#833] opened 2020-06-30 14:33 UTC
Is it just me, or it's impossible to adjust plot's XY axes limits at the moment? If so, can you add such option? Without it generated plots are a little bit useless in the context of presentations, publications, reports etc. It would be also great to tinker with other parameters as well, as for example colour, linewidth, linestyle, markersize etc.

**Comment by vandenman** [comment] 2020-06-30 14:44
This looks like a duplicate of #63 and/ or #78. We're working on this but it's not possible to do this yet. As a temporary workaround, the upcoming version allows you to save plots as *.pttx. If you open the file you should be able to adjust things like size and colors. Unfortunately, this workaround does not allow you to adjust a plot's axes limits though.

**Closed** 2022-09-29 22:31 UTC
