### ISSUE TITLE
[Bug]: Graphics Not Loading

### ISSUE THREAD

**Issue by diego3498** [jasp-stats/jasp-issues#1863] opened 2022-10-16 20:33 UTC
### JASP Version

0.16.4

### JASP Module

jaspDescriptives

### What OS are you seeing the problem on?

Windows 10

### Bug Description

No graphics load in the "Results" window. It displays a message reading "Waiting for initialization of module: Descriptives" and loads but never puts out a table or graph.

![Desktop Screenshot 2022 10 15 - 17 29 12 32](https://user-images.githubusercontent.com/115952801/196056732-8f20ae00-9a30-4931-9ad8-f3becfa6bb3c.png)

### Expected Behaviour

The expected output should be a simple descriptive table of the data. 
![maxresdefault](https://user-images.githubusercontent.com/115952801/196056824-98406f4d-6d44-4385-b2f1-31d0adccf348.jpg)

### Steps to Reproduce

No steps necessary. Occurs any and all times even after reinstalling multiple times.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-10-17 08:10
thanks for reporting @diego3498, this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1862, so I will close it, and you can just subscribe to the other issue.

**Closed by juliuspf** 2022-10-17 08:10 UTC
