### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by WrldTraveler** [jasp-stats/jasp-issues#2159] opened 2023-05-23 18:41 UTC
### Description

Improve the walk through manual

### Purpose

Support new stat learners

### Is your feature request related to a problem?

Not a clear problem, but I pay for the Laerd subscription to help me run data sets because there is not thing as clear for JASP. However, I am really struggling with Forward Stepwise because neither location has good information. 

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

I clear and detail walk through on how to run tests like SPSS has

### Describe alternatives that you have considered

I buy the Laerd subscription. I would rather use something designed just for this program.

**Comment by tomtomme** [comment] 2024-02-08 10:22
@WrldTraveler 
If I understand correctly, you want to know more about hierarchical linear regression than whats documented in jasps help files or user guide (although I think those are already helpful).

Improving documentation is always a concern and there is a project on improving the help files, see 
https://github.com/jasp-stats/jasp-issues/issues/2529

And have you seen all the docs available on jasps website?
https://jasp-stats.org/support/

And if those give no answer you could ask in the forum
https://forum.cogsci.nl/categories/jasp-bayesfactor

Or try some of the material out there: 
https://www.google.com/search?client=firefox-b-d&q=Forward+Stepwise+%22hierarchical+regression%22+in+%22jasp%22

I hope this helps?
Closing as duplicate of #2529

**Closed by tomtomme** 2024-02-08 10:22 UTC
Labels: Module: jaspDescriptives, Feature Request
