### ISSUE TITLE
[Bug]: Under the Chinese interface, an error will be reported when performing confirmatory factor analysis.

### ISSUE THREAD

**Issue by akwan168** [jasp-stats/jasp-issues#2947] opened 2024-10-02 04:28 UTC
### JASP Version

0.19.0

### JASP Module

Factor

### What analysis are you seeing the problem on?

confirmatory factor analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

In "Traditional Chinese" Interface
Run "SEM/Structural Equation Modeling"
JASP will report an error message
Please watch the video：https://youtu.be/mQSaER8zvqs

### Expected Behaviour

Please watch the video：https://youtu.be/mQSaER8zvqs

### Steps to Reproduce

1. please download the data files: https://reurl.cc/1b7ZOV
2. Please watch the video：https://youtu.be/mQSaER8zvqs
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2024-10-02 08:02
thanks for creating the issue. I think you have identified an issue with the underlying R package, which is, the factor names need to follow a certain alphabet. I dont think we can do anything about this, since we do not maintain that package. @shun2wang can you confirm that this also does not run in R?

**Comment by shun2wang** [comment] 2024-10-02 08:54
OK, I will have a look later since I am in holidays.

**Comment by shun2wang** [comment] 2024-10-02 08:56
OK, I will have a look later since I am on holidays.

**Comment by shun2wang** [comment] 2024-10-09 02:44
Yes, I can reproduce also in lavaan from R. lavaan doesn't support unicode factor names I guess: https://github.com/yrosseel/lavaan/blob/48d3c00e7bd831b7a6b39331a923013d26e6e5bc/R/lav_syntax_parser.R#L74

@juliuspfadt I made a fix at https://github.com/jasp-stats/jasp-desktop/pull/5687 but I want to confirm that factor names are only used for calculations (i.e. not visible to the user) right?

@akwan168 Thanks for the report, the fix will be including in the next release. You can temporarily work around this issue by switching to English language to run the analysis.

**Closed** 2024-10-09 12:13 UTC
Labels: Module: jaspFactor, Bug: Medium
