### ISSUE TITLE
[Bug]: ANOVA Number of observations is < 2 after grouping

### ISSUE THREAD

**Issue by Catatinaz** [jasp-stats/jasp-issues#1797] opened 2022-08-08 19:29 UTC
### JASP Version

0.16.3

### JASP Module

jaspAnova

### What OS are you seeing the problem on?

mac

### Bug Description

The following problem(s) occurred while running the analysis:
Number of observations is < 2 in EstadoCivil after grouping on DASS21_TOTAL, DASS_21_Depressão, DASS_21_Ansiedade, DASS_21_Stress

### Expected Behaviour

i dont know 

### Steps to Reproduce

1. 
2. 
3. 
...

### Log (if any)

<img width="1440" alt="Captura de ecrã 2022-08-08, às 20 28 26" src="https://user-images.githubusercontent.com/110853121/183498680-c0024017-ffd0-4250-ac75-66f5a42a62f5.png">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-08-09 06:47
Hi @Catatinaz, thanks for the report. Could you describe your issue in more detail? So far I can only see desired behaviour, in that the ANOVA does not run when the number of observations in the dependent variable is smaller than 2.

**Comment by lilianjansbeken** [comment] 2022-08-09 08:31
My students and I encounter the same issue. When I run an ANOVA I get the same error
<img width="960" alt="2022-08-09 (1)" src="https://user-images.githubusercontent.com/52657670/183602077-7366150b-31e3-48ff-95c0-aa019cbe8c95.png">
When I run the same ANOVA in Jamovi, this works fine
<img width="960" alt="2022-08-09 (2)" src="https://user-images.githubusercontent.com/52657670/183602148-73ba943c-c34c-4784-9278-c185800c02df.png">
I am not sure which operating systems my students have but I run JASP 16.3 on Windows 11. 
The file can be found at [https://www.dropbox.com/s/66gjsqh4oh0mwaq/Psychologische%2Btests%20origineel.jasp?dl=0](url) but I don't think that is the problem here as more people encounter this problem with different databases.

**Comment by juliuspf** [comment] 2022-08-09 09:28
Thanks for the detailed description @lilianjansbeken. Somehow the link you posted does not lead me to the data file. Can you try again?

**Comment by lilianjansbeken** [comment] 2022-08-09 09:38
Let me send it this way... Don't know why the link doesn't work 

⁣Verzonden door BlueMail ​

Op 9 aug. 2022 11:28, om 11:28, Julius Pfadt ***@***.***> schreef:

**Comment by EJWagenmakers** [comment] 2022-08-11 07:48
@Kucharssim @vandenman maybe you can look into this as well.

**Comment by vandenman** [comment] 2022-08-11 08:59
The link works https://www.dropbox.com/s/66gjsqh4oh0mwaq/Psychologische%2Btests%20origineel.jasp?dl=0, although the hyperlink is redirecting to this issue for some reason.

The error message is not wrong btw:

![image](https://user-images.githubusercontent.com/21319932/184097822-da0c4be6-5e34-4d44-8a0f-fc504eaf96f5.png)

However, this check is too strict, since the main ANOVA table can be computed with only one observation per cell. The check is probably exists because some other components of the analysis expect that there are at least 2 observations per cell. I guess we should relax that and only show error messages in the parts that actually need multiple observations per cell. @Kucharssim do you know if GORICA has a minimum number of observations? I can take a shot at this if you'd like.

**Comment by Kucharssim** [comment] 2022-08-11 11:03
> @Kucharssim do you know if GORICA has a minimum number of observations?

No it doesn't. As long as you can fit the linear model, GORICA should work.

**Comment by EJWagenmakers** [comment] 2022-08-12 13:29
The same issue was noted earlier, I believe by one of the SKF analysts. I was under the impression that @JohnnyDoorn or @JTPetter had fixed it...

**Comment by lilianjansbeken** [comment] 2022-10-07 07:12
I was hoping that this would be fixed in the 16.4 version but regretfully this is still an issue with the same information as I provided before in this thread.

**Comment by EJWagenmakers** [comment] 2022-10-07 07:46
Thanks for the reminder. I have now assigned this to Jonas and Simon as well.

**Comment by ataylor92110** [comment] 2023-01-08 17:21
I am having the exact same problem and when I run a contingency table is it quite clear that each cell has many entries. I would be more than willing to send you my complete file of data and analyses with the error statement if that would help. I have this problem with another data set and another analysis as well and it is very frustrating because I need to know this information before moving forward.

**Comment by tomtomme** [comment] 2024-02-04 16:44
@ataylor92110 
Sorry for the late response - if you could still send the file I would look into it.

@Catatinaz 
The error message is still the same with jasp 0.18.3. I guess it is not that easy to change it.

**Comment by ataylor92110** [comment] 2024-02-05 16:47
Oh, I solved this quite some time ago.

Thanks


Annette Kujawski Taylor, Ph.D.

she/her/hers ("What Are Personal Pronouns & Why Do They Matter?"
<https://www.mypronouns.org/what-and-why>)
Professor, Emerita, Psychological Sciences
University of San Diego
***@***.***

**Comment by tomtomme** [comment] 2024-02-05 20:15
ok, then only the original posters problem persists, that we need another errror message here.

**Comment by lilianjansbeken** [comment] 2024-02-06 07:43
So, I've downloaded the newest version of JASP to see if the problem is solved. It isn't. If you run an anova on the dataset you can find at [](https://osf.io/gx3yq/) then you will receive the following error message 
![afbeelding](https://github.com/jasp-stats/jasp-issues/assets/52657670/79d76326-bf03-43c6-adaa-a4aca3cafd77)

As this is learning material for my students, I would greatly appreciate when this could be solved in one way or the other.
With gratitude,
Lilian

**Closed** 2024-02-09 15:36 UTC
Labels: Module: jaspAnova, Bug: High
