### ISSUE TITLE
Letter not detected in regression output

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1350] opened 2021-07-06 16:44 UTC
* JASP version: 14.1

* OS name and version: Windows
* Analysis: 
* Bug description: When I run a regression analysis, the coefficient output that JASP is producing does NOT seem to recognize the Swedish letter "ö", despite I am using a CSV-UTF8 file. This has been fine in other JASP outputs, when I have been running other types of analysis
* Expected behaviour:

#### Steps to reproduce:

[Enkel linjär regression - SW.zip](https://github.com/jasp-stats/jasp-issues/files/6771488/Enkel.linjar.regression.-.SW.zip)

**Comment by vandenman** [comment] 2021-07-07 07:47
Hmm the attached file indeed has this issue. However, on Ubuntu 20.04, the letter is displayed fine once I refresh the file:
![image](https://user-images.githubusercontent.com/21319932/124720056-07e34780-df08-11eb-849a-3c43570b0ce6.png)

@PerPalmgren does the issue persist if you adjust the results font? 
![image](https://user-images.githubusercontent.com/21319932/124720185-2d705100-df08-11eb-9f5c-043893525b60.png)
(`Settings` -> `Preferences` -> `Interface` -> `Fonts`)

@JorisGoosen any ideas? This could be windows specific I guess.

**Comment by PerPalmgren** [comment] 2021-07-07 08:15
Hi,
I have tried to change the font in the “settings” but this does not resolve the problem 😢. I really would like this to work so I can use the program my new Swedish statistics course🙏.

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by boutinb** [comment] 2021-07-07 11:20
Hi @PerPalmgren Which fonts do you use for Result & Help?

**Comment by PerPalmgren** [comment] 2021-07-07 11:28
I use default “Arial”

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<http://ki.se/>
________________________________

Karolinska Institutet – a medical university

7 juli 2021 kl. 13:20 skrev bruno boutin ***@***.***>:

﻿

Hi @PerPalmgren<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPerPalmgren&data=04%7C01%7Cper.palmgren%40ki.se%7C9a90f0e612474b9a19ac08d94139302f%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637612536148254512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KS6fmJ1AkKWdZ19XaM6ofOZfCnhDmdzHga7joiuUoD0%3D&reserved=0> Which fonts do you use for Result & Help?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1350%23issuecomment-875520764&data=04%7C01%7Cper.palmgren%40ki.se%7C9a90f0e612474b9a19ac08d94139302f%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637612536148254512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DDWUOePgC%2Fq%2B4UJgskrx5o2jPZY2bIhlzV4tCd3aPEk%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS5YGHVJFHG3RWNY7YLL3CDTWQZ6XANCNFSM4746EB4A&data=04%7C01%7Cper.palmgren%40ki.se%7C9a90f0e612474b9a19ac08d94139302f%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637612536148264506%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TUK%2FwFA5cNPi0vnhyeebHF%2FOIicaOIB58ClCGGRJSjM%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by boutinb** [comment] 2021-07-07 12:53
And in the Data View, as in the Analysis Options View, can you see this ö well displayed? Which fonts do you use (Interface fonts settings) ? Did you try to use the same fonts for the results?
If the problem still persist, could you send the log file of the engine: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/user-guide/logging-howto.md ?

**Comment by PerPalmgren** [comment] 2021-07-07 13:33
Hi,
In the data view it is ok, and I can see the “ö”. I have tried to change and use the same fonts for interface and results but without success and the problem is still there. When I run other analysis such as ANOVA or T-test there is no problem, it only seems to be problematic with the output when running regression models.
I attach a zip-fil with the log files.
Really happy that you try to help me😊.
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by boutinb** [comment] 2021-07-07 13:40
Can you use the GitHub website (by dragging the file in a comment) to send the log file? Via email it does not work.

**Comment by PerPalmgren** [comment] 2021-07-07 14:01
Ok!
[Per´s JASP log.zip](https://github.com/jasp-stats/jasp-issues/files/6777765/Per.s.JASP.log.zip)

**Comment by boutinb** [comment] 2021-07-08 07:36
It is really strange that a table from an ANOVA or T-Test analysis displays correctly the ö, and not a regression analysis. We have made substantial changes in 0.15 (next release) in the regression analyses. Maybe this problem is then fixed. Could you try it: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-16009c4ff93f15056002867a04dd06f4b42f6c9b.msi ?
It it still does not work on this version, could you again generate the log files (we have added more log information)?

**Comment by PerPalmgren** [comment] 2021-07-08 07:46
Unfortunately, I can't download the JASP program unless I get a clearing code from the IT department from my university. I guess that is not so good before the official release. When is this planned for?
Could I send you my raw data as compressed excel file for you to investigate?

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet - a medical university

**Comment by boutinb** [comment] 2021-07-08 10:07
There is also the possibility to install JASP with zip file: http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-development-16009c4ff93f15056002867a04dd06f4b42f6c9b.zip
You don't need admin tights for this.

**Comment by PerPalmgren** [comment] 2021-07-08 10:17
This is too complicated for me🙄 and I do not dare to do this 😜. Thanks, any way! Hopefully it will be resolved in the updated JASP version🙏.
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by boutinb** [comment] 2021-07-09 07:43
Hi @PerPalmgren As I cannot reproduce your issue, I cannot do much to fix it. I know it asks you some time, and you have probably many other things to do, but It would be really a pity if this problem is still not solved in 0.15. It is really possible to install JASP on Windows even if you are not admin of your own PC, even by using the installation file ( http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-16009c4ff93f15056002867a04dd06f4b42f6c9b.msi): for this you just need to click the 'Advanced' button, and to select the 'Install just for you' option.

**Comment by PerPalmgren** [comment] 2021-07-09 08:09
Hi Bruno,
Using the way you suggested still required me a password, but I have contacted my IT department and asked them to provide me with a code. I will try to download 15.0 and run my regression analysis .
I will return to you as soon as possible 😎😜.
All the best
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by PerPalmgren** [comment] 2021-07-09 10:55
Hi Bruno,
I manage to download JASP 0.15. I have run the regression and it seems to be ok  (print screen attached) with the letter “ö” 😊😜🙏. Two questions! When will the official 0.15 be released? Do I need to remove this 0.15 version when it is launched, or will it update automatically?
All the best
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by PerPalmgren** [comment] 2021-07-09 11:09
Hi Bruno,
I saw a glitch on when I took her for a spin. In the Descriptive plots in the One sample t-test the value zero (0) on the Y-axis looks very strange (like It is superimposed). I attach the JASP file.
All the best
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet - a medical university

**Comment by PerPalmgren** [comment] 2021-07-09 11:24
Ignore the glitch I mentioned “it was me who was to quick” 😊

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

From: Per Palmgren
Sent: den 9 juli 2021 13:09
To: jasp-stats/jasp-issues ***@***.***>
Subject: RE: [jasp-stats/jasp-issues] Letter not detected in regression output (#1350)

Hi Bruno,
I saw a glitch on when I took her for a spin. In the Descriptive plots in the One sample t-test the value zero (0) on the Y-axis looks very strange (like It is superimposed). I attach the JASP file.
All the best
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fki.se%2F&data=04%7C01%7Cper.palmgren%40ki.se%7C9f6969aac91f4526542308d875898009%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637388580700328145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f6OY6fEm6z0scmnO%2FDhlWRgL%2BujfjA072A2uHaASfNY%3D&reserved=0>
________________________________

Karolinska Institutet – a medical university

**Comment by vandenman** [comment] 2021-07-09 11:31
Hi, @PerPalmgren thanks for the quick reply and I'm happy to read that 0.15 solves the issue! From your message, it looks like you attached files, but unfortunately that doesn't get forwarded to us. To include attachments, you must directly use the GitHub website.  

> Two questions! When will the official 0.15 be released? 

The next release is planned for after the summer holidays.

> Do I need to remove this 0.15 version when it is launched, or will it update automatically?

@boutinb probably knows the answer to that.

**Comment by PerPalmgren** [comment] 2021-07-09 12:52
Thanks,
However, when I run a scatter plot in Descriptive in version 0.15 it does not see to recognize the Scandinavian letters å, ä and ö (it use to do that in version 0.14.1) 😢😢😢. See attached photo. Does JASP use CSV UTF-8 everywhere? 
![Picture2](https://user-images.githubusercontent.com/79397662/125080508-2b072600-e0c5-11eb-9d0e-be55d4227ba5.png)

**Comment by boutinb** [comment] 2021-07-09 14:28
What strange.... But I see that you use another file. Is this file also in UTF-8? Could you send it to us? And also the log files?

**Comment by PerPalmgren** [comment] 2021-07-09 15:53
Thus is also a UTF-8 file. I did a second one (attached) just in case.
It woks fin for the regression now but the variable labels for the X the Y axis on the plots seems problematic.
I also attach the log files.
Per😎
[16b Multipel linjär regression (hierarkisk).zip](https://github.com/jasp-stats/jasp-issues/files/6792545/16b.Multipel.linjar.regression.hierarkisk.zip)
[Log JASP.15 PP.zip](https://github.com/jasp-stats/jasp-issues/files/6792548/Log.JASP.15.PP.zip)

**Comment by JorisGoosen** [comment] 2021-08-17 14:38
Hey @PerPalmgren 

I think I've fixed the problem, could you try out one of the following two:
https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-fixOutputWindows-20333849051a46c05e33a728ab140e036a8a0326.msi

https://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-fixOutputWindows-20333849051a46c05e33a728ab140e036a8a0326.zip

It *should* be fixed now I hope.

**Comment by JorisGoosen** [comment] 2021-08-19 11:09
@PerPalmgren ?

**Comment by PerPalmgren** [comment] 2021-08-19 13:22
Hi,
I am in holiday for two more weeks and without computer. Sorry! But check when I am back.
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<http://ki.se/>
________________________________

Karolinska Institutet – a medical university

19 aug. 2021 kl. 13:09 skrev Joris Goosen ***@***.***>:

﻿

@PerPalmgren<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPerPalmgren&data=04%7C01%7Cper.palmgren%40ki.se%7Cbe7d61ff109047ec360808d96301c810%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649681584371628%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BZxCOzVuIyznagnYKRSLfIXwnpf89ThXDzESlD19LGA%3D&reserved=0> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1350%23issuecomment-901824241&data=04%7C01%7Cper.palmgren%40ki.se%7Cbe7d61ff109047ec360808d96301c810%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649681584381633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DZQnRIglor47cOf%2BtNSLrnGfKHs4PX4b5Gl1QeedA3c%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS5YGHVO6QZ3BCOG77IOTJTT5TQ5TANCNFSM4746EB4A&data=04%7C01%7Cper.palmgren%40ki.se%7Cbe7d61ff109047ec360808d96301c810%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649681584381633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=es8x0hStbRjJqUS3csBOfYmX1QQtRbqKY6Gl0NbMQ2Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cper.palmgren%40ki.se%7Cbe7d61ff109047ec360808d96301c810%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649681584391621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=siizcPctzDIHNbgoajKOgzf21%2Fpj1Tg3NY2uFtrXzIQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cper.palmgren%40ki.se%7Cbe7d61ff109047ec360808d96301c810%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649681584401621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QFGH6jMxjTZ3Ia9%2BfOSeaZz%2B01pRwO5iJ5Wya14OWWo%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by JorisGoosen** [comment] 2021-08-19 13:35
Enjoy your holiday!

**Comment by PerPalmgren** [comment] 2021-08-19 19:11
Thanks🤩
Joris, one question! Do you think the new version of JASP will be released before september?
Per

Per J. Palmgren | DC, FRCC, MMedEd, PhD |
Associate Professor |
Department of Learning, Informatics, Management and Ethics |
Karolinska Institutet | Tomtebodavägen 18A | 171 77 Stockholm |
Tel. + 46 8 524 85 294<tel:+%2046%208%20524%2085%C2%A0294>
***@***.******@***.***> | ki.se<http://ki.se/>
________________________________

Karolinska Institutet – a medical university

19 aug. 2021 kl. 15:35 skrev Joris Goosen ***@***.***>:

﻿

Enjoy your holiday!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjasp-stats%2Fjasp-issues%2Fissues%2F1350%23issuecomment-901921086&data=04%7C01%7Cper.palmgren%40ki.se%7C2c75a703cb14440d939008d963162fdb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649769216792315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tYOqFYpihqw%2Bm7JFHdcpZLvvb9xah1evpbg0dz8MJIQ%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS5YGHTO2WVMLXN3XOAG5J3T5UCBLANCNFSM4746EB4A&data=04%7C01%7Cper.palmgren%40ki.se%7C2c75a703cb14440d939008d963162fdb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649769216802309%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UsuvJ%2FO%2BDpsJn8wjP5mK8ITsYrzUzTXzjEuViHZqIh8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cper.palmgren%40ki.se%7C2c75a703cb14440d939008d963162fdb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649769216802309%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Izxu18yNec5XeeiC8z1BxRM0SpgvF4UWm2IAtr6L9ws%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cper.palmgren%40ki.se%7C2c75a703cb14440d939008d963162fdb%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637649769216812305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OySXVAZWwubMAS94TrBQ9xImR%2FkpXNoJqNk%2FPOEhW5M%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by JorisGoosen** [comment] 2021-08-20 20:15
We are now aiming for and hoping for the exact beginning of september.

If you want to prepare for classes you can use one of the `development` nightlies at https://static.jasp-stats.org/Nightlies/ 

We are now testing them and are getting ready to push it out to the world (if nothing explodes of course)

**Comment by PerPalmgren** [comment] 2021-08-22 10:03
Hi Joris,
I am still on holiday. I cant download the new version through the nigthlies (because I need a clearing code form my university ). But I have confidence in you :-) 
However I saw that in 0.15 version I tried before the summer the letters å, ä och ö are also problematic in the descriptive  tab (see below), so maybe you need to verify this on all statistical tests. 
All the best 
Per
![image](https://user-images.githubusercontent.com/79397662/130350908-5946d037-8ae6-47f6-9fa5-2e97dd9c21f7.png)

**Comment by JorisGoosen** [comment] 2021-08-23 08:48
I hope to have those covered, however I have seen another problem for a galician user, where it isnt the data but the r-analyses that are displayed wrong. 

I do think your example above should be fixed, or at least I hope ;)

**Closed** 2021-08-25 16:41 UTC
Labels: waiting for requester
