### ISSUE TITLE
[Feature Request]: Colour palettes for plotting

### ISSUE THREAD

**Issue by RenzoLanfranco** [jasp-stats/jasp-issues#2246] opened 2023-08-01 10:38 UTC
### Description

Currently, JASP allows to edit many aspects of the plots such as the scale of the x and y axes. However, it is currently not possible to edit the colour of plots, observed scores, rainclouds, etc. While some of these aspects can be further edited outside JASP (e.g., in Illustrator), some aren't editable (e.g., rainclouds) or it would take a lot of work to edit them (e.g., individual scores).

### Purpose

Given that some aspects of the plots produced by JASP aren't editable after being exported (e.g., rainclouds), it would be very helpful to be able to edit this inside JASP, maybe by defining the RGB values oneself.

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

No

### Describe the solution you would like

To be able to edit the colour of each plot before exporting figures outside JASP. Maybe by adding RGB values per condition in each plot, or by defining CMYK values.

### Describe alternatives that you have considered

None

**Comment by tomtomme** [comment] 2023-08-12 17:53
You can export to pptx and edit the colors there. Does this help in your case?

**Comment by tomtomme** [comment] 2024-01-11 11:37
Closing this as duplicate of: https://github.com/jasp-stats/jasp-issues/issues/2122

**Closed by tomtomme** 2024-01-11 11:37 UTC
Labels: Feature Request
