### ISSUE TITLE
[Feature Request]: PLS-SEM to have VIF, HTMT, AVE, other measures...

### ISSUE THREAD

**Issue by areeq1** [jasp-stats/jasp-issues#1982] opened 2023-01-25 13:55 UTC
### Description

The package seems to work but, thanks! I suggest adding VIF and possibly HTMT to assess the collinearity and discriminant validity. Much appreciated

### Purpose

collinearity and discriminant validity

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

Other

### Describe the solution you would like

add an option to get these measures

**Comment by juliuspfadt** [comment] 2023-11-10 15:33
also requested here: https://forum.cogsci.nl/discussion/8935/assessing-measurement-model-when-using-pls-sem

**Comment by juliuspfadt** [comment] 2023-11-10 15:35
see also https://github.com/jasp-stats/jasp-issues/issues/2089

**Comment by tomtomme** [comment] 2024-02-27 13:21
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/2089

**Closed by tomtomme** 2024-02-27 13:21 UTC
Labels: Module: jaspSem, Feature Request
