### ISSUE TITLE
Enhancement: DFA

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#256] opened 2018-11-22 16:02 UTC
* Enhancement: Add Discriminant Function Analysis 
* Purpose: Multivariate test of between group differences, and the minimum number of dimensions needed to describe these differences. 
* Use-case: Widely used in studies of animal cognition. See following papers among many others:

Slocombe, K. E., & Zuberbühler, K. (2005). Functionally referential communication in a chimpanzee. Current Biology, 15(19), 1779-1784.

Crockford, C., Gruber, T., & Zuberbühler, K. (2018). Chimpanzee quiet hoo variants differ according to context. Royal Society open science, 5(5), 172066.

Note the modified procedure in the second paper.

Also widely used in other areas of psychology, i.e. Betz, N. E. (1987). Use of discriminant analysis in counseling psychology research. Journal of Counseling Psychology, 34(4), 393.

Again amongst many other areas. 

Already available in SPSS and other proprietary software. 

Thanks for all the great work!

P.S.: As previously discussed with the team, I would be more than happy to help with beta-testing etc!

**Comment by rsbalkin** [comment] 2021-11-19 01:40
This article is a bit dated but denotes best practice with post hoc MANOVA.  I concur with TarandeepKang.  This is needed.

[Performing multivariate group comparisons following a statistically significant MANOVA.pdf](https://github.com/jasp-stats/jasp-issues/files/7567183/Performing.multivariate.group.comparisons.following.a.statistically.significant.MANOVA.pdf)

**Comment by JohnnyDoorn** [comment] 2023-02-28 11:17
Hi @rsbalkin and @TarandeepKang ,

Sorry I am just now taking note of this. I think this analysis is already implemented, but part of the machine learning module. Could you take a look and see if this analysis does what you want it to do? 

Kind regards
Johnny

**Comment by rsbalkin** [comment] 2023-02-28 21:30
So, I typically use DFA as a post hoc for MANOVA.  SPSS gives me very different output that I cannot replicate in machine learning for JASP.

Take a look.

Rick

Richard S. Balkin, Ph.D., LPC, NCC
Editor-in-Chief, International Journal for the Advancement of Counselling
Fellow, American Counseling Association
Professor & Chair, Coordinator for Educational Research and Design
Department of Leadership and Counselor Education
School of Education
University of Mississippi
email: ***@***.***


￼￼

**Comment by TarandeepKang** [comment] 2023-09-29 11:02
I would also like to request the inclusion of the permuted version of this test as I mentioned in #458 

The pDFA has a number of advantages over the regular discriminant function analysis. This analysis was designed and proposed by Mundry and Sommer (2007). In the abstract of the paper The authors summarise the advantages of the test thus:

“ The discriminant function analysis (DFA) is a multivariate method that is frequently used in bioacoustic research to examine, for instance, whether calls from different species, contexts, or social groups can be distinguished by their acoustic properties. Most published studies include more than one call per subject into such an analysis. This, in fact, leads to a two-factorial data set that includes the factor ‘subject’ in addition to the factor of interest (e.g. species, context, or social group). The regular version of the DFA, however, does not allow for the analysis of such data sets without violating the assumption of independence. In this paper, we show that analysing factorial data sets using a conventional DFA is a case of pseudoreplication and tends to produce (sometimes grossly) incorrect results. In such a case the discriminability of species, contexts or groups etc. can be drastically overestimated. Furthermore, we provide a permutation-based procedure that copes with such data sets.“

The citation for the paper is: Mundry, R., & Sommer, C. (2007). Discriminant function analysis with nonindependent data: Consequences and an alternative. Animal Behaviour, 74(4), Article 4. https://doi.org/10.1016/j.anbehav.2006.12.028

The author has developed code for SPSS and R, it is not publicly available but can be shared upon request. Happy to contact him for the code if you are interested. Apologies for taking so long to respond, I just checked back on this issue and only now saw that you had posted a question for us in February!

**Comment by tomtomme** [comment] 2023-12-23 21:00
Can be closed, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/458

**Closed** 2024-01-03 12:29 UTC
Labels: Module: jaspAnova, Feature Request
