### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Wouterwolf** [jasp-stats/jasp-issues#2283] opened 2023-09-08 11:44 UTC
### Description

Regression coefficients + HDI's for categorical x continuous ANCOVA interactions

### Purpose

To get the regression coefficients + HDI's in a table when doing ANCOVA interaction analyses with a categorical and continuous variable

### Use-case

Useful generally, but especially for teaching, allowing students who are just getting exposed to interactions how the uncertainty for regression slopes can differ between different subsamp-les

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

A table containing the regression coefficient and HDI's for the different levels of the grouping variable

### Describe alternatives that you have considered

I suppose I have tried running seperate regressions on the subgroups, but that is far from ideal

### Additional context

Interestingly, when you do this kind of ANCOVA and you make a descriptive plot with the continuous predictor on the x axis and with the grouping variable as separate lines, you get a graph that visualizes this part of the analysis beautifully:

![image](https://github.com/jasp-stats/jasp-issues/assets/35498584/7809af48-afb4-4eff-8f3c-b679b5c60132)

However, there is no way to get the coefficients and (average) HDI of this coefficient to report in addition to this.
So for now, I have always just told my students that the graph alone is fine, but it would be great if they could also discuss these values in the text.

And it would help a lot of researchers (including myself) to better describe the data.

Thanks!

**Comment by tomtomme** [comment] 2024-02-08 16:05
Closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/2119

**Closed by tomtomme** 2024-02-08 16:05 UTC
Labels: Module: jaspAnova, Feature Request
