### ISSUE TITLE
[Feature Request]: Descriptive statistic splitted by more than 1 variable at time

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#2074] opened 2023-03-28 07:42 UTC
### Description

It would be great to perform the descriptives statistics analyses splitting by more than 1 variable at time

### Purpose

In order to perform more detailed explorations of the data

### Use-case

For example, if the user wants to search for potential outliers (i.n. boxplots with labelled outliers) in groups formed by different levels of 2 or more independent factors

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

Would be great if ti was possible to add 2 or more factor in the "Split" dialogue box of the Descriptive statistics module. Please see the blue arrow at the attached screenshot.

### Additional context

<img width="620" alt="Captura de pantalla 2023-03-28 a las 9 41 11" src="https://user-images.githubusercontent.com/29978768/228164328-0064528e-0127-432a-b0c4-af36a0d59033.png">

**Comment by tomtomme** [comment] 2024-02-03 11:50
closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/2492

**Closed by tomtomme** 2024-02-03 11:50 UTC
Labels: Module: jaspDescriptives, Feature Request
