### ISSUE TITLE
[Bug]: App crashes when computing a column or creating a new column

### ISSUE THREAD

**Issue by MartinPta** [jasp-stats/jasp-issues#1971] opened 2023-01-18 14:13 UTC
### JASP Version

0.16.4

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Computing columns

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

When I try to compute a new column (either using the click-and-drag function or R code) the app crashes – the app suddenly ends. Sometimes it happens even when creating a new column. It's not 100% crash, but based on my experience it happens at least in 80-90% cases.

I cannot include a .jasp file. I was able to compute all variables after several attempts (it was annoying though) and I don't want to lose the progress. Screenshots are not needed – there is simply the app and after clicking on one of the buttons (create/compute column) there is my desktop and issue report window for Apple (JASP closed). I am using MacBook 2020 M1 and Ventura 13.0.1 system.

There is the used dataset:
[Dataset.csv](https://github.com/jasp-stats/jasp-issues/files/10447061/Dataset.csv)

Besides the bug, I love the software. Thank you.

### Expected Behaviour

Not crashing :-)

### Steps to Reproduce

1. Click + in the right upper corner (the smaller one; not the one for adding modules)
2. Name the column, select scale, and click-and-drag function or R code.
3. Press "Create Column"
Then it crashes sometimes.
4. Put in the code: SWL1+SWL2+SWLn...
5. Press "Compute column"
Then it crashes.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2023-01-20 16:13
I cannot reproduce this crash. Could you send us the log files: https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md

**Comment by tomtomme** [comment] 2024-02-04 18:01
@MartinPta
Feel free to reopen, if you can provide logs. But I guess this is fixed with newer jasp versions anyway. Tell us if not!

**Closed by tomtomme** 2024-02-04 18:01 UTC
Labels: OS: macOS Silicon, Bug
