### ISSUE TITLE
[Bug]: False CI for Rater Agreement

### ISSUE THREAD

**Issue by Blubb789** [jasp-stats/jasp-issues#2333] opened 2023-10-10 16:32 UTC
### JASP Version

0.18.1

### JASP Module

Reliability

### What analysis are you seeing the problem on?

Rater agreement

### What OS are you seeing the problem on?

Windows 10

### Bug Description

If you choose Krippendorff´s alpha and then the option raters in rows the calculation of Krippendorff´s alpha is correct but the CI (confidential interval) not. So my Krippendorff´s alpha is always outside the CI, which can´t obviously be.
My guess is that´s because the data source for the CI doesn´t switch.

### Expected Behaviour

If I switch the "raters" from colum to row the data source should not just switch for the Krippendorff´s alpha but also for the CI and SE, please.

### Steps to Reproduce

1. choose the reliability package
2. choose Rater agreement
3. unselect Cohen´s and Fleiss kapa
4. select Krippendorff´s alpha
5. select Raters are in rows
6. Look at the Results of the CI and your Alpha they shouldn´t match.
...

### Log (if any)

![bug_rater_agreement](https://github.com/jasp-stats/jasp-issues/assets/147536371/d7b3eb11-78ae-4b90-b456-54636f45215b)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2023-10-11 08:00
Hi @Blubb789, thanks for creating this issue. This is a known issue, and duplicate of https://github.com/jasp-stats/jasp-issues/issues/2318. The next version of JASP has this fixed.

**Closed by juliuspfadt** 2023-10-11 08:00 UTC
Labels: Module: jaspReliability, OS: Windows 10, Bug
