### ISSUE TITLE
Enhancement: network comparison test (R-package NetworkComparisonTest)

### ISSUE THREAD

**Issue by mberlim** [jasp-stats/jasp-issues#197] opened 2018-06-23 02:26 UTC
## Template for bug reports

* JASP version:
* OS name and version:
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by JASPUSER09990** [comment] 2019-05-27 11:53
@vandenman @JorisGoosen Any follow-up news for this suggestions? The cross group comparison tests should be considered in the future versions.

**Comment by JorisGoosen** [comment] 2019-05-27 11:59
@JASPUSER09990 This issue is hardly fleshed out so I'm not really sure what follow-up there would be?

But maybe @vandenman has a different outlook?

On the other hand if you know what you want maybe you could describe it a bit more fully here than @mberlim has done.

**Comment by JASPUSER09990** [comment] 2019-05-27 12:16
Hello @JorisGoosen Network Comparison Test (NCT) developed by van Borkulo (2018) is a way to allow researchers to conduct direct comparisons of two networks as estimated in different subpopulations. The test uses permutation testing in order to compare network structures that involve relationships between variables that are estimated from the data. The test focuses on the extent to which groups may differ in relation to (1) the structure of the network as a whole, (2) a given edge strength, (3) and the overall level of connectivity in the network.

van Borkulo, C. D. (2018). Network comparison test: Permutation-based test of differences in strength of networks. See https://www.researchgate.net/publication/317493228_A_tutorial_on_R_package_NetworkComparisonTest_NCT

**Comment by tomtomme** [comment] 2024-02-18 17:00
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/2067
lets discuss there

**Closed by tomtomme** 2024-02-18 17:00 UTC
Labels: Module: jaspNetwork, Feature Request
