### ISSUE TITLE
[Bug]: Cannot paste image to web document

### ISSUE THREAD

**Issue by kristenwebb** [jasp-stats/jasp-issues#2787] opened 2024-06-18 20:31 UTC
### JASP Version

0.18.3

### What analysis are you seeing the problem on?

Histogram

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I copied the image of the histograms from JASP.  When I attempted to paste the image in the Word Document, it only pasted the script but did not paste the image and I received an error message "can't paste image. save on your device and paste from there."  I saved the image to my laptop but I cannot find a program to open the image.  I called my university IT support (Capella) and they suggested I open a ticket with Jasp.

### Expected Behaviour

I followed the instructions, but cannot paste the image.

### Steps to Reproduce

1.
2.
3.
...
I have tried multiple times to paste the image in various formats.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2024-06-19 07:55
Hi @kristenwebb, you can save an image with different type. Per default it is in png format (which is really standard), but you can also save it as pdf: this format should be supported by any computer.

**Comment by EJWagenmakers** [comment] 2024-06-19 09:16
To elaborate, you click on the small black triangle just above the plot. This will 
open a menu where one of the options is "Save image"; you can then select this 
option and choose the desired file format and location on your computer.

**Comment by tomtomme** [comment] 2024-06-19 13:25
@kristenwebb 
Did you use Word in a browser window or as a standalone app? Which version of word? Also: Is your Win11 fully up to date?

@boutinb 
Some of my students also told me about this bug. I will try to clarify, if this was an win11 also. Copy paste graphs to word should just work on any platform, right?

**Comment by boutinb** [comment] 2024-06-19 15:11
@tomtomme If you can indeed get a real reproduction path, that would be nice.

**Comment by kristenwebb** [comment] 2024-06-19 17:17
I use Windows 11 and just recently purchased it.  It shows there are non ew
updates for my program.  I was using from a browser window.

**Comment by kristenwebb** [comment] 2024-06-19 17:23
Thank you.  That works for what I need.

**Comment by tomtomme** [comment] 2024-06-20 07:42
@kristenwebb 
thx for the feedback.
So does this mean that you can now paste the image to Word in a browser?
Or is your workaround to use word outside the browser or did anything else solve this issue for you?

**Comment by shun2wang** [comment] 2024-06-20 08:48
well if it's on web docs maybe have some problems.

I forgot: https://github.com/jasp-stats/INTERNAL-jasp/issues/2456

**Comment by tomtomme** [comment] 2024-06-20 08:59
confirmed with latest beta. copy pasting to word or excel within firefox does not work. 
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/9267056e-2aa0-4573-a8b1-6d40b1c0dbbe)

google docs is fine however.
will test further browsers.

**Comment by shun2wang** [comment] 2024-06-23 04:10
I tink we can do nothing here because these web docs will not handle mixed format of html with images, unless a image mimetype. convert to base64 is also not work. let's keep it open and see what else we can do later...

@kristenwebb you may export that plot as .png and then upload/insert image to the docs.

**Comment by tomtomme** [comment] 2024-07-06 11:18
@shun2wang 
So since we cannot fix this one, I will close it for now.

**Comment by shun2wang** [comment] 2024-07-07 02:09
No, as I said "image mimetype or upload/insert it." we will discuss a solution. just keep it open to let's keep it in mind:-)

**Comment by tomtomme** [comment] 2024-12-07 19:24
Still valid for 0.19.2 beta.
Copy pasting to Word/Excel within Firefox/Edge does not work.
GoogleDocs is fine however. Also saving the image first as png locally and inserting it then works fine too.

**Comment by tomtomme** [comment] 2024-12-14 14:29
closing as duplicate of internal https://github.com/jasp-stats/INTERNAL-jasp/issues/2456

**Closed by tomtomme** 2024-12-14 14:29 UTC
Labels: OS: Linux / Flatpak, Bug: Medium, OS: Windows 11
