### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly

### ISSUE THREAD

**Issue by AntonioJSCouto** [jasp-stats/jasp-issues#1761] opened 2022-06-26 01:03 UTC
### JASP Version

0.16.3

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This analysis terminated unexpectedly.

Error in bars[[node]] <- pnorm(GroupThresh$est[GroupThresh$lhs = GroupVars$name[node]]): attempt to select more than one element in integerOneIndex

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

SEM(...)

.semPathPlot(modelContainer, dataset, options, ready)

.semCreatePathPlot(modelContainer[['results']][['object']][[1]], NULL, pcont, options, ready)

.suppressGrDevice(semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE))

eval(plotFunc, parent.frame())

eval(plotFunc, parent.frame())

semPlot::semPaths(object = po, layout = 'tree2', intercepts = FALSE, reorder = FALSE, whatLabels = ifelse(options[['pathPlotPar']], 'par', 'name'), edge.color = 'black', color = list(lat = '#EAEAEA', man = '#EAEAEA', int = '#FFFFFF'), title = FALSE, legend = options[['pathPlotLegend']], legend.mode = 'names', legend.cex = 0.6, label.cex = 1.3, edge.label.cex = 0.9, nodeNames = decodeColNames(po@Vars$name), nCharNodes = 3, rotation = 2, ask = FALSE)

### Expected Behaviour

The analysis ended successfully.

### Steps to Reproduce

1. N/A
2. 
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-06-27 07:53
thanks for reporting the issue. this seems to be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1617, and that should be fixed with version 0.17.

**Closed by juliuspf** 2022-06-27 07:53 UTC
