### ISSUE TITLE
[Feature Request]: Distribution Plot with Percentiles

### ISSUE THREAD

**Issue by Reardon7** [jasp-stats/jasp-issues#2616] opened 2024-02-28 18:31 UTC
### Description

Show continuous variable in bins with percentile in each bin

### Purpose

Alternative way to show distribution of continuous results

### Use-case

Anytime distributions can be shown in bins

### Is your feature request related to a problem?

There is no problem with the program.  Just a desire for a "better" way to display results

### Is your feature request related to a JASP module?

Distributions

### Describe the solution you would like

I'd like to be able to display one or more continuous variables in a graph wherein each variable is shown along the x-axis, grouped into a user selected number of bins showing the percentage in each bin and, most ideally, the bin colors changing along a gradient.  See example

### Describe alternatives that you have considered

This can probably be done in Excel, but it would be great to see it in Jasp

### Additional context

![distribution](https://github.com/jasp-stats/jasp-issues/assets/17473175/fabc7942-e2b5-4872-bb85-4fba24024e35)

Below is the published paper that shows in Figure 1 how survey respondents responses to several continuous scales were divided into bins, displayed across an x axis with the percentage of the respondents in each bin shown in each bin.

https://www.cureus.com/articles/124269-effects-of-pressure-to-abort-on-womens-emotional-responses-and-mental-health#!/

**Comment by tomtomme** [comment] 2024-02-28 19:23
@Reardon7 
Thx for the request. This seems to be a duplicate of this issue: https://github.com/jasp-stats/jasp-issues/issues/1734
Am I right?
Then we could close this one and discuss over there.

**Comment by Reardon7** [comment] 2024-02-28 19:31
It may overlap that request.  I have no objection to you moving it over
there, if you feel that is best.

**Comment by Reardon7** [comment] 2024-02-28 19:56
Perhaps the biggest difference is that the variable I have is continuous,
over 100 pts, and so it also needs to be binned into 3-5 groups before
being plotted.

**Comment by tomtomme** [comment] 2024-02-29 07:10
@Reardon7 
But thats exactly like this one from #1734 
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/bd3c1b84-2aca-470d-be40-ce0361613a8c)

Only difference to me is that its 0-centered and yours starts at 0. Right?

**Comment by Reardon7** [comment] 2024-02-29 13:38
It also shows percentages from each bin.  I'm unfamiliar with what is shown
to be able to tell if there are other differences.

**Closed** 2024-02-29 14:10 UTC
Labels: Component: Result Plots, Module: jaspVisualModeling, Module: jaspDescriptives, Feature Request
