### ISSUE TITLE
JASP freezes when clicking on 'computer files/browse'

### ISSUE THREAD

**Issue by Filiol** [jasp-stats/jasp-issues#473] opened 2019-09-03 18:46 UTC
JASP version: 0.10.2
* OS name and version: Chrome OS 76.0.3809.136 
Bug description: Jasp freezes when I go to open -- computer -- browse/documents/desktop. I have to manually shut down the program and due to that I can't import any data files or use JASP.

**Comment by JorisGoosen** [comment] 2019-09-10 12:14
That is a shame but also a duplicate of https://github.com/jasp-stats/jasp-issues/issues/466

**Closed by JorisGoosen** 2019-09-10 12:14 UTC
