### ISSUE TITLE
[Feature Request]: Add Contrast Feature to Bayesian ANOVA and ANCOVA

### ISSUE THREAD

**Issue by cemsaunders** [jasp-stats/jasp-issues#1724] opened 2022-05-31 04:42 UTC
### Description

Add Contrast Feature to Bayesian ANOVA and ANCOVA

### Purpose

To allow for the bayesian analysis of a-priori orthogonal contrastss

### Use-case

ANOVA and ANCOVA represent two of the most popular experimental analyses in psychology. In designs with more than two groups it is essential to analyse contrasts (main and interaction) to determine group differences. Therefore, to facilitate widespread adoption of bayesian style analyses we should be able to conduct these analyses within JASP

### Is your feature request related to a problem?

Currently the only option in Bayes ANOVA/ANCOVA is to use post hoc tests to assess group differences, which is not sufficient to test pre specified orthogonal contrasts. See also: https://forum.cogsci.nl/discussion/7344/conducting-orthogonal-planned-contrasts-within-bayesian-ancova-in-jasp-bayes-factor

### Describe the solution you would like

In the ANOVA function of jasp there is a section to specify and analyse contrasts, ideally this functionality should also be incorporated in to the Bayesian ANOVA and ANCOVA

**Comment by EJWagenmakers** [comment] 2022-05-31 07:15
Great suggestion, but one that requires additional statistical development

**Comment by tomtomme** [comment] 2024-01-31 20:46
Closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/28

**Closed by tomtomme** 2024-01-31 20:46 UTC
Labels: Feature Request
