### ISSUE TITLE
[Feature Request]: Indicate one-tailed post-hoc t-tests in RM ANOVA (or even add a toggle to select between them).

### ISSUE THREAD

**Issue by majorminors** [jasp-stats/jasp-issues#2132] opened 2023-05-11 16:00 UTC
### Description

Currently, as far as I can tell, there is no indication that post-hoc t-tests in the RM ANOVA module is one-tailed. I had to independently check. It would be nice to indicate the tails, as you already do for e.g. number of Bonferroni corrections. As a strech goal it would be wonderful to select between tails.

### Purpose

Indicate and/or specify the tails of post-hoc t-tests.

### Use-case

For example, when predicting no-difference between conditions, I would prefer a two-tailed t-test.

### Is your feature request related to a problem?

There doesn't seem to be clear indication about this anywhere? Might be I'm bad at looking. It's worth noting that two-tailed tests are the default for the t-test module.

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

Indicate via the Table and/or permit toggling of the tails of post-hoc t-tests.

### Describe alternatives that you have considered

Just double the p-value in a calculator or in your head if you're nutty like that.

### Additional context

No other context. Always good to say how great JASP is though!

**Comment by tomtomme** [comment] 2024-02-08 08:58
@majorminors 
Confirmed. Still valid for (RM) AN(C)OVA in jasp 0.18.3. Also the help files do not mention this.
- I consider this a bug: no mention of 1vs2sided
- And a feature request: adding option to switch like in t-Tests

**Comment by JohnnyDoorn** [comment] 2024-02-08 09:54
hi @majorminors ,

Why do you think the RM ANOVA has one-tailed posthoc tests? As far as I know, they are two-sided:
<img width="570" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/15704203/f412a642-9f94-4696-a9b4-622ca74e8926">

Kind regards
Johnny

**Comment by tomtomme** [comment] 2024-02-08 10:03
@JohnnyDoorn 
Good point. I checked for normal ANOVA and there they seem two sided too!
However it still would be cool if this would be mentioned at least in the help files, no?

**Comment by JohnnyDoorn** [comment] 2024-02-14 11:12
Posthoc tests are always two-sided: since they are done "after the fact", while choosing between one-sided and two-sided *should* be done before the data analysis. Closing this issue now because I do not think it's relevant.

**Closed by JohnnyDoorn** 2024-02-14 11:12 UTC
Labels: Module: jaspAnova, Feature Request, Bug: High

**Comment by majorminors** [comment] 2024-02-27 16:44
Hm. Apologies for my delayed reply here. I actually can't remember, nor unfortunately can I remember what dataset I was working with last May, so I can't try to figure out what I was doing. I wonder if perhaps I made some error in calculation related to Bonferroni correction, given that I mention that in my issue. I agree this is the sensible default (as I seem to be puzzled by in the issue).
