### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jubera** [jasp-stats/jasp-issues#1284] opened 2021-05-04 19:32 UTC
Hi, 

I am trying to perform a Bayesian Generalized Linear Mixed Models analysis (family Binomial, link Logit), but I get the following error:

--------
This analysis terminated unexpectedly.

Error in if (nrow(temp_summary) = 1) {: argument is of length zero

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mmRunAnalysis(jaspResults, dataset, options, 'BGLMM')

.mmSummaryStanova(jaspResults, dataset, options, type)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
---------

Could you maybe help me to solve it, please?

Thanks in advance!

Esperanza

**Comment by jubera** [comment] 2021-05-07 10:20
I forgot to mention the following details: 

JASP version:0.14.1
OS name and version: Mojave 10.14.6
Analysis: Bayesian Generalized Linear Mixed Models (family Binomial, link Logit)
Bug description: Error when introducing a covariate

**Comment by jubera** [comment] 2021-05-07 10:35
Steps to reproduce:

- Go to the following link to download the .csv that I am using. Open it in JASP. Change "SsID" to nominal variable, and "Session" to ordinal:
https://www.dropbox.com/s/40ppukkm9mf70y3/TDT_5trials_before_TP_Accuracies_new_no_first_blocks.csv?dl=0

- Click on "Mixed Models" --> Bayesian Generalized Linear Mixed Models
- Family should be "Binomial", and Link, "Logit"
- Input "content_new" as dependent variable, "ACClet_TP", "ACCtarget_TP" and "Session" as fixed effects variables, and "SsID" as Random effects grouping factors
- In "Random effects", deselect all Random slopes
The error quoted above should be produced.

Thanks for your help

**Comment by FBartos** [comment] 2021-05-11 16:11
Hi @jubera ,

thank you very much for reporting the issue and the great number of details for reproducing it. It really helps o lot!
I'm working on fixing it.

Best,
Frantisek

**Comment by jubera** [comment] 2021-05-12 07:07
That's great news! Thanks for your help @FBartos

**Comment by FBartos** [comment] 2021-05-12 10:30
I'm closing the issue since the fix is already implemented in the development branch (and nightlies). It will be in the next release version. Thanks for the report!

Best,
Frantisek

**Closed by FBartos** 2021-05-12 10:30 UTC

**Comment by jubera** [comment] 2021-05-12 10:38
Thank you very much @FBartos !  I will check it out
