### ISSUE TITLE
Relocate Dunn post hoc test

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#656] opened 2020-04-02 10:33 UTC
* Enhancement: When performing the Friedman non-parametric test, the Conover's post-hoc test is located at the same menu just below the main options of the test (see the attached screenshoot below).

![Captura de pantalla 2020-04-02 a las 12 19 44](https://user-images.githubusercontent.com/29978768/78238001-57a0bb00-74dc-11ea-8653-3a4a0258f969.png)

However, this is not the case for the Kruskal-Wallis test, the Dunn's test is located with the other post-hoc tests in its own menu and it is a bit confusing (see the attached screenshoot below).

![Captura de pantalla 2020-04-02 a las 12 23 31](https://user-images.githubusercontent.com/29978768/78238454-e6add300-74dc-11ea-8051-ae21dcd023f1.png)

* Purpose: To locate the non-parametric post-hoc tests in the same way for both non-parametric test, just for coherence

* Use-case: To facilitate the comprehension and the workflow of the statistics tests 

**Additional context**

**Comment by tomtomme** [comment] 2024-01-04 18:30
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/383

**Closed** 2024-01-04 18:30 UTC
Labels: Module: jaspAnova
