### ISSUE TITLE
Missing Data Analysis and Imputation.

### ISSUE THREAD

**Issue by Nutriscience** [jasp-stats/jasp-issues#2107] opened 2023-04-22 07:30 UTC
### Description

Adding the ability to analyze missing data and implement appropriate procedures of missing data imputation.

### Purpose

Missing Data Analysis and Imputation.

### Use-case

Missing Data is a pervasive problem in the analysis of data which, more often than not, cannot be avoided. Unfortunately, listwise deletion of data is the most common solution for this problem and not always the most appropriate. A package implementation in Jasp that would help in the pattern recognition and analysis of missing values would greatly enhance the quality of many analyses and provide valuable information when reporting the results of a study. In addition, the implementation of modern and appropriate imputation methods would greatly enhance the usefulness of Jasp.

See:
- https://rdcu.be/daumS
- https://psycnet.apa.org/doiLanding?doi=10.1037%2Fmet0000563

### Is your feature request related to a problem?

Missing Data is a pervasive problem in the analysis of data which, more often than not, cannot be avoided.

### Is your feature request related to a JASP module?

Unrelated, Other

### Describe the solution you would like

Implementing functionality that is found in r packages such as mice or in software such as Blimp Studio.

### Describe alternatives that you have considered

In R a number of packages such as mice, Amelia and others are available. Blimp Studio has excellent missing data imputation capabilities.

See:
- https://github.com/amices/mice
- https://github.com/IQSS/amelia
- https://www.appliedmissingdata.com/blimp

### Additional context

It would be great if those capabilities could be implemented in Jasp :)

**Comment by EJWagenmakers** [comment] 2023-04-22 08:57
This ranks very high on our list of priorities!

**Comment by Apra119** [comment] 2023-09-07 06:34
Can JASP implement the most recent missing data package in R, which called as Model Based Treatment of Missing Data or mdmb package?
https://cran.r-project.org/web/packages/mdmb/index.html

**Comment by tomtomme** [comment] 2024-01-25 11:08
@Apra119 
MICE is now tracked here: https://github.com/jasp-stats/jasp-issues/issues/2437
If we get it in for the 0.19 release, could you test the implementation then and report in issue 2437 if this is sufficient?
If not, chime in there, regarding mdmb or rename this issue to "implement mdmb" or similar.
thx

**Comment by tomtomme** [comment] 2024-02-08 09:47
Closing as duplicate of #2437 for now

**Closed by tomtomme** 2024-02-08 09:47 UTC
Labels: Feature Request, Data Editing
