### ISSUE TITLE
Feature request: Bayesian Kruskal Wallis/ "Non-parametric" BANOVAs

### ISSUE THREAD

**Issue by AugustOlsson** [jasp-stats/jasp-issues#284] opened 2019-01-07 15:43 UTC
First, I am thankful for the inclusion of the Bayesian Mann-Whitney test in the latest update of JASP.

Enhancement request: A Baysian verison of Kruskal-Wallis H-test and/or other baysian versions of non-parametric tests for data with an independent variable with three or more levels (such as Van der Waerden test) would be very useful.
Purpose/Use-case: We often work with an independent variable with more than two levels, making Kruskal-Wallis H-test or similar rank-based tests neccesary for testning data not fullfilling assumptions for parametric testing. 

Best,
August

**Comment by EJWagenmakers** [comment] 2019-01-09 13:36
Great suggestions!
@JohnnyDoorn ?

**Comment by CharlesCousyn** [comment] 2021-04-26 18:56
Any news from this feature? I'm very interested to perform with JASP a Bayesian non parametric One Way Anova in my current project. (Bayesian equivalent of Kruskal-Wallis H-test)

**Comment by JohnnyDoorn** [comment] 2021-04-26 20:34
Hi @CharlesCousyn,

Unfortunately we are still in the research phase with this analysis (there is no comprehensive way for a Bayes factor for this test yet, as far as I know), so it will still take some time before this analysis can be in JASP (perhaps a year or so).

Kind regards,
Johnny

**Comment by CharlesCousyn** [comment] 2021-04-26 21:23
Thank you for your response
I understand! Good luck with that!

**Comment by maomiaopeng** [comment] 2022-11-17 04:27
Hi @JohnnyDoorn, I am also very interested in this feature. Any updates for it? Thanks!

**Comment by JohnnyDoorn** [comment] 2022-11-18 18:03
Hi @maomiaopeng, 

My own research has unfortunately shifted to other topics, and the development of this test had never quite taken off I'm afraid. My hope is that other researchers develop a Bayes factor Kruskal-Wallis test, which we could then implement in JASP. For now, if you are only interested in the one-way case, you could take a look at transforming your dependent variable to ranks, and then performing a Bayesian ANOVA. This is based on the approach by
Conover, W. J.; Iman, R. L. (1981). Rank transformations as a bridge between parametric and nonparametric statistics. American Statistician. 35 (3):
You can read more about the approach (which is quite rough, but ought to be a decent alternative) [here.](https://en.wikipedia.org/wiki/ANOVA_on_ranks). 

Kind regards
Johnny

**Comment by maomiaopeng** [comment] 2022-11-19 03:14
@JohnnyDoorn, Thank you so much for the help! I'll read them and try. 
Wish you all the best in the other topics!

**Comment by andrianarimisa** [comment] 2024-02-13 14:27
Let's suppose that I **found 30%, 25%, 25% , 10%, and 10% the responses** of people that I interviewed respectively choosing  event A, B, C, D, and E... If I want to use "inductive approach" for the analysis as I want to propose a general theorie on it, without doing inferentiel statistique , could someone help me to find the best way to do it...

**Comment by JohnnyDoorn** [comment] 2024-02-13 14:59
@andrianarimisa What sort of test do you want to do? Do you want to test whether these percentages/counts meaningfully differ from uniformly distributed frequencies (i.e., 20%)? In that case, I would suggest conducting a (Bayesian) multinomial test where you specify your observed counts. 
Also I am not sure this is the best platform to ask your question - you can also use the[ JASP forum ](https://forum.cogsci.nl/categories/jasp-bayesfactor)

**Comment by tomtomme** [comment] 2024-02-18 20:43
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/1531
That one is about classic and bayesian versions of those tests and has more references, so let's discuss there.

**Closed by tomtomme** 2024-02-18 20:43 UTC
Labels: Module: jaspAnova, Feature Request

**Comment by andrianarimisa** [comment] 2024-06-17 10:54
I got a critics from a rewier on a manuscript because of the test I use for a percentage data (Student T.test) : It is the percentage of individuals of Sp1 and Sp2 of Mosquitos captured in seven sites, which means percentage of individuals with   Plasmodium in their Salivary gland.

I did t-test as the data  are normally distributed - but the critique is Student t.test is far from appropriate to compare proportion data .. but find more appropriate test  - which ones ?

Below is the data

Mosquito.sp1<-c(68.42, 51.43,11.27,100,47.06,42, 25.33)

Mosquito.sp2<-c(80,68.54,71.55,84.62,91.43,62)

Can anyone help me  ? Why and what other thests sould I use to compare percentage data then ?

Cheers



________________________________

**Comment by JohnnyDoorn** [comment] 2024-06-17 11:18
Hi @andrianarimisa ,

So you want to test whether there is a significant difference in percentages between sp1 and sp2, across these different sites? Do you have the raw data instead of only percentages? Because then you could run a contingency table on the counts of sp1/sp2 and whether there is plasmodium, maybe conditional on the sites where you measured. This would result in a series of 7 chi squared tests. You could combine the counts if you want to assume there is no difference between the 7 sites.

Cheers,
Johnny

**Comment by andrianarimisa** [comment] 2024-06-17 12:19
Yes, I want to compare the difference if there is a significant difference of the percentage between Sp1 and Sp2... I do not have in total the rough data as some where from a person involved in the study - unfortunately for Sp 2 ---

One idea I had , but I dont know if it is correct : just supposing that all individuals captured and tested were based on 100 individuals so if of them

Mosquito.sp2<-c(80,68.54,71.55,84.62,91.43,62) - something like 80 indiv; 67 indiv; 72 indiv, 85 etc... But I am alittle bit afraid as it might be cheating – so that's why I used proportion to let it be harmonized but I got that "reviewer comments... And I am get stuck !

Regards,
Aristide
________________________________

**Comment by andrianarimisa** [comment] 2024-06-17 12:23
By the way, is there a real "reference stated " that t-test is not appropriate for proportion ? I was looking on the web all references but did not find any , that's why I am asking..

Cheers
________________________________
