### ISSUE TITLE
Stacked bar chart option for descriptive statistics

### ISSUE THREAD

**Issue by averixus** [jasp-stats/jasp-issues#1415] opened 2021-09-11 12:52 UTC
Enhancement: An option to create stacked bar charts in descriptive statistics, with multiple variables combined into a single bar.

Purpose: To display multiple variables in combination rather than only in the form of separate charts.

**Comment by tomtomme** [comment] 2024-01-06 15:14
duplicate of
https://github.com/jasp-stats/jasp-issues/issues/2177
https://github.com/jasp-stats/jasp-issues/issues/1734

**Closed by tomtomme** 2024-01-06 15:14 UTC
Labels: Graphs/Plots, Module: jaspDescriptives, Feature Request
