### ISSUE TITLE
[Bug]: Latent Growth modeling error

### ISSUE THREAD

**Issue by joanbak** [jasp-stats/jasp-issues#2511] opened 2024-01-05 05:52 UTC
### JASP Version

0.18.2

### JASP Module

SEM

### What analysis are you seeing the problem on?

Latent Growth modeling

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![스크린샷 2024-01-05 143833](https://github.com/jasp-stats/jasp-issues/assets/155708592/1e5f5a28-b7cf-4aa4-b9b0-e149472caccb)

### Expected Behaviour

잠재성장곡선 분석 시 variables를 투입하고 factor에 성별을 넣으면 바로 에러가 납니다
![스크린샷 2024-01-05 144505](https://github.com/jasp-stats/jasp-issues/assets/155708592/306aac44-9b10-4ee1-963d-f007843bd7a5)

### Steps to Reproduce

1. sem
2. variables
3. factor ; gender

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-01-09 19:22
Can you upload your .jasp file, so that we can try to reproduce the error?

**Comment by tomtomme** [comment] 2024-01-09 19:28
I am closing this one, since it seems to be a duplicate of your issue report right before this one. Feel free to reopen, if I am mistaken.

**Closed by tomtomme** 2024-01-09 19:28 UTC
Labels: waiting for requester, Module: jaspSem, OS: Windows 11, Bug
