### ISSUE TITLE
Enhancement: Zenodo for DOI generation and archiving

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jasp-issues#1341] opened 2021-06-15 10:52 UTC
* Enhancement: Let Zenodo automatically archive each version and create a DOI
* Purpose: Even more transparency and citability, less manual maintenance
* Use-case: Anyone who wants to refer to, or gain insight into each version of JASP

**Is your feature request related to a problem? Please describe.**

Currently there are >1 ways to find a citable reference:
- https://jasp-stats.org/faq/how-do-i-cite-jasp/, which isn't actually correct in my case, as I'm using version 0.14.**3** instead of 0.14.**1** (but I get linked here from within JASP -> About -> Citation)
- https://github.com/jasp-stats/jasp-desktop#citation-details, which is deprecated, still showing version 0.10.2

**Describe the solution you'd like**

1. Integrate Zenodo to JASP GitHub project to get DOI, see e.g. https://guides.github.com/activities/citable-code/
2. Refer from https://jasp-stats.org/faq/how-do-i-cite-jasp/ to the Zenodo DOI.
3. Refer from JASP -> About -> Citation to https://jasp-stats.org/faq/how-do-i-cite-jasp/.
4. Replace https://github.com/jasp-stats/jasp-desktop#citation-details with the nice Zenodo DOI badge.

**Additional context** 
With version 0.15 coming up, this may be actually a good time :-).

**Comment by tomtomme** [comment] 2024-02-10 17:17
Closing since now duplicate of: https://github.com/jasp-stats/jasp-issues/issues/875
All citation issues combined now there.

**Closed by tomtomme** 2024-02-10 17:17 UTC
Labels: Feature Request, installing
