### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.  Error in .extractErrorMessage(e): length(error) = 1 is not TRUE

### ISSUE THREAD

**Issue by ShunitAm** [jasp-stats/jasp-issues#2704] opened 2024-05-06 09:07 UTC
### JASP Version

0.18.3

### JASP Module

Network

### What analysis are you seeing the problem on?

classical network analysis

### What OS are you seeing the problem on?

Windows 11

### Bug Description

  Whenever i'm trying the bootstrap options- bootsrap network i get this erorr massage:

This analysis terminated unexpectedly.

Error in .extractErrorMessage(e): length(error) = 1 is not TRUE

Stack trace
.networkAnalysisBootstrap(mainContainer, network, options)

.networkAnalysisComputeBootstrap(bootstrapContainer, network, options)

tryCatch({
    jaspBase::.suppressGrDevice({
        for (nm in names(allNetworks)) {
            bootstrapResult[[nm]] <- bootnet::bootnet(data = allNetworks[[nm]], nBoots = options[['bootstrapSamples']], type = options[['bootstrapType']], nCores = nCores, statistics = c('edge', 'strength', 'closeness', 'betweenness'), labels = options[['variables']])
        }
    })
}, error = function(e) bootstrapContainer$setError(.extractErrorMessage(e)))

tryCatchList(expr, classes, parentenv, handlers)

tryCatchOne(expr, names, parentenv, handlers[[1]])

value[[3]](cond)

bootstrapContainer$setError(.extractErrorMessage(e))

private$jaspObject$setError(x)

.extractErrorMessage(e)

stopifnot(length(error) = 1)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
![Screenshot 2024-05-06 114531](https://github.com/jasp-stats/jasp-issues/assets/169034476/2e8c4280-27da-4475-9b4b-2588e3ade222)

### Expected Behaviour

It should give me the data

### Steps to Reproduce

1.classical network analysis
2.added the variables
3.network plot+clustering plot
4. bootstrap options- bootstrap network- number of bootstrap- i tried 100 and 1000
...

### Log (if any)

[JASP 2024-05-06 10_51_23 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/15218698/JASP.2024-05-06.10_51_23.Desktop.log)
[JASP 2024-05-06 10_51_23 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/15218699/JASP.2024-05-06.10_51_23.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-05-06 10:01
Appending the file via mail does not work, sorry. Pleas drag and drop as described above.

**Comment by ShunitAm** [comment] 2024-05-06 10:20
I've already sent it to- ***@***.***
and i've sent it again now as zip file

‫בתאריך יום ב׳, 6 במאי 2024 ב-13:02 מאת ‪Thomas Langkamp‬‏ <‪
***@***.***‬‏>:‬

**Comment by EJWagenmakers** [comment] 2024-05-07 07:05
I'll forward this file to Don.

**Comment by tomtomme** [comment] 2024-05-24 10:48
@vandenman 
Did you have a chance to look at that file? Can you reproduce the bug on windows?

**Comment by sitnok67155** [comment] 2024-08-05 19:51
Hi,

I have the same problem on Windows when trying to use the bootstrapping feature when running a classical network analysis.

Is there a known fix for this? I must analyse my data by the end of the week but can't if I am unable to employ bootstrapping.

<img width="851" alt="image" src="https://github.com/user-attachments/assets/1eaff2ee-50ae-415e-853e-a9eff724c283">

**Comment by tomtomme** [comment] 2024-09-02 09:06
@sitnok67155 
@ShunitAm 

Is this still a problem with JASP 0.19? 

@sitnok67155 
Can you share the data file here by renaming to zip and drag and dropping it here?

**Comment by ShunitAm** [comment] 2024-09-04 07:30
I gave up

‫בתאריך יום ב׳, 2 בספט׳ 2024 ב-12:06 מאת ‪Thomas Langkamp‬‏ <‪
***@***.***‬‏>:‬

**Comment by tomtomme** [comment] 2024-09-04 08:42
So you do not know if the error persists with 0.19?

**Comment by ShunitAm** [comment] 2024-09-04 10:01
I do not

בתאריך יום ד׳, 4 בספט׳ 2024 ב-11:43 מאת Thomas Langkamp <
***@***.***>:

**Comment by tomtomme** [comment] 2024-09-06 08:08
This seems to be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2863 and it only occurs with certain data + nonparametric or case type bootstrap. 
With the example from the data library everything is fine. 
I wil close this one, so that we can discuss all this at #2863

**Closed by tomtomme** 2024-09-06 08:08 UTC
Labels: Waiting for requester, Module: jaspNetwork, OS: Windows 11

**Comment by tomtomme** [comment] 2024-09-19 06:50
@ShunitAm @sitnok67155 

More Infos on this but from vandenman, who wrote this in https://github.com/jasp-stats/jasp-issues/issues/2088:

>     Thanks for reporting the issue! What goes wrong internally is that the correlation matrix is not positive definite. If you change the correlation method to Cor or the method for Missing values to Exclude listwise then the error disappears and you do get output. I'll adjust the code so you receive a more informative error message in the future.

Also switching form non-parametric to parametric bootstrapping could help

Sorry for the huge delay. The better error message for the network module was added at some point but seems not to work in all cases. We will work on a fix.
