### ISSUE TITLE
MW test - different formulas available, so add a note under the table of the test

### ISSUE THREAD

**Issue by chantelanuit** [jasp-stats/jasp-issues#452] opened 2019-08-14 03:51 UTC
* Enhancement: Add a note under the independent sample comparison table for the MW test
* Purpose: There are several formulas available for computing the p-value of the WMW test. 
* Use-case:

**Is your feature request related to a problem? Please describe.**
 
Since several formulas are available (depending on the way the algorithm handle the ties), asymptotic vs exact test, even in R (e.g. wilcox.test vs coin, the latter computes the exact p-value), it might be useful to add a reference under the table to indicate what formula was used (reference to a scientific paper would be useful). That would be important for comparison between results outputed by different software. For instance, the value provided by JASP does not necessarily match the values provided by SPSS when the Mann-Whitney test is used.

**Describe the solution you'd like**
 
Please add a reference under the table to indicate what formula was used 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by tomtomme** [comment] 2024-01-01 18:37
Still relevant and also a problem for other non-parametrics like Spearmans Rho, see https://github.com/jasp-stats/jasp-issues/issues/1364

**Comment by tomtomme** [comment] 2024-02-10 17:48
closed as duplicate of https://github.com/jasp-stats/jasp-issues/issues/2529 where all documentation issues are gathered

**Closed by tomtomme** 2024-02-10 17:48 UTC
Labels: Module: jaspTTests, Feature Request
