### ISSUE TITLE
Cohen's d confidence intervals: Slight difference between R and JASP

### ISSUE THREAD

**Issue by chantelanuit** [jasp-stats/jasp-issues#525] opened 2019-10-20 15:01 UTC
* JASP version: 0.11.1

* OS name and version: Win10-64

* Analysis: Independent samples T-Test

* Bug description: **Cohen's d confidence intervals: Slight difference between R and JASP**

* Add JASP files as a zip: see linked document below

* Screenshot: See document below

* Expected behaviour: **Results must converge with the effsize package**
**> packageVersion("effsize")
[1] '0.7.6'**

* Steps to reproduce: 

- **R vs JASP**: https://www.dropbox.com/s/0zd4ea8ppf6o3pn/JASP%20vs%20R%20-%20Cohen%27s%20d.docx?dl=0

- **JASP file**: https://www.dropbox.com/s/4pl3rxv568gyk3z/fume-poids-naissance.jasp?dl=0

- **R dataset**: https://www.dropbox.com/s/ydwuqf6wtadiugq/fpn.RData?dl=0

- **R Script**: https://www.dropbox.com/s/ujedokvvlqphjqh/RSyntax.R?dl=0

**Comment by TimKDJ** [comment] 2019-10-21 07:58
@Kucharssim could you have a look at this?

**Comment by Kucharssim** [comment] 2019-10-21 09:43
Dear @chantelanuit,

thank you for your question! Indeed, in case of the use of Welch t-test, JASP gives different CIs than you can obtain using effsize package. This is a feature rather than a bug. I'll try to explain on the example you provided.

1) We use non-central t-distribution to find the confidence interval. effsize package uses normal approximation by default. In case of confidence intervals for Cohen's d after conducting Student's t-test (assuming equal variances), you can obtain the JASP confidence intervals with effsize package using `effsize::cohen.d(fpn$POIDS.NAIS~fpn$FUME, noncentral=TRUE)`. Note that in this case, the point estimate of Cohen's d is calculated as the difference of means divided by the pooled standard deviation (and is about 0.395353789111493).

2) In case of Welch t-test, the point estimate of Cohen's d is calculated as the difference of means divided by the averaged standard deviation (see https://www.ncbi.nlm.nih.gov/pubmed/18557680 or https://stats.stackexchange.com/questions/210352/do-cohens-d-and-hedges-g-apply-to-the-welch-t-test) and is about 0.400998205944287. effsize package (to my knowledge) cannot calculate this. If you need to reproduce the exact numbers in R, I would recommend using the MBESS package with the following:

```
g1 <- fpn$POIDS.NAIS[fpn$FUME == "not.smoking"]
g2 <- fpn$POIDS.NAIS[fpn$FUME == "smoking"]
m1 <- mean(g1, na.rm = TRUE)
m2 <- mean(g2, na.rm = TRUE)
v1 <- var(g1, na.rm = TRUE)
v2 <- var(g2, na.rm = TRUE)
avg.sd <- sqrt((v1+v2)/2)
d <- (m1 - m2)/avg.sd # 0.400998205944287
MBESS::ci.smd(smd = d, n.1 = sum(!is.na(g1)), n.2 = sum(!is.na(g2)))
```

which should give you the JASP results exactly.

I hope this clarifies things. I am not going to close this issue for now just to have a reminder that I should update the documentation for the t-tests, because this information should definitely be there.

**Comment by chantelanuit** [comment] 2019-10-21 12:52
Hello Simon,

Thank you for your detailed reply, very appreciated !

Have a nice day,

Michael

**Comment by Kucharssim** [comment] 2019-10-21 15:43
Great, happy to help! Thanks for pointing this out and providing a reproducible example.

**Closed by Kucharssim** 2019-10-21 15:43 UTC
