### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.  Error in modW ≠ '' && encoding$W %in% vars: 'length = 2' in coercion to 'logical(1)'

### ISSUE THREAD

**Issue by joana-cruz2003** [jasp-stats/jasp-issues#3109] opened 2024-12-26 15:15 UTC
### JASP Version

0.19.2

### JASP Module

Process

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This analysis terminated unexpectedly.

Error in modW ≠ '' && encoding$W %in% vars: 'length = 2' in coercion to 'logical(1)'

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.procModelSummaryTable(jaspResults, options, modelsContainer)

lapply(options[['processModels']], function(mod) {
    graph <- modelsContainer[[mod[['name']]]][['graph']]$object
    if (!igraph::is.igraph(graph))
        return(NULL)
    return(.procRecognizeModelNumber(graph))
})

FUN(X[[i]], ...)

.procRecognizeModelNumber(graph)

sapply(.procHardCodedModelNumbers(), .procIsModelNumberGraph, graph = graph, modelOptions = modelOptions, globalDependent = globalDependent)

lapply(X = X, FUN = FUN, ...)

FUN(X[[i]], ...)

.procModelGraphInputModelNumber(modelNumberGraph, modelOptions, globalDependent)

.procReplaceDummyVars(igraph::V(graph)$name, modelOptions = modelOptions, globalDependent = globalDependent)

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
![Captura de ecrã 2024-12-26 150909](https://github.com/user-attachments/assets/688956ac-253f-4f26-b3a2-4fe26005a1dc)
![Captura de ecrã 2024-12-26 150909](https://github.com/user-attachments/assets/a010d8e7-040f-4a99-9422-f90090a957fc)

### Expected Behaviour

Model Execution:

The analysis should run without errors.
JASP should compute the specified paths, direct effects, and covariances between variables.
Results Output:

The software should provide the following:
Path coefficients for the relationships you specified (e.g., from "Loneliness" → "Life_Satisfaction" and "Wellbeing" → "Loneliness").
Significance tests (e.g., p-values) for the coefficients.
Goodness-of-fit statistics for the model (e.g., R² for the dependent variable "Life_Satisfaction").
Model diagrams illustrating the paths and relationships.
Graphical Output:

A visual representation of the model, showing the dependent variable ("Life_Satisfaction"), predictors ("Loneliness" and "Wellbeing"), and their connections (paths).
Interactive Functionality:

Allow you to adjust the model configuration interactively (e.g., add/remove variables, modify paths) and rerun the analysis without encountering errors.

### Steps to Reproduce

1.Open the JASP Project:

- Load the same data file (ISSP Social Networks and Social Resources (2017) dataset) in JASP.

2. Set Up the Analysis:

- Select "Process" from the toolbar.
- Configure the dependent variable as "Life_Satisfaction."
- Add "Loneliness" and "Wellbeing" as continuous predictors.
- Use the current path configuration (as shown in the screenshot):
- Loneliness → Life_Satisfaction.
- Wellbeing → Loneliness.

3. Run the Model:

- Click to execute the analysis

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by joana-cruz2003** [comment] 2024-12-26 15:54
I have included a JASP file (zipped) or data file that causes the crash/bug:
[(Spain) ISSP Social Networks and Social Resources (2017) erro 2.zip](https://github.com/user-attachments/files/18253866/Spain.ISSP.Social.Networks.and.Social.Resources.2017.erro.2.zip)

**Comment by tomtomme** [comment] 2024-12-26 17:34
thx for the report. this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/3079 
Lets discuss there. Or reopen if you disagree!

**Closed by tomtomme** 2024-12-26 17:34 UTC
Labels: OS: Windows 10, Bug, Module: jaspProcess
