### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly.

### ISSUE THREAD

**Issue by irisfc** [jasp-stats/jasp-issues#2767] opened 2024-06-06 00:17 UTC
### JASP Version

0.18.3

### JASP Module

SEM

### What analysis are you seeing the problem on?

Confirmatory Factor Analysis

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Error in diag(scales) %*% truevar: non-conformable arguments

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.cfaTableReliability(jaspResults, options, cfaResult)

semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)

omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIn

### Expected Behaviour

it should have run the Analysis

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by irisfc** [comment] 2024-06-06 00:19
<img width="1440" alt="Captura de ecrã 2024-06-06, às 01 19 14" src="https://github.com/jasp-stats/jasp-issues/assets/171882580/f89a2145-bd5f-4dbe-8c10-e59357f55aaa">

**Comment by juliuspfadt** [comment] 2024-06-06 07:18
@irisfc thanks for creating this issue. It is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2294. For more information see the other issue.

**Closed by juliuspfadt** 2024-06-06 07:18 UTC
Labels: Module: jaspSem, OS: macOS Intel, Bug
