### ISSUE TITLE
[Bug]: Can't install JASP on linux

### ISSUE THREAD

**Issue by Dmente92** [jasp-stats/jasp-issues#1567] opened 2022-01-06 19:29 UTC
### JASP Version

0.16

### What OS are you seeing the problem on?

Manjaro 21.2.1

### Bug Description

I was trying to install JASP following the official instructions (https://jasp-stats.org/linux-installation-guide/) and the program doesn't install. This is the output from the terminal:

```
Error: While trying to checkout 44a616e5d125c1f4e80492dcfc2bb0149f4521fdb7e678b15875e8144f383c4e into /var/lib/flatpak/app/org.jaspstats.JASP/x86_64/stable/.44a616e5d125c1f4e80492dcfc2bb0149f4521fdb7e678b15875e8144f383c4e-H1YHF1: Opening content object 04c6c83427c8857c9fa7bed13e1b46997ba949ef994f7bd98a19c7abdbf85cfb: Couldn't find file object '04c6c83427c8857c9fa7bed13e1b46997ba949ef994f7bd98a19c7abdbf85cfb'
error: Failed to install org.jaspstats.JASP: While trying to checkout 44a616e5d125c1f4e80492dcfc2bb0149f4521fdb7e678b15875e8144f383c4e into /var/lib/flatpak/app/org.jaspstats.JASP/x86_64/stable/.44a616e5d125c1f4e80492dcfc2bb0149f4521fdb7e678b15875e8144f383c4e-H1YHF1: Opening content object 04c6c83427c8857c9fa7bed13e1b46997ba949ef994f7bd98a19c7abdbf85cfb: Couldn't find file object '04c6c83427c8857c9fa7bed13e1b46997ba949ef994f7bd98a19c7abdbf85cfb'
```

### Expected Behaviour

JASP should have been installed

### Steps to Reproduce

1. flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
2. flatpak install flathub org.jaspstats.JASP
3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2022-01-26 10:37
There exist other issues with flatpak installation. Some solutions have been already proposed. Can you have a look for example to these 2 issues:
#1424
#1511

**Comment by tomtomme** [comment] 2022-02-05 14:31
I can confirm this. At least my manjaro laptop showed this this week.
My fix was to install the Jasp Beta from the flatpak beta channel. That worked always for me since the flatpak issues began.

**Comment by tomtomme** [comment] 2022-11-08 19:59
This is resolved afaik. Stable Flatpak 0.16.3 and 0.16.4 worked nicely on manjaro

**Comment by juliuspf** [comment] 2022-11-09 08:42
Let's close it then. @Dmente92 feel free to reopen the issue if needed.

**Closed by juliuspf** 2022-11-09 08:42 UTC
Labels: waiting for requester, OS: Linux / Flatpak
