### ISSUE TITLE
[Bug]: error when requesting standardized estimates in SEM module

### ISSUE THREAD

**Issue by aazaragc** [jasp-stats/jasp-issues#3016] opened 2024-11-14 21:34 UTC
### JASP Version

0.19.1

### JASP Module

SEM

### What analysis are you seeing the problem on?

SEM

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I am learning how to conduct structural equation modeling analysis. I am following the example that is being shown in the following video: https://www.youtube.com/watch?v=fno5LC5cKdM. I am using the data set included with JASP - Political Democracy.

When I include the following syntax, the analysis works. 

#latent variables
ind60 =~ x1 + x2 + x3
dem60 =~ y1 + y2 + y3 + y4
dem65 =~ y5 + y6 + y7 + y8
#regressions
dem60 ~ alpha*ind60
dem65 ~ direct*ind60 + beta*dem60
#effects of interest
indirect := alpha * beta
total := indirect + direct
proportion := indirect/total
#residual covariances
y1 ~~ y5
y2 ~~ y4 + y6
y3 ~~ y7
y4 ~~ y8
y6 ~~ y8

But when I click on the "Standardized estimates" option in Output options, I receive the following error message. "This analysis terminated unexpectedly, Error in x$`[[<-`(i, value): Did not get a vector or list as column..

Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.semParameters(modelContainer, dataset, options, ready)

.semParameterTables(modelContainer[['results']][['object']][[1]], NULL, params, options, ready, modelContainer, dataset)

`[[<-`(`*tmp*`, 'std.nox', value = NULL)

`[[<-.jaspTableR`(`*tmp*`, 'std.nox', value = NULL)

x$.__enclos_env__$private$setField(field, value)

`[[<-`(`*tmp*`, field, value = NULL)

.local(x, i, j, ..., value = value)

x$`[[<-`(i, value)"

<img width="498" alt="Screenshot 2024-11-14 at 2 24 58 PM" src="https://github.com/user-attachments/assets/32ff5441-6618-4836-aa99-aa3b9a4edfb0">

I don't know what this means.
<img width="506" alt="Screenshot 2024-11-14 at 2 28 56 PM" src="https://github.com/user-attachments/assets/6b3455b1-e83c-4974-98c5-8ebc6f866145">

### Expected Behaviour

It should include the standardized estimates in the output.

### Steps to Reproduce

Error disappears when I unclick "Standardized Estimates" and it reappears when I click on "standardized estimates"

### More Debug Information

Yes, I am

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2024-11-15 08:24
@aazaragc thanks for reporting the issue. I tried this out now in a development version of JASP, and I cannot reproduce your error. This means this will be fixed in the upcoming release (a few weeks from now). If you dont want to wait you can try a development nightly version that contains the latest changes from here https://static.jasp-stats.org/Nightlies/

**Closed by juliuspfadt** 2024-11-15 08:24 UTC
Labels: Module: jaspSem, OS: macOS Silicon, Bug
