### ISSUE TITLE
Allow header titles for columns to be used as ordinals for ANOVA, or any other ordinal-dependent test

### ISSUE THREAD

**Issue by Chokyotager** [jasp-stats/jasp-issues#1267] opened 2021-04-24 10:13 UTC
* Enhancement: Use of column lines instead of scale/ordinal data to perform ANOVA
* Purpose: Ease of use in this system
* Use-case: Ease of use from data imports

**Is your feature request related to a problem? Please describe.**
Say a 2D dataset of scores for children in a class looks like this:

**Name TestA TestB TestC TestD**
Alice 78 67 90 65 70
Bob 80 58 55 77 70
Calvin 66 53 52 50 49

In the input values for Jasp right now, I have to key this data as such:

**Name Test Score**
Alice TestA 78
Alice TestB 67
Alice TestC 90
...
Bob TestA 80
Bob TestB 58
...

in order to perform ANOVA between the two series, and to get a plot for this. This is assuming I want to compare, say, the Student's t-distribution across the tests, directly.

I understand the current model for ordinals makes it much easier to switch between comparing the tests, than the individual students, but it makes it very difficult to format the data as such without using an external script.

**Describe the solution you'd like**
Allow for the header titles to be used as ordinals. It makes ANOVA testing a lot easier as the data does not have to be reshaped. This is similar to what can be done in GraphPad Prism.

Similarly, it could be nice if there is an option in the ANOVA plots to use bars instead of dots.

- Hilbert

**Comment by JohnnyDoorn** [comment] 2021-05-07 09:50
Hi @Chokyotager,

We are currently working on a data reshaping tool, so that you can switch between wide and long formats of data. I am not entirely sure of timeline here - it's probably not in the next version, but probably in the one after that one. 
@boutinb this is not really my thing though, so I'm unassigning myself here and you can assign the relevant developer.

Cheers
Johnny

**Comment by Chokyotager** [comment] 2021-05-22 11:21
Hi there,

Hopefully things can be improved this way! It'll make JASP a lot more usable.

Hilbert

**Comment by juliuspf** [comment] 2022-11-08 14:36
@JorisGoosen, is this something up your alley?

**Comment by JorisGoosen** [comment] 2022-11-09 10:55
Well as @JohnnyDoorn mentioned in his comment, this is related to [this issue about long <> wide transform](https://github.com/jasp-stats/jasp-issues/issues/33) and it certainly is up my alley. But progress for that (which has been lacking as we have been implementing other stuff before) will be tracked there.

> Similarly, it could be nice if there is an option in the ANOVA plots to use bars instead of dots.

This sounds more like @JohnnyDoorn s thing

**Comment by tomtomme** [comment] 2024-02-03 12:41
Since bar plots in ANOVA are done I am closing this one as duplicate of #33

**Closed by tomtomme** 2024-02-03 12:41 UTC
Labels: Module: jaspTTests, Module: jaspAnova
