### ISSUE TITLE
[Bug]: JASP 0.17.3 is very slow to open jasp files, indeed cannot open files bigger than 1 mb

### ISSUE THREAD

**Issue by ErPekerkan** [jasp-stats/jasp-issues#2263] opened 2023-08-16 14:04 UTC
### JASP Version

Others

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

On opening a file

### What OS are you seeing the problem on?

Windows 11

### Bug Description

I was previously using 0.17.1. I made several analyses in Feb and saved them as jasp files. I bought a new computer with OS Windows 11 . My previous OS was Windows 10. Couple of days ago I downloaded 0.17.3 version. I tried to open the files which I saved in Feb. Small size files (i.e. 62k) opened quickly with no problem. Files around 500 k opened after 2 or 3 minutes. Files above 900 k could not be opened even though I waited for 25 minutes. Funny enough, a jasp file which I saved in May after I bought my new computer opened very quickly despite its 6mb size. Note: The jasp files which I used in Feb contains big data (421 rows x 175 columns), file size is 1,256 kb, but it was working fine previously in my old computer with 0.17.1 version. What could be the problem?
![Ekran görüntüsü 2023-08-16 165418](https://github.com/jasp-stats/jasp-issues/assets/142411077/56b76fc9-547e-4cc7-abde-5f08d0c747b7)

### Expected Behaviour

My previous jasp files should be opened easily with no hassle.

### Steps to Reproduce

1. I reloaded jasp 0.17.1 to see if my previous files are opening properly but I had the same problems (either opening late or not opening at all).
2.
3.
...

### Log (if any)

[JASP 2023-08-16 16_49_32 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/12360210/JASP.2023-08-16.16_49_32.Desktop.log)
[JASP 2023-08-16 16_49_32 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/12360212/JASP.2023-08-16.16_49_32.Engine.0.log)
[JASP 2023-08-16 16_58_14 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/12360213/JASP.2023-08-16.16_58_14.Desktop.log)
[JASP 2023-08-16 16_58_14 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/12360214/JASP.2023-08-16.16_58_14.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment] 2023-08-16 18:40
Hi! Thanks for your report!

Does the jasp file contain any sensitive data? If not, would you be willing to share it with us ?
I will try to recreate the issue tomorrow with some of my own files otherwise.

We have changed many things for the next release we are preparing perhaps/hopefully the issue already resolved in one of our nightlies: https://static.jasp-stats.org/Nightlies/

-Rens

**Comment by ErPekerkan** [comment] 2023-08-16 18:47
Thanks for your response Rens. Unfortunately the jasp file contains very sensitive data, that's why I cannot share, sorry!

**Comment by RensDofferhoff** [comment] 2023-08-16 18:55
No problem, I'll make a file of similar size with JASP 0.17.1 and see what happens.
Does your data contain mixed types (scalar, nominal , ordinal) or predominantly one type?

-Rens

**Comment by ErPekerkan** [comment] 2023-08-17 04:43
All types but nominal is more common. Thx a lot.
Erkan

**Comment by RensDofferhoff** [comment] 2023-08-17 09:50
Hi I cannot recreate the issue at the moment.
Files of 10 MB with similar columns load pretty much instantly.
Could you tell me what sort of analyses are in the files?

-Rens

**Comment by JorisGoosen** [comment] 2023-08-17 10:25
I had a look in the logfiles and it seems that it contains at least 51 analyses, if I see it right?
Lots of Frequencies-Contingency-Tables

And it seems to get stuck loading numero 51 'Contingency Tables - Proteinuri - KA3 Tipine Göre'

@ErPekerkan when you are loading how is you memory-usage?
Also, this file still loads properly in the previous JASP release?

**Comment by ErPekerkan** [comment] 2023-08-17 12:02
Thank you Rens and Joris for your efforts to solve my roblem. As Joris said, lots of frequency and contigency tables. This file was being loaded in the previous version JASP 0.17.1. I downloaded this version (0.17.1) and tried to open the same file but it could not open it now. By the way, "numero 51 'Contingency Tables - Proteinuri - KA3 Tipine Göre' " is probably the last contigency table in the file). I will check with the memory usage now and let you know about it. Thx a lot. Erkan

**Comment by ErPekerkan** [comment] 2023-08-17 12:48
Dear Rens and Joris,
I have taken pictures of my task manager while I was loading the JASP file (which I could not open), so that you can see the details of processor. Sorry it is in Turkish. I hope you can figure the terms out from English Task Manager. However, "Bellek" is memory (RAM). "Ağ" is network, "Kullanım" is usage, "Hız" is speed. Please feel free to ask me if any translation is needed. Regards, Erkan
![Ekran görüntüsü 2023-08-17 151815](https://github.com/jasp-stats/jasp-issues/assets/142411077/a45a7a87-fa1c-49c8-87e6-ece8b9ea0629)
![Ekran görüntüsü 2023-08-17 151855](https://github.com/jasp-stats/jasp-issues/assets/142411077/3fb06f3a-da87-439a-9e85-c4de04eca03a)
![Ekran görüntüsü 2023-08-17 151947](https://github.com/jasp-stats/jasp-issues/assets/142411077/9c7fd509-ef95-460c-adcf-9cdb07fe8efd)
![Ekran görüntüsü 2023-08-17 152048](https://github.com/jasp-stats/jasp-issues/assets/142411077/d3b2718e-38e8-4e15-b0bc-c530e4055b8e)

**Comment by JorisGoosen** [comment] 2023-08-17 12:59
And it stays stuck with the loading/progressbar visible?

**Comment by ErPekerkan** [comment] 2023-08-17 13:48
Exactly

**Comment by JorisGoosen** [comment] 2023-08-17 14:05
So your file cant be opened in either 0.17.1 or 0.17.3?

because that would mean the file is broken somehow...

but without your jaspfile we cannot reproduce your problem it seems... Maybe you can share it via our email or something? because it seems like quite an annoying problem but im not sure how we can help you further without actually having something to work with

**Comment by ErPekerkan** [comment] 2023-08-17 15:56
You are right Joris that you cannot come up with an answer to my problem without having the file but the data is so sensitive that I signed an secrecy agreement with the association I work with, sorry!
I can further explain what I am facing: I did the analyses in Feb this year. Now new entries came (25 new responsents) so I need to re-run all these analyses. The data is big and I did many many analyses using descriptive statistics, Independent Samples T test, ANOVA, Correlation, Regression. In order not to crash the JASP program I did these analyses in different JASP files (there are roughly 15 files). My aim was to open these old files and re-run them with new enteries. The files with small sizes (around 100k) from these analyses opened very quickly. Files with medium size (around 500 kb) opened as well but it took a minute or 2 to be opened. When I want to work with these medium sized files some of the actions (eg. duplicating an analysis) takes a while (like 20-25 seconds) to respond (this was not happening before). Files over 900 kb from these analyses I cannot open. The files that can be opened  and cannot be opened use the same data file (.csv). I can give you one striking example: File named "AraAnaliz_1_Part1" cannot be opened (1,256 kb) and it has exactly the same statistics with the file named "AraAnaliz_1_Part1A" (515 kb) except that the former file has contigency tables with four and three columns and the latter has contingency table with only 2 columns. Rows are exactly the same. Number of tables in each files are the same.
Sorry it became a long mail, but I tried to express the problem I am facing. I can understand if you cannot come up with a solution. In the meantime I started re-running the analyses with the loadable files. I think I can live with that. I thank you very much for your kind efforts. Regards Erkan.

**Comment by EJWagenmakers** [comment] 2023-08-17 17:20
Suggestion: could you generate fake data with the same structure, showing the same problem?

**Comment by ErPekerkan** [comment] 2023-08-17 21:06
Hi EJ, I understand, you suggest me to produce fake .csv data with the same name as my previous JASP file using and try to open it again. I have a question here; Will JASP try to open the jasp file with the new fake .csv data synchronized and that there will be (let's say) newly calculated contigency tables. The reason that I am asking this is: If you try to open the Jasp file and if the file still uses the original .csv data or if the (cotingency tables) are not synchronized will you be able to see the original data or analyses? Please do not get me wrong but as I have mentioned before it is a sensitive data and I need to be careful. Regards Erkan.

**Comment by JorisGoosen** [comment] 2023-08-18 07:56
@ErPekerkan ah yes, well you definitely cant share the file then indeed..

The idea with a different synchronisation file could work.
However for that you need to be able to load it in the older jasp version right?
Which didnt work I think you said before?

If it *does* load and you have a fake-data-file then rerunning all the analyses and saving the file under another name will make sure the real data is not stored anywhere in there anymore.

**Comment by JorisGoosen** [comment] 2023-08-20 20:34
Ah you just press Ctrl/Cmd+R ^^

**Comment by ErPekerkan** [comment] 2023-08-21 16:15
Thank you very much Joris. Regards, Erkan

**Comment by ErPekerkan** [comment] 2023-08-23 21:36
Dear Joris,
About my aforementioned problem (that I could not open some of my previous files) I would like to share my problem with an example I happened to come across. I attached a jasp file which I produced with a fake data (nr of rows and columns are the same). It takes me 1 minute 15 seconds to open this file. I attach the log file as well. I will be grateful if you try to open the file and tell me your experience. Note-1: I noticed one thing with files which I cannot open or takes long time to open that is in these analyses (as you will see in the attached file) I asked for bootstrap confidence intervals. Note-2: As a comparison a Jasp file with 28 contingecy tables (size 243 kb) takes 15 seconds to open (I still find this a long time by the way). Note-3: In the attached file when I want to duplicate an analysis (descriptive with bootstrap confidence intervals) 12-15 seconds to respond.
My Best Regards, Erkan
[Analiz_Agustos2023_Fake.zip](https://github.com/jasp-stats/jasp-issues/files/12423514/Analiz_Agustos2023_Fake.zip)
[JASP 2023-08-24 00_04_11 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/12423524/JASP.2023-08-24.00_04_11.Desktop.log)
[JASP 2023-08-24 00_04_11 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/12423525/JASP.2023-08-24.00_04_11.Engine.0.log)

**Comment by JorisGoosen** [comment] 2023-08-30 11:40
Hey @ErPekerkan 

I am a bit busy with the release of 0.18 but I did manage now to download and testload your fake-data file.
It loads in 4 seconds on my computer, however this is a mac.
I will also try it on a windows computer.

**Comment by ErPekerkan** [comment] 2023-08-30 14:03
Thanks a lot I am grateful to you.

My computer is Lenovo Ideapad Flex 5i

12th Gen Intel(R) Core(TM) i5-1235U   1.30 GHz
RAM	8,00 GB (usable: 7,57 GB)
64 bit operating system, x64 processor based

Windows 11 Home Single Language
Edition	22H2

I am using Norton 360 as antivirus program.
Best Regards
Erkan

**Comment by shun2wang** [comment] 2023-08-31 02:00
@JorisGoosen I can also using 0.17.3 (~2s) and 0.18 (~4s) open that fake dataset nothing seems abnormal, dont know why 0.17.3 faster on my PC (win11), but the 0.18 feel slowly while doing some editing like insert rows/values?

**Comment by JorisGoosen** [comment] 2023-09-12 14:41
Sorry it took me a while to get back to you @ErPekerkan but im not sure what more I can do to help you...

You might try disabling norton 360 and seeing if JASP runs quicker then?
For the rest, your computer seems not that powerful, but also not so bad it shouldnt be able to run JASP.

Hoewever, your main problem in this issue is that the file that you cannot share with me does not ever finish loading right?
While the files that you *can share* do finish loading, even if slow.

Seeing as how I cannot reproduce your problem nor investigate the behaviour while loading your file (even if it would somehow finish loading on one of my systems) I can't really do anything more Im afraid...
Im closing the issue

@shun2wang there are def still some optimizations possible for the new data-backend in 0.18

**Closed by JorisGoosen** 2023-09-12 14:41 UTC
Labels: OS: Windows 11, Bug
