### ISSUE TITLE
[Feature Request]: Network Analysis Groups (communities)

### ISSUE THREAD

**Issue by Robbins80** [jasp-stats/jasp-issues#2935] opened 2024-09-27 10:56 UTC
### Description

Please can you add the option to automatically detect groups when completing a network analysis? 

### Purpose

Expand Network Analysis and help improve impact of results 

### Is your feature request related to a problem?

Limitation of the Network Module

### Is your feature request related to a JASP module?

Network

### Describe the solution you would like

When creating networks using the Isingfit model in r the 'cluster_walktrap' command works well at identifying and labelling nodes into communities, it would be great to see this feature added to JASP.

### Describe alternatives that you have considered

I can code in R, but it is much faster to use JASP.

### Additional context

I am aware that there are a range of other commands for community detection in network analysis, though I have not tried the commands so cannot comment on how well they work. 

Thank you!

**Comment by tomtomme** [comment] 2024-09-27 11:02
@Robbins80 
thx for the request. This seems to be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/198
Do you agree? If so, we should close this issue and discuss there.

**Closed** 2024-09-27 13:10 UTC
Labels: Duplicate, Waiting for requester, Module: jaspNetwork, Feature Request
