### ISSUE TITLE
graphics and output to cluster analysis

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#563] opened 2019-12-01 11:48 UTC
Please consider additional graphic outputs and results for cluster analysis. I run then currently in Radiant, a GUI add on to R studio. Note the output, shows the case clusters relate to mean score (on 4 point scale) for each variable. This seems so easy to report and write about. Can we have that output in JASP?

![cluster](https://user-images.githubusercontent.com/33431829/69913437-d2aa7580-1405-11ea-9ff0-5ed1d2547af2.JPG)

Also other graphic outputs that are helpful in publishing:

![cluster 2](https://user-images.githubusercontent.com/33431829/69913474-52d0db00-1406-11ea-9df4-c73a0d572aaa.JPG)

![Cluster 3](https://user-images.githubusercontent.com/33431829/69913491-77c54e00-1406-11ea-8ce4-4cc934cfbe57.JPG)

Thank you! 

Dr. Thomas Mueller 
Appalachian State University

**Comment by koenderks** [comment] 2020-01-05 12:13
Please confirm that I have understood this request correctly. To be specific, you are requesting the following additions:

+ A table containing the cluster means for every variable
+ A table containing percentage of within cluster heterogeneity accounted for by every cluster
+ A plot containing for each variable the cluster means with their x% confidence intervals
+ A plot containing for each variable the cluster densities

I will get on it. Do you happen to have R code that produces this output?

**Comment by App-State-Prof** [comment] 2020-01-05 13:52
Koen yes that does seem correct. Sometimes I take the table that gives me
the mean scores within the variables for each of the Clusters and build a
graph for that.

The other two graphic representations show mean comparison for each
variable and data distribution and overlap within the variable.

I am sorry I do not have the R code... I do this work in Radiant within R
studio because I do not know how to code.

Thank you for helping with this; my goal is to get everything we need in
JASP and discontinue using the other programs.

**Comment by koenderks** [comment] 2020-01-06 19:09
Alright, I have implemented a cluster means table and a cluster density plot so far. It should be fine to have these things in the next release I think. The plot and table right now look like below. @App-State-Prof Do you have any feedback on this table and figure so far? Will let you know more when finishing the other two!

![image](https://user-images.githubusercontent.com/25059399/71841630-2886d300-30c0-11ea-9157-13bc0f97c501.png)

![image](https://user-images.githubusercontent.com/25059399/71841754-74397c80-30c0-11ea-961e-09873a5a8ffc.png)

**Comment by koenderks** [comment] 2020-01-06 20:41
These things should be implemented in the following pull request. 

+ Added a table entry in the "cluster information" table for "Explained proportion within-cluster heterogeneity":
![image](https://user-images.githubusercontent.com/25059399/71847336-eca63a80-30cc-11ea-867d-7e337dad9585.png)

+ Added a new table containing cluster means for each predictor variable
![image](https://user-images.githubusercontent.com/25059399/71847398-12cbda80-30cd-11ea-9efa-544a69a46799.png)

+ Added a plot that visualizes the cluster means and 95% credible interval
![image](https://user-images.githubusercontent.com/25059399/71847422-22e3ba00-30cd-11ea-8ee1-81db877d6f84.png)

+ Added a plot that visualizes the densities of clusters on each variable
![image](https://user-images.githubusercontent.com/25059399/71847456-34c55d00-30cd-11ea-93b1-165a284cc5c2.png)

@App-State-Prof Any feedback on these before this gets merged into the main repository of JASP?

**Comment by koenderks** [comment] 2020-01-06 20:51
@App-State-Prof If you keep track of when the pull request is merged into the development branch, you can download the version of JASP containing these implementations the following day at http://static.jasp-stats.org/Nightlies/

**Comment by App-State-Prof** [comment] 2020-01-06 22:34
This is excellent I will love to test the latest versions.

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by App-State-Prof** [comment] 2020-01-06 22:36
Density of clusters graphics are excellent...love it!

I don't understand Sepal and Pedal length and width. How does this reflect
on the mean score for each of the variables captured in each cluster?

Is there a way to have a graphic output showing comparison graphs with mean
scores with the cluster variables?


Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment] 2020-01-06 22:56
I'm sorry, I do not understand your question entirely. For this output, I used some example data. Do you have some data you can share (maybe as a .csv file) here that I may create an example with and share back here? Maybe that clarifies. 

"Is there a way to have a graphic output showing comparison graphs with mean
scores with the cluster variables?"

Do you mean a graph with the clusters grouped? Or with the variables grouped? Can you provide me with an example of such a graph?

**Comment by App-State-Prof** [comment] 2020-01-07 15:09
Koen good morning. Please see below. This is output from Radiant for a
cluster analysis on ten resilience variables. Each variable was a 4-point
measure. The output gives me the mean score for each cluster, related to
each variable.

I took those results and built the graph displayed, using Excel.

Is this what you are looking for? I am not sure I am expressing this
correctly.

Also sorry, I can't send the dataset, per our IRB requirements.

Does this help?

[image: image.png]

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment] 2020-01-07 15:25
Hi Thomas,

I understand the problem with sending the dataset. Thank you for taking the effort to clarify your requests. I cannot see your image in your latest post however, do you mind attaching it again?

Best,
Koen

**Comment by App-State-Prof** [comment] 2020-01-07 15:57
Sure see attached. Thank you!

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment] 2020-01-07 16:03
Please visit the issue on https://github.com/jasp-stats/jasp-issues/issues/563 and insert the image there in a comment. I still cannot see the image, as I believe you are sending it through e-mail? 

Thanks in advance, and sorry for the hassle.

**Comment by App-State-Prof** [comment] 2020-01-07 16:16
![JASP example cluster](https://user-images.githubusercontent.com/33431829/71910028-231c9d80-313f-11ea-8ef6-0a01dceef11e.JPG)

**Comment by App-State-Prof** [comment] 2020-01-07 16:16
Please let me know you can see this...thank you!

**Comment by koenderks** [comment] 2020-01-07 16:25
Yes, perfect this way! So the graph you are showing is basically a grouped version (per variable) of the cluster means figures that I made yesterday, am I correct? Would it suffice to have a checkbox to switch between the individual cluster means plots and the combined cluster means plots into one figure, thereby creating the graph that you show? The user may then switch between these variations of the same graph. Will work on it tomorrow if I have some time, shouldn't be too much work to add.

**Comment by App-State-Prof** [comment] 2020-01-07 16:29
Yes! The two option switch would be excellent. This will allow JASP users to extract graphing that helps visualize the behavior within the cluster. Note how I named the clusters to better "sell" the results.

Based on your work, I may switch my research methods course and conduct clustering rather than factoring. We're doing a study on "Do It Yourself" home improvement consumers.

**Comment by koenderks** [comment] 2020-01-08 18:35
Alright, I have added two additional options to the "Cluster means" plot option: Display Bars (as I noticed that you prefer barplots for this) and Group into one figure.

![image](https://user-images.githubusercontent.com/25059399/72005258-7bda5c00-324d-11ea-80ea-ce74a0f54808.png)

Display bars allows you to switch between:
A) 
![image](https://user-images.githubusercontent.com/25059399/72005395-cfe54080-324d-11ea-9f45-041bbba46c3f.png)


versus B)
![image](https://user-images.githubusercontent.com/25059399/72005367-bd6b0700-324d-11ea-88b9-a7ed4abb349d.png)


While Group into one figure allows you to switch between

A)
![image](https://user-images.githubusercontent.com/25059399/72005364-b9d78000-324d-11ea-8f48-a585b51a734b.png)

versus B)
![image](https://user-images.githubusercontent.com/25059399/72005442-e55a6a80-324d-11ea-9a74-b68e2a035c00.png)

@App-State-Prof Any feedback?

**Comment by App-State-Prof** [comment] 2020-01-08 22:43
This is excellent. What I will promote, is that with the graphics now downloadable from JASP, little need to recreate in Excel. These, options, with the densities of clusters graphics, will allow us to fully visualize the cluster relationships. Thank you! Now "full service" for cluster analysis.

**Comment by koenderks** [comment] 2020-01-16 23:13
@App-State-Prof This pull request is merged, which means that your request will be in the next version of JASP. You may try these changes already by downloading the latest JASP Nightly build (as of 18-01-2020) from http://static.jasp-stats.org/Nightlies/. 

Would you be willing to participate is a beta testing round for the newest release of JASP?

**Closed by koenderks** 2020-01-16 23:13 UTC

**Comment by App-State-Prof** [comment] 2020-01-17 14:43
Koen good morning. I found the latest version and downloaded it, but I
don't know how to load and run a .dmg file.

Yes, I want to be a beta tester, but am not sure how formal the reporting
will need to be. I did get a protocol manual but have not yet read it.

Let me know what you need I will surely help.

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment] 2020-01-19 12:06
I do not have a mac computer myself. It would be amazing if you would be willing to participate in the beta testing for the next release!

@JorisGoosen Maybe you can shed some light on how to load and run a .dmg file on Mac?

@MyrtheV Do you know more about the beta-testing pool? Are there guidelines for this? Maybe you can provide some information? :)

**Comment by App-State-Prof** [comment] 2020-01-19 12:08
Actually I am on a PC computer not a Mac. When I download the file it
doesn't automatically go into the upload an update mode for JASP.

**Comment by koenderks** [comment] 2020-01-19 12:16
Actually, when I went and looked at http://static.jasp-stats.org/Nightlies/, I saw that there is no new JASP version on there that has these changes in them... I will make sure that on Monday this will be taken care of.

If you are on a PC, then you may download the latest .msi file (like shown below). However, since the latest is from 14-01-2020 and https://github.com/jasp-stats/jasp-desktop/pull/3716 was only merged 3 days ago, the changes are not in the latest version.

Whenever a new version comes online, you may download the .msi file. That version contains the clustering changes as they will be in the next release.
![image](https://user-images.githubusercontent.com/25059399/72680742-856d8a80-3abd-11ea-92d3-778cf49b91a8.png)

**Comment by App-State-Prof** [comment] 2020-01-19 12:46
Thank you I will look for the proper file later tomorrow.

**Comment by App-State-Prof** [comment] 2020-01-20 12:43
By the way does the new version have the graphic output for decision trees?

**Comment by App-State-Prof** [comment] 2020-01-20 18:34
I loaded the new version! Please see below; if the items I am clustering measure on a 1 to 4 scale, how do they receive negative values and/or negative mean scores?

![testing resilience JASP 1 20 20](https://user-images.githubusercontent.com/33431829/72749969-88ce4800-3b89-11ea-8048-2ebeac26c02f.PNG)

**Comment by koenderks** [comment] 2020-01-20 18:49
Do you have the option `scale variables` under 'Training parameters' on? If so, the variables are first standardized so they can have negative values

**Comment by App-State-Prof** [comment] 2020-01-20 18:56
Yes I did...turned that off and it's fixed! Thank you!

**Comment by App-State-Prof** [comment] 2020-01-20 19:08
One more question please. If I uncheck the scale variables box, I lose the color bar graphs?
![no color plots](https://user-images.githubusercontent.com/33431829/72751712-570bb000-3b8e-11ea-911a-746078043e29.PNG)

**Comment by koenderks** [comment] 2020-01-21 22:12
Oef, that is not supposed to happen. However, when I try this on my machine, this does not occur. Can you replicate this behavior using one of the built-in datasets in JASP and send a screenshot of it? Then I will try to replicate this on my machine as well.

**Comment by koenderks** [comment] 2020-01-21 22:15
Also, as a response to this:

> By the way does the new version have the graphic output for decision trees?

Not yet, but for clarity (and future discussion about this topic) you can keep an eye on https://github.com/jasp-stats/jasp-issues/issues/564

**Comment by App-State-Prof** [comment] 2020-01-22 16:29
Very odd...I tried another data set I had. Same thing, when I uncheck the scale variable box I lose the color bar graphics.

![k means JASP data 2](https://user-images.githubusercontent.com/33431829/72912962-6c0d4e00-3d0a-11ea-8056-ba1a1031c725.PNG)

**Comment by koenderks** [comment] 2020-01-22 18:18
Hmmm that's so very weird, this makes the problem hard to isolate. So this only seems to occur when you load a dataset from your computer and unscale the variables, but not if you use a data set from JASP? To try to find out what is the difference, is there anything odd about these datasets? Do they contain missing/weird values for instance? I'm in the dark about this one here

**Comment by App-State-Prof** [comment] 2020-01-22 18:37
I am not sure...my data has been cleaned. PRetty basic Likert measure variable items.

![JASP my data](https://user-images.githubusercontent.com/33431829/72923023-2fe2e900-3d1c-11ea-83c9-e32e59e1cbf1.PNG)

**Comment by App-State-Prof** [comment] 2020-01-22 18:44
Might it be...that my data is whole numbers? I noted your JASP test data is varied, some times to the right of the decimal point.

![image](https://user-images.githubusercontent.com/33431829/72923535-4473b100-3d1d-11ea-882c-c138c196f873.png)

**Comment by JorisGoosen** [comment] 2020-01-22 19:05
Is it possible for you to share the data with us?
Because if it can cause something like that, there is probably a bug somewhere in our code that gets triggered by it.

**Comment by koenderks** [comment] 2020-01-22 19:09
I can now reproduce this if I just make some random data containing whole numbers. Will look into it

**Comment by App-State-Prof** [comment] 2020-01-22 19:16
Sure here is one of the data sets I tested.

Thomas S. Mueller PhD MBA
Professor, Advertising Communication
Faculty in Residence, founder Active Living RLC
Appalachian State University
(828)262-2228
profwriter.com

**Comment by koenderks** [comment] 2020-01-22 19:36
Alright, it was an easy fix. I created pull request https://github.com/jasp-stats/jasp-desktop/pull/3772 that fixes this issue. Thank you for spotting it!
