### ISSUE TITLE
[Feature Request]: Bayes Repeated Measures ANOVA post hoc options

### ISSUE THREAD

**Issue by 64bitGA** [jasp-stats/jasp-issues#2444] opened 2023-11-28 12:32 UTC
### Description

Bayes Repeated Measures ANOVA post hoc options

### Is your feature request related to a problem?

No

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

Like for the frequentist repeated measures ANOVA, I would like JASP to display the mean difference for each pairwise comparison in the post hoc table, together with the adjusted credible interval for each mean difference. I would also like the effect size and credible interval to be displayed for each mean difference.

**Comment by tomtomme** [comment] 2024-02-19 12:14
@64bitGA 
This seems to be a duplicate of https://github.com/jasp-stats/jasp-issues/issues/669
Do you agree?

**Closed** 2024-03-03 19:19 UTC
Labels: Waiting for requester, Module: jaspAnova, Feature Request
