### ISSUE TITLE
JASP crashed

### ISSUE THREAD

**Issue by moonlitpath66** [jasp-stats/jasp-issues#1272] opened 2021-04-29 18:26 UTC
* JASP version: 0.14.3
* OS name and version: KDE Flatpak runtime

* Analysis: 
* Bug description:
* Expected behaviour:

#### Steps to reproduce:

-----------------------------------------------------------------------

### Debug information:
**Engine # 0** process *crashed* and it's state is *initializing*.
**Engine # 1** process *does not exist (anymore)* and it's state is *stopped*.
**Engine # 2** process *does not exist (anymore)* and it's state is *stopped*.
**Engine # 3** process *does not exist (anymore)* and it's state is *stopped*.

[Commit used](https://github.com/jasp-stats/jasp-desktop/commit/c618f4f749569939c9082daaf2949a4ba7d53437)

**Comment by boutinb** [comment] 2021-04-30 06:49
Hi @moonlitpath66 Could you describe precisely what you do before the crash? Is it when starting JASP, when loading data, when starting an analysis?

**Comment by moonlitpath66** [comment] 2021-04-30 15:45
Hello, I sent in another report as I had the same issue today. It happens
when I try to open two separate JASP programs. I honestly do not mean to. I
am trying to work on an assignment for school. I do not think my computer
can handle the running capability. When I open a second JASP to run, it
will freeze up and crash.

**Comment by juliuspf** [comment] 2022-11-08 14:28
I will close this as it is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1277

**Closed by juliuspf** 2022-11-08 14:28 UTC
Labels: OS: Linux / Flatpak
