### ISSUE TITLE
[Feature Request]: Option to analyze statistical designs used in agriculture research.

### ISSUE THREAD

**Issue by samsuriwahid** [jasp-stats/jasp-issues#2892] opened 2024-09-02 09:20 UTC
### Description

Option to analyze data using Repeated Measures MANOVA, Splot design and Nested Design.

### Is your feature request related to a JASP module?

ANOVA

### Describe the solution you would like

An option to analyze data from those experimental designs.

**Comment by tomtomme** [comment] 2024-09-02 09:40
@samsuriwahid 
Thx for the request.
We had similar ones in the past, but those were closed - maybe due to misunderstandings on our side in combination with a lack of details on the side of the requesters. You could help us here by reading those two past issues about split-plot designs (which I suppose you are referring to with "splot" and "nested":

https://github.com/jasp-stats/jasp-issues/issues/793
https://github.com/jasp-stats/jasp-issues/issues/1682

After reading those:
Can you confirm that split-plot is not yet covered by RM ANOVA and factorial ANOVA?
Can you then give some more details and maybe links to R-Packages which implement those designs or papers where those are detailed?
Thank you very much!

**Comment by TarandeepKang** [comment] 2024-09-02 09:59
Hi, Thomas,

I am obviously not the original poster, but I just saw this and thought I would share something. Clock designs are not covered by repeated measures and overall factorial and over as currently implemented neither as far as I'm aware of the nested variation as requested here. There is however a great package that takes care of this developed by Sarah Friedrich, Frank Konietschke and Markus Pauly 
https://journal.r-project.org/archive/2019/RJ-2019-051/index.html

Despite the name of the package I'm not really sure about this repeated measures MANOVA

**Comment by samsuriwahid** [comment] 2024-09-02 10:58
I appreciate your prompt response. Let me respond on the RM MANOVA. The R code for RM MANOVA is multRM() function.Let me give a hypothetical example of RM MANOVA experiment. An experiment was conducted to study the effects of 3 Nitrogen level and 2 irrigation regimes on the growth parameters and yield of maize plants in pots arranged as CRD. For each factor combinations, the samples were replicated 5 times. Every week, the height, leaf numbers and leave SPAD readings were taken.IV - Nitrogen level and Water regimeDV - Height, Leave numbers, SPAD readings (measured every week until harvest)I don’t know how the data can be analysed using JASP under current options.I have a feeling that the split plot and nested design can be analysed using the GLM or GLMM option in JASP but I haven’t explored it yet.Thank you.Sent from my iPhoneOn 2 Sep 2024, at 6:00 PM, TarandeepKang ***@***.***> wrote:﻿
Hi, Thomas,
I am obviously not the original poster, but I just saw this and thought I would share something. Clock designs are not covered by repeated measures and overall factorial and over as currently implemented neither as far as I'm aware of the nested variation as requested here. There is however a great package that takes care of this developed by Sarah Friedrich, Frank Konietschke and Markus Pauly
https://journal.r-project.org/archive/2019/RJ-2019-051/index.html
Despite the name of the package I'm not really sure about this repeated measures MANOVA

**Comment by TarandeepKang** [comment] 2024-09-03 17:22
@tomtomme this issue seems to be a difficulty of #1660 and there is a lot of useful information in the thread. Especially this paper:

O’Brien, R. G., & Kaiser, M. K. (1985). MANOVA method for analyzing repeated measures designs: An extensive primer. Psychological Bulletin, 97(2), 316–333. https://doi.org/10.1037/0033-2909.97.2.316

**Comment by TarandeepKang** [comment] 2024-09-03 17:34
I apologies for the typo @tomtomme. There seems to be a duplication of an issue. I have clarified now.

**Comment by tomtomme** [comment] 2024-09-06 06:10
@samsuriwahid 
Do you agree, that this request is a duplicate of #1660 ?
If so I would close this one, so that we can discuss over there.

**Comment by samsuriwahid** [comment] 2024-09-06 06:17
Yes, but the #1660 there is no definite answer to the request. Currently there is no option to analyze a RM MANOVA, the option is only for RM ANOVA.Thank you.Sent from my iPhoneOn 6 Sep 2024, at 2:10 PM, Thomas Langkamp ***@***.***> wrote:﻿
@samsuriwahid
Do you agree, that this request is a duplicate of #1660 ?
If so I would close this one, so that we can discuss over there.

**Comment by tomtomme** [comment] 2024-09-06 06:46
@samsuriwahid 
Thx for confirmation. I summed up all information from all issues now in #1660

**Closed by tomtomme** 2024-09-06 06:46 UTC
Labels: Module: jaspMixedModels, Module: jaspAnova, Feature Request
