### ISSUE TITLE
Canonical Correlation Analysis

### ISSUE THREAD

**Issue by sujitiiml** [jasp-stats/jasp-issues#372] opened 2019-06-08 00:31 UTC
Is it possible to add canonical correlation analysis to JASP ?

**Comment by sfchyd** [comment] 2023-07-29 08:26
while searching for simliar string, i came across your link

**Comment by tomtomme** [comment] 2023-12-25 19:20
duplicate of https://github.com/jasp-stats/jasp-issues/issues/2084
can be closed.

**Closed** 2024-01-03 12:35 UTC
Labels: Module: jaspRegression, Feature Request
