### ISSUE TITLE
User interface unresponsive in Win10 high-contrast mode

### ISSUE THREAD

**Issue by clutteroth** [jasp-stats/jasp-issues#1117] opened 2021-01-06 11:30 UTC
* JASP version: 0.14.1

* OS name and version: Windows 10 Enterprise
* Bug description: When enabling the Windows high-contrast mode, the JASP user interface becomes unresponsive. Not all clicks are registered and the interface updates infrequently, only after a few clicks and with long delays. This happens as soon as high contrast mode is enabled, no matter is JASP is already running or is started after enabling high-contrast mode. The problem disappears as soon as high-contrast mode is disabled.

#### Steps to reproduce:
1. Start JASP in normal (non high-contrast) mode.
2. Open the Windows Start menu and type "high contrast" (without quotes), then select the first option in the menu "Turn high contrast on or off".
3. The System Settings open and at the top there is a switch "Turn on high contrast". Turn it on.
4. Now go back to the JASP window and interacting with the interface, e.g. opening the menu. 

<!

**Comment by JorisGoosen** [comment] 2021-01-18 14:22
So I can reproduce this easily indeed, basically open JASP and enable high-contrast and then JASP becomes unresponsive.

However, closing and reopening JASP solves the problem. Because the new JASP instance works normally.
This is such a bordercase that I won't try to look for a fix at all but just recommend the workaround:

Restart JASP after switching *to* high-contrast mode.

**Closed by JorisGoosen** 2021-01-18 14:22 UTC
