### ISSUE TITLE
 This analysis terminated unexpectedly. (Reliability - Single Test - Cronbach's, Cronach's (if item dropped))

### ISSUE THREAD

**Issue by SophiaQP** [jasp-stats/jasp-issues#1057] opened 2020-11-17 20:24 UTC
* JASP version: 0.9.2
 MasOS
* OS name and version: macOS Catalina Version 10.15.6
* Analysis: Reliability 
* Bug description: 
Error in relyFit[['freq']][['omega.fit']] <- omega[['indices']]: replacement has length zero

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistReliabilityMainResults(jaspResults, dataset, options)
* Expected behaviour: Single Test Reliability

#### Steps to reproduce:
[PS2103Dataset2020First10participants.pdf](https://github.com/jasp-stats/jasp-issues/files/5556005/PS2103Dataset2020First10participants.pdf)

**Comment by SophiaQP** [comment] 2020-11-17 20:25
Hi there! Not sure if I've filled this out 100%ly accurately, but let me know if any more information is needed

**Comment by boutinb** [comment] 2020-11-18 08:55
Hi @SophiaQP, the JASP version you use is quite old. We have now 0.14 version here https://jasp-stats.org/download/
Can you try it, and check whether the problem still occurs.

**Comment by juliuspf** [comment] 2020-11-19 14:56
I am quite certain the version number she provided is inaccurate. Such an error would one occur in the two latest versions of JASP. @SophiaQP you might try the latest nightly (https://static.jasp-stats.org/Nightlies/) and check if the problem still occurs.

**Comment by fplatz** [comment] 2020-11-23 13:52
Dear JASP development team,
I'm running JASP 0.14 on a Mac (OS Catalina, 10.15.07) having the same issue as reported above when trying to conduct a reliability analysis ("classical") by requesting cronbach's alpha. JASP terminated the process, giving the following information:

> Error in `*tmp*`[['freq']]: Indizierung außerhalb der Grenzen

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.frequentistReliabilityMainResults(jaspResults, dataset, options)

Any suggestions are appreciated.

All the best,
Friedrich

**Comment by juliuspf** [comment] 2020-11-23 13:55
Dear Friedrich, 
is it possible for you to try the approach I suggested above (https://github.com/jasp-stats/jasp-issues/issues/1057#issuecomment-730429423)?

**Comment by fplatz** [comment] 2020-11-23 13:58
I am downloading the latest nightly built version. I keep you updated, after running it. I expect to need 30 minutes for the complete task.

**Comment by fplatz** [comment] 2020-11-23 14:14
> Dear Friedrich,
> is it possible for you to try the approach I suggested above ([#1057 (comment)](https://github.com/jasp-stats/jasp-issues/issues/1057#issuecomment-730429423))?

Dear Julius,

unfortunately, the error remains:

>This analysis terminated unexpectedly.
>Error in relyFit[['freq']][['omega.fit']] <- omega[['indices']]: Ersetzung hat Länge 0
>
>Stack trace
>tryCatchOne(expr, names, parentenv, handlers[[1]])
>doTryCatch(return(expr), name, parentenv, handler)
>withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
>
>analysis(jaspResults = jaspResults, dataset = dataset, options = options)
>
>reliabilityFrequentist(...)

>.frequentistReliabilityMainResults(jaspResults, dataset, options)
>
>To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

**Comment by juliuspf** [comment] 2020-11-23 14:16
okay. Can you provide the .jasp file by any chance?

**Comment by fplatz** [comment] 2020-11-23 14:18
> okay. Can you provide the .jasp file by any chance?

Sure, no problem. Could you please give me an email address? I will sent you all files. 
Best
Friedrich

**Comment by juliuspf** [comment] 2020-11-23 14:20
Well, it would be best to zip them and upload them here. otherwise use julius.pfadt@gmail.com.

**Comment by fplatz** [comment] 2020-11-23 14:35
I sent you an email.

**Comment by juliuspf** [comment] 2020-11-23 15:07
okay, so from a first look this caused by the bootstrap. Unfortunately, this is a problem for lambda6 and omega, but not for alpha. However, the current setup makes it impossible to compute any result as long as the computations for one estimator fail (which are done in the background). This will be fixed with version 0.15. I am sorry for not being able to provide better support.

**Comment by fplatz** [comment] 2020-11-23 15:10
Ok. That means, that it is not possible to get alpha at this moment, right?!
Great, that you could identify the source for that problem! Hopefully, there is a solution in the next few days...we'll have to wait
All the best
Friedrich

**Comment by juliuspf** [comment] 2020-11-23 15:19
Well,  I am afraid this will take more than a few days. With this data, there is no solution for alpha in Jasp right now, I am sorry.

**Comment by juliuspf** [comment] 2020-11-23 15:47
What you came upon are actually two problems, one happens when intervals are computed, and one happens regardless. So when you uncheck confidence intervals there should not be an error. This I should be able to fix in the near future.

**Comment by juliuspf** [comment] 2020-11-23 16:27
For now, you can get a point estimate for alpha if you uncheck the confidence interval box, then you check the omega box, and in 'Advance Options' you now check PFA instead of CFA, then you can go back to the top and check alpha, and you should see a point estimate. 
This is due to the fact that some computation of omega breaks it in this case. Sorry for the confusing workaround.

**Comment by fplatz** [comment] 2020-11-24 07:23
;-) Again, thank you for that fast support! It works for now!

**Closed** 2021-01-19 10:47 UTC
