### ISSUE TITLE
[Bug]: JASP crashed

### ISSUE THREAD

**Issue by lklende** [jasp-stats/jasp-issues#2542] opened 2024-01-23 15:31 UTC
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I closed a data file and the R-console. When I then tried to open anoter data file the program crashed.

### Expected Behaviour

I should have opende the other data file, which have been opende in earlier versions of JASP several times.

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2024-01-23 17:35
Hi @lklende, do you have a precise reproduction path? Do you open a datafile, close it and open a new datafile, then it crashes? I cannot reproduce this, so please describe the issue step by step, and whether it happens with only some datasets/analyses.

**Comment by lklende** [comment] 2024-01-24 21:13
I was not able to reproduce the crash. May be it was an external thing.
However, a few other things 'i want to mention. When I wanted to instal
version 0.18.3 neither the msi downloaded with your download link nor with
Windows store worked. I got an error message after several minutes
saying that installation was interrupted. I had to download the
pre-installer version. Also another strange thing I show in my enclosed
video, see link below.

https://youtu.be/5ALtMsU7kZc


Vennlig hilsen
Leif Kåre Lende
Leitebrotet 59
4322 Sandnes

tlf 91603374


tir. 23. jan. 2024 kl. 18:35 skrev bruno boutin ***@***.***>:

**Comment by boutinb** [comment] 2024-01-25 09:22
Hi @lklende I can reproduce this issue that the first time you open the Variable Window by clicking on the header of a variable, you get a Variable Window with no selected variable. If you click on another variable header, then you get the right variable in the Variable Window. I have made another issue for this (https://github.com/jasp-stats/jasp-issues/issues/2546) This should be fixed for the next version.
That you cannot install JASP with the Windows installer is annoying. Some people reported this issue, but mainly this was due to either a permission issue or the PC capacity was too low. What can be also the problem is if you have a username with non-latin characters (or a latin character with special accent on it).
That sometimes JASP is slow is mainly due to the kind of analysis must be run.
I will close this issue, since you cannot reproduce the crash. Reopen it if you can reproduce it.

**Closed by boutinb** 2024-01-25 09:22 UTC
Labels: OS: Windows 10, Crash, Bug
