### ISSUE TITLE
[Bug]: cannot use a PostgreSQL database source, error message ''Error: Driver not loaded Driver not loaded"

### ISSUE THREAD

**Issue by natmaka** [jasp-stats/jasp-issues#2209] opened 2023-07-03 14:35 UTC
### JASP Version

0.17.2.1 (this report also apply to 0.18.3)

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Flatpak

### Bug Description

(Coming from #2199)

I installed JASP through "flatpak --user ..." on a Debian bookworm (amd64) .

Using the menu Open-Database I try to access to a remote PostgreSQL instance (which otherwise works OK, including when accessed thru psql from the local computer).  It fails.  On the "preview" zone an error message appears: "Error: Driver not loaded Driver not loaded".

I tried to circumvent the sandboxing in order to let JASP access to Qt libraries (see #2199), to no avail.

Upon trying the connect to a DB (clicking on the "Connect to database" button) on JASP's stderr I can read:
QSqlDatabase: QPSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE

Are all libs required for PostgreSQL access integrated to the Flatpak build?

### Expected Behaviour

JASP should be able to access to a PostgreSQL instance.

### Steps to Reproduce

1. Menu: Open
2. Menu: Database
3. try to access to a remote PostgreSQL instance

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by natmaka** [comment] 2023-07-04 13:34
I edited my report in order to add the error message.  Here is a screenshot: https://postimg.cc/5jNvhXM7

**Comment by RensDofferhoff** [comment] 2023-07-12 09:53
>All potentially pertinent (Qt) Debian packages are installed systemwide, however I understand that the flatpak sandbox cannot access to them (as /usr and such are blacklisted).

This is correct. We sadly do not ship the database drivers (psql) in the flatpak.
The Qt drivers that are shipped are nothing but wrappers.
We could consider doing it for the next release at the cost of a larger flatpak with more dependencies to manage.
I will discuss it at our next meeting.

**Comment by natmaka** [comment] 2023-07-12 14:36
Thank you!
It seems to me that a trick may offer a way to avoid including the drivers/libraries files into the flatpak while enabling those who need it to let JASP access to it.  In the flatpak can you add a LD_LIBRARY_PATH path pointing to some specific non-blacklisted directory (such as "/mountedlibs"), which will by empty, for the user to download then copy those files in a directory pertaining to the host computer, then use flatpak's "--filesystem" argument to map this directory into "/mountedlibs"?

**Comment by natmaka** [comment] 2023-09-17 06:43
0.18 doesn't solve the problem, therefore I suppose that shipping the database drivers (psql) in the flatpak wasn't considered sound or isn't possible.  Is it a dead end or do you plan to find a way?
Did you consider the trick described just above (LD_LIBRARY_PATH-based)?

Thank you!

**Comment by JorisGoosen** [comment] 2023-09-20 09:48
Im not sure how easy it is to use libraries and databases outside the flatpak in the flatpak. Do they have the same ABI and all?

Maybe it would be better to include some drivers?
THey shouldnt be so big right?
Maybe just a basic ODBC, postgres and sqlite or something?

Also yeah we didnt look at it for the last release @natmaka , too much work on data editing

**Comment by tomtomme** [comment] 2024-02-12 08:32
@JorisGoosen 
Is a fix for this planned for 0.19?

@natmaka 
Natmaka posted this update accidentaly in another thread:

> It still does not work (here) with JASP 0.18.3.
>  All related Flatpak dependencies are up-to-date. I also tried after installing psqlodbc
>  Same error message "Error: Driver not loaded Driver not loaded" (sic).> 
> I'm pretty sure that my connection string is adequate (it works on the command line, using psql).
> Were you able to find a way?

**Comment by JorisGoosen** [comment] 2024-03-20 12:27
> Is a fix for this planned for 0.19?

Im afraid not, I want to look at this but it is rather low prio

**Comment by tomtomme** [comment] 2024-10-02 08:58
Closing as duplicate of  #2946 now. Lets disuss there.

**Closed by tomtomme** 2024-10-02 08:58 UTC
Labels: Duplicate, OS: Linux / Flatpak, Feature Request, Component: Import/Export
