### ISSUE TITLE
K-fold for random forest classification

### ISSUE THREAD

**Issue by nirotem** [jasp-stats/jasp-issues#747] opened 2020-05-16 10:37 UTC
Hello,

I am very new to JASP (just learned about it yesterday) and the first impression is great. I am used to STATA and with the help of a friend was running some random forest classification models on Python.  The fact that JASP offers a simple way to run machine learning models is supper helpful for folks like me.

I noted that there is a k-fold cross validation option for K-nearest models but not for the random forest classification. Adding this option will be very useful, as it is really a common practice in machine learning. 

Also - Adding matthews correlation coefficient to the evaluation metrics will be great. This is a key metrics when dealing with unbalanced data (see here - https://doi.org/10.1186/s12864-019-6413-7 )

Lastly, turning to the variable importance, the method JASP is using is unclear. Specifically, is it possible to add also permutation importance? Breiman in his 2001 paper 'Random Forests' refers to it, and I believe there are a couple of R packages that support it.

The fact that you included the option for an optimized number of trees is great, and so is the set seed (for replication). Truly helpful!

Thanks so much!
Nir

**Comment by tomtomme** [comment] 2024-01-05 12:58
@nirotem 
Matthews correlation is in now.
However we still do not document what "feature importance" actually does or if we already use "permutation importance" from Breiman 2001. Could you add the paper and the needed R-Packages. Same for the still missing k-fold cross validation with random forests.
Maybe then someone can find time to implement this. I am not promising anything here, but you can increase the likelyhood of this happening :D

Thank you!

**Comment by tomtomme** [comment] 2024-02-08 08:17
related: https://github.com/jasp-stats/jasp-issues/issues/2131

And I realized this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2104
Lets discuss there!
Also for the lacking documentation there is now a central issue here: https://github.com/jasp-stats/jasp-issues/issues/2529
I will mention your request there

**Closed by tomtomme** 2024-02-08 08:17 UTC
Labels: Module: jaspMachineLearning, Feature Request
