### ISSUE TITLE
[Bug]: plots empty in JASP 16.2.0 and 16.1.0

### ISSUE THREAD

**Issue by TangWeiCAS** [jasp-stats/jasp-issues#1703] opened 2022-05-05 15:54 UTC
### JASP Version

0.16.2

### JASP Module

jaspTTests

### What analysis are you seeing the problem on?

paired sampling TTest

### What OS are you seeing the problem on?

Windows 10

### Bug Description

when I did TTest, raincloud plots as well as descriptive plots were all gone, there is only an empty window for my plots ,and I cannot save any figure (which means it's not a problem about figure display, but a bug in producing figures). 
![figure](https://user-images.githubusercontent.com/105002091/166961733-3a645b38-d149-49c6-b0ab-8d9306bfd75d.jpg)

### Expected Behaviour

display plots as below (made by JASP 16.0) after turning on "raincloud plots".
![figure](https://user-images.githubusercontent.com/105002091/166961490-ba7a204a-1b44-45d3-8046-580aa04dd59f.png)

### Steps to Reproduce

1. choose a dataset, select T-Tests, classical, paired sample T;
2. put 2 vars in;
3. select "descriptive plots" and "raincloud plots". Then it happens.

### Log (if any)

sorry but I've already uninstalled the latest version on jasp-stats.org.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-05-05 19:27
Hi @TangWeiCAS, thanks for reporting the bug. It seems I cannot reproduce this error on macOS, so it might be an issue with windows. Do plots in other analyses appear for you?

**Comment by TangWeiCAS** [comment] 2022-05-05 20:05
Hi @juliuspf , I also tried the descriptive module, but the plots didn't appear as well. Unfortunately, I don't know if this bug would appear in the other analyses. More feedbacks from other users similar to me are expected.

**Comment by juliuspf** [comment] 2022-05-05 20:21
Can someone else on windows replicate this, @koenderks, @FBartos ?

**Comment by shun2wang** [comment] 2022-05-05 23:00
this maybe related to #1671 and @TangWeiCAS  do you have a Unicode character in your system username? If so, you can do that temporarily to resolve problem and wait for the new version with reference to the practices I gave there #1671 .

**Comment by TangWeiCAS** [comment] 2022-05-06 02:56
Helps a lot! I checked my wd and yes, there are 2 Chinese characters in my username @shun2wang . However, it's weird that my new version Rstudio still works normally with Chinese strings (a bit different from #1671 ). I'd like to wait for your latest version of JASP to solve this problem!

**Comment by shun2wang** [comment] 2022-05-06 03:30
good! could you please send a example .jasp file to me (shuonwang<at>gmail.com) and also r/rstudio libpath and another info by use `rstudio.exe --run-diagnostics`, thank you!

**Comment by TangWeiCAS** [comment] 2022-05-06 03:56
@shun2wang Sorry but I've uninstalled the 16.2 version yesterday. I'll try to install the new 16.2 version again and then feedback in this post later.

**Comment by TangWeiCAS** [comment] 2022-05-06 04:43
`setwd("C:/Users/唐为/Desktop/strongsad/")`
I used the code above to do SVM with Rstudio.
The R codes run successfully with Chinese characters in pathway, but when I run diagnostics, a piece of warning jumps out like this:
I guess it's hard for Rstudio to display Chinese strings, but it can read the wd as expected. This can also explain why my JASP could read .csv on my .\desktop but couldn't make plots. @shun2wang 
![捕获](https://user-images.githubusercontent.com/105002091/167068305-629e6b0e-d5b4-4b58-81a6-41c592d95991.JPG)

**Comment by shun2wang** [comment] 2022-09-16 13:41
fixed by https://github.com/jasp-stats/jasp-desktop/pull/4855

@TangWeiCAS  if you want to test it can download a pre-release version at http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-stable-4478bbc84b4124659dcaacaebe119128eba9029f.zip

**Closed by shun2wang** 2022-09-16 13:41 UTC
Labels: OS: Windows
