### ISSUE TITLE
Enhancement: Credible intervals with informed priors / intervals from the model

### ISSUE THREAD

**Issue by AugustOlsson** [jasp-stats/jasp-issues#612] opened 2020-02-13 15:14 UTC
I would like the option to have credible intervals (both graphical and descriptives) based on the fitted model/actual distribution of data. To exemplify I am currently performing a repeated measure BANOVA with RMSE as the dependent variable. Because the credible intervals in JASP are based on a uniform prior I get credible intervals that include negative values (which are of course impossible for RMSE) and thus the same "problem" that is common with confidence intervals - impossible values within the interval. 

Given that the bayesian framework has the possibility to create intervals that are not symetrical around the mean but rather based on the actual distribution of the data/fitted model I would highly apprichiate more options when it comes to the descriptives, e.g. basing them on the intervals from the model and allowing skewed intervals around the mean. 

Linking the forum post I posted on the same manner: https://forum.cogsci.nl/discussion/5761/impossible-values-included-in-credible-interval#latest

Best,
August

**Comment by FransMeerhoff** [comment] 2020-02-18 08:34
Hi @AugustOlsson,

Thanks for the suggestion.
@JohnnyDoorn  or @EJWagenmakers can one of you look at this one.

Best,
Frans Meerhoff

**Comment by tomtomme** [comment] 2024-02-19 12:03
@AugustOlsson 
closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/785
Please reopen if you disagree!

**Closed by tomtomme** 2024-02-19 12:03 UTC
Labels: Module: jaspAnova, Feature Request
