### ISSUE TITLE
[Bug]: Reordering of factors in ANOVA leads to reordering of factors in plots but NOT in tables

### ISSUE THREAD

**Issue by hrgodmann** [jasp-stats/jasp-issues#2111] opened 2023-04-28 12:43 UTC
### JASP Version

0.17.1

### JASP Module

ANOVA

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

When I am running an ANOVA and I reorder the factors in the data, this leads to the desired reordering in the plots. However, it does not lead to a reordering of the factors in the output tables of the analysis.

### Expected Behaviour

The factors should also be reordered in the tables.

### Steps to Reproduce

It is easy to reproduce this with the data library data set Pain thresholds.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-02-08 07:24
@hrgodmann 
Still true for the descriptives table in ANOVA with jasp 0.18.3. 
Other tables (contrasts, post hocs, marginals...) are fine.

@JohnnyDoorn 
seems like a quick fix. Am I right?

**Comment by tomtomme** [comment] 2024-02-08 11:13
So this is apparently a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1741
Closing. 
Lets discuss there.

**Closed by tomtomme** 2024-02-08 11:13 UTC
Labels: Module: jaspAnova, OS: Linux / Flatpak, OS: macOS Intel, Bug: Medium
