### ISSUE TITLE
[Feature Request] jaspFactor: PCA should display object scores (predictions)

### ISSUE THREAD

**Issue by juliuspfadt** [jasp-stats/jasp-issues#1666] opened 2022-03-22 10:05 UTC
### Description

via https://forum.cogsci.nl/discussion/7885/principal-component-analysis#latest 
The factor module, in particular PCA, does not show the projected object scores along the components or factors, there is no option for it

### Solution
These statistics are within the output of the psych package. They should be easy to display. However, the object scores should be plot in a certain way, a table is unfeasible.

**Comment by juliuspf** [comment] 2022-03-22 10:50
It seems to me as though there is the option to add the object scores to the data as a new column, but it is not working.
![Screenshot 2022-03-22 at 11 49 36](https://user-images.githubusercontent.com/38500953/159465520-65f14ea3-8a7d-4e4f-ab26-151ad8bd0727.png)

**Comment by juliuspf** [comment] 2022-03-22 13:47
we would need this in order to get the scores added to the data as a new column: https://github.com/jasp-stats/INTERNAL-jasp/issues/694

**Comment by juliuspfadt** [comment] 2023-03-21 08:47
related and possible duplicate of https://github.com/jasp-stats/jasp-issues/issues/151

**Comment by tomtomme** [comment] 2024-02-09 11:04
Closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/101

**Closed by tomtomme** 2024-02-09 11:04 UTC
Labels: Module: jaspFactor, Feature Request, Data Editing
