### ISSUE TITLE
[Feature Request]: Option to rotate x-axis label to 45 degrees (or other)

### ISSUE THREAD

**Issue by kadewe** [jasp-stats/jasp-issues#1952] opened 2022-12-30 11:47 UTC
### Description

Support an option in the BASIC PLOTS > DISTRIBUTION PLOTS to rotate x-axis label to 45 degrees (or any other degree, but 45 degrees would be a good start)

### Purpose

If your labels a too long, the overlap in the histogram distribution plot. Rotating them would make them readable

### Use-case

Anytime you plot nominal data in a histogram and you have long labels

### Is your feature request related to a problem?

The x-axis labels overlap.

### Is your feature request related to a JASP module?

Descriptives

### Describe the solution you would like

give us an checkmark-option "Rotate x-axis labels" with an text-input field for degrees with a default of 45

### Additional context

<img width="545" alt="Bildschirmfoto 2022-12-30 um 12 44 37" src="https://user-images.githubusercontent.com/169315/210066872-d530026f-956d-498b-9484-63842823eba8.png">

something like supporting "angle = 45" should be sufficient, see code example

library(ggplot2)
disprt <- data.frame(group = rep(c("AAAAAAAA", "BBBBBBBBBB"), 50), distances = rnorm(100))
ggplot(disprt, aes(group, distances)) + geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

gives

<img width="670" alt="Bildschirmfoto 2022-12-30 um 12 46 57" src="https://user-images.githubusercontent.com/169315/210067077-f5b2c6a1-da57-4e19-848b-e8c8c6556642.png">

**Comment by kadewe** [comment] 2023-09-29 13:13
Come on, it is such a small addition. Better to fix it by myself and add a pull-request?

**Comment by EJWagenmakers** [comment] 2023-09-29 13:24
Ha! Well, first off, we have a gazillion small additions to handle :-) Second, PRs are always welcome!! However, this one may take some thinking: we have many graphs and several will have the same issue. How best to handle this?

**Comment by EJWagenmakers** [comment] 2023-09-30 07:10
OK, so my current thinking is that this is an option that could be added to our graph editor! Then it would automatically apply to all editable graphs. What do you think, @vandenman?

**Comment by shun2wang** [comment] 2023-09-30 09:16
duplicate of https://github.com/jasp-stats/jasp-issues/issues/1453 this should be added into jaspGraphs This can be applied to general situations.

**Comment by tomtomme** [comment] 2024-02-09 10:38
Closing as duplicate then.

**Closed by tomtomme** 2024-02-09 10:38 UTC
Labels: Graphs/Plots, Module: jaspDescriptives, Feature Request
