### ISSUE TITLE
Text not correctly visible in the output

### ISSUE THREAD

**Issue by lilianjansbeken** [jasp-stats/jasp-issues#430] opened 2019-07-23 06:37 UTC
* JASP version: 0.10.2.0
* OS name and version: Windows 10 Home, version 1803, Build 17134.885
* Analysis:
* Bug description: When opening a .sav file, text is not correctly visible in the output 
[SPSSfile.zip](https://github.com/jasp-stats/jasp-issues/files/3420538/SPSSfile.zip)

* Add JASP files as a zip:
* Screenshot: 
<img width="247" alt="2019-07-23 (1)" src="https://user-images.githubusercontent.com/52657670/61688217-b8a8aa00-ad24-11e9-9ba9-bee8d6f26e08.png">
* Expected behaviour:
* Steps to reproduce:

**Comment by JorisGoosen** [comment] 2019-07-23 08:50
This is a duplicate of #420

**Closed by JorisGoosen** 2019-07-23 08:50 UTC
