### ISSUE TITLE
[Bug]: Unidimensional reliability does not run on arm-macOS

### ISSUE THREAD

**Issue by sinasina84** [jasp-stats/jasp-issues#1707] opened 2022-05-12 14:42 UTC
### JASP Version

0.16.2

### JASP Module

jaspReliability

### What analysis are you seeing the problem on?

Reliability

### What OS are you seeing the problem on?

MacOS Apple Silicon

### Bug Description

Please see the description below

<img width="662" alt="Bildschirmfoto 2022-05-12 um 16 31 14" src="https://user-images.githubusercontent.com/105441134/168099453-8e02ad09-9eef-46a7-a62d-cecaa14662ed.png">

[Auswertung Ina Susmann.csv](https://github.com/jasp-stats/jasp-issues/files/8679964/Auswertung.Ina.Susmann.csv)

### Expected Behaviour

<img width="527" alt="Bildschirmfoto 2022-05-12 um 16 31 44" src="https://user-images.githubusercontent.com/105441134/168099532-b730abe0-03c0-4d7a-a08a-df7fca941fa9.png">

### Steps to Reproduce

<img width="662" alt="Bildschirmfoto 2022-05-12 um 16 31 14" src="https://user-images.githubusercontent.com/105441134/168101661-75ec6e26-5b0c-482f-b0d0-e048f79a50dc.png">

1.  Open Jass and load data (.csv)
2. Choose Reliability and then undimensional reliability
3. Choose Files BS_Consumptions 1 to 5 
4. Error occurred (same happened with the data my professor gave us yesterday. It worked yesterday on his pc, but today not on mine

### Log (if any)

[JASP 2022-05-12 16_23_00 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/8679929/JASP.2022-05-12.16_23_00.Engine.0.log)

[JASP 2022-05-12 16_23_00 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/8679935/JASP.2022-05-12.16_23_00.Desktop.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by sinasina84** [comment] 2022-05-12 14:43
Please help me as soon as possible, I have to finish my work until 15th, of May, 2022.

Kind regards!

**Comment by juliuspf** [comment] 2022-05-12 17:05
You can also check the intel version of the 0.16.2 release. that one should also run on your computer and the analysis should work without trouble.

**Comment by juliuspf** [comment] 2022-05-24 13:04
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1694, I will close this for now. To receive updates on the progress you can subscribe to the other issue https://github.com/jasp-stats/jasp-issues/issues/1694.

**Closed by juliuspf** 2022-05-24 13:04 UTC
Labels: duplicate, Module: jaspReliability, Bug: High
