### ISSUE TITLE
[Bug]: Cyrillic 

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#1525] opened 2021-12-03 15:06 UTC
### JASP Version

0.15

### JASP Module

jaspDescriptives, jaspAnova, jaspFactor, jaspFrequencies, jaspRegression, jaspTTests, jaspMixedModels, jaspAudit, jaspBain, jaspNetwork, jaspSem, jaspMachineLearning, jaspSummaryStatistics, jaspMetaAnalysis, jaspDistributions, jaspEquivalenceTTests, jaspJags, jaspReliability, jaspVisualModeling, jaspLearnBayes, jaspProphet, jaspProcessControl

### What analysis are you seeing the problem on?

Cyrrilic

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Please, make the program recognize the Cyrillic alphabet. ASAP

### Expected Behaviour

To make the program recognize the Cyrillic alphabet 

### Steps to Reproduce

1. ?
2. 
3. 
...
I don't know

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by amirmasoudabdol** [comment] 2021-12-03 15:17
Hey @NikitaKhromov-Borisov! I have a few questions that would help us pinpoint the problem a bit better, 

- Do you experience this in specific parts of JASP, analysis, results section, plots, tables?
- Would you also please check your default font? You can check it from Preferences → Interface.
- I see that you are using Windows 11. If you have recently upgraded to Windows 11, did you have this problem on your previous system as well?

**Comment by JorisGoosen** [comment] 2021-12-07 10:51
@NikitaKhromov-Borisov if you do not respond to our questions we cannot help you "ASAP" can we?

**Comment by NikitaKhromov-Borisov** [comment] 2021-12-07 12:28
JASP doesn't recognize Cyrillic





вт, 7 дек. 2021 г. в 13:52, Joris Goosen ***@***.***>:

**Comment by JorisGoosen** [comment] 2021-12-07 12:35
> JASP doesn't recognize Cyrillic

Except that it does.

We have worked very hard on this in previous versions and noone else has complained so it would be good to know where or how "JASP doesn't recognize" cyrillic.

- Is it loading a file?
- Is it typing a column name?
- Is it somewhere else?

I  cannot see your screen and I do not know what you are doing so if you can't describe the problem in more detail we cannot help you.

**Comment by JorisGoosen** [comment] 2021-12-07 17:40
Ah, well, I would like to see them indeed.

But github sadly enough does not support uploading attachments to an issue via an email response.
So if you could go to this issue at https://github.com/jasp-stats/jasp-issues/issues/1525 and leave a comment there with the attachment, thank you.

**Comment by NikitaKhromov-Borisov** [comment] 2021-12-09 19:46
[Cyrillic.zip](https://github.com/jasp-stats/jasp-issues/files/7687999/Cyrillic.zip)
Here are examples of how Cyrilic looks like as a JASP file

**Comment by JorisGoosen** [comment] 2021-12-10 10:20
Alright, I think I know what is going wrong here. You could try enabling the "Windows Workaround" in the data preferences as:
![image](https://user-images.githubusercontent.com/29062713/145558167-5bd7065d-2031-42f3-806a-43027256cc54.png)

If you then try to read your `csv` file again it should work.

**Comment by NikitaKhromov-Borisov** [comment] 2021-12-10 23:06
Dear Joris,

thank you, that's great!
However, the last cell in my example is not recognized. What's the reason?

[image: image.png]
Cheers,
Nikita

пт, 10 дек. 2021 г. в 13:21, Joris Goosen ***@***.***>:

**Comment by JorisGoosen** [comment] 2021-12-10 23:50
Ah, nice that it's helping.

I can't see your example because this also needs to be attached in a comment on https://github.com/jasp-stats/jasp-issues/issues/1525

**Comment by NikitaKhromov-Borisov** [comment] 2021-12-12 17:59
[Cyrillic_1_2_3.zip](https://github.com/jasp-stats/jasp-issues/files/7699263/Cyrillic_1_2_3.zip)
Here are 3 examples. Cyrillic_1: 17 rows, but JASP recognizes only 9 and the last cell is not recognized.  Cyrillic_2: 31 rows. But JASP recognizes only 17. DB_IR: 616 rows, but JASP recognizes only 521
[Cyrillic_1_2_3.zip](https://github.com/jasp-stats/jasp-issues/files/7699281/Cyrillic_1_2_3.zip)

**Comment by NikitaKhromov-Borisov** [comment] 2021-12-13 21:55
Additional confusion with Cyrillic
[Cyrillic_Tabs_and_Figs.docx](https://github.com/jasp-stats/jasp-issues/files/7707212/Cyrillic_Tabs_and_Figs.docx)

**Comment by JorisGoosen** [comment] 2021-12-14 12:21
Ah so from the docx:
![image](https://user-images.githubusercontent.com/29062713/145996690-bba19422-b075-4a7b-9ab3-44dae5143a7a.png)
The raincloud plot has  wrong information on the axis (@maltelueken @vandenman you guys aware of this?)

While the descriptives one is fine:
![image](https://user-images.githubusercontent.com/29062713/145996965-c4e42dc9-335c-4e99-96eb-320c5cb30027.png)


And as far as the data in "Cyrillic_1_2_3" goes, is this a correct representation:
```
АО | Группа
Нет | БАК
Нет | БАК
Нет | БАК
Нет | БАК
Нет | ТАК
Нет | ТАК
Нет | БАК
Нет | ТАК
Нет | ТАК
Нет | БАК
Нет | БАК
Нет | БАК
Нет | БАК
Нет | ТАК
Нет | БАК
Нет | кат
Нет | каб
Нет | ТАК
Нет | БАК
Нет | ТАК
Нет | ТАК
Нет | ТАК
Нет | ТАК
Нет | БАК
Нет | ТАК
Нет | БАК
Нет | БАК
Нет | БАК
Нет | БАК
Нет | ТАК
```

Because I do not have my system in Russian so had to guess the way it should be interpreted.

**Comment by NikitaKhromov-Borisov** [comment] 2021-12-14 12:34
"НЕТ" = "No" - outcomes in columns, ТАК and БАК - abbreviations

Best regards,
Nikita

вт, 14 дек. 2021 г. в 15:21, Joris Goosen ***@***.***>:

**Comment by JorisGoosen** [comment] 2021-12-14 12:45
Thank you.

I see the problem with the last entry being wrong.
This should of course be fixed.

But in the meantime (because it will take a while what with Christmas and all that) you can try one other workaround.
If you save your file as “CSV UTF-8 (comma delimited) (*. csv)” in excel, that might also help you out. 

And also will make the file so that it can be opened anywhere in the world and still be correct. While the files you have now will only display correctly on windows-systems set to Russian/Cyrillic.

**Comment by icekylin** [comment] 2022-02-10 02:51
@JorisGoosen This issue could be closed by https://github.com/jasp-stats/jaspTTests/commit/fcd5f25116168f0dc890cf654c595d623f9e5d23

**Comment by JorisGoosen** [comment] 2022-02-10 10:59
> @JorisGoosen This issue could be closed by [jasp-stats/jaspTTests@fcd5f25](https://github.com/jasp-stats/jaspTTests/commit/fcd5f25116168f0dc890cf654c595d623f9e5d23)

Only the part with the wrong axis-info under the raincloud plot right?

I think I still have to look at the last entry being read wrong.

**Comment by icekylin** [comment] 2022-02-10 11:41
>Only the part with the wrong axis-info under the raincloud plot right?

yup,the problem is solved. The characters in the axis are normal. 

for data read and encode needs to go further investigation.

**Comment by shun2wang** [comment] 2022-10-17 08:26
Closed due to inactivity for a long time. and the encoding in dataset was replaced by a new specifically issue.

**Closed by shun2wang** 2022-10-17 08:26 UTC
Labels: OS: Windows

**Comment by juliuspf** [comment] 2022-10-17 09:01
@shun2wang, could you also mention the issue that now contains the part of this one still unsolved?

**Comment by shun2wang** [comment] 2022-10-17 09:04
yes, I think this one: https://github.com/jasp-stats/jasp-issues/issues/1842 and Joris is work on it.
