### ISSUE TITLE
[Bug]: i cant see out of bag predictions in random forest classification

### ISSUE THREAD

**Issue by medoteto** [jasp-stats/jasp-issues#2902] opened 2024-09-08 22:58 UTC
### JASP Version

0.19.0

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

random forest classfication

### What OS are you seeing the problem on?

Windows 10

### Bug Description

i cant see out of bag predictions in random forest classification

### Expected Behaviour

i cant see out of bag predictions in random forest classification

### Steps to Reproduce

i cant see out of bag predictions in random forest classification
![Untitled](https://github.com/user-attachments/assets/c62af5d2-c8a0-4bde-a128-350e798777d4)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-09-09 06:58
I did not use the ML module much yet, but I guess the predictions would be saved as a new column. So just cklick on the arrow on the very left to get to the data view and look there? I hope...

**Comment by medoteto** [comment] 2024-09-10 00:06
i tried many times to see out of bag predictions but i cant see it i suggest to add out of bag predictions to jasp machine learning random forest classfication model

**Comment by tomtomme** [comment] 2024-09-10 10:17
So I just tried what @koenderks already explained in  https://github.com/jasp-stats/jasp-issues/issues/2894#issuecomment-2328206697 - and I got results, see below - and one error message, which seems irrelevant, since you are getting no results at all.
So please look again at the workflow, maybe this screenshot helps explaining it - and especially make sure that the variable names match!

![grafik](https://github.com/user-attachments/assets/7a98d3b9-854c-4543-97be-e7bac4ca706f)

Here again koens explanation with some more details
> The workflow is as follows (see also https://jasp-stats.org/2022/04/26/how-to-predict-with-machine-learning-models-in-jasp-classification/)
> 
>     Train a model on training data
>     Save the trained model as .jaspML file
>    in a new JASP session  load new  data  that you want to make predictions for - but make sure to use matched variable names
>     Load the trained model (i.e., .jaspML file) into "machine learning => Prediction" within that new session
>     Now you can view the predictions of the model for the new data and save them as a new column

If all this does not help please make sure to read the link koen provided in detail. Everything there is laid out nicely and I can follow it even if I have never done machine-learning-predictions before. So you can do it too! The functionality is there!

https://jasp-stats.org/2022/04/26/how-to-predict-with-machine-learning-models-in-jasp-classification

**Comment by medoteto** [comment] 2024-09-10 16:41
this is not out of bag predictions this is training and test predictions

**Comment by tomtomme** [comment] 2024-09-10 19:56
Ao predictions based on the data you trained your model on?
Or what do you mean by "out of bag"

**Comment by medoteto** [comment] 2024-09-10 20:22
in randomforest right screen you can see out of bag accuracy on the right of validation and test accuracy i mean this out bag predictions that have accuracy 0.882 in the right of screen shot right of validation and test accuracy
    On Tuesday 10 September 2024 at 21:57:10 GMT+2, Thomas Langkamp ***@***.***> wrote:  
 
 


So predictions based on the data you trained your model on?
Or what do you mean by "out of bag"

**Comment by medoteto** [comment] 2024-09-11 00:13
you can see in this picture out-of-bag classfication accuracy plot in training set and validation set





    On Tuesday 10 September 2024 at 22:21:48 GMT+2, muhammad tamer ***@***.***> wrote:  
 
  in randomforest right screen you can see out of bag accuracy on the right of validation and test accuracy i mean this out bag predictions that have accuracy 0.882 in the right of screen shot right of validation and test accuracy
    On Tuesday 10 September 2024 at 21:57:10 GMT+2, Thomas Langkamp ***@***.***> wrote:  
 
 


So predictions based on the data you trained your model on?
Or what do you mean by "out of bag"

**Comment by medoteto** [comment] 2024-09-11 02:44
i dont know what out of bag mean but i dont see out of bag predcitions i can see training and validation and test predcitions only

**Comment by tomtomme** [comment] 2024-09-11 07:06
@koenderks 
Can you help me out here?

**Comment by koenderks** [comment] 2024-09-11 07:18
In Random Forest, many decision trees are built using different random samples of the data. Some data points are repeated in these samples, while others (about 1/2 of the data by default) are left out. The data points not used to train a particular tree are called **out-of-bag** samples. After training each tree, it can make predictions on its out-of-bag samples, which were not used in that tree’s training. Since every point is left out of some trees (about 1/2 of them by default), all those trees can make predictions for it. The final out-of-bag prediction for each data point is the majority vote of the predictions from the trees where that point was an out-of-bag sample. So suppose you trained 100 trees, then 50 of those trees can make a prediction for each out-of-bag data point. If we do this for all each possible number of trees to train, we can show the out-of-bag accuracy as a function of the number of trees. This is what you see in the figure. It is mainly used to assess performance as a function of the number of trees.

However, we don't actually show the out-of-bag predictions to users because:
1. There are too many trees and predictions to display.
2. Out-of-bag predictions can be misleading since they don't reflect the final output of the full model.

**Comment by medoteto** [comment] 2024-09-11 13:06
ok thank you very much

**Comment by medoteto** [comment] 2024-09-11 13:07
i suggest to add out of bag predcitions

**Comment by tomtomme** [comment] 2024-09-14 08:49
Closing as duplicate of #2909

**Closed** 2024-09-14 08:49 UTC
Labels: Module: jaspMachineLearning, Feature Request
