### ISSUE TITLE
[Bug]: Linear Modeling terminates 

### ISSUE THREAD

**Issue by Dazzizle** [jasp-stats/jasp-issues#1871] opened 2022-10-24 20:14 UTC
### JASP Version

0.16.4

### JASP Module

jaspVisualModeling

### What analysis are you seeing the problem on?

Linear modeling

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This analysis terminated unexpectedly.

Error in UseMethod('.applyEnDeCoder', x): no applicable method for '.applyEnDeCoder' applied to an object of class 'character'

Stack trace

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports

### Expected Behaviour

Should have gotten a regression plot

### Steps to Reproduce

1. Visual modeling
2. Linear modeling
3.  insert dependent and independent variable
4. Bug appears in output window
...
![Screenshot (116)](https://user-images.githubusercontent.com/98485202/197619944-c23bdf5a-964d-42ce-8acd-f0cf2316636a.png)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment] 2022-10-25 07:22
Hi @Dazzizle, thanks for reporting this. Is it possible that you upload a .jasp file or data file that causes the issue?

**Comment by juliuspf** [comment] 2022-10-25 07:24
@dustinfif, do you know what is going wrong? Somehow GitHub doesnt allow me to assign you to the issue.

**Comment by Dazzizle** [comment] 2022-10-25 07:28
Hi,

Thanks for answering. I cannot upload the original data file which is a jasp file. But the same issue appears if i use a csv file. I have created a random file with two variables, which i would use as dependent/independent in the linear modeling. Same thing happens with this one
[test.csv](https://github.com/jasp-stats/jasp-issues/files/9858044/test.csv)

**Comment by juliuspf** [comment] 2022-10-25 07:38
Ah I see, that this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1849. I will close this issue then, and you could subscribe to the other issue to see when it will be resolved. Thanks for reporting though!

**Closed by juliuspf** 2022-10-25 07:38 UTC
Labels: Module: jaspVisualModeling
