### ISSUE TITLE
PROCESS macro 

### ISSUE THREAD

**Issue by Jacksonj1290** [jasp-stats/jasp-issues#1035] opened 2020-11-02 01:16 UTC
Andrew Hayes' has a free PROCESS macro that works with SPSS, SAS, and R
http://www.processmacro.org/index.html
 
It is great for performing 74 different mediation, moderation, and mediated-moderation analyses (aka indirect, conditional, and conditional indirect tests). It goes along with his book: Introduction to Mediation, Moderation, and Conditional Process Analysis
Second Edition A Regression-Based Approach (2017) Andrew F. Hayes. 

PROCESS is widely used in psychology (at least in social psychology, personality psychology, and I/O)

I am going to try using JASP exclusively for my advanced research classes (my students have free access to spss on campus, but not at home), but would love to be able to use PROCESS with it. I've become rather dependant on it over the years. 

Since it looks like JASP uses R I was wondering if the R version of PROCESS could work with JASP. I'm sorry if my question is way out of line. I don't know much about programing.    

I will also ask Andrew Hayes if he has any plans for creating a version of PROCESS for JASP. 

Thank you for your product and for all of the resources. I've not worked with it much yet, but it seems like a wonderful program and set of materials. 

Sincerely, 

Jay Jackson, Professor of Psychology, Purdue Fort Wayne

**Comment by boutinb** [comment] 2020-11-02 15:42
@EJWagenmakers Do you know PROCESS? 
@Jacksonj1290 We are in the process to make it easier for the R programmer to add a module in JASP. It is already possible but in a beta mode in 0.14. Documentation is already here: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-adding-module.md
So if someone is willing to add a module for PROCESS, we will be happy to help.

**Comment by Jacksonj1290** [comment] 2020-11-02 15:50
Thanks for your speedy response. I use PROCESS, but I don't know much about programming. I will forward your message to Andrew Hayes, the developer of PROCESS.   
@Jacksonj1290

**Comment by KarisColyerPatel** [comment] 2022-02-22 07:39
Hey there, I am hoping to use JASP for a moderation analysis and was wondering if it is yet possible to use PROCESS macro?

**Comment by Kucharssim** [comment] 2022-02-22 08:46
Dear all,

Thank you for this request. In general, models that are implemented in PROCESS can be run within the SEM module in JASP. Classic mediation models can be run using the "Mediation" analysis, more complicated models can be run using lavaan syntax in the "Structural Equation Modeling".

I understand though that this is not for everyone, as PROCESS became a standard in some fields and it's not easy to switch from PROCESS to lavaan.

I think we could in theory implement PROCESS inside of the SEM module, but it comes with some difficulties. The official PROCESS for R maintained by A. F. Hayes is not on CRAN (and is not a traditional R package but a single script containing R functions), but we would have to include the functions after downloading them manually from the PROCESS website. This makes it cumbersome to maintain, but theoretically it would be possible. However, the license of the PROCESS says the following (http://www.processmacro.org/download.html):

> This software should not be posted or stored on any webpage, server, or directory accessible to the public whether free or for a charge unless written permission has been granted by the copyright holder.  The copyright holder requests that this software be distributed by directing users to processmacro.org where the latest release of the software and documentation is archived and can be downloaded.

All in all, including the official version of PROCESS for R in JASP brings additional implementation and maintenance burden on us compared to other functionality implemented in traditional R packages included on CRAN.

That said, there is a processR package on CRAN (https://cran.r-project.org/web/packages/processR/index.html), which is not maintained by Hayes himself, but is an independent implementation of the functionality. Given that the package basically generates lavaan syntax given a specification of the PROCESS model, it should be relatively straightforward to implement in the SEM module. The downside is that this package does not implement all models that are available in official PROCESS, and for those that are available, does not guarantee that they lead to identical result as the official version. It is a possibility though.

I wonder what @EJWagenmakers thinks about this?

**Comment by EJWagenmakers** [comment] 2022-02-22 09:53
We should definitely do that. Let's discuss how much work this would take.

**Comment by juliuspfadt** [comment] 2023-02-09 07:12
I am just now seeing that this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/675, but lets keep this open, as it has useful info in the comments.

**Comment by EJWagenmakers** [comment] 2023-02-09 07:51
Update: we have received a grant to implement this, and a first version should be ready this year.

**Comment by tomtomme** [comment] 2023-12-22 21:07
This can be closed

PROCESS is now available in beta: 
https://github.com/jasp-stats/jasp-desktop/releases/tag/v0.18.2.beta
 
or via our nightly builds: 
https://static.jasp-stats.org/Nightlies/

final 0.18.2 will be out soonTM.

**Comment by boutinb** [comment] 2024-01-03 10:24
It is now officially released.

**Closed by boutinb** 2024-01-03 10:24 UTC
Labels: Module: jaspSem, Feature Request
