### ISSUE TITLE
BayesianLMM

### ISSUE THREAD

**Issue by Ilse90** [jasp-stats/jasp-issues#1334] opened 2021-06-11 08:56 UTC
* JASP version: 0.14.1

* OS name and version: MACOS Big sur 11.4
* Analysis: Bayesian LMM
* Bug description: Error in if (var_name ≠ 'Intercept' && nrow(temp_summary) > 1) {: missing value where TRUE/FALSE needed
* Expected behaviour:

What can I do to perform this analysis?

**Comment by Ilse90** [comment] 2021-06-22 12:27
I see that I did not wrote the complete error previously:

This is the whole bug description:

Error in if (var_name ≠ 'Intercept' && nrow(temp_summary) > 1) {: missing value where TRUE/FALSE needed

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mmRunAnalysis(jaspResults, dataset, options, 'BLMM')

.mmSummaryStanova(jaspResults, dataset, options, type)

**Comment by FBartos** [comment] 2021-06-22 19:38
Hi @Ilse90 ,

sorry for getting so late to you.

I have recently fixed a similar issue for the new release. Could you please save the analysis that throws error as a .JASP file, zip it, and upload it here? I could test whether the latest fix solves the issue. If not, I will resolve it and make sure it will work with the new release.

Cheers,
Frantisek

**Comment by Ilse90** [comment] 2021-06-23 06:31
Hi Frantisek,

Thank you for reaching out. Please find attached the file. I am looking forward to hearing from you.

Regards, Ilse

[MFB-vALIC LMM 22-6-2021-1.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6699464/MFB-vALIC.LMM.22-6-2021-1.jasp.zip)

**Comment by FBartos** [comment] 2021-06-23 09:22
Hi Ilse,

thanks for the file. I was able to reproduce the bug. It's unfortunatelly a different issue I was dealing with previously, but I will work on it to make it work with the next release.

Cheers,
Frantisek

**Comment by Ilse90** [comment] 2021-06-23 09:24
Dear Frantisek,

Thank you for your quick reply and for looking at the issue. Can you please send a message in this chat when the bug is solved in the next release? Thanks in advance!

Regards, Ilse

**Comment by FBartos** [comment] 2021-06-23 09:35
I will link the fix to the issue to this report, so when it is merged you will recieve a notification regarding this thread. Then, it will be a part of the new release version of JASP, mentioned on twitter and everywhere else. Would that be sufficient?

Regards,
Frantisek

**Comment by Ilse90** [comment] 2021-06-23 09:36
Great! Thanks a lot :)

**Comment by Ilse90** [comment] 2021-07-15 11:10
Hi Frantisek,

Do you maybe know when the next JASP version will be launched?

Regards,
Ilse

**Comment by FBartos** [comment] 2021-07-15 15:54
Hi Ilse,

the planned launch is at the end of Augustus. 
(it's taking a bit longer than expected, but we have many new features that require extensive testing)

Cheers,
Frantisek

**Comment by Ilse90** [comment] 2021-07-16 12:20
Thank you for letting me know!

**Comment by FBartos** [comment] 2021-09-04 06:45
Hi Ilse, 

the issue is currently fixed in the development version. It will be out with the next release but you can also check it out with a [Nightly](http://static.jasp-stats.org/Nightlies/) if you wish.

Best,
Frantisek

**Closed by FBartos** 2021-09-04 06:45 UTC
Labels: Module: jaspMixedModels

**Comment by Ilse90** [comment] 2021-09-09 08:52
Dear Frantisek,

Thank you for teaching out and I am glad to hear that the issue is fixen. Do you have any idea around what time the next version will be released?

Cheers,
Ilse

**Comment by FBartos** [comment] 2021-09-09 11:38
Dear Ilse,

we are in the final stages of preparing the new version (the aim is within two months I think). Unfortunately, I can't pinpoint the precise date yet.

Best,
Frantisek

**Comment by Ilse90** [comment] 2021-11-16 02:51
Hi Frantisek,

I saw that the new version of JASP is released and that the bug is fixed! So I can run the analyses now. However I don’t get a Bayes factor when running the analysis. I read in an old post on a forum that Bayes mixed model didn’t support Bayes factor yet. Is this also the case in the new version? And will it support Bayes factor in the future?

Thank you in advance for your help!

Cheers,
Ilse

**Comment by FBartos** [comment] 2021-11-16 09:16
Hi Ilse,

Glad that your analyses are working now. Yes, you are right, Bayes factors are not supported yet. Our group is still figuring out what would be the most sensible way of implementing them -- there was even a [special issue](https://link.springer.com/article/10.1007/s42113-021-00113-2) trying to tackle the current obstacles.
Adding Bayes factors to Mixed Models will definitely be a notable announcement, so you won't miss it if you follow the JASP twitter/blog.

Cheers,
Frantisek

**Comment by Ilse90** [comment] 2021-11-16 23:23
Hi Frantisek,

Thank you for your reply and I can imagine implementing BF in Mixed Models must be difficult. Good luck with it! And I look forward to your groups solution :) 

Cheers,
Ilse
