### ISSUE TITLE
The sign of the correlation index is not shown in regression procedure

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-issues#489] opened 2019-09-16 09:48 UTC
* JASP version: 0.10.2
* OS name and version: Mac OS Mojave 10.14.6
* Analysis: Linear Regression
* Bug description: the sign of the correlation index is not shown, see red mark in the attached images
* Add JASP files as a zip:
[Correlación y regresión ejercicio 4.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3615610/Correlacion.y.regresion.ejercicio.4.jasp.zip)

* Screenshot: 
<img width="541" alt="Captura de pantalla 2019-09-16 a las 11 43 37" src="https://user-images.githubusercontent.com/29978768/64948509-87a5ab00-d877-11e9-8a7d-59ee3d173cc0.png">
<img width="532" alt="Captura de pantalla 2019-09-16 a las 11 43 43" src="https://user-images.githubusercontent.com/29978768/64948510-87a5ab00-d877-11e9-862e-d12df11e6f6a.png">

* Expected behaviour: a negative correlation index, as we could see at the attached screenshot 
* Steps to reproduce: 
See the attached JASP file

**Comment by Kucharssim** [comment] 2019-11-21 12:21
Hello @vicenteinefo,

thank you for pointing this out! However, this is not a bug, because the coefficient R in the linear regression table is not a classical Pearson's correlation between the two variables, but a multiple correlation coefficient (see help files and https://en.wikipedia.org/wiki/Multiple_correlation) so that it can be generalised to models with multiple predictors. As such, it is a correlation between the dependent variable and the _predictions_ of the dependent variable given by the model and so it would be suspicious indeed to see a negative value there. 

I am now closing this issue - please reopen if you want a follow up on this question.

Best,
Simon

**Closed by Kucharssim** 2019-11-21 12:21 UTC
