### ISSUE TITLE
Bayes Repeated Measure Anova Crashing on on large analysis

### ISSUE THREAD

**Issue by georgelovell** [jasp-stats/jasp-issues#315] opened 2019-03-01 09:27 UTC
Bayes Repeated Measure Anova Crashing on a large analysis

PC Windows 10, 32GB RAM, Core i7 and Cuda.

JASP file
https://www.dropbox.com/s/a85ltpsgb40ltxx/AdelsonMergedANOVAdata.jasp?dl=1

RAW data
https://www.dropbox.com/s/2060zgjsh851u7i/AdelsonMergedANOVAdata.csv?dl=1

[MergedANOVAdata.zip](https://github.com/jasp-stats/jasp-issues/files/2918749/MergedANOVAdata.zip)

* JASP version:
* OS name and version:

JASP Version 0.9.2
PC Windows 10

* Analysis:

Bayesian Repeated Measures ANOVA

* Bug description:

This is a rather complex data set (sorry!) with 4 within subjects factors (2x2x2x2) and 2 between subjects factors (2x2). I can analyse the data successfully in conventional frequentist ANOVA. When I try and run it using Bayes the software hangs. Sometimes I get the progress bar as it starts to analyse (possibly when the data were in long-form (all rows). But I can't get it to analyse the data to completion.

* Add JASP files as a zip:
* Screenshot: 

![screenshot 2019-03-01 09 24 52](https://user-images.githubusercontent.com/24653425/53628816-eff6ad00-3c03-11e9-9c80-42c92ad44d95.png)

* Expected behaviour:
* Steps to reproduce: 

The results shown on the right were for the data prior to the inclusion of the between subjects factors (flip and shadL). Once those are dragged across nothing happens (CPU use goes to zero percent for JASP).

**Comment by vandenman** [comment] 2019-03-01 12:58
Thanks for reporting this! 

By default, we consider all possible interaction effects and all possible models that arise. In your case, the number of models is:

`2^(sum(choose(7, 1:7)) = 2^127 ~= 1.701412e+38`

Given this astronomical amount of models, either the computation time takes forever or JASP encounters an internal error and quits.

Most likely a lot of higher interactions are not worth considering, so to make life easy we can exclude those models by excluding all interaction effects. To do so you go to model, select under model terms all interaction effects and click on the left arrow. Since JASP normally gives output immediately, you might want to enter the dependent variable last. The resulting number of models is still large (2^7 = 127) and computation might take a couple of minutes. Still JASP could compute this on my laptop (8 GB RAM, intel i7 CPU @ 2.40 GHz). Let me know if this solves the problem!

**Comment by georgelovell** [comment] 2019-03-01 15:39
Thanks, I had a feeling the crazy number of interactions might be the problem. I hadn't realised you could simplify the model using the arrow. I'll try that now, thanks very much!

George

**Comment by vandenman** [comment] 2019-03-06 11:24
I'm closing this now assuming the problem is fixed. Feel free to reopen if this is not the case!

**Closed by vandenman** 2019-03-06 11:24 UTC
