### ISSUE TITLE
[Bug]: This analysis terminated unexpectedly REGRESSION

### ISSUE THREAD

**Issue by statsinkin** [jasp-stats/jasp-issues#1523] opened 2021-12-03 05:24 UTC
### JASP Version

0.16 (Development)

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Correlation scatter plot and pairwise

### What OS are you seeing the problem on?

macOS big sur 11.5.2

### Bug Description

This analysis terminated unexpectedly.

Error in Summary.factor(structure(c(6L, 3L, 5L, 1L, 7L, 4L, 2L), .Label = c('1', : ‘range’ not meaningful for factors

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

Correlation(...)

.corrPlot(jaspResults, dataset, options, ready, corrResults)

.corrPairwisePlot(jaspResults, dataset, options, ready, corrResults)

.corrScatter(xVar = data[, 1, drop = TRUE], yVar = data[, 2, drop = TRUE], options = options, xBreaks = var1Breaks, yBreaks = var2Breaks, drawAxes = FALSE)

.plotScatter(xVar = xVar, yVar = yVar, options, xBreaks = xBreaks, yBreaks = yBreaks, xName = xName, yName = yName, drawAxes = drawAxes)

ggplot2::scale_x_continuous(name = NULL, breaks = xBreaks, labels = NULL, limits = range(xBreaks))

continuous_scale(ggplot_global$x_aes, 'position_c', identity, name = name, breaks = breaks, n.breaks = n.breaks, minor_breaks = minor_breaks, labels = labels, limits = limits, expand = expand, oob = oob, na.value = na.value, trans = trans, guide = guide, position = position, super = ScaleContinuousPosition)

Summary.factor(c(6, 3, 5, 1, 7, 4, 2), na.rm = FALSE)

stop(gettextf('%s not meaningful for factors', sQuote(.Generic)))

### Expected Behaviour

Correlation plot should have regression line and display pairwise should create a table. 

### Steps to Reproduce

1. create a regression, select correlation
2. select pearsons r, display pairwise, report significance, flag significance, confidence intervals 95%
3. select scatter plots, densities for variables and statistics 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment] 2021-12-03 08:05
[correlation_error.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/7647728/correlation_error.jasp.zip) (rename and drop .zip)

@Kucharssim do you have time to take a look?

**Comment by Kucharssim** [comment] 2021-12-03 08:06
I will hve a look

**Comment by statsinkin** [comment] 2021-12-03 23:38
Do you know why its not working?

**Comment by vandenman** [comment] 2021-12-06 12:37
@statsinkin The error happens because you used an ordinal variable. In R, ordinal and continuous variables are represented differently (numeric vs factor). For some operations, such as creating plots, we need to treat ordinal variables differently from continuous variables, otherwise, errors occur such as the one you reported. This is now fixed by jasp-stats/jaspRegression#97 and in the next release of JASP the error should no longer appear.

In the meantime, you can change your ordinal variable to continuous in the following manner:

1. Click on the icon next to your variable name in data view:
2. Click on `Scale`.
![image](https://user-images.githubusercontent.com/21319932/144847009-cf92fa17-5953-45c0-a2f6-b0c1fa7c9885.png)

Since @Kucharssim's fix solves the bug I'm closing this issue now. The error should disappear once the variable is interpreted as scale (but do let us know if this is not the case!).

**Closed** 2021-12-06 12:37 UTC
Labels: Module: jaspRegression, Bug: Low
