### ISSUE TITLE
[Bug]: JASP Raincloud plots jumble (disorder) variable orders and colours

### ISSUE THREAD

**Issue by JayD05** [jasp-stats/jasp-issues#1935] opened 2022-12-08 16:04 UTC
### JASP Version

0.16.4

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Paired-Samples T-test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I want to produce two raincloud plots: one for reaction times (RTs) and one for error counts (omissions), both comparing responses on high-value vs. low-value trials. Obviously I'd like to present these graphs with consistency, with variables in the same order and colours, but this seems impossible in JASP. 

The image below shows that even when variables are entered in the same order (high then low) for both RTs and omissions, JASP presents them in different orders and colours. This makes interpretations for future readers much more confusing. 

![Capture](https://user-images.githubusercontent.com/120119018/206496520-578ddf56-ba36-4959-89e8-1f3ad015c7f6.PNG)

Nothing I've done changes the outcome at all. Data.zip is below. Thanks

[data.zip](https://github.com/jasp-stats/jasp-issues/files/10187228/data.zip)

### Expected Behaviour

I would expect the plots to show the variables in the order in which they are entered in the "variable pairs" box. 

### Steps to Reproduce

1. Run Paired-samples t-test (Frequentist or Bayesian)
2. Select Raincloud plot
3. That's it
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment] 2023-01-18 08:33
Yes, we clearly need to address this, thanks for pointing it out. We are developing extensive raincloud functionality so this issue has our attention.
E.J.

**Comment by JayD05** [comment] 2023-01-22 15:56
Great, thanks E.J.

Jay

**Comment by tomtomme** [comment] 2024-02-04 18:04
@JayD05 
Closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/1784
There is work underway to improve raincloud plots atm! Lets hope this is fixed soon!

**Closed by tomtomme** 2024-02-04 18:04 UTC
Labels: Module: jaspTTests, OS: Windows 10, Bug
