### ISSUE TITLE
Network Theory Stability Coefficient 

### ISSUE THREAD

**Issue by rcgraz** [jasp-stats/jasp-issues#1184] opened 2021-02-26 19:19 UTC
* Enhancement: Network Theory Stability Coefficient 
* Purpose: To keep network theory applicability up to date
* Use-case: When using network theory

**Is your feature request related to a problem? Please describe.**
 It is now standard practice in the psychological Network Theory literature to include a stability coefficient, which is not currently included in JASP. 

**Describe the solution you'd like**
 Inclusion of the stability coefficient, which is now part of the R package bootnet

**Describe alternatives you've considered**
 

**Additional context**

**Comment by vandenman** [comment] 2021-03-01 07:56
Thanks for the feature request! 

Just to make sure we're on the same page, you're referring to [`corStability`](https://rdrr.io/cran/bootnet/man/corStability.html), which is only applicable when doing a case-drop bootstrap?

**Comment by rcgraz** [comment] 2021-03-01 14:54
Hello,

Yes! This is what I mean. It was also be great if a centrality stability plot could be created. 

Both are part of the bootnet R package but neither of these are currently available via JASP (which uses the bootnet package I believe). 

If it’s helpful, here is the bootnet package pdf: https://cran.r-project.org/web/packages/bootnet/bootnet.pdf <https://cran.r-project.org/web/packages/bootnet/bootnet.pdf>. Please see page 8 and/or page 11 for the code for both the centrality stability coefficient and centrality stability plot. 

This would be incredible helpful (a real game changer) for the applicability of using network analysis on JASP if those were both implement.

Thank you so much for your time and help!

Best,
Robert

**Comment by tomtomme** [comment] 2024-01-15 13:37
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1184

Please reopen, if I am mistaken.

Also related: https://github.com/jasp-stats/jasp-issues/issues/2235

**Closed by tomtomme** 2024-01-15 13:37 UTC
Labels: Module: jaspNetwork, Feature Request
