### ISSUE TITLE
Bug Report: JASP 0.9.0.1 If I save a file with many plots, I get empty plots at some point

### ISSUE THREAD

**Issue by GerineL** [jasp-stats/jasp-issues#182] opened 2018-09-26 14:02 UTC
* JASP version: 0.9.0.1
* OS name and version: Windows 7 [but idem with Windows 10 at home]
* Problem: 
I have a file with approximately 9500 cases for which I want to examine 17 correlation pairs with Prior and Posterior plots, Robustness Check and Sequential Plots (i.e., approx 50 plots).
The problem occurs when I try to export my results to a HTML page. 
If everything goes right, the file is about 1,1 MB, but oftentimes a file with the size of 150k or 330k is saved, that does not show all plots. Restarting Jasp a few times sometimes - but not always - helps. 
For some other files, I noticed that saving it the first time will get me half a file, and if I save it again it will fill it until complete. 
I had the same issue when I tried to upload my results to OSF instead.
Also, I had the same issue about a year ago when I started this paper (can't remember what version of Jasp I used then).

A desired solution would be to either fix it so it always saves the entire file, or give a warning already during the analyses to indicate that the maximum file size is reached.

**Comment by JorisGoosen** [comment] 2019-07-02 16:06
@GerineL Hopefully the problem is gone now with the newest release.

On the other hand, it sounds like the analyses were still running perhaps? Seeing as how this is all quite a while ago I will close this issue now. But in case the problems persist, feel free to reopen this issue.

**Closed by JorisGoosen** 2019-07-02 16:06 UTC
