### ISSUE TITLE
[Bug]: Label Editor Cannot alter order

### ISSUE THREAD

**Issue by iandol** [jasp-stats/jasp-issues#2388] opened 2023-11-07 03:09 UTC
### JASP Version

0.18.1

### Commit ID

75f023c7fcfbc4ec813b081b1a633e406c74a29b

### JASP Module

Unrelated

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

We are trying to reorder labels. With the Label Editor open we select a label but when we push the ↑ icon all items get selected. Click again and some labels remain selected. Clicking ↓ and nothing happens. We've tested on Ubuntu 23.10 using the official release 0.18.1 and macOS silicon using the latest nightly.

### Expected Behaviour

Pressing up and down icons orders the labels.

### Steps to Reproduce

1. Open the label editor
2. Select a label
3. Press the UP button
...

### Log (if any)

https://github.com/jasp-stats/jasp-issues/assets/153905/8ace9e46-f09b-405f-b7f5-67bec49ad253

[TotalTimeChart.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/13275292/TotalTimeChart.jasp.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2023-11-07 07:53
I cannot reproduce this on AMD x64 using Manjaro Linux and JASPs 0.18.1 Flatpak build. I guess you use Flatpak on Ubuntu too? Maybe its the special  combination with a Apple Silicon chip. As far as I know those chips are not yet fully supported by the linux kernel.

**Comment by boutinb** [comment] 2023-11-07 08:55
Hi @iandol I see already that in the label editor, there is no value. There is something wrong with the data. I could not load your jasp file, could you send just your data file? Then I can check if I can reproduce this with your data.

**Comment by tomtomme** [comment] 2023-11-07 10:07
sorry, I overlooked the data file. I can reproduce this with the JASP data file. I had no problem loading the data, but csv export gives mostly empty cells, because the value column in the label-editor is empty and only the labels are filled. 
I had this same effect lately with data imported from a .SAV, where some variables included whole scentences / strings. The scentences were stored in the label field while the value field was empty.

**Comment by iandol** [comment] 2023-11-08 01:00
Thank you both! I submitted this bug on behalf of my postdoc, I need to ask him for the source file. I think a Libreoffice Calc ODS file was the source, not a plain CSV file. Perhaps this may be part of the problem. @tomtomme mentions that the import only partially imported the values, I can confirm export data to CSV and all text content is missing:

![Screenshot 2023-11-08 at 08 42 47](https://github.com/jasp-stats/jasp-issues/assets/153905/a25426b6-f4c5-441f-977c-2773b23b4b20)

So i tried to make a new ODS to test a new project:

[Test.ods](https://github.com/jasp-stats/jasp-issues/files/13290768/Test.ods)

But I can't reproduce the missing values, that ODS file imports just fine. So unfortunately we can't reproduce this, perhaps a Libreoffice upgrade, or JASP upgrade has changed this. As it can't be reproduced (though it is real in that JASP file), should this issue be closed?


----

Just for clarification, we originally saw this bug on a Dell+Intel laptop running Ubuntu. I tested on my Macbook M2 running macOS 14, both the official Jasp 0.18.1 and then the nightly. We are using macOS on Apple Silicon and Ubuntu on the Intel Dell.

**Comment by shun2wang** [comment] 2023-11-08 01:38
Thanks for your clarification.

If it's a LibreOffice bug then recommended that you file a report to them to resolve the issue for more people. following https://wiki.documentfoundation.org/QA/BugReport

we can close it for now if still JASP issue please feel free to repoen it or file a new issue.♥

**Closed by shun2wang** 2023-11-08 01:38 UTC
Labels: OS: macOS Silicon, Bug

**Comment by iandol** [comment] 2023-11-08 07:17
@shun2wang — just to be clear, the bug is clearly in JASP. The ODS file is fine and LibreOffice Calc works, as does opening in Excel. But for some unreproducible reason, when importing from ODS, it caused JASP to have incomplete data which was exposed when reordering. It is fine to keep this closed as we cannot however reproduce how we ended up with incomplete data in JASP.

**Comment by shun2wang** [comment] 2023-11-08 07:25
Okay, thanks for your take care. we can open it once this can be reproduced otherwise seems we can do nothing. I cannot reproduce too.

**Comment by shun2wang** [comment] 2023-11-09 06:18
Now maybe I know what happend, we have a reproduce path and tracked at here:https://github.com/jasp-stats/jasp-issues/issues/2396
