### ISSUE TITLE
[Feature Request]: stable jasp-desktop for Arch Linux AUR

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1781] opened 2022-07-21 07:42 UTC
### Description

native Arch Linux package of a stable jasp version

### Purpose

more reliably using jasp on linux

### Use-case

every day work :D

### Is your feature request related to a problem?

Yes. We have jasp stable via flatpak, but the flatpak road faced issues in the past (uninstalling then installing again needed; one version of jasp skipped etc.). Then came the famous @sukanka to give us a native Arch package via BioArchLinux repo. However the update frequency there is high, more akin to daily snapshots of jasp devel.

### Describe the solution you would like

Track jasp stable via the standard AUR repo

### Describe alternatives that you have considered

see above

### Additional context

I do not know how much work this would be - I never packaged any software. So it might not be feasible. 
The situation on Arch Linux is already pretty solid, having flatpak stable, beta and bioArch native (Thanks again @sukanka!). So this is entirely a luxury issue.

**Comment by sukanka** [comment] 2022-07-21 07:53
Well, I agree with you. But there are several difficulties, I attempted to build stable versions of jasp and its modules, but jasp modules have no release or tags, see for example, [jaspBase](https://github.com/jasp-stats/jaspBase).

So in BioArchLinux repo, we have to check the DESCRIPTION file of the module, see https://github.com/jasp-stats/jaspBase/blob/master/DESCRIPTION, and compare the version number in the file with current version.

Example: below is part of the DESCRIPTION file, and its version is 0.16.4, if the version in the repo is below 0.16.4, it will be updated.
```
Package: jaspBase
Type: Package
Title: JASP Base
Version: 0.16.4
Author: JASP Team
Maintainer: Bruno Boutin <B.Boutin@uva.nl>
```

I prefer jasp-state release their modules as they release jasp-desktop. So I can use the stable releases to build them.

**Comment by vandenman** [comment] 2022-07-21 08:26
>  I attempted to build stable versions of jasp and its modules, but jasp modules have no release or tags

The goal is to change this at some point and give tag each module once there is a release. Until then, would it be possible to base everything on the commits listed in the released version of jasp-desktop? See for example https://github.com/jasp-stats/jasp-desktop/tree/v0.16.3/Modules.

**Comment by sukanka** [comment] 2022-07-21 09:03
> The goal is to change this at some point and give tag each module once there is a release. Until then, would it be possible to base everything on the commits listed in the released version of jasp-desktop? See for example https://github.com/jasp-stats/jasp-desktop/tree/v0.16.3/Modules.

Sure, as long as these commits are consistent with the latest tag or latest release, archlinux always follows the latest release or latest tag. 
For example, [jaspAnova @ 6a270bf](https://github.com/jasp-stats/jaspAnova/tree/6a270bf1cb200f72744a58b2d7450ac49391828b), if the latest release of jaspAnova points to `6a270bf`, and keeps unchanged (no newer release of jaspAnova) until the next release of `jasp-desktop`, it is ok.

And whenever a newer release of jasp-desktop is out, it **must** use the latest release of jaspAnova, if not, add a new release of jaspAnova with the commit used in `jasp-dekstop`

Note when we use the latest release, it is ok to make a new tag even when a new version of jasp-desktop is not released, as we can build packages only using releases instead of tags.

**Comment by tomtomme** [comment] 2022-07-21 10:08
Very cool! If this happens it would be cool to keep the "daily-snapshots" alongside a stable build for "beta-testing" purpuses on linux.

**Comment by tomtomme** [comment] 2022-10-05 15:57
Is this "tagging each module" a thing yet, so that I can close this issue?
Or should BioArch update its base now to this: https://github.com/jasp-stats/jasp-desktop/tree/v0.16.4/Modules

Either way - we are still on 0.16.3 within the BioArch. An Update would be great :)

**Comment by sukanka** [comment] 2022-10-06 00:59
> Is this "tagging each module" a thing yet, so that I can close this issue? Or should BioArch update its base now to this: https://github.com/jasp-stats/jasp-desktop/tree/v0.16.4/Modules
> 
> Either way - we are still on 0.16.3 within the BioArch. An Update would be great :)

The modules are still not tagged. But in BioArch,  some modules (jaspBase, jaspJags, jaspReliability)  are pinned to the commit in https://github.com/jasp-stats/jasp-desktop/tree/v0.16.4/Modules.

As there is trouble with `r-matrix`, we cannot build `jasp-desktop-0.16.4` with all its dependencies, you may have to build it yourself currently (you have to build `r-jaspbase`, `r-jaspjags`, see https://github.com/BioArchLinux/Packages/commit/9b650329565f381149a13079daaf9de955d96b42). The reason is that some of its dependencies require `Matrix>=1.4.2`, but `r` only provides `Matrix=1.4.1`, we have to wait for the `r-4.3.0` release.

**Comment by vandenman** [comment] 2022-10-06 07:27
There has been Matrix 1.5.1 since September 13th on CRAN, see https://cran.r-project.org/package=Matrix. I don't think you need R-4.3.0 to install that?

**Comment by sukanka** [comment] 2022-10-06 07:55
> There has been Matrix 1.5.1 since September 13th on CRAN, see https://cran.r-project.org/package=Matrix. I don't think you need R-4.3.0 to install that?

Different from other packages such as `arm`, `Matrix` is a built-in package of `r` itself. In archlinux, systemwide `Matrix` is provided by `r`, we cannot upgrade `Matrix` to `1.5.1` without overwriting files shipped with `r` (but this is definitely not recommended).

I have tried rebuilding `r-4.2.1`, but the built-in `Matrix` is still `1.4.1`,  so we have to wait for the upstream to fix this, that is, wait for a new release of `r` (maybe `4.3.0`) which ships `Matrix=1.5.1`

**Comment by vandenman** [comment] 2022-10-06 10:08
> but this is definitely not recommended

There is a difference between packages with priority "base", such as `base`, `compiler`, `datasets`, etc. and packages with priority "recommended". Recommended packages, like `MASS`, `Matrix`, `nlme` etc., are shipped by R because they provide functionality that many users need. But these packages are not developed as a part of the R project, they are developed as separate software projects and updates are distributed through CRAN. There should really be no danger in updating a recommended package, and I've never encountered any error from doing so. 

Is it possible to separate the installation of recommended packages from the installation of R and then distributing recommended packages like the usual R packages? When configuring R there is an option like `--with-recommended-packages=no`.

Nevertheless, This time you can also just wait because the next R release (4.2.2) is scheduled for the 31st of October (see https://developer.r-project.org/) and it should contain a newer version of Matrix.

**Comment by sukanka** [comment] 2022-10-06 11:23
> Is it possible to separate the installation of recommended packages from the installation of R and then distribute recommended packages like the usual R packages? When configuring R there is an option like `--with-recommended-packages=no`.

Surely we can, but `r` is distributed via the official repository, and I don't think the packager in the official repository will do that, as the official repository does not have any r package. 

Another way is to distribute `r` (built with `--with-recommended-packages=no`) in  BioArch repository and package these *Recommended packages* separately, but when you run `pacman -S r` it will install `r` from the official repository as it has higher priority.

> Nevertheless, This time you can also just wait because the next R release (4.2.2) is scheduled for the 31st of October (see https://developer.r-project.org/) and it should contain a newer version of Matrix.

This is good news for me. We can solve the problem caused by `Matrix` at that time

**Comment by tomtomme** [comment] 2022-10-25 14:05
Status when trying to launch JASP from AUR / bioARCH since about a week:

```
jasp
Setting special options for software rendering (aka safe graphics).
Making new argument list for Application startup: ./JASP --disable-gpu
Starting JASP 0.16.3 from commit  and branch 
QtWebEngineQuick initialized
Application initialized
qt.webenginecontext: 

GL Type: disabled
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.5
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: yes
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name JASP 
  *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-gpu  
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl disabled 

Application init entered
MainWindow constructor started
TempFiles::createSessionDir(): '/home/thomasl/.JASP/temp/77554' about to be (removed and re)created.
Going to construct the necessary models for JASP to function.
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-pt.qm
Desktop:        Language (Portuguese) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-de.qm
Desktop:        Language (German) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-es.qm
Desktop:        Language (Spanish) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-ja.qm
Desktop:        Language (Japanese) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-nl.qm
Desktop:        Language (Dutch) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-gl.qm
Desktop:        Language (Galician) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-id.qm
Desktop:        Language (Indonesian) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-tr.qm
Desktop:        Invalid translation file found with name: jaspDesktop-tr.qm
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-fr.qm
Desktop:        Language (French) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-eo.qm
Desktop:        Invalid translation file found with name: jaspDesktop-eo.qm
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-zh_Hans.qm
Desktop:        Language (Chinese) not registered in LanguageModel, adding it now
Desktop:        loadQmFile(/usr/lib/jasp-desktop/bin/../Resources/Translations/jaspDesktop-de.qm)
Entering eventloop
QWebEngineCertificateError is neither a QObject, nor default- and copy-constructible. You should not use it as a QML type.
QWebEngineFullScreenRequest is neither a QObject, nor default- and copy-constructible. You should not use it as a QML type.
QWebEngineLoadingInfo is neither a QObject, nor default- and copy-constructible. You should not use it as a QML type.
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QQmlApplicationEngine failed to load component
qrc:/components/JASP/Widgets/MainWindow.qml:115:3: Type CustomMenu unavailable
qrc:/components/JASP/Widgets/CustomMenu.qml:341:2: Type RectangularGlow unavailable
qrc:/qt-project.org/imports/Qt5Compat/GraphicalEffects/RectangularGlow.qml:5:1: Cannot load library /usr/lib/qt6/qml/Qt5Compat/GraphicalEffects/private/libqtgraphicaleffectsprivateplugin.so: (libQt6ShaderTools.so.6: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden)
Could not load QML: qrc:/components/JASP/Widgets/MainWindow.qml
Load namespace: ragg
```

**Comment by kthun91** [comment] 2022-10-25 23:16
`Currently JASP does not launch.`
i tried to build it as singularity container via bioarch and got the same output as @tomtomme

**Comment by sukanka** [comment] 2022-10-26 01:32
> `Currently JASP does not launch.` i tried to build it as singularity container via bioarch and got the same output as @tomtomme

I can reproduce this, and can fix this by installing `qt6-shadertools`, 
```
pacman -S qt6-shadertools
```

We will fix all of these errors and update it to the latest version when `r-4.2.2` is available.

**Comment by tomtomme** [comment] 2022-10-26 06:36
Thx :) - can confirm this hotfix is working :D

**Comment by tomtomme** [comment] 2022-11-01 15:31
nice. The rebuild of 0.16.4 is here :)
But I cannot click anything within the analysis pane in the middle. Also the "arrow" buttons to quickly switch between results, analysis and data do not work. The 3 dots to move the panes work however.

**Comment by sukanka** [comment] 2022-11-01 16:18
> nice. The rebuild of 0.16.4 is here :) But I cannot click anything within the analysis pane in the middle. Also the "arrow" buttons to quickly switch between results, analysis and data do not work. The 3 dots to move the panes work however. This is with and wihout safe graphics. I am on wayland if this is relavant.

Confirmed. I have the same issue, the middle part (Descriptive statistics) is not clickable
![image](https://user-images.githubusercontent.com/31362108/199282510-70f0aa53-98ca-44bc-a76f-5ca49724bc7a.png)

Unfortunately, I do not know how to fix this, maybe it's related to Qt.

Below is a relevant log run in the terminal.
```
➜  ~ jasp
Desktop:        QML cache directory: /home/sukanka/.cache/JASP/JASP/qmlcache_
Making new argument list for Application startup: ./JASP
Starting JASP 0.16.4 from commit  and branch 
QtWebEngineQuick initialized
Application initialized
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name JASP 
  *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

Application init entered
MainWindow constructor started
TempFiles::createSessionDir(): '/home/sukanka/.JASP/temp/667188' about to be (removed and re)created.
Going to construct the necessary models for JASP to function.
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-de.qm
Desktop:        Language (German) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-fr.qm
Desktop:        Language (French) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-gl.qm
Desktop:        Language (Galician) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-id.qm
Desktop:        Language (Indonesian) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-pt.qm
Desktop:        Language (Portuguese) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-nl.qm
Desktop:        Language (Dutch) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-ja.qm
Desktop:        Language (Japanese) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-eo.qm
Desktop:        Invalid translation file found with name: jaspDesktop-eo.qm
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-zh_Hans.qm
Desktop:        Language (Chinese) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-es.qm
Desktop:        Language (Spanish) not registered in LanguageModel, adding it now
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-tr.qm
Desktop:        Invalid translation file found with name: jaspDesktop-tr.qm
Desktop:        Checking qm file: /usr/lib/jasp-desktop/Resources/Translations/jaspDesktop-zh_Hant.qm
Desktop:        Language (Chinese) not registered in LanguageModel, adding it now
Desktop:        DataSetPackage::reset()
Entering eventloop
QWebEngineCertificateError is neither a QObject, nor default- and copy-constructible. You should not use it as a QML type.
QWebEngineFullScreenRequest is neither a QObject, nor default- and copy-constructible. You should not use it as a QML type.
QWebEngineLoadingInfo is neither a QObject, nor default- and copy-constructible. You should not use it as a QML type.
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
Failed to compute left/right minimum bearings for "Courier"
Failed to compute left/right minimum bearings for "Courier"
Failed to compute left/right minimum bearings for "Courier"
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QSGPlainTexture: Mipmap settings changed without having image data available. Call setImage() again or enable m_retain_image. Falling back to previous mipmap filtering mode.
So the entire column had a change? yes
QSGPlainTexture: Mipmap settings changed without having image data available. Call setImage() again or enable m_retain_image. Falling back to previous mipmap filtering mode.
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
Loading required namespace: ragg
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
QT_QUICK_CONTROLS_TEXT_SELECTION_BEHAVIOR ""
```

**Comment by vandenman** [comment] 2022-11-02 14:08
@sukanka can you try cherry-picking https://github.com/jasp-stats/jasp-desktop/commit/f2956103f0f0898ad41fc39c625948791056f3b1 after checking out the 0.16.4 tag?

Jasp 0.16.4 was built with Qt 6.3.1 and since then there was an update in Qt 6.4.0 that caused exactly this issue. It has already been fixed in the linked commit. The danger of always being up to date I guess :sweat_smile:

**Comment by sukanka** [comment] 2022-11-02 15:19
> @sukanka can you try cherry-picking [jasp-stats/jasp-desktop@f295610](https://github.com/jasp-stats/jasp-desktop/commit/f2956103f0f0898ad41fc39c625948791056f3b1) after checking out the 0.16.4 tag?
> 
> Jasp 0.16.4 was built with Qt 6.3.1 and since then there was an update in Qt 6.4.0 that caused exactly this issue. It has already been fixed in the linked commit. The danger of always being up to date I guess sweat_smile

Thanks for your comment! This commit solves the issue. But I'm not familiar with `cherry-pick`, I don't know how to resolve conflicts between two commits. 

So I  simply use this diff ([v0.16.4..f2956103](https://github.com/jasp-stats/jasp-desktop/compare/v0.16.4..f2956103.diff)) as a patch. 
And the newly built binary runs fine on my machine.

**Comment by kthun91** [comment] 2022-11-02 15:44
Now the GUI seems to work in my bioarch based singularity container as well. 

Somehow that's the only way it works so far.

**Comment by tomtomme** [comment] 2022-11-22 09:13
I just tried 0.16-4-5
It works mostly, but while e.g. t-Tests and everything work fine for all ANOVA and linear mixed models I get this: 
![grafik](https://user-images.githubusercontent.com/4428185/203272893-7f643136-829d-473d-a955-816339d45873.png)

This might show again that stable / pinned versions of the modules could be a great feature for the bioarch repo :)

**Comment by sukanka** [comment] 2022-11-22 09:42
> I just tried 0.16-4-5 It works mostly, but while e.g. t-Tests and everything work fine for all ANOVA and linear mixed models I get this:

I'll look into it, would you please provided a detailed steps to reproduce？

> This might show again that stable / pinned versions of the modules could be a great feature for the bioarch repo :)

This requires the jasp Devs to make tags for the jasp modules. Since the modules are packaged separately, we need a way to check for updates.

**Comment by tomtomme** [comment] 2022-11-22 10:03
Steps to repoduce: Open JASP, open any dataset, click any ANOVA-module.
thanks sukanka

**Comment by sukanka** [comment] 2022-11-22 14:43
> Steps to repoduce: Open JASP, open any dataset, click any ANOVA-module. thanks sukanka

Confirmed and fixed (I manually pinned the commit used to build this package). 
This is caused by https://github.com/jasp-stats/jaspAnova/commit/f5198382ced8f1f7c24e685235e996803bedf768, as the version number changes, it is updated, but jasp requires 0.16.4. Unfortunately, this breaks anova function.
If we can use tags to check for updates, this would not happen. So **tags for the modules are needed.**

**Comment by tomtomme** [comment] 2022-11-22 15:02
I can confirm the fix is working :)

**Comment by tomtomme** [comment] 2023-01-14 09:58
With JASP from BioArch I now get

"unable to load shared object '/usr/lib/R/library/ragg/libs/ragg.so': libtiff.so.6: cannot open shared object file: No such file or directory"

when jasp tries to render any plot with any data file.
This is due to a recent upgrade of ragg, I suppose.

@sukanka: I do not expect another workaround, as we already established that the real fix is "tags for modules" - afaik.
Until tagging is enabled I will stop using / testing JASP from BioArch. As it stands now even the flatpak-beta channel breaks less often (while also being less frequently updated of course).

Maybe someone from the team can confirm that tagging is or is not on the roadmap - and if not, we can close this. The latter would be very sad of course, because sukanka put so much love into this and I would love to see a native Arch version of JASP. When it works, it works very well & even better in some regards than flatpak stable.

Cheers, tomtomme

**Comment by sukanka** [comment] 2023-01-14 10:29
> With JASP from BioArch I now get
> 
> "unable to load shared object '/usr/lib/R/library/ragg/libs/ragg.so': libtiff.so.6: cannot open shared object file: No such file or directory"
> 
> when jasp tries to render any plot with any data file. This is due to a recent upgrade of ragg, I suppose.
> 
> @sukanka: I do not expect another workaround, as we already established that the real fix is "tags for modules" - afaik. Until tagging is enabled I will stop using / testing JASP from BioArch. As it stands now even the flatpak-beta channel breaks less often (while also being less frequently updated of course).
> 
> Maybe someone from the team can confirm that tagging is or is not on the roadmap - and if not, we can close this. The latter would be very sad of course, because sukanka put so much love into this and I would love to see a native Arch version of JASP. When it works, it works very well & even better in some regards than flatpak stable.
> 
> Cheers, tomtomme

Hi, I'm not sure what's wrong with your installation, maybe a partial upgrade?

```
➜  ~ ldd /usr/lib/R/library/ragg/libs/ragg.so
        linux-vdso.so.1 (0x00007ffe5c399000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fd714dc1000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fd714d88000)
        libtiff.so.6 => /usr/lib/libtiff.so.6 (0x00007fd714cf1000)
```
and ` /usr/lib/libtiff.so.6` is owned by `libtiff`, which is required by many other packages.

Oh, I get what your issue actually is.

The reason is that you use Manjaro, which provides only `libtiff 4.4.0` (`provides /usr/lib/libtiff.so.5`)  but in archlinux repo, it's `libtiff 4.5.0` (provides `/usr/lib/libtiff.so.6`). See https://archlinux.org/packages/extra/x86_64/libtiff/ for more details
There is a so name bump. When there is a so name bump, your installation may break again.

Since you are a manjaro user, I now recommend you use flatpak version (we do not have a native version for manjaro)

Cheers, sukanka

**Comment by shun2wang** [comment] 2023-10-10 06:32
Given that our BioArchLinux partners have currently maintained a stable JASP build on ArchLinux for quite long time, I'm closing it for now.  please create a new one if have other problems.

**Closed by shun2wang** 2023-10-10 06:32 UTC
Labels: Feature Request
