### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tlecerf1205** [jasp-stats/jasp-issues#1738] opened 2022-06-04 16:32 UTC
### JASP Version

0.16.2

### JASP Module

jaspReliability

### What analysis are you seeing the problem on?

unidimensional reliability

### What OS are you seeing the problem on?

MacOS Monterey

### Bug Description

<img width="1066" alt="Capture d’écran 2022-06-04 à 18 26 47" src="https://user-images.githubusercontent.com/106429848/172016283-0af6d230-f673-4bbc-9b6b-b20e76cb150c.png">

### Expected Behaviour

analysis terminated unexpectedly 

### Steps to Reproduce

bug reproduced by trying several time

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2022-06-07 14:40
Could you try our last beta version: https://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-stable-e829d5bc8c31cb8154ada3a33bd14e22409846ae.dmg ?

**Comment by juliuspf** [comment] 2022-06-20 09:36
this is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1694

**Closed by juliuspf** 2022-06-20 09:36 UTC
