### ISSUE TITLE
[Feature Request]: Multidimensional Scaling Analysis (MDS)

### ISSUE THREAD

**Issue by LSLindeloo** [jasp-stats/jasp-issues#1870] opened 2022-10-24 13:01 UTC
### Description

add MDS to the factor module

### Additional context

request via email

**Comment by TarandeepKang** [comment] 2023-08-17 09:27
Hi team, just wanted to make a request for this feature, when I saw somebody else has already requested it.

This package is particularly useful and contains a very comprehensive set of features:

Leeuw, J. de, & Mair, P. (2009). Multidimensional Scaling Using Majorization: SMACOF in R. Journal of Statistical Software, 31, 1–30. https://doi.org/10.18637/jss.v031.i03
Mair, P., Groenen, P. J. F., & Leeuw, J. de. (2022). More on Multidimensional Scaling and Unfolding in R: Smacof Version 2. Journal of Statistical Software, 102, 1–47. https://doi.org/10.18637/jss.v102.i10

**Comment by tomtomme** [comment] 2024-01-31 11:30
closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/217

**Closed by tomtomme** 2024-01-31 11:30 UTC
Labels: Module: jaspFactor, Feature Request
