### ISSUE TITLE
[Feature Request]: Jasp version 0.17.1 Cannot perform tests because there are only two levels of the RM factor. What can I do to fix this?

### ISSUE THREAD

**Issue by Mattiwinks** [jasp-stats/jasp-issues#2060] opened 2023-03-17 18:03 UTC
### Additional context

![image](https://user-images.githubusercontent.com/128178314/225983393-6f7b7eb1-34f6-4f03-8161-836ee2273a39.png)
![image](https://user-images.githubusercontent.com/128178314/225983457-a74c75bf-1ed2-4fb7-975c-d76e0efad6ae.png)
![image](https://user-images.githubusercontent.com/128178314/225983485-901658da-6c0b-4563-9fe3-d6d0fd9e45d4.png)

**Comment by SA-YEM** [comment] 2023-07-29 14:55
Hi team,

May I please ask if this error has been fixed?

I am currently getting the same error when using repeated measure anova. 
I have two conditions (Pre and Post), and the between subjects, I have 1 variable with 3 groups. 
 

I am using JASP 0.17.1

Appreciate your support!

Thank you,
Sameha

**Comment by SA-YEM** [comment] 2023-07-30 10:10
Hi team,

is this error because of using only two conditions in the within-subject, and hence sphericity test is not required?
however, if only homogeneity test to perform in this case and sphericity is not required, what corrections can be done when homogeneity test is failed in mixed ANOVA?

Regards,
SA

**Comment by EJWagenmakers** [comment] 2023-07-30 13:04
Hello SA,

I am assigning this to Johnny, but because of the holidays it may take some time to respond...

EJ

**Comment by SA-YEM** [comment] 2023-07-31 07:32
Hi EJ,

Noted, Thank you!

SA

**Comment by JohnnyDoorn** [comment] 2023-07-31 11:59
Hi @SA-YEM ,

You cannot test sphericity for only 2 levels of a RM factor, because it analyzes correlations of difference scores (which you will only have 1 column of, with 2 levels). We also do not provide sphericity corrections for only 2 levels. So this is not a bug in JASP but a feature of the test. Please reopen if you have additional questions.

Kind regards
Johnny

**Closed by JohnnyDoorn** 2023-07-31 11:59 UTC
Labels: Feature Request
