### ISSUE TITLE
[Feature Request]: enhanced the split of boxplots

### ISSUE THREAD

**Issue by lt2002** [jasp-stats/jasp-issues#1850] opened 2022-10-07 01:53 UTC
### Description

we could not add two groups in the split of boxplots,it is hard to draw the complicated boxplots

### Purpose

sometimes we need to analysis different groups in boxplots

### Is your feature request related to a problem?

we just  can choose one group in the  split

### Describe the solution you would like

we can add two groups in the split of boxplots

### Describe alternatives that you have considered

we can add two groups in the split of boxplots

### Additional context

i wish the function of split  just like "jamovi".
![image](https://user-images.githubusercontent.com/87117281/194449760-2a62f0a0-c19e-4fb1-88b6-2a15ee887041.png)

**Comment by tomtomme** [comment] 2024-02-03 11:24
Since this is a duplicate of the more general issue here: https://github.com/jasp-stats/jasp-issues/issues/2492
I am closing this one. Lets discuss there :)

**Closed by tomtomme** 2024-02-03 11:24 UTC
Labels: Graphs/Plots, Module: jaspDescriptives, Feature Request
