### ISSUE TITLE
[Bug]: Raincloud plots (Paired-Samples t-test) - lines do not correctly match up cases.

### ISSUE THREAD

**Issue by JayD05** [jasp-stats/jasp-issues#2101] opened 2023-04-18 09:58 UTC
### JASP Version

0.16.4

### JASP Module

T-Tests

### What analysis are you seeing the problem on?

Paired-Samples t-test

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I just noticed that Paired-Samples t-test (including Wilcoxon) Raincloud plots do not correctly match up cases across conditions. Examples given below:

Example 1

![Raincloud plot 1](https://user-images.githubusercontent.com/120119018/232737830-fad0d428-8f31-4bdc-adad-86397291b507.png)

For 'ORB_Recog' score 6, the corresponding score should be 10 (rather than 9). 

For 'CYL_Recog' score 6, the corresponding score should be 10 (rather than 7).

Image of data for Example 1 below:

![RC 1 data](https://user-images.githubusercontent.com/120119018/232738907-06b0d6f1-ab5e-4f28-9710-4254274cee35.PNG)

Example 2

![Raincloud plot 2](https://user-images.githubusercontent.com/120119018/232739641-1a4d13ce-cac5-4d3e-8aaf-982a3e83b6cd.png)

For 'ORB_App' scores of 1, there should only be one corresponding case which scores 2 in 'CYL_App' (not two cases). 

Image of data for Example 2 below (See row 6 for correct corresponding case - no other case follows this pattern):

![RC 2 data](https://user-images.githubusercontent.com/120119018/232740259-2b617309-9203-4b7c-8021-eab3e98be602.PNG)

Datafile below:

[JASP file.zip](https://github.com/jasp-stats/jasp-issues/files/11260451/JASP.file.zip)

### Expected Behaviour

Raincloud plot should correctly match up cases across conditions.

### Steps to Reproduce

1. Run Paired-Samples t-test
2. Select Raincloud Plot

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment] 2024-02-07 20:13
@JayD05 
looks all good in jasp 0.18.3 - pls reopen if not fixed on your side

**Comment by JayD05** [comment] 2024-02-08 13:31
Hi @tomtomme,

I've just tried this again in JASP 0.18.3 using the same data zip file and I'm getting the exact same results, unfortunately (new graphs below):

![image](https://github.com/jasp-stats/jasp-issues/assets/120119018/7871e6e5-aae3-48b5-bf41-3385ce41424a)

![image](https://github.com/jasp-stats/jasp-issues/assets/120119018/6ab9f806-e076-4abf-ba38-cb2eb62ffc69)

Not sure how to reopen this issue, but can create a new one if needed? 

Thanks,

Jay

**Comment by tomtomme** [comment] 2024-02-08 13:50
@JayD05 & @vandenman 
I can confirm now!
Sorry for not looking closely enough - my eyes were fixed on the malformed density lines, whicht appear fixed. But yes, the scores do not line up. This is apparently due to the missing value. For the Raincloud plot it seems, that all scores in the var CYL_App are shifted upwards because of the missing in line 2.
This is a really nasty bug! Lets try with "critical" to get this fixed!

**Comment by JayD05** [comment] 2024-02-08 14:02
Great, thanks @tomtomme!

**Comment by JohnnyDoorn** [comment] 2024-05-07 11:56
@JayD05 The paired raincloud plots were not handling missingness correctly (per variable, rather than listwise) - great spotting! I fixed the issue, so the next JASP release (0.19, this month) will include the correct plots.

**Closed** 2024-05-07 12:07 UTC
Labels: Component: Result Plots, Module: jaspTTests, Bug: Critical
