### ISSUE TITLE
Dealing with multiple response variables...

### ISSUE THREAD

**Issue by HoracioSD** [jasp-stats/jasp-issues#523] opened 2019-10-17 15:25 UTC
Hi, I´m an SPSS user but exploring alternatives to it. I would like to know if Jasp can deal with multiple response variables (used in surveys, in questions with many optional answers, with chekboxes).
Can Jasp run frequencies managing this kind of variables?
 
Thanks in advance!

**Comment by HoracioSD** [comment] 2019-10-21 11:51
The data includes a bunch of dichotomic variables (yes/no response). Imagine for example the following survey question: 
What brand of car do you prefer? (choose all that correspond)
Ford
Hyundai
Toyota
Fiat
Chevrolet
BYD

In the data set, each brand of cars is a dichotomic variable (the repondent can choose it or not = yes or no response). But then, we are interested in analize grouped these answers, for example to run  frequencies of each brand, with a total of 100%.

Hope this can help. Thanks again

**Comment by TimKDJ** [comment] 2019-10-21 12:00
Well, you could drag each of these variables into Descriptive Statistics and then tick "Frequency tables" -- you'll get a table for each car brand containing the frequency with which either option is chosen. 

If this does not do what you want, I'm going to need a little more information :)

**Comment by HoracioSD** [comment] 2019-10-21 23:40
Here you can see a more detailed examples using SPSS:
https://youtu.be/JhzaF-TvbW4
https://youtu.be/Juv5GPcP1Kk

Thanks!

_______________________________________

Horacio Saravia Díaz
Unidad de Comunicación y Transferencia de Tecnología
Tel:        ++598 44522023 Int. 1235
Móvil:    ++598 91312010
E-mail:  hsaravia@inia.org.uy<mailto:hsaravia@inia.org.uy>
Web:    www.inia.uy<http://www.inia.uy/>

[image002]

De: Tim de Jong <notifications@github.com>
Enviado el: lunes, 21 de octubre de 2019 09:00 a.m.
Para: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
CC: Horacio Saravia <hsaravia@inia.org.uy>; Author <author@noreply.github.com>
Asunto: Re: [jasp-stats/jasp-issues] Dealing with multiple response variables... (#523)


Well, you could drag each of these variables into Descriptive Statistics and then tick "Frequency tables" -- you'll get a table for each car brand containing the frequency with which either option is chosen.

If this does not do what you want, I'm going to need a little more information :)

**Comment by AlexanderLyNL** [comment] 2019-10-23 11:26
Hi HoracioSD, 

JASP is able to read sav files. Could you please install JASP and check if it does what you'd like it to do. If not, please report it, and we then we have a concrete case to work with. 

Cheers,
Alexander

**Comment by HoracioSD** [comment] 2019-11-01 15:51
[Hi Alexander.docx](https://github.com/jasp-stats/jasp-issues/files/3798570/Hi.Alexander.docx)
Hi Alexander. I´ve tried but y think JASP isn´t able to do what I need. Please, I´ve attached an example I would like you can look at this.
TIA

**Comment by akmurrayku** [comment] 2020-10-11 16:20
Multiple response variables are those that come for example from a survey where people can check more than one brand of toothpaste that they have heard of. In the data each brand of toothpaste is treated as a separate dichotomous variable with a 1 if checked and a 0 or missing if not checked. While it is possible to do the analysis with a series of separate frequency tables, SPSS has a great feature that allows you to create a variable set so that you can create one table with all toothpaste brands combined and allows you to do crosstabs. I would love to have my students use JASP instead of SPSS, but this is an important limitation. Here's an example of the multiple response frequency table. 
![image](https://user-images.githubusercontent.com/72702092/95683879-7aaad680-0bb3-11eb-9546-75f7665bdaf9.png)

**Comment by HoracioSD** [comment] 2020-10-12 12:18
Thanks a lot @akmurrayku for your explanation (better than mine!).
Hope Jasp can add this feature soon.

**Comment by HoracioSD** [comment] 2021-03-19 16:58
Hi Murray, any news about this topic?

_______________________________________

Horacio Saravia Díaz
Unidad de Comunicación y Transferencia de Tecnología
Tel:        ++598 44522023 Int. 5235
Móvil:    ++598 91312010
E-mail:  ***@***.******@***.***>
Web:    www.inia.uy<http://www.inia.uy/>

[image002]

De: akmurrayku ***@***.***>
Enviado el: domingo, 11 de octubre de 2020 01:21 p.m.
Para: jasp-stats/jasp-issues ***@***.***>
CC: Horacio Saravia ***@***.***>; Author ***@***.***>
Asunto: Re: [jasp-stats/jasp-issues] Dealing with multiple response variables... (#523)


Multiple response variables are those that come for example from a survey where people can check more than one brand of toothpaste that they have heard of. In the data each brand of toothpaste is treated as a separate dichotomous variable with a 1 if checked and a 0 or missing if not checked. While it is possible to do the analysis with a series of separate frequency tables, SPSS has a great feature that allows you to create a variable set so that you can create one table with all toothpaste brands combined and allows you to do crosstabs. I would love to have my students use JASP instead of SPSS, but this is an important limitation. Here's an example of the multiple response frequency table.
[image]<https://user-images.githubusercontent.com/72702092/95683879-7aaad680-0bb3-11eb-9546-75f7665bdaf9.png>

**Comment by akmurrayku** [comment] 2021-03-25 02:49
Yes! There is now a module that can do this and it works beautifully! It's called "UFS - Tools for confidence intervals and other tricks." It has a Multi Response function.
 
![image](https://user-images.githubusercontent.com/72702092/112411251-98e03b00-8cea-11eb-962c-ea11a5da2cf0.png)

**Comment by HoracioSD** [comment] 2021-03-25 10:48
Thanks a lot! I will take a look.


_______________________________________

Horacio Saravia Díaz
Unidad de Comunicación y Transferencia de Tecnología
Tel:        ++598 44522023 Int. 5235
Móvil:    ++598 91312010
E-mail:  ***@***.******@***.***>
Web:    www.inia.uy<http://www.inia.uy/>

[image002]

De: akmurrayku ***@***.***>
Enviado el: miércoles, 24 de marzo de 2021 11:50 p.m.
Para: jasp-stats/jasp-issues ***@***.***>
CC: Horacio Saravia ***@***.***>; Author ***@***.***>
Asunto: Re: [jasp-stats/jasp-issues] Dealing with multiple response variables... (#523)


Yes! There is now a module that can do this and it works beautifully! It's called "UFS - Tools for confidence intervals and other tricks." It has a Multi Response function.

[image]<https://user-images.githubusercontent.com/72702092/112411251-98e03b00-8cea-11eb-962c-ea11a5da2cf0.png>

**Comment by HoracioSD** [comment] 2021-03-25 11:28
Murray, I´ve downloaded the latest version of Jasp and I dón’t know where to find the UFS -tools package you mention.


After that, I´ve tried to download the package from https://www.jamovi.org/library.html
But I have no idea how to use it with Jasp.
May I open or add this package to Jasp?

Sorry for my ignorance about that

_______________________________________

Horacio Saravia Díaz
Unidad de Comunicación y Transferencia de Tecnología
Tel:        ++598 44522023 Int. 5235
Móvil:    ++598 91312010
E-mail:  ***@***.******@***.***>
Web:    www.inia.uy<http://www.inia.uy/>

[image002]

De: akmurrayku ***@***.***>
Enviado el: miércoles, 24 de marzo de 2021 11:50 p.m.
Para: jasp-stats/jasp-issues ***@***.***>
CC: Horacio Saravia ***@***.***>; Author ***@***.***>
Asunto: Re: [jasp-stats/jasp-issues] Dealing with multiple response variables... (#523)


Yes! There is now a module that can do this and it works beautifully! It's called "UFS - Tools for confidence intervals and other tricks." It has a Multi Response function.

[image]<https://user-images.githubusercontent.com/72702092/112411251-98e03b00-8cea-11eb-962c-ea11a5da2cf0.png>

**Comment by EJWagenmakers** [comment] 2021-03-25 11:50
Yes, this is a different software program (they look very similar). We will look in to how we can make such content available within JASP.

**Comment by HoracioSD** [comment] 2021-03-25 12:10
Ah! Ok, Jamovi is other statistical software? If so, don´t worry! I will try it.
I´m not an user of Jasp, I´m only looking for a SPSS free alternative. I´ve tried PSPP but it have the same limitation with multiple response variables.

Thanks a lot!

_______________________________________

Horacio Saravia Díaz
Unidad de Comunicación y Transferencia de Tecnología
Tel:        ++598 44522023 Int. 5235
Móvil:    ++598 91312010
E-mail:  ***@***.******@***.***>
Web:    www.inia.uy<http://www.inia.uy/>

[image002]

De: EJ ***@***.***>
Enviado el: jueves, 25 de marzo de 2021 08:51 a.m.
Para: jasp-stats/jasp-issues ***@***.***>
CC: Horacio Saravia ***@***.***>; Mention ***@***.***>
Asunto: Re: [jasp-stats/jasp-issues] Dealing with multiple response variables... (#523)


Yes, this is a different software program (they look very similar). We will look in to how we can make such content available within JASP.

**Comment by akmurrayku** [comment] 2021-03-25 16:02
Oh my mistake! The names are similar (at least they both start with J!) and I posted similar questions in forums for both software systems. Yes, I have used JAMOVI with my class this semester and it's worked well. I'm sure JASP is a good option as well. We just have several faculty members trying various free alternatives to SPSS to evaluate them.

**Comment by tomtomme** [comment] 2024-01-01 19:13
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/50
and can be closed.

**Closed** 2024-01-03 13:03 UTC
Labels: Module: jaspDescriptives, Feature Request
