### ISSUE TITLE
[Bug]: Flexplot, undefined columns selected

### ISSUE THREAD

**Issue by xhzair** [jasp-stats/jasp-issues#2188] opened 2023-06-12 15:53 UTC
### JASP Version

0.17.2.1

### JASP Module

Visual Modeling

### What analysis are you seeing the problem on?

Flexplot

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/55773327/96e34817-eddd-4b42-8632-4c8ade2e5a0b)

### Expected Behaviour

The .csv file was generated by using function _write.table_ in R. However, no matter how to set the col names, the Flexplot could not plot as expected.

### Steps to Reproduce

1. Generate the .csv file by using function _write.table_ in R.
2. Open the .csv file by JASP.
3. Drag the dependent and independent variable into the box and then the warning appear.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment] 2023-06-19 08:40
@dustinfife Can you have allot at this issue?

**Comment by dustinfife** [comment] 2023-06-27 02:10
I'm guessing it has to do with the spaces in the variable names. Maybe you can try without spacing and see if that fixes the issue? If it does, I can look into making flexplot not quit when it sees spaces in variable names.

**Comment by tomtomme** [comment] 2024-02-07 10:33
@xhzair 
Can you re-test with jasp 0.18.3? Flexplot got some updates. If this does not fix it - can you share your jasp file? Rename it to .zip first, then drag and drop here. thx!

**Comment by xhzair** [comment] 2024-02-07 13:55
> @xhzair Can you re-test with jasp 0.18.3? Flexplot got some updates. If this does not fix it - can you share your jasp file? Rename it to .zip first, then drag and drop here. thx!

Thanks for your reply! I tried again with the latest version 0.18.3 and found something confused. 
In the .zip attachment, the examplar data include 10 rows and several cols. After launching the .jasp file and opening Flexplot function, the bug appeared just as I added the dependent variable (e.g., _Confidence_). You can see the bug as shown below.
However, I found some changes seemed to help fix the bug. But I really do not know why they work. Maybe you can figure out. 
1. Delete other cols and only keep the IV (e.g., _ObjecitivePhi_) and DV (e.g., _Confidence_) alive. 
2. Change all other cols' names. For example, I named other cols as V1, V2, V3, etc. 
Both work no matter I edit through EXCEL or in JASP directly. The .jasp file is attached below. Again, thanks for your help! 
![image](https://github.com/jasp-stats/jasp-issues/assets/55773327/00af6466-2f57-451b-987d-6a8a32f2ec1c)
[example data.zip](https://github.com/jasp-stats/jasp-issues/files/14194610/example.data.zip)

**Comment by tomtomme** [comment] 2024-02-26 09:36
@xhzair @dustinfife 
I just tested this with a completely different file that includes many constants and that works fine! 
I then tried to change the short var names A B C etc. to longer names and that works!!!

So flexplot actually does not like var names that are only one character long. We had this problem with other module (RM anova) in the past. So I hope this is fixable for flexplot too?

**Comment by tomtomme** [comment] 2024-06-20 08:30
@dustinfife 
still valid for latest 0.19beta

here is the file to reproduce 
[example.data.zip](https://github.com/user-attachments/files/15911114/example.data.zip)

Delete the Vars with names of only one character and the error disappears.


-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: HEAD
Build Date: Jun 18 2024 13:07:48 (Netherlands)
Last Commit: a6131f3f59ec89e1804870d99b73e0e63803d8d9

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.7
Kernel Type: linux
Kernel Version: 6.9.3-3-MANJARO
Architecture: x86_64
Install Path: /app/bin
Platfotm Name: wayland
System Local: de_DE

**Comment by boutinb** [comment] 2024-10-18 09:37
@dustinfife We are going to release a new version (0.19.2). Do you have time to have a look at this issue?

**Comment by tomtomme** [comment] 2024-10-23 13:21
yep, still there with 0.19.2 beta flatpak

**Comment by dustinfife** [comment] 2024-10-24 00:54
I'll look into it.

**Comment by dustinfife** [comment] 2024-10-24 02:18
I believe I have fixed the issue with [this commit](https://github.com/dustinfife/flexplot/commit/23731df64bc442710653b53811f0e5fc8dc84a02). Am I correct in understanding that the encodeNames function has essentially been deprecated?

**Comment by boutinb** [comment] 2024-10-24 15:30
> Am I correct in understanding that the encodeNames function has essentially been deprecated?

Yes you should not need use it.

**Comment by boutinb** [comment] 2024-11-06 10:56
Hi @dustinfife I have tried again with example.data file given by Thomas, and I still get an error with an another message:
![Screenshot 2024-11-06 at 11 54 44](https://github.com/user-attachments/assets/38d0e28d-4e8a-42db-82e3-b1c473a8df09)

**Comment by dustinfife** [comment] 2024-11-07 03:11
That's not happening on my end. Is there some sort of a cache you need to clear?
<img width="1848" alt="03 - Images 2024-11-06 at 10 10 40 PM" src="https://github.com/user-attachments/assets/8863e32b-6242-4bf5-b892-f5b94d29c987">

**Comment by tomtomme** [comment] 2024-11-07 13:19
with current flatpak 0.19.2 beta (configs cleared) I cannot open my old file: 

PopUp:
Unable to open file because:
Archive missing version information.

from terminal
Error in loadNamespace(x) : there is no package called ‘jaspBase’

![grafik](https://github.com/user-attachments/assets/0e410ea3-ebd2-47a1-a65c-ec1fc922b27b)

opening smth from data-lib filters out all data and gives flexplot error:

![grafik](https://github.com/user-attachments/assets/14a1b8d2-0e8e-4f9e-a7df-b9d26df5283b)

Error evaluating: jaspBase::runJaspResults(name=name, title=title, dataKey=dataKey, options=options, stateKey=stateKey, functionCall=moduleCall, preloadData=preloadData)

-------- Application Info --------
JASP Version: JASP 0.19.2
Build Branch: HEAD
Build Date: Nov  6 2024 07:23:44 (Netherlands)
Last Commit: afa1ecd99de9e210c366d43b321731abb479dcf0

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.7
Kernel Type: linux
Kernel Version: 6.6.54-2-MANJARO
Architecture: x86_64
Install Path: /app/bin
Platfotm Name: wayland
System Local: de_DE

**Comment by boutinb** [comment] 2024-11-08 16:25
With the last Nightly Mac version, it works. Thanks!
The jaspBase problem is something else. I have seen that for Mixed models also sometimes...
I think we can close this issue.

**Closed by boutinb** 2024-11-08 16:25 UTC
Labels: Module: jaspVisualModeling, Bug: High
