### ISSUE TITLE
Following up interaction effects using 'simple main effects' in Bayesian ANOVAs

### ISSUE THREAD

**Issue by nahorp** [jasp-stats/jasp-issues#670] opened 2020-04-12 09:59 UTC
Hello :)

I have outlined the request (an 'issue' at the time of posting it at the forum but I've since been told that it is not possible in the current version of JASP) at the link below,

https://forum.cogsci.nl/discussion/5963/following-up-an-interaction-in-bayesian-rm-anova#latest

It is similar to this actioned request, which was for a frequentist ANOVA, but for Bayesian ANOVAs as well.

Thank you

**Comment by JohnnyDoorn** [comment] 2020-04-13 09:18
Hi rohanp16,

The simple main effects analysis is essentially running ANOVA's for different subset of the data (conditioning on each level of the "moderator variable"). In the frequentist ANOVA this is automated for you, but unfortunately this feature is still missing in the Bayesian ANOVA. 

What you can do in the meantime, is to manually subset the data yourself with the column filtering option (see the gif illustration here: https://jasp-stats.org/wp-content/uploads/2018/06/01_click_filter.gif)

You can repeat this for each level of the moderator variable. This is a crude method though, as it will not take into account the full ANOVA (which is what the simple main effects analysis does), but it can already give you an indication for which level of the moderator variable there is a difference between the levels of the variable of interest.

I hope this clarifies the issue a bit, I will discuss with the relevant team member about possible implementation of Bayesian simple main effects. 

Kind regards,
Johnny

**Comment by nahorp** [comment] 2020-04-13 09:40
Hi Johnny,

Thank you for the prompt and detailed reply. Couple of questions/thoughts,

1) The column filtering approach would, firstly, only work for a between-subject factor, correct? Secondly, if I do apply the column filtering, then the filtering applies to _all_ the analyses in that .jasp file, right? That is, I will have to create a new .jasp file for these subsetted analyses as there is no way to apply filtering to specific analyses in .jasp file or is there a way for me to apply filtering to specific analyses?

2) If I was running a 3 way ANOVA (say, A * B * C) and wanted to follow up a 2 way interaction (say, A * B), I would have to manually average across the levels of the third factor (C in this instance). Though not overly cumbersome, this involves more data wrangling and the opportunity for errors.

I am aware of the method you describe (i.e., running separate ANOVAs) but was being slightly lazy and hoping it could all be there nicely in one .jasp analysis :) Thank you for taking the time to discuss it with a relevant team member, appreciate it.

**Comment by JohnnyDoorn** [comment] 2020-04-13 13:39
Hi Nahorp,

1. I think that for RM ANOVA, you can then just specify the cells accordingly (i..e, only include the 2 RM levels that you want to compare), but again, this is a crude measure. You are right in that it is a lot of extra work since the filtering is applied to all analyses in the JASP instance.
2. For simple main effects to follow up on a three-way interaction, I think the procedure would be to subset on two variables, instead of just the one (when following up on a two-way interaction). But again, this is a lot of work, having to make multiple different jasp files so this approach is far from ideal. 

Kind regards,
Johnny

**Comment by tomtomme** [comment] 2024-02-09 18:18
Closing as duplicate of https://github.com/jasp-stats/jasp-issues/issues/588

**Closed by tomtomme** 2024-02-09 18:18 UTC
Labels: Module: jaspAnova, Feature Request
