### ISSUE TITLE
[Bug]: Duplicate of CFA gives different results

### ISSUE THREAD

**Issue by Boert98** [jasp-stats/jasp-issues#2007] opened 2023-02-10 09:01 UTC
### JASP Version

0.16.4

### JASP Module

Factor

### What analysis are you seeing the problem on?

CFA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

I duplicated a CFA and got completely different results without changing the settings

### Expected Behaviour

Getting the same results

### Steps to Reproduce

1.CFA
2.Duplicate CFA
3.
<img width="446" alt="Bildschirmfoto 2023-02-10 um 09 53 22" src="https://user-images.githubusercontent.com/125014619/218048395-6c78154a-ba87-4153-9952-3201465fd8f2.png">

[](url)
<img width="463" alt="Bildschirmfoto 2023-02-10 um 09 53 40" src="https://user-images.githubusercontent.com/125014619/218048476-436d9e22-aaa7-4e8b-a2e5-3e560afb5aab.png">

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment] 2023-02-10 09:21
@Boert98, thanks for creating the issue. Is there any chance you could share a zipped .jasp file with us? Or the data file and describe the steps you took?

**Comment by Boert98** [comment] 2023-02-10 10:26
Unfortunately it is too big and the results change (to the same results as copy of in attached screenshot above) if you want to recreate it within a new jasp file

**Comment by juliuspfadt** [comment] 2023-02-10 12:41
Hmm, that is difficult. With any regular data set I am unable to recreate your issue. Have you tried this with a smaller subset of your data? Or any other data set?

**Comment by Boert98** [comment] 2023-02-10 13:28
The issue is if I recreate it now, it always shows the "worse" data. I have written everything already and can't reproduce the initial model with the data set.

**Comment by juliuspfadt** [comment] 2023-02-10 13:30
so the issue disappeared?

**Comment by Boert98** [comment] 2023-02-10 14:25
No. I don't know what JASP changed but I don't get the initial results anymore. It calculated it newly but I don't know why the results have been different the first time I have done it without changing anything.

**Comment by Boert98** [comment] 2023-02-10 14:33
<img width="713" alt="Bildschirmfoto 2023-02-10 um 15 33 33" src="https://user-images.githubusercontent.com/125014619/218117638-8ebffe6a-55a2-43c9-9ad2-427b60fe2fb5.png">
I also got this error. Could you assist what that means?

**Comment by juliuspfadt** [comment] 2023-02-12 16:49
So all I can extract from this error message is that while computing a fit measure the program could not invert a matrix from the fitted output object. But without the data I cannot really trace back the problem, I am afraid.

**Comment by juliuspfadt** [comment] 2023-02-12 16:50
It is definitely an error that we should have caught and then displayed a more informative error message.

**Comment by juliuspfadt** [comment] 2023-02-16 08:08
Well since this is not reproducible and you have opened another issue for your second bug, I will close this.

**Closed by juliuspfadt** 2023-02-16 08:08 UTC
Labels: Module: jaspFactor, OS: macOS Silicon, Bug

**Comment by Boert98** [comment] 2023-02-16 08:14
Yes, thank you! I was only able to reproduce the second result all the time and fixed my data based on those results. Thanks!
