### ISSUE TITLE
Jasp crashes system on Linux Mint 20 (ulyana)

### ISSUE THREAD

**Issue by famuvie** [jasp-stats/jasp-issues#917] opened 2020-07-30 12:54 UTC
* JASP version: 0.13.1.0

* OS name and version: Linux Mint 20 (ulyana) (based on Ubuntu 20.04 (focal fossa))
* Analysis: The first 3 or 4 times this happened, the app closed abruptly but the system continued to work. On one occasion I managed to capture JASP freezing (but the system working)
![jasp_freezes](https://user-images.githubusercontent.com/5693966/88924972-3d050580-d274-11ea-97ed-faf8e971cde6.gif). From then on, the system completely freezes.

* Bug description: The system freezes after a few moments of working with the graphical interface, at random points, but systematically. 
* Expected behaviour: No crash.

#### Steps to reproduce:
1. Open some CSV (from local dir or data library), 
2. Click on "Descriptives" 
3. Drag the left pane to see the data table. 
4. The system crashes. Everything freezes and I have to shut the computer down.

**Comment by famuvie** [comment] 2020-07-30 12:56
For the record, in another computer with Ubuntu 18.04 (bionic) I don't have this problem.

**Comment by JorisGoosen** [comment] 2021-01-18 12:48
Hey @famuvie 

My apologies for the extremely slow response to your wellcrafted issue.
For the 0.14(.1) release I solved a few problems related to crashing on ubuntu 20.04 as opposed to 18.04 not crashing.

I sincerely hope that your issue was also fixed by this.
If you are not too disappointed in our/my slow response and want to test it out (or you are maybe already using it?) and see if the problem is solved then great!

If JASP still crashes you can reopen this issue because then I will make sure to look into it deeper.

**Closed by JorisGoosen** 2021-01-18 12:48 UTC

**Comment by famuvie** [comment] 2021-01-30 14:25
Hey @JorisGoosen 
Thanks for your response and for working in the issue! 
**I confirm the problem was solved.**
I checked with JASP v0.14.2 in the same system as before (although with the regular kernel and package updates since then).
Thanks again!

**Comment by JorisGoosen** [comment] 2021-01-31 13:08
Great!
