### ISSUE TITLE
Graphic depiction/output for classification and regression trees

### ISSUE THREAD

**Issue by App-State-Prof** [jasp-stats/jasp-issues#1090] opened 2020-12-04 17:34 UTC
I may have asked about this earlier...is it possible to add a graphical output for decision trees? So useful for student learning and reporting. There is an add-on in R Studio called "radiant" that produces the trees:

![Tree for relationships](https://user-images.githubusercontent.com/33431829/101195257-28bf8380-362d-11eb-9ea9-dbc46fcc2ecf.PNG)

Can we have something similar in JASP?

Thank you!

**Comment by koenderks** [comment] 2020-12-07 12:27
Thank you, this is indeed a duplicate of https://github.com/jasp-stats/jasp-issues/issues/564. We would very much like to implement this feature, but this will take a considerable amount of time and we have not (yet) planned a large update for the machine learning module. We will keep you posted in the issue linked above about the status of this feature, and I will close this issue for now.

**Closed by koenderks** 2020-12-07 12:27 UTC
