### ISSUE TITLE
Better scaling of plots, based on specified values

### ISSUE THREAD

**Issue by bmatyasb** [jasp-stats/jasp-issues#2534] opened 2024-01-17 20:53 UTC
### Description

It would be nice if, when editing plots, the size of the plots could be defined by two specific numbers, width and height, and not just by using the mouse.

### Purpose

If you make several plots of the same type,  and you want to resize them, it is very difficult to make them the same size with the cursor. But not only if you want to make several of the same type, in practically all cases it would be more reasonable to specify numerically what size plot you want to make. Scaling with a cursor is very time consuming, annoying.  Under the "edit plot" option, specifying the width and length numerically would help quite a bit.

### Use-case

Whenever we make a plot.

**Comment by tomtomme** [comment] 2024-01-19 18:43
@bmatyasb 
Thank you for the request. I second it. However I will also clos this issue, since its a duplicate of https://github.com/jasp-stats/jasp-issues/issues/1674

So lets track it there and see how many supporters it gets :D

**Closed by tomtomme** 2024-01-19 18:43 UTC
Labels: Feature Request
