### ISSUE TITLE
[Feature Request]:  Export data of tables and plots

### ISSUE THREAD

**Issue by dekuenstle** [jasp-stats/jasp-issues#2231] opened 2023-07-17 11:44 UTC
### Description

 Export data of tables and plots

### Use-case

continue analysis or plotting in another tool. 

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

 In the interface, any result screen, every table and plot could provide a "Save CSV" function (next to "copy Latex" or "copy PDF").  

### Additional context

 
 Tables and plots can be easily copied to a manuscript as text, Latex, images or PDF.
 Sometimes it would be great to use the results of JAGS analysis (not just the filtered data) 
 and continue analysis or plotting in another tool. 
 This is especially useful to create coherent plots despite using other analysis software next to JAGS.

**Comment by boutinb** [comment] 2023-07-17 12:34
We will further develop the R Syntax feature, so that you can run the same analysis directly in R Studio. You will be able then to use directly the results (tables & plots) as R objects. The plots are in fact already R objects used in JASP, they are available in the temporary files...
You can also save any plots in svg format (or eps, png pdf, tiff format) and with a good svg tool, you can already further tune the plot.

**Comment by tomtomme** [comment] 2023-07-18 08:47
Most Plots can also be saved as pptx and edited in powerpoint etc.

**Comment by dekuenstle** [comment] 2023-07-28 12:42
With post-editing it is an enormous effort to match the styles of MATLAB, rplot, ggplot, matplotlib,… that users might use to plot results from other analysis. 

The JASP file already has a reusable JSON representation of each plot as part of the `analyses.json`. It might be a pretty convenient and flexible option for power users if the UI offers an "Export as JSON" button to get the specific JSON of this plot.

![Mock](https://github.com/jasp-stats/jasp-issues/assets/734721/5824ef25-c0b9-47b2-adc7-fba80195527d)


```json
{
							"aspectRatio" : 0.0,
							"convertible" : true,
							"data" : "resources/0/_0_t1690546749865.png",
							"editOptions" : 
							{
								"error" : "success",
								"xAxis" : 
								{
									"settings" : 
									{
										"breaks" : 
										[
											0,
											10,
											20,
											30,
											40,
											50
										],
										"breaksType" : "range",
										"expand" : 
										[
											0.050000000000000003,
											0,
											0.050000000000000003,
											0
										],
										"labels" : 
										[
											0,
											10,
											20,
											30,
											40,
											50
										],
										"limits" : 
										[
											0,
											50
										],
										"limitsType" : "breaks",
										"range" : 
										[
											0,
											50,
											10
										],
										"title" : "fuseTime",
										"titleType" : "character"
									},
									"type" : "ScaleContinuous"
								},
								"yAxis" : 
								{
									"settings" : 
									{
										"breaks" : 
										[
											0,
											10,
											20,
											30,
											40
										],
										"breaksType" : "range",
										"expand" : 
										[
											0.050000000000000003,
											0,
											0.050000000000000003,
											0
										],
										"labels" : 
										[
											"0",
											"10",
											"20",
											"30",
											"40"
										],
										"limits" : 
										[
											0,
											40
										],
										"limitsType" : "breaks",
										"range" : 
										[
											0,
											40,
											10
										],
										"title" : "Counts",
										"titleType" : "character"
									},
									"type" : "ScaleContinuous"
								}
							},
```

**Comment by tomtomme** [comment] 2024-02-08 21:38
Closing, since duplicate of https://github.com/jasp-stats/jasp-issues/issues/1095
I will add the additional request for json there too.

**Closed by tomtomme** 2024-02-08 21:38 UTC
Labels: Graphs/Plots, Feature Request, R Syntax
