### ISSUE TITLE
Changing data type at multiple points

### ISSUE THREAD

**Issue by brandenjohnson1** [jasp-stats/jasp-issues#1421] opened 2021-09-20 16:20 UTC
* Enhancement: To allow people to change the data type at multiple points or in multiple ways, rather than just when one first opens the data file and can click on the column heading
* Purpose: If one begins a data analysis and realizes that the JASP assignment of data type erroneously prevents one from using that particular statistic, there is no way to change the data type then and there. One must close down one's work, close the data file, and then open up the data file again in order to access the data type change function. At best this is time-consuming; at worst it doesn't work, and one has to close JASP entirely, and perhaps reboot the computer, to get back to the vertical-variable view. If the data-set is small, checking the entire JASP assignment of data type codes upon the very first opening of the data file would be prudent and resolve the problem. But when it is a large file (e.g. 800+ variables) with only a few variables being used in the analysis, one just expects that the data file will work, as it does in the original SPSS file.

**Describe the solution you'd like**
<Multiple options could be used. The easiest for the user (don't know about programming) would allow for one-click toggling between the horizontal variable format (for dragging them into the statistical function box) and the vertical variable format for changing data type, searching for anomalous entries perhaps revealed by the statistical analysis, etc. An alternative would be to have a separate Data File tab on the lefthand menu or next to the statistical option tabs, so one could get to it without closing the current open statistics tasks, yet have the variables in the latter horizontal format updated in real time. (A good add-on would be to have a Save function when one has updated the data type formats; this appears when one closes JASP, but it doesn't seem to be available at the time one makes the changes, which leaves open the possibility of losing the changes if there is a crash, etc.

**Comment by juliuspf** [comment] 2022-10-14 09:00
The Data-Editing release will solve this issue!

**Comment by tomtomme** [comment] 2024-01-02 17:37
This is a duplicate of https://github.com/jasp-stats/jasp-issues/issues/2483
and can be closed

**Closed** 2024-01-03 13:08 UTC
Labels: Feature Request, Data Editing
